dojo.declare("classes.managers.Achievements",com.nuclearunicorn.core.TabManager,{game:null,badgesUnlocked:!1,achievements:[{name:"theElderLegacy",title:$I("achievements.theElderLegacy.title"),description:$I("achievements.theElderLegacy.desc"),condition:function(){var a=new Date;return 0==a.getMonth()&&2017==a.getFullYear()},hidden:!0},{name:"unicornConspiracy",title:$I("achievements.unicornConspiracy.title"),description:$I("achievements.unicornConspiracy.desc"),condition:function(){return 0<this.game.resPool.get("unicorns").value}},
{name:"uniception",title:$I("achievements.uniception.title"),description:$I("achievements.uniception.desc"),condition:function(){return 0<this.game.resPool.get("tears").value}},{name:"sinsOfEmpire",title:$I("achievements.sinsOfEmpire.title"),description:$I("achievements.sinsOfEmpire.desc"),condition:function(){return 0<this.game.resPool.get("alicorn").value}},{name:"anachronox",title:$I("achievements.anachronox.title"),description:$I("achievements.anachronox.desc"),condition:function(){return 0<this.game.resPool.get("timeCrystal").value}},
{name:"deadSpace",title:$I("achievements.deadSpace.title"),description:$I("achievements.deadSpace.desc"),condition:function(){return 0<this.game.resPool.get("necrocorn").value}},{name:"ironWill",title:$I("achievements.ironWill.title"),description:$I("achievements.ironWill.desc"),condition:function(){return this.game.ironWill&&!this.game.resPool.get("kittens").value&&0<this.game.bld.get("mine").val}},{name:"uberkatzhen",title:$I("achievements.uberkatzhen.title"),description:$I("achievements.uberkatzhen.desc"),
condition:function(){return this.game.ironWill&&!this.game.resPool.get("kittens").value&&0<this.game.bld.get("warehouse").val}},{name:"hundredYearsSolitude",title:$I("achievements.hundredYearsSolitude.title"),description:$I("achievements.hundredYearsSolitude.desc"),condition:function(){return this.game.ironWill&&!this.game.resPool.get("kittens").value&&0<this.game.bld.get("steamworks").val}},{name:"soilUptuned",title:$I("achievements.soilUptuned.title"),description:$I("achievements.soilUptuned.desc"),
condition:function(){return this.game.ironWill&&!this.game.resPool.get("kittens").value&&45<=this.game.bld.get("pasture").val}},{name:"atlasUnmeowed",title:$I("achievements.atlasUnmeowed.title"),description:$I("achievements.atlasUnmeowed.desc"),condition:function(){return this.game.ironWill&&!this.game.resPool.get("kittens").value&&0<this.game.bld.get("magneto").val}},{name:"meowMeowRevolution",title:$I("achievements.meowMeowRevolution.title"),description:$I("achievements.meowMeowRevolution.desc"),
condition:function(){return this.game.ironWill&&!this.game.resPool.get("kittens").value&&0<this.game.bld.get("factory").val}},{name:"spaceOddity",title:$I("achievements.spaceOddity.title"),description:$I("achievements.spaceOddity.desc"),starDescription:$I("achievements.spaceOddity.starDesc"),condition:function(){return this.game.ironWill&&this.game.space.getProgram("moonMission").on},starCondition:function(){return this.game.ironWill&&this.game.space.getProgram("moonMission").on&&10>this.game.resPool.get("paragon").value}},
{name:"jupiterAscending",title:$I("achievements.jupiterAscending.title"),description:$I("achievements.jupiterAscending.desc"),condition:function(){return this.game.space.getProgram("orbitalLaunch").on&&1>=this.game.calendar.year}},{name:"shadowOfTheColossus",title:$I("achievements.shadowOfTheColossus.title"),description:$I("achievements.shadowOfTheColossus.desc"),condition:function(){return 0<this.game.bld.get("ziggurat").val&&1==this.game.village.maxKittens}},{name:"sunGod",title:$I("achievements.sunGod.title"),
description:$I("achievements.sunGod.desc"),condition:function(){return 696342<=this.game.religion.faith}},{name:"heartOfDarkness",title:$I("achievements.heartOfDarkness.title"),description:$I("achievements.heartOfDarkness.desc"),condition:function(){return 1<this.game.resPool.get("zebras").value}},{name:"winterIsComing",title:$I("achievements.winterIsComing.title"),description:$I("achievements.winterIsComing.desc"),unethical:!0,condition:function(){return 10<=this.game.deadKittens}},{name:"youMonster",
title:$I("achievements.youMonster.title"),unethical:!0,description:$I("achievements.youMonster.desc"),condition:function(){return 100<=this.game.deadKittens},starCondition:function(){return 666666<=this.game.deadKittens}},{name:"superUnethicalClimax",title:$I("achievements.superUnethicalClimax.title"),unethical:!0,description:$I("achievements.superUnethicalClimax.desc"),condition:function(){return this.game.cheatMode}},{name:"systemShock",title:$I("achievements.systemShock.title"),unethical:!0,description:$I("achievements.systemShock.desc"),
condition:function(){return this.game.systemShockMode}},{name:"lotusMachine",title:$I("achievements.lotusMachine.title"),description:$I("achievements.lotusMachine.desc"),condition:function(){return 1<=this.game.resPool.get("karma").value}},{name:"serenity",title:$I("achievements.serenity.title"),description:$I("achievements.serenity.desc"),condition:function(){return 50<=this.game.village.getKittens()&&0==this.game.deadKittens}},{name:"utopiaProject",title:$I("achievements.utopiaProject.title"),description:$I("achievements.utopiaProject.desc"),
starDescription:$I("achievements.utopiaProject.starDesc"),condition:function(){return 1.5<=this.game.village.happiness&&35<this.game.resPool.get("kittens").value},starCondition:function(){return 5<=this.game.village.happiness&&35<this.game.resPool.get("kittens").value}},{name:"deathStranding",title:$I("achievements.deathStranding.title"),description:$I("achievements.deathStranding.desc"),condition:function(){return this.game.space.getPlanet("furthestRing").reached}},{name:"cathammer",title:$I("achievements.cathammer.title"),
description:$I("achievements.cathammer.desc"),starDescription:$I("achievements.cathammer.starDesc"),condition:function(){return this.game.stats.getStat("totalYears").val>=this.game.calendar.darkFutureBeginning},starCondition:function(){return this.game.calendar.trueYear()>=this.game.calendar.darkFutureBeginning}}],badges:[{name:"lotus",title:"\u9189\u751f\u68a6\u6b7b",description:"\u5468\u76ee\u6570\u5927\u4e8e50",difficulty:"A",condition:function(){return 50<=this.game.stats.getStat("totalResets").val}},
{name:"ivoryTower",title:"\u767d\u8272\u5de8\u5854",description:"\u94a2\u94c1\u65e0\u795e\u8bba\u4e2d\u91cd\u7f6e",difficulty:"S+"},{name:"useless",title:"\u7ba1\u7406\u6709\u65b9",description:"\u4f7f\u7528\u65e0\u7279\u8d28\u7684\u9886\u8896",difficulty:"F",condition:function(){var a=this.game.village.leader;return null!=a&&"none"==a.trait.name}},{name:"beta",title:"\u03b2\u6d4b\u8bd5\u733f",description:"\u53c2\u52a0\u8fc7\u6d4b\u8bd5\u6a21\u5f0f",difficulty:"B",condition:function(){return window&&
window.location&&window.location.href?0<=window.location.href.indexOf("beta"):!1}},{name:"silentHill",title:"\u9759\u5bc2\u5cad",description:"\u83b7\u53d6\u4e0d\u5230\u670d\u52a1\u5668\u4fe1\u606f",difficulty:"S",condition:function(){return""==this.game.server.motdContent}},{name:"evergreen",title:"\u6728\u8d28\u5956\u7ae0",description:"\u6211\u60f3\u4f60\u5236\u4f5c\u4e86\u51fa\u4e00\u5757\u6728\u6750\uff1f",difficulty:"F"},{name:"deadSpace",title:"\u6b7b\u4ea1\u7a7a\u95f4",description:"\u732b\u54aa\u5728\u865a\u7a7a\u4e2d\u6e38\u8361",
difficulty:"S",condition:function(){var a=this.game.resPool.get("kittens");return 1E3<=a.value&&0==a.maxValue}},{name:"reginaNoctis",title:"\u591c\u4e4b\u5973\u738b",description:"\u62e5\u6709500\u53ea\u732b\u54aa\u4e14\u6ca1\u6709\u5929\u89d2\u517d",difficulty:"S",condition:function(){return 500<this.game.resPool.get("kittens").value&&0==this.game.resPool.get("alicorn").value}},{name:"ghostInTheMachine",title:"\u9047\u5230\u4e86BUG",description:"\u264b\ufe0e\u2b27\ufe0e\u29eb\ufe0e\u264f\ufe0e\u2752\ufe0e\ud83d\udd6f\ufe0e\u2b27\ufe0e \u25cf\ufe0e\u264b\ufe0e\u25a0\ufe0e\u2651\ufe0e\u25c6\ufe0e\u264b\ufe0e\u2651\ufe0e\u264f\ufe0e \ud83d\uddb3\ufe0e\u2706",
difficulty:"S"},{name:"abOwo",title:"Ab Owo",description:"Ab Owo",difficulty:"A"},{name:"cleanPaws",title:"\u7c89\u5ae9\u55b5\u722a",description:"\u4e0d\u901a\u8fc7\u55b5\u55b5\u548c\u5e73\u8d38\u6613",difficulty:"C"}],constructor:function(a){this.game=a},get:function(a){return this.getMeta(a,this.achievements)},getBadge:function(a){return this.getMeta(a,this.badges)},unlockBadge:function(a){this.getBadge(a).unlocked=!0;this.game.achievements.badgesUnlocked=!0},hasUnlocked:function(){for(var a=0;a<
this.achievements.length;a++)if(this.achievements[a].unlocked)return!0;return!1},update:function(){for(var a in this.achievements){var b=this.achievements[a];!b.unlocked&&b.condition&&b.condition.call(this)&&(b.unlocked=!0,this.game.msg($I("achievements.msg.unlock",[b.title])),this.game.achievementTab.visible=!0);!b.starUnlocked&&b.starCondition&&b.starCondition.call(this)&&(b.starUnlocked=!0,this.game.msg($I("achievements.msg.starUnlock",[b.title])),this.game.achievementTab.visible=!0)}for(a in this.badges)b=
this.badges[a],!b.unlocked&&b.condition&&b.condition.call(this)&&(this.badgesUnlocked=b.unlocked=!0)},resetState:function(){for(var a=0;a<this.achievements.length;a++){var b=this.achievements[a];b.unlocked=!1;b.starUnlocked=!1}this.badgesUnlocked=!1;for(a=0;a<this.badges.length;a++)this.badges[a].unlocked=!1},save:function(a){a.achievements=this.filterMetadata(this.achievements,["name","unlocked","starUnlocked"]);a.ach={badgesUnlocked:this.badgesUnlocked,badges:this.filterMetadata(this.badges,["name",
"unlocked"])}},load:function(a){this.loadMetadata(this.achievements,a.achievements);a=a.ach||{};this.badgesUnlocked=a.badgesUnlocked||!1;a.badges&&this.loadMetadata(this.badges,a.badges)},unlockAll:function(){for(var a in this.achievements)this.achievements[a].unlocked=!0;this.game.msg("All achievements are unlocked")}});
dojo.declare("classes.ui.AchievementsPanel",com.nuclearunicorn.game.ui.Panel,{game:null,constructor:function(){},render:function(a){var b=this.inherited(arguments),e=dojo.create("div",{},b);e.innerHTML="";b=dojo.create("div",{className:"achievement-header"},e);var h=0,k=0,l=0,f=0,d;for(d in this.game.achievements.achievements){var c=this.game.achievements.achievements[d];if(c.unlocked||!c.hidden){c.unethical||h++;c.unlocked&&!c.unethical&&k++;var g="achievement";c.unlocked&&c.unethical&&(g+=" unethical");
c.unlocked&&(g+=" unlocked");c.starUnlocked&&(g+=" starUnlocked");g=dojo.create("span",{className:g,title:c.unlocked?c.description:"???",innerHTML:c.unlocked?c.title:"???"},e);void 0!=c.starCondition&&(c.starUnlocked?l++:f++,dojo.create("div",{className:"star",innerHTML:c.starUnlocked?"&#9733;":"&#9734;",title:c.starUnlocked?c.starDescription:"???"},g))}}b.innerHTML=$I("achievements.header",[k,h]);e="";for(d=l;0<d;--d)e+="&#9733;";for(d=f;0<d;--d)e+="&#9734;";dojo.create("span",{className:"star",
innerHTML:e},b)}});
dojo.declare("classes.ui.BadgesPanel",com.nuclearunicorn.game.ui.Panel,{game:null,constructor:function(){},render:function(a){var b=this.inherited(arguments);b=dojo.create("div",{},b);b.innerHTML="";var e=dojo.create("div",{className:"achievement-header"},b),h=0,k=0,l;for(l in this.game.achievements.badges){var f=this.game.achievements.badges[l];h++;f.unlocked&&k++;var d="achievement badge";f.unlocked&&(d+=" unlocked");dojo.create("span",{className:d,title:f.unlocked?f.description:"???",innerHTML:f.unlocked?
f.title:"???"},b)}e.innerHTML=$I("badges.header",[k,h])}});
dojo.declare("com.nuclearunicorn.game.ui.tab.AchTab",com.nuclearunicorn.game.ui.tab,{constructor:function(){},render:function(a){this.achievementsPanel=new classes.ui.AchievementsPanel($I("achievements.panel.label"),this.game.achievements);this.achievementsPanel.game=this.game;this.achievementsPanel.render(a);this.badgesPanel=new classes.ui.BadgesPanel($I("badges.panel.label"),this.game.achievements);this.badgesPanel.game=this.game;this.badgesPanel.render(a);this.container=a;this.inherited(arguments);
this.update()},update:function(){this.inherited(arguments)}});
