dojo.declare("classes.managers.ChallengesManager",com.nuclearunicorn.core.TabManager,{constructor:function(a){this.game=a;this.registerMeta("stackable",this.challenges,null);this.setEffectsCachedExisting();this.reserves=new classes.reserveMan(a)},currentChallenge:null,challenges:[{name:"ironWill",label:$I("challendge.ironWill.label"),description:$I("challendge.ironWill.desc"),effectDesc:$I("challendge.ironWill.effect.desc"),researched:!1,unlocked:!0},{name:"winterIsComing",label:$I("challendge.winterIsComing.label"),
description:$I("challendge.winterIsComing.desc"),effectDesc:$I("challendge.winterIsComing.effect.desc"),researched:!1,unlocked:!0,upgrades:{buildings:["pasture"]},effects:{springCatnipRatio:.05,summerSolarFarmRatio:.05,coldChance:0,coldHarshness:0},calculateEffects:function(a,b){a.active?(a.effects.springCatnipRatio=0,a.effects.summerSolarFarmRatio=0,a.effects.coldChance=.05,a.effects.coldHarshness=-.02):(a.effects.springCatnipRatio=.05,a.effects.summerSolarFarmRatio=.05,a.effects.coldChance=0,a.effects.coldHarshness=
0)},checkCompletionCondition:function(a){return a.space.getPlanet("helios").reached}},{name:"anarchy",label:$I("challendge.anarchy.label"),description:$I("challendge.anarchy.desc"),effectDesc:$I("challendge.anarchy.effect.desc"),researched:!1,unlocked:!0,effects:{masterSkillMultiplier:.2,kittenLaziness:0},calculateEffects:function(a,b){a.active?(a.effects.masterSkillMultiplier=0,a.effects.kittenLaziness=.05):a.effects.masterSkillMultiplier=.2},checkCompletionCondition:function(a){return 0<a.bld.get("aiCore").val}},
{name:"energy",label:$I("challendge.energy.label"),description:$I("challendge.energy.desc"),effectDesc:$I("challendge.energy.effect.desc"),researched:!1,unlocked:!1,upgrades:{buildings:"library biolab calciner oilWell factory accelerator chronosphere aiCore".split(" "),spaceBuilding:"sattelite spaceStation moonOutpost moonBase orbitalArray containmentChamber".split(" "),voidSpace:["chronocontrol"]},effects:{energyConsumptionRatio:-.02,energyConsumptionIncrease:0},calculateEffects:function(a,b){a.active?
(a.effects.energyConsumptionRatio=0,a.effects.energyConsumptionIncrease=.1):(a.effects.energyConsumptionRatio=-.02,a.effects.energyConsumptionIncrease=0)},checkCompletionCondition:function(a){return 0<a.bld.get("pasture").val&&1==a.bld.get("pasture").stage&&0<a.bld.get("aqueduct").val&&1==a.bld.get("aqueduct").stage&&0<a.bld.get("steamworks").val&&0<a.bld.get("magneto").val&&0<a.bld.get("reactor").val&&0<a.space.getBuilding("sattelite").val&&a.workshop.get("solarSatellites").researched&&0<a.space.getBuilding("sunlifter").val&&
0<a.space.getBuilding("tectonic").val&&0<a.space.getBuilding("hrHarvester").val}},{name:"atheism",label:$I("challendge.atheism.label"),description:$I("challendge.atheism.desc"),effectDesc:$I("challendge.atheism.effect.desc"),effects:{faithSolarRevolutionBoost:.1,cultureMaxChallenge:0,scienceMaxChallenge:0,manpowerMaxChallenge:0,challengeHappiness:0},calculateEffects:function(a,b){a.active?(a.effects.faithSolarRevolutionBoost=0,a.effects.cultureMaxChallenge=-250,a.effects.scienceMaxChallenge=-500,
a.effects.challengeHappiness=-.5,a.effects.manpowerMaxChallenge=-125):(a.effects.faithSolarRevolutionBoost=.1,a.effects.cultureMaxChallenge=0,a.effects.scienceMaxChallenge=0,a.effects.challengeHappiness=0,a.effects.manpowerMaxChallenge=0)},checkCompletionConditionOnReset:function(a){return 0<a.time.getVSU("cryochambers").on},researched:!1,reserveDelay:!0,unlocked:!1},{name:"1000Years",label:$I("challendge.1000Years.label"),description:$I("challendge.1000Years.desc"),effectDesc:$I("challendge.1000Years.effect.desc"),
effects:{shatterCostReduction:-.02,shatterCostIncreaseChallenge:0,shatterVoidCost:0,temporalPressCap:0},calculateEffects:function(a,b){a.active?(a.effects.shatterCostReduction=0,a.effects.shatterCostIncreaseChallenge=.5,a.effects.shatterVoidCost=.4,a.effects.temporalPressCap=0):(a.effects.shatterCostReduction=-.02,a.effects.shatterCostIncreaseChallenge=0,a.effects.shatterVoidCost=0,a.effects.temporalPressCap=5);b.upgrade(a.upgrades)},researched:!1,unlocked:!1,upgrades:{chronoforge:["temporalPress"]},
unlocks:{chronoforge:["temporalPress"]}},{name:"blackSky",label:$I("challendge.blackSky.label"),description:$I("challendge.blackSky.desc"),effectDesc:$I("challendge.blackSky.effect.desc"),researched:!1,unlocked:!1,effects:{corruptionBoostRatioChallenge:.1},calculateEffects:function(a,b){a.effects.corruptionBoostRatioChallenge=a.active?0:.1;b.upgrade(a.upgrades)},checkCompletionCondition:function(a){return a.space.getBuilding("spaceBeacon").val>(a.challenges.getChallenge("blackSky").on||0)},upgrades:{zigguratUpgrades:["marker"]}},
{name:"pacifism",label:$I("challendge.pacifism.label"),description:$I("challendge.pacifism.desc"),effectDesc:$I("challendge.pacifism.effect.desc"),effects:{alicornPerTickRatio:.1,tradeKnowledge:1,weaponEfficency:0,policyFakeBought:0,embassyFakeBought:0,steamworksFakeBought:0,tradeKnowledgeRatio:0},calculateEffects:function(a,b){a.active?(a.effects.alicornPerTickRatio=0,a.effects.tradeKnowledge=0,a.effects.weaponEfficency=-.1,a.effects.policyFakeBought=1,a.effects.embassyFakeBought=1,a.effects.steamworksFakeBought=
Math.floor(1.5*a.on||1)/(a.on||1),a.effects.tradeKnowledgeRatio=0):(a.effects.alicornPerTickRatio=.1,a.effects.tradeKnowledge=1,a.effects.weaponEfficency=0,a.effects.policyFakeBought=0,a.effects.embassyFakeBought=0,a.effects.steamworksFakeBought=0,a.effects.tradeKnowledgeRatio=a.getTradeBonusEffect(b));b.upgrade(a.upgrades)},updateTradeKnowledgeRatio:function(a,b){a.effects.tradeKnowledgeRatio=a.getTradeBonusEffect(b)},checkCompletionConditionOnReset:function(a){0<a.diplomacy.baseManpowerCost&&!a.village.sim.hadKittenHunters&&
0<a.stats.getStatCurrent("totalTrades").val&&a.achievements.unlockBadge("cleanPaws");return a.science.getPolicy("outerSpaceTreaty").researched},upgrades:{upgrades:["compositeBow","crossbow","railgun"]},researched:!1,reserveDelay:!0,unlocked:!1,getTradeBonusEffect:function(a){if(!a.challenges.getChallenge("pacifism").on||a.challenges.isActive("pacifism"))return 0;var b=a.bld.getBuildingExt("tradepost").meta,c=a.getEffect("tradeKnowledge"),d=(7+3*c)*(.99+.01*c);a=a.getLimitedDR(.099+.0075*c,.25);return b.effects.tradeRatio*
Math.min(d,b.val*a)}},{name:"postApocalypse",label:$I("challendge.postApocalypse.label"),description:$I("challendge.postApocalypse.desc"),effectDesc:$I("challendge.postApocalypse.effect.desc"),researched:!1,unlocked:!1,flavor:$I("challendge.postApocalypse.flavor"),effects:{arrivalSlowdown:0,cryochamberSupport:1},calculateEffects:function(a,b){a.effects.arrivalSlowdown=a.active?10:0;a.effects.cryochamberSupport=1},findRuins:function(a,b){},checkCompletionCondition:function(a){return 0==a.bld.cathPollution},
actionOnCompletion:function(a){a.bld.effectsBase.hutFakeBought=0;a.bld.effectsBase.logHouseFakeBought=0;a.bld.effectsBase.mansionFakeBought=0;a.bld.pollutionEffects.pollutionDissipationRatio=1E-7;a.science.getPolicy("terraformingInsight").unlocked=!0;a.science.getPolicy("cryochamberExtraction").unlocked=!0}}],game:null,resetState:function(){for(var a=0;a<this.challenges.length;a++){var b=this.challenges[a];b.enabled=!1;b.pending=!1;b.active=!1;this.resetStateStackable(b)}this.currentChallenge=null;
this.reserves.resetState()},save:function(a){a.challenges={challenges:this.filterMetadata(this.challenges,["name","researched","on","unlocked","active"])};var b=[],c;for(c in this.game.challenges.reserves.reserveKittens){var d=this.game.challenges.reserves.reserveKittens[c].save(this.game.opts.compressSaveFile,this.game.village.jobNames);b.push(d)}a.challenges.reserves=this.reserves.getSaveData()},load:function(a){if(a.challenges){this.loadMetadata(this.challenges,a.challenges.challenges);var b=a.challenges.currentChallenge;
b&&(this.getChallenge(b).active=!0);for(b=0;b<this.challenges.length;b++)this.challenges[b].researched&&!this.challenges[b].on&&(this.challenges[b].on=1),this.challenges[b].unlocks&&this.challenges[b].on&&!this.challenges[b].active&&this.game.unlock(this.challenges[b].unlocks);if(a.challenges.reserves){var c=a.challenges.reserves.reserveKittens,d=[];for(b=c.length-1;0<=b;b--){var e=c[b],f=new com.nuclearunicorn.game.village.Kitten;f.load(e,this.game.village.jobNames);d.unshift(f)}this.game.challenges.reserves.reserveKittens=
d;this.game.challenges.reserves.reserveResources=a.challenges.reserves.reserveResources;this.game.challenges.reserves.reserveCryochambers=a.challenges.reserves.reserveCryochambers||c.length}}},update:function(){0!=this.getChallenge("energy").unlocked||0==this.game.resPool.energyProd&&0==this.game.resPool.energyCons||(this.getChallenge("energy").unlocked=!0);for(var a=0;a<this.challenges.length;a++)this.challenges[a].active&&this.challenges[a].checkCompletionCondition&&this.challenges[a].checkCompletionCondition(this.game)&&
this.researchChallenge(this.challenges[a].name)},getChallenge:function(a){return this.getMeta(a,this.challenges)},anyChallengeActive:function(){var a=!1,b;for(b in this.challenges)this.isActive(this.challenges[b].name)&&(a=!0);return a},isActive:function(a){return!!this.getChallenge(a).active},researchChallenge:function(a){this.isActive(a)&&(this.getChallenge(a).researched=!0,this.getChallenge(a).on+=1,this.getChallenge(a).active=!1,this.game.msg($I("challendge.btn.log.message.on.complete",[this.getChallenge(a).label])),
this.getChallenge(a).actionOnCompletion&&this.getChallenge(a).actionOnCompletion(this.game),this.getChallenge(a).unlocks&&this.game.unlock(this.getChallenge(a).unlocks),this.game.calculateAllEffects())},onRunReset:function(){for(var a=0;a<this.challenges.length;a++)this.challenges[a].active&&this.challenges[a].checkCompletionConditionOnReset&&this.challenges[a].checkCompletionConditionOnReset(this.game)&&this.researchChallenge(this.challenges[a].name)},applyPending:function(a){var b=this.game,c=b.challenges.getChallenge("postApocalypse").pending&&
b.challenges.getChallenge("winterIsComing").pending&&!a&&b.time.getVSU("cryochambers").val,d=$I("challendge.btn.confirmation_postApocalypse_winterIsComing.msg");b.ui.confirm($I("challendge.btn.confirmation.title"),c?$I("challendge.btn.confirmation.msg")+d:$I("challendge.btn.confirmation.msg"),function(){void 0!=b.opts.autoSaveReset&&b.opts.autoSaveReset&&b.saveToFile(!0);b.challenges.onRunReset();b.challenges.reserves.calculateReserves(a);b.bld.get("chronosphere").val=0;b.bld.get("chronosphere").on=
0;!b.challenges.getChallenge("postApocalypse").pending||a?(b.time.getVSU("cryochambers").val=0,b.time.getVSU("cryochambers").on=0):b.challenges.getChallenge("anarchy").pending&&this.game.village.leader&&(this.game.village.leader.isLeader=!1,this.game.village.leader=null);b.resetAutomatic()},function(){})}});
dojo.declare("classes.reserveMan",null,{constructor:function(a){this.game=a;this.reserveKittens=this.reserveResources=null;this.reserveCryochambers=0},resetState:function(){this.reserveResources={};this.reserveKittens=[];this.reserveCryochambers=0},calculateReserveResources:function(){var a=0<this.game.bld.get("chronosphere").val?this.game.getEffect("resStasisRatio"):0;if(a){var b=this.game.challenges.reserves.reserveResources,c;for(c in this.game.resPool.resources){var d=this.game.resPool.resources[c];
if("timeCrystal"!=d.name){var e=this.game.workshop.get("fluxCondensator");!1===d.persists||d.craftable&&"wood"!=d.name&&!e.researched||(e=0,d.persists||(d.craftable&&"wood"!=d.name?0<d.value&&(e=Math.sqrt(d.value)*a*100):(e=d.value*a,"void"==d.name&&(e=Math.floor(e)))),0<e&&(b[d.name]=Math.max(b[d.name]||0,e)))}}this.game.challenges.reserves.reserveResources=b}},calculateReserveKittens:function(){var a=[],b=this.game.time.getVSU("cryochambers").on;if(0<b){this.game.village.sim.sortKittensByExp();
a=this.game.village.sim.kittens.slice(-b);for(var c in a)delete a[c].job,delete a[c].isLeader,delete a[c].engineerSpeciality}this.game.challenges.reserves.reserveKittens=this.game.challenges.reserves.reserveKittens.concat(a)},calculateReserves:function(a){this.game.challenges.reserves.calculateReserveResources();if(!this.game.challenges.getChallenge("postApocalypse").pending||a)this.game.challenges.reserves.calculateReserveKittens(),this.reserveCryochambers+=this.game.time.getVSU("cryochambers").on},
addReserves:function(){for(var a in this.reserveResources)"timeCrystal"!=a&&(this.reserveResources[a]=null==this.reserveResources[a]?Infinity:this.reserveResources[a],this.game.resPool.get(a).maxValue?this.game.resPool.get(a).value=Math.max(this.game.resPool.get(a).value,this.reserveResources[a]):this.game.resPool.get(a).value+=this.reserveResources[a]),delete this.reserveResources[a];for(a in this.reserveKittens)this.game.village.sim.kittens.push(this.reserveKittens[a]);this.game.time.getVSU("usedCryochambers").val+=
this.reserveCryochambers;this.game.time.getVSU("usedCryochambers").on+=this.reserveCryochambers;this.reserveCryochambers=0;this.reserveKittens=[];this.game.msg($I("challendge.reservesReclaimed.msg"))},getSaveData:function(){var a=[],b;for(b in this.game.challenges.reserves.reserveKittens){var c=this.game.challenges.reserves.reserveKittens[b].save(this.game.opts.compressSaveFile,this.game.village.jobNames);a.push(c)}return{reserveKittens:a,reserveResources:this.game.challenges.reserves.reserveResources,
ironWillClaim:this.ironWillClaim,reserveCryochambers:this.reserveCryochambers}},reservesExist:function(){return Object.keys(this.reserveResources).length||this.reserveKittens.length}});
dojo.declare("classes.ui.ChallengeBtnController",com.nuclearunicorn.game.ui.BuildingBtnController,{getMetadata:function(a){a.metaCached||(a.metaCached=this.game.challenges.getChallenge(a.options.id));return a.metaCached},getDescription:function(a){var b=0<this.game.bld.get("chronosphere").val?"ironWill"==a.metadata.name?$I("challendge.btn.chronosphere.with.ironWill.desc"):$I("challendge.btn.chronosphere.desc"):"";return this.inherited(arguments)+$I("challendge.btn.desc",[a.metadata.effectDesc,b])},
getName:function(a){a=a.metadata;var b=a.label;a.active||a.name==this.game.challenges.active?b=$I("challendge.btn.name.current",[a.label]):a.researched&&(b=$I("challendge.btn.name.complete",[a.label]));a.pending&&(b+=" ("+$I("challendge.pending")+")");a.on&&(b+=" ("+a.on+")");return b},updateVisible:function(a){a.visible=a.metadata.unlocked},getPrices:function(a){return $.extend(!0,[],a.metadata.prices)},buyItem:function(a,b,c){this.togglePending(a)},togglePending:function(a){"ironWill"==a.metadata.name?
this.game.challenges.applyPending(!0):a.metadata.pending=!a.metadata.pending},updateEnabled:function(a){this.inherited(arguments);a.metadata.researched&&(a.enabled=!1)}});
dojo.declare("classes.ui.ChallengePanel",com.nuclearunicorn.game.ui.Panel,{game:null,constructor:function(){},render:function(a){var b=this.inherited(arguments),c=this,d=new classes.ui.ChallengeBtnController(c.game);dojo.forEach(this.game.challenges.challenges,function(e,f){e=new com.nuclearunicorn.game.ui.BuildingBtn({id:e.name,controller:d},c.game);e.render(b);c.addChild(e)})}});
dojo.declare("classes.tab.ChallengesTab",com.nuclearunicorn.game.ui.tab,{render:function(a){this.challengesPanel=new classes.ui.ChallengePanel($I("challendge.panel.label"),this.game.challenges);this.challengesPanel.game=this.game;this.challengesPanel.render(a);dojo.create("div",{style:{marginBottom:"15px"}},a);var b=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("challendge.applyPending.label"),description:$I("challendge.applyPending.desc"),handler:dojo.hitch(this,function(){this.game.challenges.applyPending()}),
controller:new com.nuclearunicorn.game.ui.ButtonController(this.game,{updateVisible:function(c){c.visible=!1;for(var d=0;d<this.game.challenges.challenges.length;d++)this.game.challenges.challenges[d].pending&&(c.visible=!0)},getName:function(){for(var c=0,d=0;d<this.game.challenges.challenges.length;d++)this.game.challenges.challenges[d].pending&&c++;return $I("challendge.applyPending.label",[c])}})},this.game);b.render(a);this.applyPendingBtn=b;b=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("challendge.reclaimReserves.label"),
description:$I("challendge.reclaimReserves.desc"),handler:dojo.hitch(this,function(){this.game.challenges.reserves.addReserves()}),controller:new com.nuclearunicorn.game.ui.ButtonController(this.game,{updateVisible:function(c){c.visible=!this.game.challenges.anyChallengeActive()&&!this.game.ironWill&&this.game.challenges.reserves.reservesExist()}})},this.game);b.render(a);this.reclaimReservesBtn=b},update:function(){this.challengesPanel.update();this.applyPendingBtn.update()}});
