dojo.declare("classes.managers.PrestigeManager",com.nuclearunicorn.core.TabManager,{perks:[{name:"engeneering",label:$I("prestige.engeneering.label"),description:$I("prestige.engeneering.desc"),prices:[{name:"paragon",val:5}],unlocked:!0,defaultUnlocked:!0,researched:!1,unlocks:{perks:["megalomania","goldenRatio","codexVox"]},effects:{priceRatio:-.01}},{name:"codexVox",label:$I("prestige.codexVox.label"),description:$I("prestige.codexVox.desc"),prices:[{name:"paragon",val:25}],unlocked:!1,researched:!1,
unlocks:{perks:["codexLogos"]},effects:{manuscriptCraftRatio:.25,manuscriptGlobalCraftRatio:.05}},{name:"codexLogos",label:$I("prestige.codexLogos.label"),description:$I("prestige.codexLogos.desc"),prices:[{name:"paragon",val:50}],unlocked:!1,researched:!1,unlocks:{perks:["codexAgrum","codexLeviathanianus"]},effects:{manuscriptGlobalCraftRatio:.05,compediumCraftRatio:.25,compediumGlobalCraftRatio:.05}},{name:"codexAgrum",label:$I("prestige.codexAgrum.label"),description:$I("prestige.codexAgrum.desc"),
prices:[{name:"paragon",val:75}],unlocked:!1,researched:!1,effects:{manuscriptGlobalCraftRatio:.05,compediumGlobalCraftRatio:.05,blueprintCraftRatio:.25,blueprintGlobalCraftRatio:.05}},{name:"megalomania",label:$I("prestige.megalomania.label"),description:$I("prestige.megalomania.desc"),prices:[{name:"paragon",val:10}],unlocked:!1,researched:!1,unlocks:{perks:["blackCodex"],zigguratUpgrades:["marker","blackPyramid"]}},{name:"blackCodex",label:$I("prestige.blackCodex.label"),description:$I("prestige.blackCodex.desc"),
prices:[{name:"paragon",val:25}],unlocked:!1,researched:!1,unlocks:{zigguratUpgrades:["unicornGraveyard"]}},{name:"codexLeviathanianus",label:$I("prestige.codexLeviathanianus.label"),description:$I("prestige.codexLeviathanianus.desc"),prices:[{name:"paragon",val:75}],unlocked:!1,researched:!1,unlocks:{}},{name:"goldenRatio",label:$I("prestige.goldenRatio.label"),description:$I("prestige.goldenRatio.desc"),prices:[{name:"paragon",val:50}],unlocked:!1,researched:!1,unlocks:{perks:["divineProportion"]},
effects:{priceRatio:-(1+Math.sqrt(5))/200}},{name:"divineProportion",label:$I("prestige.divineProportion.label"),description:$I("prestige.divineProportion.desc"),prices:[{name:"paragon",val:100}],unlocked:!1,researched:!1,unlocks:{perks:["vitruvianFeline"]},effects:{priceRatio:-16/900}},{name:"vitruvianFeline",label:$I("prestige.vitruvianFeline.label"),description:$I("prestige.vitruvianFeline.desc"),prices:[{name:"paragon",val:250}],unlocked:!1,researched:!1,unlocks:{perks:["renaissance"]},effects:{priceRatio:-.02}},
{name:"renaissance",label:$I("prestige.renaissance.label"),description:$I("prestige.renaissance.desc"),prices:[{name:"paragon",val:750}],unlocked:!1,researched:!1,effects:{priceRatio:-.0225}},{name:"diplomacy",label:$I("prestige.diplomacy.label"),description:$I("prestige.diplomacy.desc"),prices:[{name:"paragon",val:5}],unlocked:!0,defaultUnlocked:!0,researched:!1,effects:{standingRatio:.1},unlocks:{perks:["zebraDiplomacy"]}},{name:"zebraDiplomacy",label:$I("prestige.zebraDiplomacy.label"),description:$I("prestige.zebraDiplomacy.desc"),
prices:[{name:"paragon",val:35}],unlocked:!1,researched:!1,unlocks:{perks:["zebraCovenant"]}},{name:"zebraCovenant",label:$I("prestige.zebraCovenant.label"),description:$I("prestige.zebraCovenant.desc"),prices:[{name:"paragon",val:75}],unlocked:!1,researched:!1,unlocks:{perks:["navigationDiplomacy"]}},{name:"navigationDiplomacy",label:$I("prestige.navigationDiplomacy.label"),description:$I("prestige.navigationDiplomacy.desc"),prices:[{name:"paragon",val:300}],unlocked:!1,researched:!1},{name:"chronomancy",
label:$I("prestige.chronomancy.label"),description:$I("prestige.chronomancy.desc"),prices:[{name:"paragon",val:25}],unlocked:!0,defaultUnlocked:!0,researched:!1,unlocks:{perks:["astromancy","anachronomancy","unicornmancy"]}},{name:"astromancy",label:$I("prestige.astromancy.label"),description:$I("prestige.astromancy.desc"),prices:[{name:"paragon",val:50}],unlocked:!1,researched:!1,unlocks:{}},{name:"unicornmancy",label:$I("prestige.unicornmancy.label"),description:$I("prestige.unicornmancy.desc"),
prices:[{name:"paragon",val:125}],unlocked:!0,defaultUnlocked:!0,researched:!1},{name:"anachronomancy",label:$I("prestige.anachronomancy.label"),description:$I("prestige.anachronomancy.desc"),prices:[{name:"paragon",val:125}],unlocked:!1,researched:!1},{name:"carnivals",label:$I("prestige.carnivals.label"),description:$I("prestige.carnivals.desc"),prices:[{name:"paragon",val:25}],unlocked:!0,defaultUnlocked:!0,researched:!1,unlocks:{perks:["numerology"]}},{name:"willenfluff",label:$I("prestige.willenfluff.label"),
description:$I("prestige.willenfluff.desc"),prices:[{name:"paragon",val:150}],unlocked:!1,researched:!1,effects:{kittenGrowthRatio:.75},unlocks:{perks:["pawgan"]}},{name:"pawgan",label:$I("prestige.pawgan.label"),description:$I("prestige.pawgan.desc"),prices:[{name:"paragon",val:400}],unlocked:!1,researched:!1,effects:{kittenGrowthRatio:1.5}},{name:"numerology",label:$I("prestige.numerology.label"),description:$I("prestige.numerology.desc"),prices:[{name:"paragon",val:50}],unlocked:!1,researched:!1,
unlocks:{perks:["numeromancy","willenfluff","voidOrder"]}},{name:"numeromancy",label:$I("prestige.numeromancy.label"),description:$I("prestige.numeromancy.desc"),prices:[{name:"paragon",val:250}],unlocked:!1,researched:!1,unlocks:{perks:["malkuth"]}},{name:"malkuth",label:$I("prestige.malkuth.label"),description:$I("prestige.malkuth.desc"),prices:[{name:"paragon",val:500}],unlocked:!1,researched:!1,effects:{paragonRatio:.05},unlocks:{perks:["yesod"]}},{name:"yesod",label:$I("prestige.yesod.label"),
description:$I("prestige.yesod.desc"),prices:[{name:"paragon",val:750}],unlocked:!1,researched:!1,effects:{paragonRatio:.05},unlocks:{perks:["hod"]}},{name:"hod",label:$I("prestige.hod.label"),description:$I("prestige.hod.desc"),prices:[{name:"paragon",val:1250}],unlocked:!1,researched:!1,effects:{paragonRatio:.05},unlocks:{perks:["netzach"]}},{name:"netzach",label:$I("prestige.netzach.label"),description:$I("prestige.netzach.desc"),prices:[{name:"paragon",val:1750}],unlocked:!1,researched:!1,effects:{paragonRatio:.05},
unlocks:{perks:["tiferet"]}},{name:"tiferet",label:$I("prestige.tiferet.label"),description:$I("prestige.tiferet.desc"),prices:[{name:"paragon",val:2500}],unlocked:!1,researched:!1,effects:{paragonRatio:.05},unlocks:{perks:["gevurah"]}},{name:"gevurah",label:$I("prestige.gevurah.label"),description:$I("prestige.gevurah.desc"),prices:[{name:"paragon",val:5E3}],unlocked:!1,researched:!1,effects:{paragonRatio:.05},unlocks:{perks:["chesed"]}},{name:"chesed",label:$I("prestige.chesed.label"),description:$I("prestige.chesed.desc"),
prices:[{name:"paragon",val:7500}],unlocked:!1,researched:!1,effects:{paragonRatio:.05},unlocks:{perks:["binah"]}},{name:"binah",label:$I("prestige.binah.label"),description:$I("prestige.binah.desc"),prices:[{name:"paragon",val:15E3}],unlocked:!1,researched:!1,effects:{paragonRatio:.05},unlocks:{perks:["chokhmah"]}},{name:"chokhmah",label:$I("prestige.chokhmah.label"),description:$I("prestige.chokhmah.desc"),prices:[{name:"paragon",val:3E4}],unlocked:!1,researched:!1,effects:{paragonRatio:.05},unlocks:{perks:["keter"]}},
{name:"keter",label:$I("prestige.keter.label"),description:$I("prestige.keter.desc"),prices:[{name:"paragon",val:6E4}],unlocked:!1,researched:!1,effects:{paragonRatio:.05}},{name:"voidOrder",label:$I("prestige.voidOrder.label"),description:$I("prestige.voidOrder.desc"),prices:[{name:"paragon",val:75}],unlocked:!1,researched:!1},{name:"adjustmentBureau",label:$I("prestige.adjustmentBureau.label"),description:$I("prestige.adjustmentBureau.desc"),prices:[{name:"paragon",val:5}],unlocked:!0,defaultUnlocked:!0,
researched:!1,unlocks:{perks:["ascoh"],tabs:["challenges"]}},{name:"ascoh",label:$I("prestige.ascoh.label"),description:$I("prestige.ascoh.desc"),prices:[{name:"paragon",val:5}],unlocked:!1,defaultUnlocked:!1,researched:!1}],game:null,constructor:function(a){this.game=a;this.registerMeta("research",this.perks,null);this.setEffectsCachedExisting()},resetState:function(){for(var a=0;a<this.perks.length;a++){var b=this.perks[a];b.unlocked=b.defaultUnlocked||!1;b.researched=!1}},save:function(a){a.prestige=
{perks:this.filterMetadata(this.perks,["name","unlocked","researched"])}},load:function(a){if(a.prestige)for(this.loadMetadata(this.perks,a.prestige.perks),a=0;a<this.perks.length;a++){var b=this.perks[a];b.researched&&this.game.unlock(b.unlocks)}},update:function(){},getPerk:function(a){return this.getMeta(a,this.perks)},getSpentParagon:function(){for(var a=0,b=0;b<this.perks.length;b++){var c=this.perks[b];c.researched&&(a+=c.paragon||0)}return a},getParagonRatio:function(){return 1+this.game.getEffect("paragonRatio")},
getBurnedParagonRatio:function(){return this.game.getUnlimitedDR(this.game.resPool.get("burnedParagon").value,500)},getParagonProductionRatio:function(){var a=this.getParagonRatio(),b=.01*this.game.resPool.get("paragon").value*a;b=this.game.getLimitedDR(b,2*a);var c=0<=this.game.calendar.darkFutureYears()?4:1,d=.01*this.game.resPool.get("burnedParagon").value*a;d=this.game.getLimitedDR(d,c*a);return b+d},getParagonStorageRatio:function(){var a=this.getParagonRatio(),b=this.game.resPool.get("paragon").value/
1E3*a;return b=0<=this.game.calendar.darkFutureYears()?b+this.game.resPool.get("burnedParagon").value/500*a:b+this.game.resPool.get("burnedParagon").value/2E3*a},unlockAll:function(){for(var a in this.perks)this.perks[a].unlocked=!0;this.game.msg("All meta upgrades are unlocked!")}});
dojo.declare("classes.ui.PrestigeBtnController",com.nuclearunicorn.game.ui.BuildingNotStackableBtnController,{getMetadata:function(a){a.metaCached||(a.metaCached=this.game.prestige.getPerk(a.options.id));return a.metaCached},buyItem:function(a,b,c){this.game.science.get("metaphysics").researched?this.inherited(arguments):c(!1)},updateVisible:function(a){var b=a.metadata;a.visible=b.unlocked&&(b.researched||this.game.science.get("metaphysics").researched);b.researched&&this.game.science.hideResearched&&
(a.visible=!1)}});dojo.declare("classes.ui.BurnParagonBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{updateVisible:function(a){a.visible=0<this.game.resPool.get("paragon").value}});dojo.declare("classes.ui.turnHGOffButtonController",com.nuclearunicorn.game.ui.ButtonModernController,{updateVisible:function(a){a.visible=0<this.game.religion.activeHolyGenocide||0<this.game.religion.getTU("holyGenocide").on}});
dojo.declare("classes.ui.PrestigePanel",com.nuclearunicorn.game.ui.Panel,{game:null,constructor:function(){},render:function(a){var b=this.inherited(arguments),c=this,d=new classes.ui.PrestigeBtnController(this.game);dojo.forEach(this.game.prestige.perks,function(f,g){f=new com.nuclearunicorn.game.ui.BuildingResearchBtn({id:f.name,controller:d},c.game);f.render(b);c.addChild(f)});var e=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("prestige.btn.burnParagon.label"),description:$I("prestige.btn.burnParagon.desc"),
handler:dojo.hitch(this,function(){this.game.discardParagon()}),controller:new classes.ui.BurnParagonBtnController(c.game)},c.game);e.render(b);c.addChild(e);e=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("prestige.btn.turnHGOff.label"),description:$I("prestige.btn.turnHGOff.desc"),handler:dojo.hitch(this,function(){this.game.religion.turnHGOff()}),controller:new classes.ui.turnHGOffButtonController(c.game)},c.game);e.render(b);c.addChild(e)}});
