dojo.declare("classes.managers.ReligionManager",com.nuclearunicorn.core.TabManager,{game:null,pactsManager:null,transcendenceTier:0,faith:0,faithRatio:0,corruption:0,alicornCounter:0,activeHolyGenocide:0,constructor:function(a){this.game=a;this.registerMeta(!1,this.zigguratUpgrades,{getEffect:function(b,c){return"blackPyramid"==b.name?b.effects?b.effects[c]*b.getEffectiveValue(a):0:b.effects?b.effects[c]*b.on:0}});this.registerMeta("stackable",this.religionUpgrades,null);this.registerMeta(!1,this.transcendenceUpgrades,
{getEffect:function(b,c){c=b.effects[c]||0;return"holyGenocide"==b.name?c*a.religion.activeHolyGenocide:c*b.on}});this.pactsManager=new classes.religion.pactsManager(a);this.registerMeta("stackable",this.pactsManager.pacts,null);this.setEffectsCachedExisting()},resetState:function(){for(var a=this.faithRatio=this.transcendenceTier=this.corruption=this.faith=0;a<this.zigguratUpgrades.length;a++){var b=this.zigguratUpgrades[a];b.unlocked=b.defaultUnlocked||!1;this.resetStateStackable(b)}for(a=0;a<this.religionUpgrades.length;a++)this.resetStateStackable(this.religionUpgrades[a]);
for(a=0;a<this.transcendenceUpgrades.length;a++)b=this.transcendenceUpgrades[a],b.unlocked=!1,this.resetStateStackable(b);this.pactsManager.resetState()},save:function(a){a.religion={faith:this.faith,corruption:this.corruption,faithRatio:this.faithRatio,transcendenceTier:this.transcendenceTier,activeHolyGenocide:this.activeHolyGenocide,necrocornDeficit:this.pactsManager.necrocornDeficit,tcratio:this._getTranscendTotalPrice(this.transcendenceTier),zu:this.filterMetadata(this.zigguratUpgrades,["name",
"val","on","unlocked"]),ru:this.filterMetadata(this.religionUpgrades,["name","val","on"]),tu:this.filterMetadata(this.transcendenceUpgrades,["name","val","on","unlocked"]),pact:this.filterMetadata(this.pactsManager.pacts,["name","val","on","unlocked"])}},load:function(a){if(a.religion){var b=a.religion;this.faith=b.faith||0;this.corruption=b.corruption||0;this.faithRatio=b.faithRatio||0;this.transcendenceTier=b.transcendenceTier||0;this.activeHolyGenocide=b.activeHolyGenocide||0;this.pactsManager.necrocornDeficit=
a.religion.necrocornDeficit||0;0==this.transcendenceTier&&0<b.tcratio&&(this.transcendenceTier=Math.max(0,Math.round(Math.log(10*this.game.getUnlimitedDR(b.tcratio,.1)))));this.loadMetadata(this.zigguratUpgrades,b.zu);this.loadMetadata(this.religionUpgrades,b.ru);this.loadMetadata(this.transcendenceUpgrades,b.tu);this.loadMetadata(this.pactsManager.pacts,b.pact);for(a=0;a<this.transcendenceUpgrades.length;a++)b=this.transcendenceUpgrades[a],this.transcendenceTier>=b.tier&&(!b.evaluateLocks||b.evaluateLocks(this.game))&&
(b.unlocked=!0),0<b.val&&b.unlocks&&this.game.unlock(b.unlocks);b=this.pactsManager.pacts;for(a=0;a<b.length;a++)b[a].calculateEffects(b[a],this.game);this.getZU("blackPyramid").updateEffects(this.getZU("blackPyramid"),this.game);console.log("pactsAdjustment");!this.getPact("fractured").researched&&0<this.getZU("blackPyramid").val&&(0<this.game.religion.getTU("mausoleum").val||this.game.science.getPolicy("radicalXenophobia").researched)&&this.game.unlock({pacts:["pactOfCleansing","pactOfDestruction",
"pactOfExtermination","pactOfPurity"]})}},getCorruptionPerTickProduction:function(a){if(0<this.game.resPool.get("alicorn").value){var b=void 0===a?0<this.game.resPool.get("necrocorn").value:a;a=1+Math.sqrt(this.game.resPool.get("sorrow").value*this.game.getEffect("blsCorruptionRatio"));b=b?.25*(1+this.game.getEffect("corruptionBoostRatio")):1;return this.game.getEffect("corruptionRatio")*a*b}return 0},getCorruptionPerTickConsumption:function(){return 0<this.game.getFeatureFlag("MAUSOLEUM_PACTS")&&
this.game.science.getPolicy("siphoning").researched?this.game.getEffect("necrocornPerDay")/this.game.calendar.ticksPerDay:0},getCorruptionDeficitPerTick:function(){return Math.max(-this.getCorruptionPerTickProduction()-this.getCorruptionPerTickConsumption(),0)},getCorruptionPerTick:function(a){a=this.getCorruptionPerTickProduction(a);this.game.getFeatureFlag("MAUSOLEUM_PACTS")&&0<a&&this.game.science.getPolicy("siphoning").researched&&(a+=this.getCorruptionPerTickConsumption());return Math.max(a,
0)},update:function(){if(0<this.game.resPool.get("faith").value||this.game.challenges.isActive("atheism")&&0<this.game.bld.get("ziggurat").val)this.game.religionTab.visible=!0;isNaN(this.faith)&&(this.faith=0);0<this.game.resPool.get("alicorn").value?this.corruption+=this.getCorruptionPerTick():this.corruption=0;1<=this.corruption&&0<this.corruptNecrocorns()&&this.game.msg($I("religion.msg.corruption"),"important","alicornCorruption");0<=this.game.calendar.day&&this.triggerOrderOfTheVoid(1)},fastforward:function(a){var b=
a*this.game.calendar.ticksPerDay;isNaN(this.faith)&&(this.faith=0);this.necrocornFastForward(a,b);this.triggerOrderOfTheVoid(b)},corruptNecrocorns:function(){var a=this.game.resPool.get("alicorn"),b=Math.floor(Math.min(this.corruption,Math.ceil(a.value)-1));0<b&&(this.corruption-=b,a.value-=b,this.game.resPool.get("necrocorn").value+=b,this.game.upgrade({zigguratUpgrades:["skyPalace","unicornUtopia","sunspire"]}));1<=this.corruption&&(this.corruption=1);return b},necrocornsNaiveFastForward:function(a,
b){if(0<this.game.resPool.get("alicorn").value){var c=this.getCorruptionPerTick(),d=0==this.game.resPool.get("necrocorn").value?Math.min(Math.ceil((1-this.corruption)/c),b):0;0<d&&d<b?(this.corruption=1,b-=d,c=this.getCorruptionPerTick(!0),this.corruption+=b*c,this.game.resPool.get("necrocorn").value=0):this.corruption+=c*b}this.corruptNecrocorns();this.pactsManager.necrocornConsumptionDays(a)},gesSiphoningAlicornConsumptionPerDay:function(){if(this.game.science.getPolicy(["siphoning"]).researched){var a=
1;0<this.pactsManager.necrocornDeficit&&(a=1+.15*(1+this.game.getEffect("deficitRecoveryRatio")/2));return this.game.getEffect("necrocornPerDay")*a}return 0},necrocornFastForward:function(a,b){var c=1;0<this.pactsManager.necrocornDeficit&&(c=1+.15*(1+this.game.getEffect("deficitRecoveryRatio")/2));var d=this.game.getEffect("necrocornPerDay"),e=this.game.resPool.get("necrocorn").value,g=this.game.religion.getCorruptionPerTickProduction(!0),f=g*a*this.game.calendar.ticksPerDay+g;if(!this.game.science.getPolicy(["siphoning"]).researched&&
(0<=f||0>f&&0<e+f*a&&0<=this.game.resPool.get("alicorns").value-1+d*a))this.necrocornsNaiveFastForward(a,b);else{var k=this.game.religion.getCorruptionPerTickProduction(!1);0>g*a/this.game.calendar.ticksPerDay+d&&0<k*a/this.game.calendar.ticksPerDay+d?(f=this.game.resPool.get("alicorns").value-1+d*a,b=d*a,0<k*a/this.game.calendar.ticksPerDay+d*c&&0<this.pactsManager.necrocornDeficit&&(k+=d*(c-1)),g=-(d*a+g/this.game.calendar.ticksPerDay),k=d*a+k/this.game.calendar.ticksPerDay,a-=e*g,0>f&&(this.pactsManager.deficit-=
f,b+=f,a+=f/d),e=a%(k+g),this.pactsManager.necrocornDeficit+=a*k/(k+g)*d*(c-1),0>this.pactsManager.necrocornDeficit&&(this.pactsManager.necrocornDeficit=0),e/k<=1-this.corruption?(this.corruption+=e/k,this.game.resPool.get("necrocorn").value=0):this.game.resPool.get("necrocorn").value=(e-k)/g,this.game.resPool.addResPerTick("alicorn",b)):(e=Math.min(this.game.resPool.get("alicorn").value-1,d*a),f=this.pactsManager.getSiphonedCorruption(a),e=Math.max(e,-f),this.game.resPool.addResPerTick("alicorn",
e),0>this.game.resPool.get("necrocorn").value+d*a*c-e?(this.necrocornDeficit+=Math.max(-d*a-this.game.resPool.get("necrocorn").value+e,0),c=1):0<this.necrocornDeficit&&(this.necrocornDeficit+=.15*d*(1+this.game.getEffect("deficitRecoveryRatio"))*a,this.necrocornDeficit=Math.max(this.necrocornDeficit,0)),this.game.resPool.addResPerTick("necrocorn",d*c*a-e),this.corruption+=this.getCorruptionPerTick()*b,this.corruptNecrocorns())}},triggerOrderOfTheVoid:function(a){this.game.prestige.getPerk("voidOrder").researched&&
(a=a*this.game.calcResourcePerTick("faith")*.1*(1+this.game.getEffect("voidResonance")),this.faith+=a*(1+this.getApocryphaBonus()/4))},zigguratUpgrades:[{name:"unicornTomb",label:$I("religion.zu.unicornTomb.label"),description:$I("religion.zu.unicornTomb.desc"),prices:[{name:"ivory",val:500},{name:"tears",val:5}],priceRatio:1.15,effects:{unicornsRatioReligion:.05},unlocked:!0,defaultUnlocked:!0,unlocks:{zigguratUpgrades:["ivoryTower"]}},{name:"ivoryTower",label:$I("religion.zu.ivoryTower.label"),
description:$I("religion.zu.ivoryTower.desc"),prices:[{name:"ivory",val:25E3},{name:"tears",val:25}],priceRatio:1.15,effects:{unicornsRatioReligion:.1,riftChance:5E-4},unlocked:!1,defaultUnlocked:!1,unlocks:{zigguratUpgrades:["ivoryCitadel"]}},{name:"ivoryCitadel",label:$I("religion.zu.ivoryCitadel.label"),description:$I("religion.zu.ivoryCitadel.desc"),prices:[{name:"ivory",val:5E4},{name:"tears",val:50}],priceRatio:1.15,effects:{unicornsRatioReligion:.25,ivoryMeteorChance:5E-4},unlocked:!1,defaultUnlocked:!1,
unlocks:{zigguratUpgrades:["skyPalace"]}},{name:"skyPalace",label:$I("religion.zu.skyPalace.label"),description:$I("religion.zu.skyPalace.desc"),prices:[{name:"ivory",val:125E3},{name:"tears",val:500},{name:"megalith",val:5}],priceRatio:1.15,effects:{goldMaxRatio:0,unicornsRatioReligion:0,alicornChance:0,alicornPerTick:0,ivoryMeteorRatio:0},calculateEffects:function(a,b){var c={goldMaxRatio:.01,unicornsRatioReligion:.5,alicornChance:1E-4,alicornPerTick:0,ivoryMeteorRatio:.05};0<b.resPool.get("alicorn").value&&
(c.alicornPerTick=2E-5);a.effects=c},unlocked:!1,defaultUnlocked:!1,unlocks:{zigguratUpgrades:["unicornUtopia"]}},{name:"unicornUtopia",label:$I("religion.zu.unicornUtopia.label"),description:$I("religion.zu.unicornUtopia.desc"),prices:[{name:"gold",val:500},{name:"ivory",val:1E6},{name:"tears",val:5E3}],priceRatio:1.15,effects:{unicornsRatioReligion:0,alicornChance:0,alicornPerTick:0,tcRefineRatio:0,ivoryMeteorRatio:0},calculateEffects:function(a,b){var c={unicornsRatioReligion:2.5,alicornChance:1.5E-4,
alicornPerTick:0,tcRefineRatio:.05,ivoryMeteorRatio:.15};0<b.resPool.get("alicorn").value&&(c.alicornPerTick=2.5E-5);a.effects=c},unlocked:!1,defaultUnlocked:!1,unlocks:{zigguratUpgrades:["sunspire"]},unlockScheme:{name:"unicorn",threshold:1}},{name:"sunspire",label:$I("religion.zu.sunspire.label"),description:$I("religion.zu.sunspire.desc"),prices:[{name:"gold",val:1250},{name:"ivory",val:75E4},{name:"tears",val:25E3}],priceRatio:1.15,effects:{unicornsRatioReligion:0,alicornChance:0,alicornPerTick:0,
tcRefineRatio:0,ivoryMeteorRatio:0},calculateEffects:function(a,b){var c={unicornsRatioReligion:5,alicornChance:3E-4,alicornPerTick:0,tcRefineRatio:.1,ivoryMeteorRatio:.5};0<b.resPool.get("alicorn").value&&(c.alicornPerTick=5E-5);a.effects=c},unlocked:!1,defaultUnlocked:!1},{name:"marker",label:$I("religion.zu.marker.label"),description:$I("religion.zu.marker.desc"),prices:[{name:"unobtainium",val:2500},{name:"spice",val:5E4},{name:"tears",val:5E3},{name:"megalith",val:750}],priceRatio:1.15,effects:{corruptionRatio:1E-6},
calculateEffects:function(a,b){a.effects.corruptionRatio=1E-6*(1+b.getLimitedDR(b.getEffect("corruptionBoostRatioChallenge"),2))},unlocked:!1,getEffectiveValue:function(a){return this.val*(1+a.getLimitedDR(a.getEffect("corruptionBoostRatioChallenge"),2))}},{name:"unicornGraveyard",label:$I("religion.zu.unicornGraveyard.label"),description:$I("religion.zu.unicornGraveyard.desc"),prices:[{name:"necrocorn",val:5},{name:"megalith",val:1E3}],priceRatio:1.15,effects:{cultureMaxRatioBonus:.01,blackLibraryBonus:.02},
upgrades:{buildings:["ziggurat"]},unlocks:{zigguratUpgrades:["unicornNecropolis"]},unlocked:!1},{name:"unicornNecropolis",label:$I("religion.zu.unicornNecropolis.label"),description:$I("religion.zu.unicornNecropolis.desc"),prices:[{name:"alicorn",val:100},{name:"necrocorn",val:15},{name:"void",val:5},{name:"megalith",val:2500}],priceRatio:1.15,effects:{corruptionBoostRatio:.1},unlocked:!1},{name:"blackPyramid",label:$I("religion.zu.blackPyramid.label"),description:$I("religion.zu.blackPyramid.desc"),
prices:[{name:"unobtainium",val:5E3},{name:"spice",val:15E4},{name:"sorrow",val:5},{name:"megalith",val:2500}],priceRatio:1.15,effectsPreDeficit:{},jammed:!1,effects:{pyramidGlobalResourceRatio:0,pyramidGlobalProductionRatio:0,pyramidFaithRatio:0,deficitRecoveryRatio:0,blackLibraryBonus:0,pyramidSpaceCompendiumRatio:0},simpleEffectNames:["GlobalResourceRatio","RecoveryRatio","GlobalProductionRatio","FaithRatio","SpaceCompendiumRatio"],upgrades:{spaceBuilding:["spaceBeacon"]},calculateEffects:function(a,
b){a.togglable=!1;if(b.getFeatureFlag("MAUSOLEUM_PACTS")){a=b.religion.pactsManager.pacts;for(var c=0;c<a.length;c++)a[c].updatePreDeficitEffects&&a[c].updatePreDeficitEffects(b)}else for(c in a.effects)a.effects[c]=0},cashPreDeficitEffects:function(a){var b=Math.max(a.religion.transcendenceTier-25,1),c=a.religion.getZU("blackPyramid"),d;for(d in c.simpleEffectNames)c.effectsPreDeficit["pyramid"+c.simpleEffectNames[d]]=a.getEffect("pact"+c.simpleEffectNames[d])*b;c.effectsPreDeficit.deficitRecoveryRatio=
a.getEffect("pactDeficitRecoveryRatio");if(b*=a.getEffect("pactBlackLibraryBoost"))a=a.religion.getZU("unicornGraveyard"),c.effectsPreDeficit.blackLibraryBonus=b*a.effects.blackLibraryBonus*(1+a.on)},updateEffects:function(a,b){a.jammed||(a.cashPreDeficitEffects(b),a.jammed=!0);a.effects.deficitRecoveryRatio=a.effectsPreDeficit.deficitRecoveryRatio;var c=1-b.religion.pactsManager.necrocornDeficit/50,d=!1,e;for(e in a.effectsPreDeficit)if("deficitRecoveryRatio"!=e){var g=a.effects[e];a.effects[e]=
a.effectsPreDeficit[e]*c;a.effects[e]!=g&&(d=!0)}d&&b.upgrade(a.upgrades)},unlocked:!1,flavor:$I("religion.zu.blackPyramid.flavor"),getEffectiveValue:function(a){return this.val+(a.challenges.getChallenge("blackSky").researched&&!a.challenges.isActive("blackSky")?1:0)}}],religionUpgrades:[{name:"solarchant",label:$I("religion.ru.solarchant.label"),description:$I("religion.ru.solarchant.desc"),prices:[{name:"faith",val:100}],faith:150,effects:{faithRatioReligion:.1},calculateEffects:function(a,b){a.noStackable=
0==b.religion.getRU("transcendence").on},noStackable:!0,priceRatio:2.5},{name:"scholasticism",label:$I("religion.ru.scholasticism.label"),description:$I("religion.ru.scholasticism.desc"),prices:[{name:"faith",val:250}],faith:300,effects:{},upgrades:{buildings:["temple"]},calculateEffects:function(a,b){a.noStackable=0==b.religion.getRU("transcendence").on},noStackable:!0,priceRatio:2.5},{name:"goldenSpire",label:$I("religion.ru.goldenSpire.label"),description:$I("religion.ru.goldenSpire.desc"),prices:[{name:"gold",
val:150},{name:"faith",val:350}],faith:500,effects:{},upgrades:{buildings:["temple"]},calculateEffects:function(a,b){a.noStackable=0==b.religion.getRU("transcendence").on},noStackable:!0,priceRatio:2.5,flavor:$I("religion.ru.goldenSpire.flavor")},{name:"sunAltar",label:$I("religion.ru.sunAltar.label"),description:$I("religion.ru.sunAltar.desc"),prices:[{name:"gold",val:250},{name:"faith",val:500}],faith:750,effects:{},upgrades:{buildings:["temple"]},calculateEffects:function(a,b){a.noStackable=0==
b.religion.getRU("transcendence").on},noStackable:!0,priceRatio:2.5},{name:"stainedGlass",label:$I("religion.ru.stainedGlass.label"),description:$I("religion.ru.stainedGlass.desc"),prices:[{name:"gold",val:250},{name:"faith",val:500}],faith:750,effects:{},upgrades:{buildings:["temple"]},calculateEffects:function(a,b){a.noStackable=0==b.religion.getRU("transcendence").on},noStackable:!0,priceRatio:2.5},{name:"solarRevolution",label:$I("religion.ru.solarRevolution.label"),description:$I("religion.ru.solarRevolution.desc"),
prices:[{name:"gold",val:500},{name:"faith",val:750}],faith:1E3,effects:{solarRevolutionRatio:0},calculateEffects:function(a,b){a.effects.solarRevolutionRatio=b.religion.getSolarRevolutionRatio()},noStackable:!0},{name:"basilica",label:$I("religion.ru.basilica.label"),description:$I("religion.ru.basilica.desc"),prices:[{name:"gold",val:750},{name:"faith",val:1250}],faith:1E4,effects:{},upgrades:{buildings:["temple"]},calculateEffects:function(a,b){a.noStackable=0==b.religion.getRU("transcendence").on},
noStackable:!0,priceRatio:2.5},{name:"templars",label:$I("religion.ru.templars.label"),description:$I("religion.ru.templars.desc"),prices:[{name:"gold",val:3E3},{name:"faith",val:3500}],faith:75E3,effects:{},upgrades:{buildings:["temple"]},calculateEffects:function(a,b){a.noStackable=0==b.religion.getRU("transcendence").on},noStackable:!0,priceRatio:2.5},{name:"apocripha",label:$I("religion.ru.apocripha.label"),description:$I("religion.ru.apocripha.desc"),prices:[{name:"gold",val:5E3},{name:"faith",
val:5E3}],faith:1E5,effects:{},noStackable:!0},{name:"transcendence",label:$I("religion.ru.transcendence.label"),description:$I("religion.ru.transcendence.desc"),prices:[{name:"gold",val:7500},{name:"faith",val:7500}],faith:125E3,effects:{},upgrades:{religion:"solarchant scholasticism goldenSpire sunAltar stainedGlass basilica templars".split(" ")},noStackable:!0}],transcendenceUpgrades:[{name:"blackObelisk",label:$I("religion.tu.blackObelisk.label"),description:$I("religion.tu.blackObelisk.desc"),
prices:[{name:"relic",val:100}],tier:1,priceRatio:1.15,effects:{solarRevolutionLimit:.05},calculateEffects:function(a,b){a.effects.solarRevolutionLimit=.05*b.religion.transcendenceTier},unlocked:!1,flavor:$I("religion.tu.blackObelisk.flavor")},{name:"blackNexus",label:$I("religion.tu.blackNexus.label"),description:$I("religion.tu.blackNexus.desc"),prices:[{name:"relic",val:5E3}],tier:3,priceRatio:1.15,effects:{relicRefineRatio:1},upgrades:{spaceBuilding:["spaceBeacon"]},unlocked:!1,flavor:$I("religion.tu.blackNexus.flavor")},
{name:"blackCore",label:$I("religion.tu.blackCore.label"),description:$I("religion.tu.blackCore.desc"),prices:[{name:"relic",val:1E4}],tier:5,priceRatio:1.15,effects:{blsLimit:1},unlocked:!1,flavor:$I("religion.tu.blackCore.flavor")},{name:"singularity",label:$I("religion.tu.singularity.label"),description:$I("religion.tu.singularity.desc"),prices:[{name:"relic",val:25E3}],tier:7,priceRatio:1.15,effects:{globalResourceRatio:.1},unlocked:!1,flavor:$I("religion.tu.singularity.flavor")},{name:"blackLibrary",
label:$I("religion.tu.blackLibrary.label"),description:$I("religion.tu.blackLibrary.desc"),prices:[{name:"relic",val:3E4}],tier:9,priceRatio:1.15,effects:{compendiaTTBoostRatio:.02},unlocked:!1,flavor:$I("religion.tu.blackLibrary.flavor")},{name:"blackRadiance",label:$I("religion.tu.blackRadiance.label"),description:$I("religion.tu.blackRadiance.desc"),prices:[{name:"relic",val:37500}],tier:12,priceRatio:1.15,effects:{blsCorruptionRatio:.0012},unlocked:!1,flavor:$I("religion.tu.blackRadiance.flavor")},
{name:"blazar",label:$I("religion.tu.blazar.label"),description:$I("religion.tu.blazar.desc"),prices:[{name:"relic",val:5E4}],tier:15,priceRatio:1.15,effects:{timeRatio:.1,rrRatio:.02},upgrades:{chronoforge:["temporalImpedance"]},unlocked:!1,flavor:$I("religion.tu.blazar.flavor")},{name:"darkNova",label:$I("religion.tu.darkNova.label"),description:$I("religion.tu.darkNova.desc"),prices:[{name:"relic",val:75E3},{name:"void",val:7500}],tier:20,priceRatio:1.15,effects:{energyProductionRatio:.02},unlocked:!1,
flavor:$I("religion.tu.darkNova.flavor")},{name:"mausoleum",label:$I("religion.tu.mausoleum.label"),description:$I("religion.tu.mausoleum.desc"),tier:23,priceRatio:1.15,prices:[{name:"relic",val:5E4},{name:"void",val:12500},{name:"necrocorn",val:10}],effects:{pactsAvailable:1},upgrades:{pacts:["fractured"]},unlocked:!1,unlocks:{pacts:["pactOfCleansing","pactOfDestruction","pactOfExtermination","pactOfPurity"],policies:["siphoning"]},calculateEffects:function(a,b){b.getFeatureFlag("MAUSOLEUM_PACTS")?
(a.effects={pactsAvailable:1+b.getEffect("mausoleumBonus")},1<=b.religion.getPact("fractured").on&&(a.effects.pactsAvailable=0)):(a.effects.pactsAvailable=0,a.unlocked=!1);b.updateCaches()},evaluateLocks:function(a){return a.getFeatureFlag("MAUSOLEUM_PACTS")}},{name:"holyGenocide",label:$I("religion.tu.holyGenocide.label"),description:$I("religion.tu.holyGenocide.desc"),prices:[{name:"relic",val:1E5},{name:"void",val:25E3}],tier:25,priceRatio:1.15,effects:{maxKittensRatio:-.01,simScalingRatio:.02,
activeHG:0},unlocked:!1,unlocks:{challenges:["postApocalypse"]},calculateEffects:function(a,b){a.effects.activeHG=b.religion.activeHolyGenocide},togglable:!0,flavor:$I("religion.tu.holyGenocide.flavor")}],necrocornDeficitPunishment:function(){for(var a in this.game.village.sim.kittens){var b=this.game.village.sim.kittens[a].skills,c;for(c in b)b[c]=0}this.game.religion.getPact("fractured").on=1;this.game.religion.getPact("fractured").val=1;this.game.upgrade({transcendenceUpgrades:["mausoleum"],policies:["radicalXenophobia"],
pacts:["fractured"]});this.game.religion.necrocornDeficit=0;this.game.msg($I("msg.pacts.fractured",[Math.round(100*this.game.resPool.get("alicorn").value)/100]),"alert","ai");this.game.resPool.get("alicorn").value=0;a=this.game.religion.getZU("blackPyramid");for(var d in a.effectsPreDeficit)a.effectsPreDeficit[d]=0;this.game.religion.getZU("blackPyramid").updateEffects(this.game.religion.getZU("blackPyramid"),this.game)},effectsBase:{kittensKarmaPerMinneliaRatio:1E-4,pactNecrocornConsumption:-5E-4},
getZU:function(a){return this.getMeta(a,this.zigguratUpgrades)},getRU:function(a){return this.getMeta(a,this.religionUpgrades)},getTU:function(a){return this.getMeta(a,this.transcendenceUpgrades)},getPact:function(a){return this.getMeta(a,this.pactsManager.pacts)},getSolarRevolutionRatio:function(){var a=this.getRU("solarRevolution").on?this.game.getUnlimitedDR(this.faith,1E3)/100:0;return this.game.getLimitedDR(a,10+this.game.getEffect("solarRevolutionLimit")+(this.game.challenges.getChallenge("atheism").researched?
this.game.religion.transcendenceTier:0))*(1+this.game.getLimitedDR(this.game.getEffect("faithSolarRevolutionBoost"),4))},getApocryphaBonus:function(){return.1*this.game.getUnlimitedDR(this.faithRatio,.1)},getHGScalingBonus:function(){var a=this.game.getLimitedDR(this.game.getEffect("simScalingRatio"),1);return a?1/(1+this.game.getLimitedDR(this.game.getEffect("maxKittensRatio"),1))*(1+a):1},turnHGOff:function(){var a=this;this.game.ui.confirm("",$I("turnHGOff.confirmation.msg"),function(){a.activeHolyGenocide=
0;a.getTU("holyGenocide").on=0})},praise:function(){var a=this.game.resPool.get("faith");this.faith+=a.value*(1+this.getApocryphaBonus());this.game.msg($I("religion.praise.msg",[this.game.getDisplayValueExt(a.value,!1,!1,0)]),"","faith");a.value=1E-4},getApocryphaResetBonus:function(a){this.getRU("transcendence").on&&(a*=Math.pow(1+this.transcendenceTier,2));return this.faith/1E5*.1*a},resetFaith:function(a,b){if(b&&!this.game.opts.noConfirm){var c=this;this.game.ui.confirm("",$I("religion.adore.confirmation.msg"),
function(){c._resetFaithInternal(a)})}else this._resetFaithInternal(a)},_resetFaithInternal:function(a){var b=(this.game.religion.getRU("transcendence").on?this.game.religion.transcendenceTier:0)+1;this.faithRatio+=this.faith/1E6*b*b*a;this.faith=.01},transcend:function(){var a=this.game.religion;if(a.getRU("transcendence").on){var b=this.game;b.ui.confirm($I("religion.transcend.confirmation.title"),$I("religion.transcend.confirmation.msg"),function(){var c=a._getTranscendTotalPrice(a.transcendenceTier+
1)-a._getTranscendTotalPrice(a.transcendenceTier);a.faithRatio>c?(a.faithRatio-=c,a.tcratio+=c,a.transcendenceTier+=1,c=b.challenges.getChallenge("atheism"),c.calculateEffects(c,b),c=a.getTU("blackObelisk"),c.calculateEffects(c,b),b.getFeatureFlag("MAUSOLEUM_PACTS")&&b.religion.getTU("mausoleum").val&&(c=b.religion.getZU("blackPyramid"),c.calculateEffects(c,b),c.cashPreDeficitEffects(b)),b.msg($I("religion.transcend.msg.success",[a.transcendenceTier]))):b.msg($I("religion.transcend.msg.failure",[b.toDisplayPercentage(a.faithRatio/
c,2,!0)]))})}},_getTranscendTotalPrice:function(a){return this.game.getInverseUnlimitedDR(Math.exp(a)/10,.1)},unlockAll:function(){for(var a in this.religionUpgrades)this.religionUpgrades[a].unlocked=!0,this.religionUpgrades[a].researched=!0;for(a in this.zigguratUpgrades)this.zigguratUpgrades[a].unlocked=!0;for(a in this.transcendenceUpgrades)this.transcendenceUpgrades[a].unlocked=!0;for(a in this.pacts)this.pacts[a].unlocked=!0;this.faith=1E6;this.transcendenceTier=25;this.game.msg("All religion upgrades are unlocked!")},
undo:function(a){var b=this.game.resPool;"refine"==a.action&&b.get(a.resTo).value>a.valTo&&(this.game.resPool.addResEvent(a.resFrom,a.valFrom),this.game.resPool.addResEvent(a.resTo,-a.valTo))}});
dojo.declare("com.nuclearunicorn.game.ui.ZigguratBtnController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.tooltipName=!0;return a},getMetadata:function(a){a.metaCached||(a.metaCached=this.game.religion.getZU(a.options.id));return a.metaCached},getName:function(a){if("marker"==a.metadata.name&&0<a.metadata.val){var b=this.game.toDisplayPercentage(this.game.religion.corruption,0,!0);return a.metadata.label+" ["+b+"%] ("+a.metadata.val+
")"}return this.inherited(arguments)}});
dojo.declare("com.nuclearunicorn.game.ui.ReligionBtnController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.tooltipName=!0;return a},getMetadata:function(a){a.metaCached||(a.metaCached=this.game.religion.getRU(a.options.id));return a.metaCached},hasSellLink:function(a){return!this.game.opts.hideSell&&!a.metadata.noStackable&&1<a.metadata.val},getPrices:function(a){return this.game.village.getEffectLeader("wise",this.inherited(arguments))},
updateVisible:function(a){a.visible=0<a.metadata.on||this.game.religion.faith>=a.metadata.faith}});dojo.declare("classes.ui.TranscendenceBtnController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.tooltipName=!0;return a},getMetadata:function(a){a.metaCached||(a.metaCached=this.game.religion.getTU(a.options.id));return a.metaCached}});
dojo.declare("com.nuclearunicorn.game.ui.PraiseBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{getName:function(a){return 0<this.game.religion.faithRatio?a.options.name+" ["+this.game.getDisplayValueExt(100*this.game.religion.getApocryphaBonus(),!0,!1,3)+"%]":a.options.name}});
dojo.declare("com.nuclearunicorn.game.ui.ResetFaithBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{getName:function(a){var b=this.game.religion.transcendenceTier+1;return a.options.name+(this.game.religion.getRU("transcendence").on?" [\u00d7"+b*b+"]":"")},updateVisible:function(a){a.visible=this.game.religion.getRU("apocripha").on}});
dojo.declare("com.nuclearunicorn.game.ui.TranscendBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{getName:function(a){return a.options.name+(0<this.game.religion.transcendenceTier?" ["+this.game.religion.transcendenceTier+"]":"")},updateVisible:function(a){a.visible=this.game.religion.getRU("transcendence").on}});
dojo.declare("classes.ui.religion.TransformBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{defaults:function(){var a=this.inherited(arguments);a.hasResourceHover=!0;a.simplePrices=!1;return a},fetchModel:function(a){var b=this.inherited(arguments);b.fifthLink=this._newLink(b,5);b.halfLink=this._newLink(b,2);b.allLink=this._newLink(b,1);return b},_newLink:function(a,b){var c=Math.floor(this._canAfford(a)/b),d=this;return{visible:this.game.opts.showNonApplicableButtons||1<c,title:1==
b?$I("religion.sacrificeBtn.all"):this.game.opts.usePercentageConsumptionValues?100/b+"%":"x"+this.game.getDisplayValueExt(c,null,!1,0),tooltip:1==b||this.game.opts.usePercentageConsumptionValues?"x"+this.game.getDisplayValueExt(c,null,!1,0):100/b+"%",handler:function(e,g){d.transform(a,b,e,g)}}},buyItem:function(a,b,c){a.enabled&&this.hasResources(a)&&c(this._transform(a,b.shiftKey?1E4:b.ctrlKey||b.metaKey?this.game.opts.batchSize:1));c(!1)},_canAfford:function(a){return Math.floor(this.game.resPool.get(a.prices[0].name).value/
a.prices[0].val)},transform:function(a,b,c,d){c=Math.floor(this._canAfford(a)/b);c=Infinity==c?Number.MAX_VALUE/a.prices[0].val/b:c;a.enabled&&1<=c&&d(this._transform(a,c));d(!1)},_transform:function(a,b){var c=a.prices[0].val*b;if(c>this.game.resPool.get(a.prices[0].name).value)return!1;b*=this.controllerOpts.gainMultiplier.call(this);this.game.resPool.addResEvent(a.prices[0].name,-c);this.game.resPool.addResEvent(this.controllerOpts.gainedResource,b);this.controllerOpts.applyAtGain&&this.controllerOpts.applyAtGain.call(this,
c);this.game.registerUndoChange().addEvent("religion",{action:"refine",resFrom:a.prices[0].name,resTo:this.controllerOpts.gainedResource,valFrom:c,valTo:b});this.game.msg($I(this.controllerOpts.logTextID,[this.game.getDisplayValueExt(c),this.game.getDisplayValueExt(b)]),"",this.controllerOpts.logfilterID);return!0}});
dojo.declare("classes.ui.religion.MultiLinkBtn",com.nuclearunicorn.game.ui.ButtonModern,{renderLinks:function(){this.all=this.addLink(this.model.allLink);this.half=this.addLink(this.model.halfLink);this.fifth=this.addLink(this.model.fifthLink)},update:function(){this.inherited(arguments);this.updateLink(this.fifth,this.model.fifthLink);this.updateLink(this.half,this.model.halfLink);this.updateLink(this.all,this.model.allLink)}});
dojo.declare("classes.ui.religion.RefineTearsBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{defaults:function(){var a=this.inherited(arguments);a.hasResourceHover=!0;return a},fetchModel:function(a){var b=this.inherited(arguments);b.fiveLink=this._newLink(b,5);b.twentyFiveLink=this._newLink(b,25);b.hundredLink=this._newLink(b,100);return b},_newLink:function(a,b){var c=this;return{visible:this.game.opts.showNonApplicableButtons||this.game.resPool.get("sorrow").value<=this.game.resPool.get("sorrow").maxValue-
b&&c._canAfford(a,b)>=b,title:"x"+b,handler:function(d){c.buyItem(a,{},this.update.bind(this),b)}}},_canAfford:function(a,b){return Math.floor(this.game.resPool.get(a.prices[0].name).value/a.prices[0].val)},buyItem:function(a,b,c,d){if(a.enabled&&this.hasResources(a)){if(this.game.resPool.get("sorrow").value>=this.game.resPool.get("sorrow").maxValue){this.game.msg($I("religion.refineTearsBtn.refine.msg.failure"));c(!1);return}for(b=d||(b.ctrlKey?this.game.opts.batchSize:1);0<b&&this.hasResources(a)&&
this.game.resPool.get("sorrow").value<this.game.resPool.get("sorrow").maxValue;b--)this.payPrice(a),this.refine();c(!0)}c(!1)},refine:function(){this.game.resPool.get("sorrow").value++}});
dojo.declare("classes.ui.CryptotheologyWGT",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){var b=this,c=classes.ui.TranscendenceBtnController(a);dojo.forEach(a.religion.transcendenceUpgrades,function(d,e){d=new com.nuclearunicorn.game.ui.BuildingStackableBtn({id:d.name,name:d.label,description:d.description,controller:c},a);b.addChild(d)})},render:function(a){var b=dojo.create("div",null,a);b=dojo.create("div",null,b);this.inherited(arguments,[b])},update:function(){this.inherited(arguments)}});
dojo.declare("classes.ui.CryptotheologyPanel",com.nuclearunicorn.game.ui.Panel,{visible:!1});
dojo.declare("classes.ui.PactsWGT",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){var b=this,c=com.nuclearunicorn.game.ui.PactsBtnController(a);dojo.forEach(a.religion.pactsManager.pacts,function(d,e){d=new com.nuclearunicorn.game.ui.BuildingStackableBtn({id:d.name,name:d.label,description:d.description,controller:c},a);b.addChild(d)})},render:function(a){var b=dojo.create("div",null,a);dojo.create("span",{innerHTML:this.game.religion.pactsManager.getPactsTextSum()},b);var c=dojo.create("div",
null,b);dojo.create("span",{innerHTML:this.game.religion.pactsManager.getPactsTextDeficit()},b);this.inherited(arguments,[c])},update:function(){this.inherited(arguments)}});dojo.declare("classes.ui.PactsPanel",com.nuclearunicorn.game.ui.Panel,{visible:!1});
dojo.declare("com.nuclearunicorn.game.ui.PactsBtnController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.tooltipName=!0;return a},getMetadata:function(a){a.metaCached||(a.metaCached=this.game.religion.getPact(a.options.id));return a.metaCached},updateEnabled:function(a){this.inherited(arguments);0>=this.game.getEffect("pactsAvailable")&&0!=a.metadata.effects.pactsAvailable&&(a.enabled=!1)},shouldBeBough:function(a,b){return 0<=b.getEffect("pactsAvailable")+
a.metadata.effects.pactsAvailable},buyItem:function(a,b,c){this.game.updateCaches();this.updateEnabled(a);this.hasResources(a)||this.game.devMode?this.shouldBeBough(a,this.game)?this._buyItem_step2(a,b,c):c(!1):c(!1)},build:function(a,b){var c=a.metadata,d=0;"number"==typeof c.limitBuild&&c.limitBuild-c.val<b&&(b=c.limitBuild-c.val);0!=c.effects.pactsAvailable&&(b=Math.min(b,this.game.getEffect("pactsAvailable")/-c.effects.pactsAvailable));if(a.enabled&&this.hasResources(a)||this.game.devMode){for(;this.hasResources(a)&&
0<b;)this.incrementValue(a),this.payPrice(a),d++,b--;c.notAddDeficit||(this.game.religion.pactsManager.necrocornDeficit+=.5*d);1<d&&this.game.msg(c.label+" x"+d+" constructed.","notice");c.breakIronWill&&(this.game.ironWill=!1);c.unlocks&&this.game.unlock(c.unlocks);c.unlockScheme&&c.val>=c.unlockScheme.threshold&&this.game.ui.unlockScheme(c.unlockScheme.name);c.upgrades&&(c.updateEffects&&c.updateEffects(c,this.game),this.game.upgrade(c.upgrades));c.updatePreDeficitEffects&&c.updatePreDeficitEffects(this.game);
c.special||this.game.upgrade({pacts:["payDebt"]});"payDebt"!=c.name&&(this.game.religion.getZU("blackPyramid").jammed=!1)}return d}});
dojo.declare("classes.ui.religion.RefineBtn",com.nuclearunicorn.game.ui.ButtonModern,{renderLinks:function(){this.hundred=this.addLink(this.model.hundredLink);this.twentyFive=this.addLink(this.model.twentyFiveLink);this.five=this.addLink(this.model.fiveLink)},update:function(){this.inherited(arguments);dojo.style(this.five.link,"display",this.model.fiveLink.visible?"":"none");dojo.style(this.twentyFive.link,"display",this.model.twentyFiveLink.visible?"":"none");dojo.style(this.hundred.link,"display",
this.model.hundredLink.visible?"":"none")}});
dojo.declare("classes.religion.pactsManager",null,{game:null,necrocornDeficit:0,fractureNecrocornDeficit:50,pacts:[{name:"pactOfCleansing",label:$I("religion.pact.pactOfCleansing.label"),description:$I("religion.pact.pactOfCleansing.desc"),prices:[{name:"relic",val:100}],unlocks:{},priceRatio:1,effects:{pactsAvailable:-1,necrocornPerDay:0,pactDeficitRecoveryRatio:.003,pactGlobalResourceRatio:5E-4},unlocked:!1,calculateEffects:function(a,b){b.getFeatureFlag("MAUSOLEUM_PACTS")&&(a.effects.necrocornPerDay=
b.getEffect("pactNecrocornConsumption"))}},{name:"pactOfDestruction",label:$I("religion.pact.pactOfDestruction.label"),description:$I("religion.pact.pactOfDestruction.desc"),prices:[{name:"relic",val:100}],priceRatio:1,unlocks:{},effects:{pactsAvailable:-1,necrocornPerDay:0,pactDeficitRecoveryRatio:-1E-4,pactGlobalProductionRatio:5E-4},unlocked:!1,calculateEffects:function(a,b){b.getFeatureFlag("MAUSOLEUM_PACTS")&&(a.effects.necrocornPerDay=b.getEffect("pactNecrocornConsumption"))}},{name:"pactOfExtermination",
label:$I("religion.pact.pactOfExtermination.label"),description:$I("religion.pact.pactOfExtermination.desc"),prices:[{name:"relic",val:100}],priceRatio:1.02,effects:{pactsAvailable:-1,necrocornPerDay:0,pactFaithRatio:.001},unlocked:!1,calculateEffects:function(a,b){b.getFeatureFlag("MAUSOLEUM_PACTS")&&(a.effects.necrocornPerDay=b.getEffect("pactNecrocornConsumption"))}},{name:"pactOfPurity",label:$I("religion.pact.pactOfPurity.label"),description:$I("religion.pact.pactOfPurity.desc"),prices:[{name:"relic",
val:100}],priceRatio:1,effects:{pactsAvailable:-1,necrocornPerDay:0,pactDeficitRecoveryRatio:.005,pactBlackLibraryBoost:5E-4,pactSpaceCompendiumRatio:.001},unlocked:!1,calculateEffects:function(a,b){b.getFeatureFlag("MAUSOLEUM_PACTS")&&(a.effects.necrocornPerDay=b.getEffect("pactNecrocornConsumption"),b.religion.getZU("blackPyramid").jammed=!1)}},{name:"payDebt",label:$I("religion.pact.payDebt.label"),description:$I("religion.pact.payDebt.desc"),prices:[{name:"necrocorn",val:0}],upgrades:{pacts:["payDebt"]},
priceRatio:1,effects:{pactsAvailable:0},special:!0,unlocked:!1,calculateEffects:function(a,b){a.onNewDay(b);0<a.val&&(a.on=0,a.val=0,b.religion.pactsManager.necrocornDeficit=0,a.unlocked=!1)},onNewDay:function(a){var b=a.religion.getPact("payDebt");b.prices[0].val=Math.ceil(a.religion.pactsManager.necrocornDeficit);b.unlocked=this.evaluateLocks(a)},limitBuild:1,notAddDeficit:!0,evaluateLocks:function(a){return 0<a.religion.pactsManager.necrocornDeficit&&a.getFeatureFlag("MAUSOLEUM_PACTS")}},{name:"fractured",
label:$I("religion.pact.fractured.label"),description:$I("religion.pact.fractured.desc"),prices:[{name:"catnip",val:1}],effects:{pyramidGlobalResourceRatio:-.5,pyramidGlobalProductionRatio:-.5,pyramidFaithRatio:-.5,pactsAvailable:0},limitBuild:1,special:!0,unlocked:!1,calculateEffects:function(a,b){if(!b.getFeatureFlag("MAUSOLEUM_PACTS"))a.effects={pyramidGlobalResourceRatio:0,pyramidGlobalProductionRatio:0,pyramidFaithRatio:0,pactsAvailable:0};else if(1<=a.on){for(var c=0;c<b.religion.pactsManager.pacts.length;c++)b.religion.pactsManager.pacts[c].on=
0,b.religion.pactsManager.pacts[c].val=0,b.religion.pactsManager.pacts[c].unlocked="fractured"==b.religion.pactsManager.pacts[c].name;a.val=1;a.on=1}}}],necrocornDeficitPunishment:function(){for(var a in this.game.village.sim.kittens){var b=this.game.village.sim.kittens[a].skills,c;for(c in b)b[c]=0}this.game.religion.getPact("fractured").on=1;this.game.religion.getPact("fractured").val=1;this.game.upgrade({transcendenceUpgrades:["mausoleum"],policies:["radicalXenophobia"],pacts:["fractured"]});this.game.religion.pactsManager.necrocornDeficit=
0;this.game.msg($I("msg.pacts.fractured",[Math.round(100*this.game.resPool.get("alicorn").value)/100]),"alert","ai");this.game.resPool.get("alicorn").value=0;a=this.game.religion.getZU("blackPyramid");for(var d in a.effectsPreDeficit)a.effectsPreDeficit[d]=0;this.game.religion.getZU("blackPyramid").updateEffects(this.game.religion.getZU("blackPyramid"),this.game)},constructor:function(a){this.game=a},resetState:function(){for(var a in this.game.religion.pactsManager.pacts)this.game.religion.pactsManager.pacts[a].on=
0,this.game.religion.pactsManager.pacts[a].val=0,this.game.religion.pactsManager.pacts[a].unlocked=!1},getPactsTextSum:function(){return $I("msg.pacts.info",[this.game.getEffect("pactsAvailable"),-this.game.getEffect("pactNecrocornConsumption")])},getPactsTextDeficit:function(){return 0<this.game.religion.pactsManager.necrocornDeficit?$I("msg.necrocornDeficit.info",[Math.round(1E4*this.game.religion.pactsManager.necrocornDeficit)/1E4,-Math.round(this.game.religion.pactsManager.necrocornDeficit/50*
100),Math.round(1500*(1+this.game.getEffect("deficitRecoveryRatio")/2))/100,-Math.round(.15*this.game.getEffect("necrocornPerDay")*(1+this.game.getEffect("deficitRecoveryRatio"))*1E6)/1E6]):""},getNecrocornDeficitConsumptionModifier:function(){if(0>=this.necrocornDeficit)return 1;var a=this.game.getEffect("necrocornPerDay");if(this.game.science.getPolicy(["siphoning"]).researched&&0==this.game.religion.getCorruptionDeficitPerTick()&&1<=this.game.resPool.get("alicorn").value-a)return 1;var b=1+.15*
(1+this.game.getEffect("deficitRecoveryRatio")/2);0>this.game.resPool.get("necrocorn").value+a*b&&(b=Math.max((a*b+this.game.resPool.get("necrocorn").value)/a,0));return b},getSiphonedCorruption:function(a){var b=this.game.getEffect("necrocornPerDay");return this.game.science.getPolicy(["siphoning"]).researched?0>=this.game.religion.getCorruptionDeficitPerTick()?-b*a:Math.min(-b*a,this.game.religion.getCorruptionPerTickProduction()*this.game.calendar.ticksPerDay*a):0},necrocornConsumptionDays:function(a){var b=
1,c=this.game.getEffect("necrocornPerDay"),d=0;if(this.game.science.getPolicy(["siphoning"]).researched){if(0==this.game.religion.getCorruptionDeficitPerTick()&&1<=this.game.resPool.get("alicorn").value-c*a){this.game.resPool.addResPerTick("alicorn",c*a);return}d=Math.min(this.game.resPool.get("alicorn").value-1,c*a);var e=this.getSiphonedCorruption(a);d=Math.max(d,-e);this.game.resPool.addResPerTick("alicorn",d)}0<this.necrocornDeficit&&(b=1+.15*(1+this.game.getEffect("deficitRecoveryRatio")/2));
0>this.game.resPool.get("necrocorn").value+c*a*b-d?(this.necrocornDeficit+=Math.max(-c*a-this.game.resPool.get("necrocorn").value+d,0),b=1):0<this.necrocornDeficit&&(this.necrocornDeficit+=.15*c*(1+this.game.getEffect("deficitRecoveryRatio"))*a,this.necrocornDeficit=Math.max(this.necrocornDeficit,0));this.game.resPool.addResPerTick("necrocorn",c*b*a-d)},pactsMilleniumKarmaKittens:function(a){var b=Math.round(this.game.resPool.get("kittens").value*(1+this.game.getEffect("simScalingRatio")));if(35<
b&&0<this.game.getEffect("pactsAvailable")){var c=this.game.getEffect("kittensKarmaPerMinneliaRatio");this.game.karmaKittens+=a*this.game._getKarmaKittens(b)*this.game.getUnlimitedDR(c*Math.max(1+.1*(this.game.religion.transcendenceTier-25),1)*this.game.getEffect("pactsAvailable"),100);a=this.game.resPool.get("karma").value;this.game.updateKarma();return this.game.resPool.get("karma").value-a}return 0}});
dojo.declare("com.nuclearunicorn.game.ui.tab.ReligionTab",com.nuclearunicorn.game.ui.tab,{sacrificeBtn:null,sacrificeAlicornsBtn:null,zgUpgradeButtons:null,rUpgradeButtons:null,pactUpgradeButtons:null,constructor:function(){this.zgUpgradeButtons=[];this.rUpgradeButtons=[];this.pactUpgradeButtons=[];var a=new classes.ui.CryptotheologyPanel($I("religion.panel.cryptotheology.label"));a.game=this.game;this.addChild(a);this.ctPanel=a;var b=new classes.ui.CryptotheologyWGT(this.game);b.setGame(this.game);
a.addChild(b);a=new classes.ui.PactsPanel("Pacts");a.game=this.game;this.addChild(a);this.ptPanel=a;b=new classes.ui.PactsWGT(this.game);b.setGame(this.game);a.addChild(b)},render:function(a){var b=this.game;this.zgUpgradeButtons=[];this.rUpgradeButtons=[];this.pactUpgradeButtons=[];if(0<b.bld.get("ziggurat").on){var c=(new com.nuclearunicorn.game.ui.Panel($I("religion.panel.ziggurat.label"),b.religion)).render(a),d=new classes.ui.religion.MultiLinkBtn({name:$I("religion.sacrificeBtn.label"),description:$I("religion.sacrificeBtn.desc"),
prices:[{name:"unicorns",val:2500}],controller:new classes.ui.religion.TransformBtnController(b,{gainMultiplier:function(){return this.game.bld.get("ziggurat").on},gainedResource:"tears",applyAtGain:function(h){this.game.stats.getStat("unicornsSacrificed").val+=h},logTextID:"religion.sacrificeBtn.sacrifice.msg",logfilterID:"unicornSacrifice"})},b);d.render(c);this.sacrificeBtn=d;d=classes.ui.religion.MultiLinkBtn({name:$I("religion.sacrificeAlicornsBtn.label"),description:$I("religion.sacrificeAlicornsBtn.desc"),
prices:[{name:"alicorn",val:25}],controller:new classes.ui.religion.TransformBtnController(b,{updateVisible:function(h){h.visible=this.hasResources(h)||0<this.game.resPool.get("alicorn").value&&this.game.resPool.get("timeCrystal").unlocked},gainMultiplier:function(){return 1+this.game.getEffect("tcRefineRatio")},gainedResource:"timeCrystal",applyAtGain:function(){this.game.upgrade({zigguratUpgrades:["skyPalace","unicornUtopia","sunspire"]})},logTextID:"religion.sacrificeAlicornsBtn.sacrifice.msg",
logfilterID:"alicornSacrifice"})},b);d.render(c);this.sacrificeAlicornsBtn=d;d=new classes.ui.religion.RefineBtn({name:$I("religion.refineTearsBtn.label"),description:$I("religion.refineTearsBtn.desc"),prices:[{name:"tears",val:1E4}],controller:new classes.ui.religion.RefineTearsBtnController(b,{updateVisible:function(h){h.visible=this.game.religion.getZU("blackPyramid").unlocked}})},b);d.render(c);this.refineBtn=d;d=new classes.ui.religion.MultiLinkBtn({name:$I("religion.refineTCsBtn.label"),description:$I("religion.refineTCsBtn.desc"),
prices:[{name:"timeCrystal",val:25}],controller:new classes.ui.religion.TransformBtnController(b,{updateVisible:function(h){h.visible=this.hasResources(h)},gainMultiplier:function(){return 1+this.game.getEffect("relicRefineRatio")*this.game.religion.getZU("blackPyramid").getEffectiveValue(this.game)},gainedResource:"relic",logTextID:"religion.refineTCsBtn.refine.msg",logfilterID:"tcRefine"})},b);d.render(c);this.refineTCBtn=d;var e=new com.nuclearunicorn.game.ui.ZigguratBtnController(b);d=b.religion.zigguratUpgrades;
for(var g=0;g<d.length;g++){var f=d[g],k=new com.nuclearunicorn.game.ui.BuildingStackableBtn({id:f.name,name:f.label,description:f.description,prices:f.prices,controller:e,handler:f.handler},b);k.render(c);this.zgUpgradeButtons.push(k)}}if(!b.challenges.isActive("atheism")){c=(new com.nuclearunicorn.game.ui.Panel($I("religion.panel.orderOfTheSun.label"),b.religion)).render(a);this.faithCount=dojo.create("span",{style:{display:"inline-block",marginBottom:"10px"}},c);this.praiseBtn=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("religion.praiseBtn.label"),
description:$I("religion.praiseBtn.desc"),controller:new com.nuclearunicorn.game.ui.PraiseBtnController(b),handler:function(){b.religion.praise()}},b);this.adoreBtn=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("religion.adoreBtn.label"),description:$I("religion.adoreBtn.desc"),controller:new com.nuclearunicorn.game.ui.ResetFaithBtnController(b),handler:function(h){b.religion.resetFaith(1.01,!0)}},b);this.transcendBtn=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("religion.transcendBtn.label"),
description:$I("religion.transcendBtn.desc"),controller:new com.nuclearunicorn.game.ui.TranscendBtnController(b),handler:function(h){b.religion.transcend();h=b.religion.transcendenceTier;for(var l=0;l<b.religion.transcendenceUpgrades.length;l++)(!b.religion.transcendenceUpgrades[l].evaluateLocks||b.religion.transcendenceUpgrades[l].evaluateLocks(b))&&h>=b.religion.transcendenceUpgrades[l].tier&&(b.religion.transcendenceUpgrades[l].unlocked=!0)}},b);e={transcendence:this.transcendBtn};this.praiseBtn.render(c);
this.adoreBtn.render(c);var m=new com.nuclearunicorn.game.ui.ReligionBtnController(b);d=b.religion.religionUpgrades;for(g=0;g<d.length;g++)f=d[g],k=new com.nuclearunicorn.game.ui.BuildingStackableBtn({id:f.name,name:f.label,description:f.description,prices:f.prices,controller:m,handler:function(h){h=h.model.metadata;h.upgrades&&b.upgrade(h.upgrades)}},b),k.render(c),(f=e[f.name])&&f.render(c),this.rUpgradeButtons.push(k)}this.inherited(arguments);this.update()},update:function(){this.inherited(arguments);
var a=this.game.religion;this.sacrificeBtn&&this.sacrificeBtn.update();this.sacrificeAlicornsBtn&&this.sacrificeAlicornsBtn.update();this.refineBtn&&this.refineBtn.update();this.refineTCBtn&&this.refineTCBtn.update();if(!this.game.challenges.isActive("atheism")){this.praiseBtn&&this.praiseBtn.update();var b=this.game.religion.getRU("solarRevolution");b.calculateEffects(b,this.game);this.adoreBtn&&this.adoreBtn.update();this.transcendBtn&&this.transcendBtn.update();this.faithCount.innerHTML=a.faith&&
this.faithCount?$I("religion.faithCount.pool",[this.game.getDisplayValueExt(a.faith)]):"";a=a.getSolarRevolutionRatio();0!=a&&(this.faithCount.innerHTML+=" (+"+this.game.getDisplayValueExt(100*a)+"% "+$I("religion.faithCount.bonus")+")");dojo.forEach(this.rUpgradeButtons,function(c,d){c.update()})}this.game.science.get("cryptotheology").researched&&0<this.game.religion.transcendenceTier&&this.ctPanel.setVisible(!0);dojo.forEach(this.zgUpgradeButtons,function(c,d){c.update()});(a=(a=!this.game.religion.getPact("fractured").researched&&
0<this.game.religion.getZU("blackPyramid").val&&(0<this.game.religion.getTU("mausoleum").val||this.game.science.getPolicy("radicalXenophobia").researched))&&this.game.getFeatureFlag("MAUSOLEUM_PACTS"))&&this.ptPanel.setVisible(!0)}});
