dojo.declare("classes.managers.ResourceManager",com.nuclearunicorn.core.TabManager,{resourceData:[{name:"catnip",title:$I("resources.catnip.title"),type:"common",visible:!0,calculatePerTick:!0,aiCanDestroy:!0},{name:"wood",title:$I("resources.wood.title"),type:"common",craftable:!0,visible:!0,calculatePerTick:!0,aiCanDestroy:!0},{name:"minerals",title:$I("resources.minerals.title"),type:"common",visible:!0,calculatePerTick:!0,aiCanDestroy:!0},{name:"coal",title:$I("resources.coal.title"),type:"common",
visible:!0,calculatePerTick:!0,aiCanDestroy:!0},{name:"iron",title:$I("resources.iron.title"),type:"common",visible:!0,calculatePerTick:!0,aiCanDestroy:!0,tag:"baseMetal"},{name:"titanium",title:$I("resources.titanium.title"),type:"common",visible:!0,calculatePerTick:!0,aiCanDestroy:!0,tag:"baseMetal"},{name:"gold",title:$I("resources.gold.title"),type:"common",visible:!0,calculatePerTick:!0,aiCanDestroy:!0,tag:"baseMetal"},{name:"oil",title:$I("resources.oil.title"),type:"common",visible:!0,calculatePerTick:!0,
aiCanDestroy:!0,isNotRefundable:!0},{name:"uranium",title:$I("resources.uranium.title"),type:"common",visible:!0,color:"#4EA24E",calculatePerTick:!0,aiCanDestroy:!0,tag:"baseMetal"},{name:"unobtainium",title:$I("resources.unobtainium.title"),type:"common",visible:!0,display:!0,color:"#A00000",calculatePerTick:!0,aiCanDestroy:!0,tag:"baseMetal"},{name:"antimatter",title:$I("resources.antimatter.title"),type:"common",transient:!0,visible:!0,color:"#5A0EDE",calculateOnYear:!0,isRefundable:function(a){return a.resPool.energyProd>=
a.resPool.energyCons}},{name:"manpower",title:$I("resources.manpower.title"),type:"common",visible:!0,transient:!0,color:"#DBA901",calculatePerTick:!0},{name:"science",title:$I("resources.science.title"),type:"common",visible:!0,transient:!0,color:"#01A9DB",calculatePerTick:!0},{name:"culture",title:$I("resources.culture.title"),type:"common",visible:!0,transient:!0,color:"#DF01D7",calculatePerTick:!0},{name:"faith",title:$I("resources.faith.title"),type:"common",visible:!0,transient:!0,color:"gray",
calculatePerTick:!0},{name:"kittens",title:$I("resources.kittens.title"),type:"common",transient:!0,visible:!0,persists:!1},{name:"zebras",title:$I("resources.zebras.title"),type:"common",transient:!0,visible:!0,persists:!1},{name:"starchart",title:$I("resources.starchart.title"),type:"common",transient:!0,visible:!0,color:"#9A2EFE",calculatePerTick:!0},{name:"temporalFlux",title:$I("resources.temporalFlux.title"),type:"common",craftable:!1,visible:!1,persists:!0},{name:"gflops",title:$I("resources.gflops.title"),
type:"common",transient:!0,craftable:!1,visible:!1,persists:!1},{name:"hashrates",title:$I("resources.hashrates.title"),type:"common",transient:!0,craftable:!1,visible:!1,persists:!1},{name:"furs",title:$I("resources.furs.title"),type:"uncommon",transient:!0,visible:!0,persists:!1,calculatePerTick:!0,aiCanDestroy:!0},{name:"ivory",title:$I("resources.ivory.title"),type:"uncommon",transient:!0,visible:!0,persists:!1,calculatePerTick:!0,aiCanDestroy:!0},{name:"spice",title:$I("resources.spice.title"),
type:"uncommon",transient:!0,visible:!0,persists:!1,calculatePerTick:!0,aiCanDestroy:!0},{name:"unicorns",title:$I("resources.unicorns.title"),type:"rare",transient:!0,visible:!0,persists:!1,calculatePerTick:!0,aiCanDestroy:!0},{name:"alicorn",title:$I("resources.alicorn.title"),type:"rare",visible:!0,persists:!1,calculatePerTick:!0,aiCanDestroy:!0},{name:"necrocorn",title:$I("resources.necrocorn.title"),type:"rare",visible:!0,color:"#E00000",persists:!1,calculatePerDay:!0},{name:"tears",title:$I("resources.tears.title"),
type:"rare",visible:!0,persists:!1},{name:"karma",title:$I("resources.karma.title"),type:"rare",visible:!0,persists:!1},{name:"paragon",title:$I("resources.paragon.title"),type:"common",visible:!0,color:"#6141CD",persists:!0},{name:"burnedParagon",title:$I("resources.burnedParagon.title"),type:"common",visible:!0,color:"#493099",persists:!0},{name:"timeCrystal",title:$I("resources.timeCrystal.title"),type:"common",visible:!0,color:"#14CD61"},{name:"sorrow",title:$I("resources.sorrow.title"),type:"common",
visible:!1,color:"black",persists:!0},{name:"relic",title:$I("resources.relic.title"),type:"exotic",craftable:!1,visible:!0,color:"#5A0EDE",calculatePerDay:!0},{name:"void",title:$I("resources.void.title"),type:"exotic",craftable:!1,visible:!0,color:"#5A0EDE"},{name:"elderBox",title:$I("resources.elderBox.title"),description:$I("resources.elderBox.desc"),type:"exotic",craftable:!1,visible:!0,color:"#FA0EDE",persists:!0},{name:"wrappingPaper",title:$I("resources.wrappingPaper.title"),type:"exotic",
craftable:!1,visible:!0,color:"#FA0EDE",persists:!0},{name:"blackcoin",title:$I("resources.blackcoin.title"),type:"exotic",craftable:!1,visible:!0,color:"gold"},{name:"bloodstone",title:$I("resources.bloodstone.title"),type:"exotic",craftable:!0,visible:!0,color:"red"},{name:"tMythril",title:$I("resources.tMythril.title"),type:"exotic",transient:!0,calculatePerTick:!0,craftable:!0,visible:!0,color:"#00e6b8"},{name:"beam",title:$I("resources.beam.title"),type:"common",craftable:!0},{name:"slab",title:$I("resources.slab.title"),
type:"common",craftable:!0},{name:"plate",title:$I("resources.plate.title"),type:"common",craftable:!0,tag:"metallurgist"},{name:"steel",title:$I("resources.steel.title"),type:"common",craftable:!0,visible:!1,color:"gray",calculatePerTick:!0,tag:"metallurgist"},{name:"concrate",title:$I("resources.concrate.title"),type:"common",craftable:!0,tag:"chemist"},{name:"gear",title:$I("resources.gear.title"),type:"common",craftable:!0,color:"gray",tag:"metallurgist"},{name:"alloy",title:$I("resources.alloy.title"),
type:"common",craftable:!0,visible:!1,color:"gray",tag:"metallurgist"},{name:"eludium",title:$I("resources.eludium.title"),type:"common",craftable:!0,visible:!1,color:"darkViolet",tag:"chemist"},{name:"scaffold",title:$I("resources.scaffold.title"),type:"common",craftable:!0,color:"#FF7F50"},{name:"ship",title:$I("resources.ship.title"),type:"common",craftable:!0,color:"#FF571A"},{name:"tanker",title:$I("resources.tanker.title"),type:"common",craftable:!0,color:"#CF4F20"},{name:"kerosene",title:$I("resources.kerosene.title"),
type:"common",craftable:!0,color:"darkYellow",isNotRefundable:!0,tag:"chemist"},{name:"parchment",title:$I("resources.parchment.title"),type:"common",craftable:!0,color:"#DF01D7"},{name:"manuscript",title:$I("resources.manuscript.title"),type:"common",craftable:!0,color:"#01A9DB",calculatePerTick:!0},{name:"compedium",title:$I("resources.compedium.title"),type:"common",craftable:!0,color:"#01A9DB"},{name:"blueprint",title:$I("resources.blueprint.title"),type:"common",transient:!0,visible:!0,craftable:!0,
color:"#01A9DB"},{name:"thorium",title:$I("resources.thorium.title"),type:"common",visible:!0,craftable:!0,color:"#4EA24E",calculatePerTick:!0,isNotRefundable:!0,tag:"chemist"},{name:"megalith",title:$I("resources.megalith.title"),type:"common",craftable:!0,color:"gray"}],resources:null,village:null,game:null,energyProd:0,energyWinterProd:0,energyCons:0,isLocked:!1,constructor:function(a){this.game=a;this.resources=[];this.resourceMap={};for(a=0;a<this.resourceData.length;a++){var b=dojo.clone(this.resourceData[a]);
b.value=0;b.unlocked=!1;b.isRefundable||(b.isRefundable=function(c){return!this.isNotRefundable});this.resources.push(b);this.resourceMap[b.name]=b}},get:function(a){return(a=this.resourceMap[a])?a:!1},getPseudoResources:function(){return[{name:"worship",title:$I("resources.worship.title"),value:this.game.religion.faith,unlocked:!0,visible:!1},{name:"epiphany",title:$I("resources.epiphany.title"),value:this.game.religion.faithRatio,unlocked:!0,visible:!1},{name:"necrocornDeficit",title:$I("resources.necrocornDeficit.title"),
value:this.game.religion.pactsManager.necrocornDeficit,unlocked:!0,visible:!1,color:"#E00000"}]},createResource:function(a){return{name:a,value:0,isHidden:!1,unlocked:!1}},addRes:function(a,b,c,d){if(0>this.game.calendar.day&&!c||0==b)return 0;c=a.value||0;var e=Math.max(a.value,a.maxValue||Number.POSITIVE_INFINITY);a.value+=b;d||(a.value=Math.min(a.value,e));"void"==a.name&&(a.value=Math.floor(a.value));if(isNaN(a.value)||1E-10>a.value)a.value=0;"karma"==a.name&&(this.game.karmaKittens=Math.round(this.game.getInverseUnlimitedDR(a.value,
5)),a.value=this.game.getUnlimitedDR(this.game.karmaKittens,5));return a.value-c},addResPerTick:function(a,b){return this.addRes(this.get(a),b,!1)},addResEvent:function(a,b){return this.addRes(this.get(a),b,!0)},getAmtDependsOnStock:function(a,b){if(0==b)return 0;for(var c=b,d=0,e=a.length;d<e;d++){var f=this.get(a[d].res).value;f<a[d].amt*b&&(b=Math.min(b,f/a[d].amt))}for(d in a)this.addResPerTick(a[d].res,-a[d].amt*b);return b/c},update:function(){var a=this.game;for(e in this.resources){var b=
this.resources[e];if("sorrow"==b.name)b.maxValue=16+(a.getEffect("blsLimit")||0),b.value=b.value>b.maxValue?b.maxValue:b.value;else{0==b.unlocked&&0<b.value?b.unlocked=!0:0!=b.value||1!=b.unlocked||"zebras"!=b.name&&"paragon"!=b.name&&"elderBox"!=b.name||(b.unlocked=!1);var c=a.getEffect(b.name+"Max")||0;c=this.addResMaxRatios(b,c);var d=this.game.getEffect(b.name+"MaxChallenge");d&&(d=this.game.getLimitedDR(this.addResMaxRatios(b,d),c-1),c+=d);0>c&&(c=0);b.maxValue=c;a.loadingSave||(c=a.getResourcePerTick(b.name,
!1),this.addResPerTick(b.name,c))}}a.updateKarma();var e=1+a.getEffect("energyProductionRatio");this.energyWinterProd=this.energyProd=a.getEffect("energyProduction")*e;b=1+a.getLimitedDR(a.getEffect("energyConsumptionRatio"),1)+a.getEffect("energyConsumptionIncrease");this.energyCons=a.getEffect("energyConsumption")*b*(this.game.challenges.isActive("energy")?2:1);c=a.calendar.season;b=a.bld.getBuildingExt("pasture");d=b.get("calculateEnergyProduction");3!=c&&d&&(a=d(a,c)-d(a,3),this.energyWinterProd-=
b.get("on")*a*e)},fastforward:function(a){var b={},c;for(c in this.resources){var d=this.resources[c];d.perTickCached&&("catnip"!=d.name||0<=d.perTickCached)&&(d.maxValue&&(b[d.name]=Math.max(d.value,d.maxValue)),this.addRes(d,d.perTickCached*a*this.game.calendar.ticksPerDay,!0,!0))}return b},enforceLimits:function(a){for(var b in this.resources){var c=this.resources[b];if(c.maxValue){var d=a[c.name];d&&(c.value=Math.min(c.value,d))}}},resConsHackForResTable:function(){if(0<=this.game.calendar.day)for(var a in this.resources){var b=
this.resources[a];if(b.maxValue){var c=this.game.getResourcePerTickConvertion(b.name);0>c&&0<this.game.getResourcePerTick(b.name,!0)&&b.maxValue+c<=b.value&&(b.value+=-c)}}},addBarnWarehouseRatio:function(a){var b={},c=this.game.getEffect("barnRatio"),d=1+this.game.getEffect("warehouseRatio"),e;for(e in a){var f=a[e];"catnipMax"===e&&this.game.workshop.get("silos").researched&&(f*=1+.25*c);if("woodMax"==e||"mineralsMax"==e||"ironMax"==e)f*=1+c,f*=d;if("coalMax"==e||"titaniumMax"==e||"goldMax"==e)f*=
d;b[e]=f}return b},addResMaxRatios:function(a,b){if("temporalFlux"==a.name)return b;b*=1+this.game.prestige.getParagonStorageRatio();this.game.opts.disableCMBR||(b*=1+this.game.getCMBRBonus());b*=1+this.game.getEffect(a.name+"MaxRatio");this.isNormalCraftableResource(a)||a.transient||(b*=1+this.game.getEffect("globalResourceRatio"));if(!this.isNormalCraftableResource(a)&&!a.transient){var c=this.game.getEffect("pyramidGlobalResourceRatio");b*=1+c}"baseMetal"==a.tag&&(b*=1+this.game.getEffect("baseMetalMaxRatio"));
"science"==a.name&&(b*=1+this.game.getEffect("technocracyScienceCap"));"culture"==a.name&&(b*=1+this.game.getEffect("onAHillCultureCap"));return b},setVillage:function(a){this.village=a},reset:function(){this.resources=[]},resetState:function(){this.isLocked=!1;for(var a=0;a<this.resources.length;a++){var b=this.resources[a];b.value=0;b.maxValue=0;b.perTickCached=0;b.unlocked=!1;b.isHidden=!1}},save:function(a){a.res={isLocked:this.isLocked}},load:function(a){this.loadMetadata(this.resources,a.resources);
a.res&&(this.isLocked=!!a.res.isLocked)},hasRes:function(a,b){b||=1;var c=!0;if(a.length)for(var d=0;d<a.length;d++){var e=a[d],f=this.get(e.name);if(Infinity==e.val*b&&Infinity==f.value&&(0!==f.maxValue||"void"===f.name)){c=!1;break}if(f.value<e.val*b){c=!1;break}}return c},isStorageLimited:function(a){if(a&&a.length)for(var b=0;b<a.length;b++){var c=a[b],d=this.get(c.name);if(0<d.maxValue&&c.val>d.maxValue&&c.val>d.value||d.craftable&&c.val>d.value&&(c=this.game.workshop.getCraft(d.name),c.unlocked&&
c.isLimited))return!0}return!1},payPrices:function(a){if(a.length)for(var b=0;b<a.length;b++){var c=a[b];this.addResEvent(c.name,-c.val)}},maxAll:function(){for(var a=0;a<this.resources.length;a++){var b=this.resources[a];b.maxValue&&b.value<b.maxValue&&(b.value=b.maxValue)}},getEnergyDelta:function(){if(0==this.energyCons)return 0;var a=this.energyProd/this.energyCons;.25>a&&(a=.25);this.game.challenges.getChallenge("energy").researched&&!this.game.challenges.isActive("energy")&&(a=1-(1-a)/2);return a},
getVoidQuantity:function(){return this.game.rand(this.game.getEffect("temporalParadoxVoid")+4)-1},getVoidQuantityStatistically:function(){return(this.game.getEffect("temporalParadoxVoid")+1)/2},setDisplayAll:function(){for(var a=0;a<this.resources.length;a++)this.resources[a].isHidden=!1},toggleLock:function(){this.isLocked=!this.isLocked},isNormalCraftableResource:function(a){return a.craftable&&"wood"!=a.name}});
