dojo.declare("classes.managers.ScienceManager",com.nuclearunicorn.core.TabManager,{game:null,hideResearched:!1,policyToggleBlocked:!1,policyToggleResearched:!1,techs:[{name:"calendar",label:$I("science.calendar.label"),description:$I("science.calendar.desc"),effectDesc:$I("science.calendar.effectDesc"),prices:[{name:"science",val:30}],unlocks:{tabs:["time"],tech:["agriculture"]},flavor:$I("science.calendar.flavor")},{name:"agriculture",label:$I("science.agriculture.label"),description:$I("science.agriculture.desc"),
effectDesc:$I("science.agriculture.effectDesc"),prices:[{name:"science",val:100}],unlocks:{buildings:["barn"],jobs:["farmer"],tech:["mining","archery"]},flavor:$I("science.agriculture.flavor")},{name:"archery",label:$I("science.archery.label"),description:$I("science.archery.desc"),effectDesc:$I("science.archery.effectDesc"),prices:[{name:"science",val:300}],unlocks:{buildings:["zebraOutpost","zebraWorkshop","zebraForge"],jobs:["hunter"],tech:["animal"]},flavor:$I("science.archery.flavor")},{name:"mining",
label:$I("science.mining.label"),description:$I("science.mining.desc"),effectDesc:$I("science.mining.effectDesc"),prices:[{name:"science",val:500}],unlocks:{buildings:["mine","workshop"],tech:["metal"],upgrades:["bolas"]},flavor:$I("science.mining.flavor")},{name:"metal",label:$I("science.metal.label"),description:$I("science.metal.desc"),effectDesc:$I("science.metal.effectDesc"),prices:[{name:"science",val:900}],unlocks:{buildings:["smelter"],upgrades:["huntingArmor"]}},{name:"animal",label:$I("science.animal.label"),
description:$I("science.animal.desc"),effectDesc:$I("science.animal.effectDesc"),prices:[{name:"science",val:500}],unlocks:{buildings:["pasture","unicornPasture"],tech:["civil","math","construction"]}},{name:"brewery",label:$I("science.brewery.label"),description:$I("science.brewery.desc"),effectDesc:$I("science.brewery.effectDesc"),prices:[{name:"science",val:1200}]},{name:"civil",label:$I("science.civil.label"),description:$I("science.civil.desc"),effectDesc:$I("science.civil.effectDesc"),prices:[{name:"science",
val:1500}],unlocks:{tech:["currency"]},flavor:$I("science.civil.flavor")},{name:"math",label:$I("science.math.label"),description:$I("science.math.desc"),effectDesc:$I("science.math.effectDesc"),prices:[{name:"science",val:1E3}],unlocks:{tabs:["stats"],buildings:["academy"],upgrades:["celestialMechanics"]},flavor:$I("science.math.flavor")},{name:"construction",label:$I("science.construction.label"),description:$I("science.construction.desc"),effectDesc:$I("science.construction.effectDesc"),prices:[{name:"science",
val:1300}],unlocks:{buildings:["logHouse","warehouse","lumberMill","ziggurat"],tech:["engineering"],upgrades:["compositeBow","advancedRefinement","reinforcedSaw"]},flavor:$I("science.construction.flavor")},{name:"engineering",label:$I("science.engineering.label"),description:$I("science.engineering.desc"),effectDesc:$I("science.engineering.effectDesc"),prices:[{name:"science",val:1500}],unlocks:{buildings:["aqueduct"],tech:["writing"],policies:["stripMining","clearCutting","environmentalism"]}},{name:"currency",
label:$I("science.currency.label"),description:$I("science.currency.desc"),effectDesc:$I("science.currency.effectDesc"),prices:[{name:"science",val:2200}],unlocks:{buildings:["tradepost"],policies:["diplomacy","isolationism"],upgrades:["goldOre"]}},{name:"writing",label:$I("science.writing.label"),description:$I("science.writing.desc"),effectDesc:$I("science.writing.effectDesc"),prices:[{name:"science",val:3600}],unlocks:{buildings:["amphitheatre"],tech:["philosophy","machinery","steel"],policies:["liberty",
"tradition"],upgrades:["register"],crafts:["parchment"]},flavor:$I("science.writing.flavor")},{name:"philosophy",label:$I("science.philosophy.label"),description:$I("science.philosophy.desc"),effectDesc:$I("science.philosophy.effectDesc"),prices:[{name:"science",val:9500}],unlocks:{buildings:["temple"],tech:["theology"],policies:["stoicism","epicurianism"],crafts:["compedium"]},flavor:$I("science.philosophy.flavor")},{name:"machinery",label:$I("science.machinery.label"),description:$I("science.machinery.desc"),
effectDesc:$I("science.machinery.effectDesc"),prices:[{name:"science",val:15E3}],unlocks:{buildings:["steamworks"],upgrades:["printingPress","factoryAutomation","crossbow"]}},{name:"steel",label:$I("science.steel.label"),description:$I("science.steel.desc"),effectDesc:$I("science.steel.effectDesc"),prices:[{name:"science",val:12E3}],unlocks:{upgrades:"deepMining coalFurnace combustionEngine reinforcedWarehouses steelAxe steelArmor".split(" "),crafts:["steel"]}},{name:"theology",label:$I("science.theology.label"),
description:$I("science.theology.desc"),effectDesc:$I("science.theology.effectDesc"),prices:[{name:"science",val:2E4},{name:"manuscript",val:35}],unlocks:{jobs:["priest"],tech:["astronomy","cryptotheology"]},upgrades:{buildings:["temple"]},flavor:$I("science.theology.flavor")},{name:"astronomy",label:$I("science.astronomy.label"),description:$I("science.astronomy.desc"),effectDesc:$I("science.astronomy.effectDesc"),prices:[{name:"science",val:28E3},{name:"manuscript",val:65}],unlocks:{buildings:["observatory"],
tech:["navigation"],policies:["knowledgeSharing","culturalExchange","bigStickPolicy","cityOnAHill"]}},{name:"navigation",label:$I("science.navigation.label"),description:$I("science.navigation.desc"),effectDesc:$I("science.navigation.effectDesc"),prices:[{name:"science",val:35E3},{name:"manuscript",val:100}],unlocks:{buildings:["harbor"],tech:["physics","archeology","architecture"],upgrades:["caravanserai","cargoShips","astrolabe","titaniumMirrors","titaniumAxe"],crafts:["ship"]}},{name:"architecture",
label:$I("science.architecture.label"),description:$I("science.architecture.desc"),effectDesc:$I("science.architecture.effectDesc"),prices:[{name:"science",val:42E3},{name:"compedium",val:10}],unlocks:{buildings:["mansion","mint"],tech:["acoustics"]},flavor:$I("science.architecture.flavor")},{name:"physics",label:$I("science.physics.label"),description:$I("science.physics.desc"),effectDesc:$I("science.physics.effectDesc"),prices:[{name:"science",val:5E4},{name:"compedium",val:35}],unlocks:{tech:["chemistry",
"electricity","metaphysics"],upgrades:["pneumaticPress","pyrolysis","steelSaw"],crafts:["blueprint"]}},{name:"metaphysics",label:$I("science.metaphysics.label"),description:$I("science.metaphysics.desc"),effectDesc:$I("science.metaphysics.effectDesc"),prices:[{name:"unobtainium",val:5},{name:"science",val:55E3}]},{name:"chemistry",label:$I("science.chemistry.label"),description:$I("science.chemistry.desc"),effectDesc:$I("science.chemistry.effectDesc"),prices:[{name:"science",val:6E4},{name:"compedium",
val:50}],unlocks:{buildings:["calciner","oilWell"],upgrades:["alloyAxe","alloyArmor","alloyWarehouses","alloyBarns"],crafts:["alloy"]}},{name:"acoustics",label:$I("science.acoustics.label"),description:$I("science.acoustics.desc"),effectDesc:$I("science.acoustics.effectDesc"),prices:[{name:"science",val:6E4},{name:"compedium",val:60}],unlocks:{buildings:["chapel"],tech:["drama"]}},{name:"drama",label:$I("science.drama.label"),description:$I("science.drama.desc"),effectDesc:$I("science.drama.effectDesc"),
prices:[{name:"science",val:9E4},{name:"parchment",val:5E3}],unlocks:{buildings:["brewery"]}},{name:"archeology",label:$I("science.archeology.label"),description:$I("science.archeology.desc"),effectDesc:$I("science.archeology.effectDesc"),prices:[{name:"science",val:65E3},{name:"compedium",val:65}],unlocks:{buildings:["quarry"],jobs:["geologist"],tech:["biology"],upgrades:["geodesy"],zebraUpgrades:["minerologyDepartment"]},flavor:$I("science.archeology.flavor")},{name:"electricity",label:$I("science.electricity.label"),
description:$I("science.electricity.desc"),effectDesc:$I("science.electricity.effectDesc"),prices:[{name:"science",val:75E3},{name:"compedium",val:85}],unlocks:{buildings:["magneto"],tech:["industrialization"]},flavor:$I("science.electricity.flavor")},{name:"biology",label:$I("science.biology.label"),description:$I("science.biology.desc"),effectDesc:$I("science.biology.effectDesc"),prices:[{name:"science",val:85E3},{name:"compedium",val:100}],unlocks:{buildings:["biolab"],tech:["biochemistry"]},flavor:$I("science.biology.flavor")},
{name:"biochemistry",label:$I("science.biochemistry.label"),description:$I("science.biochemistry.desc"),effectDesc:$I("science.biochemistry.effectDesc"),prices:[{name:"science",val:145E3},{name:"compedium",val:500}],unlocks:{tech:["genetics"],upgrades:["biofuel"]},flavor:$I("science.biochemistry.flavor")},{name:"genetics",label:$I("science.genetics.label"),description:$I("science.genetics.desc"),effectDesc:$I("science.genetics.effectDesc"),prices:[{name:"science",val:19E4},{name:"compedium",val:1500}],
unlocks:{upgrades:["unicornSelection","gmo"]},flavor:$I("science.genetics.flavor")},{name:"industrialization",label:$I("science.industrialization.label"),description:$I("science.industrialization.desc"),effectDesc:$I("science.industrialization.effectDesc"),prices:[{name:"science",val:1E5},{name:"blueprint",val:25}],unlocks:{tech:["mechanization","metalurgy","combustion"],upgrades:["barges","advancedAutomation","logistics"],policies:["sustainability","fullIndustrialization"]}},{name:"mechanization",
label:$I("science.mechanization.label"),description:$I("science.mechanization.desc"),effectDesc:$I("science.mechanization.effectDesc"),prices:[{name:"science",val:115E3},{name:"blueprint",val:45}],unlocks:{buildings:["factory"],jobs:["engineer"],tech:["electronics"],upgrades:["pumpjack","strenghtenBuild"],crafts:["concrate"]}},{name:"metalurgy",label:$I("science.metalurgy.label"),description:$I("science.metalurgy.desc"),effectDesc:$I("science.metalurgy.effectDesc"),prices:[{name:"science",val:125E3},
{name:"blueprint",val:60}],unlocks:{upgrades:["electrolyticSmelting","oxidation","miningDrill"]}},{name:"combustion",label:$I("science.combustion.label"),description:$I("science.combustion.desc"),effectDesc:$I("science.combustion.effectDesc"),prices:[{name:"science",val:115E3},{name:"blueprint",val:45}],unlocks:{tech:["ecology"],upgrades:["offsetPress","fuelInjectors","oilRefinery"]}},{name:"ecology",label:$I("science.ecology.label"),description:$I("science.ecology.desc"),effectDesc:$I("science.ecology.effectDesc"),
prices:[{name:"science",val:125E3},{name:"blueprint",val:55}],unlocks:{stages:[{bld:"pasture",stage:1}],policies:["conservation","openWoodlands"],upgrades:["carbonSequestration"]},upgrades:{buildings:["mine","quarry"]}},{name:"electronics",label:$I("science.electronics.label"),description:$I("science.electronics.desc"),effectDesc:$I("science.electronics.effectDesc"),prices:[{name:"science",val:135E3},{name:"blueprint",val:70}],unlocks:{stages:[{bld:"library",stage:1},{bld:"amphitheatre",stage:1}],
tech:["nuclearFission","rocketry","robotics"],upgrades:"cadSystems refrigeration seti factoryLogistics factoryOptimization internet".split(" ")}},{name:"robotics",label:$I("science.robotics.label"),description:$I("science.robotics.desc"),effectDesc:$I("science.robotics.effectDesc"),prices:[{name:"science",val:14E4},{name:"blueprint",val:80}],unlocks:{stages:[{bld:"aqueduct",stage:1}],tech:["ai"],upgrades:["steelPlants","rotaryKiln","assistance","factoryRobotics"],crafts:["tanker"]}},{name:"ai",label:$I("science.ai.label"),
description:$I("science.ai.desc"),effectDesc:$I("science.ai.effectDesc"),prices:[{name:"science",val:25E4},{name:"blueprint",val:150}],unlocks:{buildings:["aiCore"],tech:["quantumCryptography"],upgrades:["neuralNetworks","aiEngineers","machineLearning"]}},{name:"quantumCryptography",label:$I("science.quantumCryptography.label"),description:$I("science.quantumCryptography.desc"),effectDesc:$I("science.quantumCryptography.effectDesc"),prices:[{name:"science",val:125E4},{name:"relic",val:1024}],unlocks:{tech:["blackchain"]}},
{name:"blackchain",label:$I("science.blackchain.label"),description:$I("science.blackchain.desc"),effectDesc:$I("science.blackchain.effectDesc"),prices:[{name:"science",val:5E6},{name:"relic",val:4096}],unlocks:{upgrades:["invisibleBlackHand"]}},{name:"nuclearFission",label:$I("science.nuclearFission.label"),description:$I("science.nuclearFission.desc"),effectDesc:$I("science.nuclearFission.effectDesc"),prices:[{name:"science",val:15E4},{name:"blueprint",val:100}],unlocks:{buildings:["reactor"],tech:["nanotechnology",
"particlePhysics"],upgrades:["reactorVessel","nuclearSmelters"]}},{name:"rocketry",label:$I("science.rocketry.label"),description:$I("science.rocketry.desc"),effectDesc:$I("science.rocketry.effectDesc"),prices:[{name:"science",val:175E3},{name:"blueprint",val:125}],unlocks:{tabs:["space"],tech:["sattelites","oilProcessing"],upgrades:["oilDistillation"]},upgrades:{planet:["cath"]}},{name:"oilProcessing",label:$I("science.oilProcessing.label"),description:$I("science.oilProcessing.desc"),effectDesc:$I("science.oilProcessing.effectDesc"),
prices:[{name:"science",val:215E3},{name:"blueprint",val:150}],unlocks:{upgrades:["factoryProcessing"],crafts:["kerosene"]}},{name:"sattelites",label:$I("science.sattelites.label"),description:$I("science.sattelites.desc"),effectDesc:$I("science.sattelites.effectDesc"),prices:[{name:"science",val:19E4},{name:"blueprint",val:125}],unlocks:{tech:["orbitalEngineering"],upgrades:["photolithography","orbitalGeodesy","uplink","thinFilm"],policies:["outerSpaceTreaty","militarizeSpace"]},flavor:$I("science.sattelites.flavor")},
{name:"orbitalEngineering",label:$I("science.orbitalEngineering.label"),description:$I("science.orbitalEngineering.desc"),effectDesc:$I("science.orbitalEngineering.effectDesc"),prices:[{name:"science",val:25E4},{name:"blueprint",val:250}],unlocks:{tech:["exogeology","thorium"],upgrades:"hubbleTelescope satelliteRadio astrophysicists solarSatellites spaceEngineers starlink".split(" ")}},{name:"thorium",label:$I("science.thorium.label"),description:$I("science.thorium.desc"),effectDesc:$I("science.thorium.effectDesc"),
prices:[{name:"science",val:375E3},{name:"blueprint",val:375}],unlocks:{upgrades:["thoriumReactors","thoriumEngine","qdot"],crafts:["thorium"]}},{name:"exogeology",label:$I("science.exogeology.label"),description:$I("science.exogeology.desc"),effectDesc:$I("science.exogeology.effectDesc"),prices:[{name:"science",val:275E3},{name:"blueprint",val:250}],unlocks:{tech:["advExogeology"],upgrades:["unobtainiumReflectors","unobtainiumHuts","unobtainiumDrill","hydroPlantTurbines","storageBunkers"]}},{name:"advExogeology",
label:$I("science.advExogeology.label"),description:$I("science.advExogeology.desc"),effectDesc:$I("science.advExogeology.effectDesc"),prices:[{name:"science",val:325E3},{name:"blueprint",val:350}],unlocks:{upgrades:["eludiumCracker","eludiumReflectors","eludiumHuts","mWReactor"],crafts:["eludium"]}},{name:"nanotechnology",label:$I("science.nanotechnology.label"),description:$I("science.nanotechnology.desc"),effectDesc:$I("science.nanotechnology.effectDesc"),prices:[{name:"science",val:2E5},{name:"blueprint",
val:150}],unlocks:{tech:["superconductors"],upgrades:["augumentation","nanosuits","photovoltaic","fluidizedReactors"]}},{name:"superconductors",label:$I("science.superconductors.label"),description:$I("science.superconductors.desc"),effectDesc:$I("science.superconductors.effectDesc"),prices:[{name:"science",val:225E3},{name:"blueprint",val:175}],unlocks:{tech:["antimatter"],upgrades:["coldFusion","spaceManufacturing","cryocomputing"]}},{name:"antimatter",label:$I("science.antimatter.label"),description:$I("science.antimatter.desc"),
effectDesc:$I("science.antimatter.effectDesc"),prices:[{name:"science",val:5E5},{name:"relic",val:1}],unlocks:{tech:["terraformation"],upgrades:["amReactors","amBases","amDrive","amFission"]}},{name:"terraformation",label:$I("science.terraformation.label"),description:$I("science.terraformation.desc"),effectDesc:$I("science.terraformation.effectDesc"),prices:[{name:"science",val:75E4},{name:"relic",val:5}],unlocks:{tech:["hydroponics"]}},{name:"hydroponics",label:$I("science.hydroponics.label"),description:$I("science.hydroponics.desc"),
effectDesc:$I("science.hydroponics.effectDesc"),prices:[{name:"science",val:1E6},{name:"relic",val:25}],unlocks:{tech:["exogeophysics"]}},{name:"exogeophysics",label:$I("science.exogeophysics.label"),description:$I("science.exogeophysics.desc"),effectDesc:$I("science.exogeophysics.effectDesc"),prices:[{name:"science",val:25E6},{name:"relic",val:500}]},{name:"particlePhysics",label:$I("science.particlePhysics.label"),description:$I("science.particlePhysics.desc"),effectDesc:$I("science.particlePhysics.effectDesc"),
prices:[{name:"science",val:185E3},{name:"blueprint",val:135}],unlocks:{buildings:["accelerator"],tech:["chronophysics","dimensionalPhysics"],upgrades:["enrichedUranium","railgun"]}},{name:"dimensionalPhysics",label:$I("science.dimensionalPhysics.label"),description:$I("science.dimensionalPhysics.desc"),effectDesc:$I("science.dimensionalPhysics.effectDesc"),prices:[{name:"science",val:235E3}],unlocks:{upgrades:["energyRifts","lhc"]}},{name:"artificialGravity",label:$I("science.artificialGravity.label"),
description:$I("science.artificialGravity.desc"),effectDesc:$I("science.artificialGravity.effectDesc"),prices:[{name:"science",val:32E4}],unlocks:{upgrades:["spiceNavigation","longRangeSpaceships"]},flavor:$I("science.artificialGravity.flavor")},{name:"chronophysics",label:$I("science.chronophysics.label"),description:$I("science.chronophysics.desc"),effectDesc:$I("science.chronophysics.effectDesc"),prices:[{name:"science",val:25E4},{name:"timeCrystal",val:5}],unlocks:{buildings:["chronosphere"],
tech:["tachyonTheory"],upgrades:["stasisChambers","fluxCondensator"]}},{name:"tachyonTheory",label:$I("science.tachyonTheory.label"),description:$I("science.tachyonTheory.desc"),effectDesc:$I("science.tachyonTheory.effectDesc"),prices:[{name:"science",val:75E4},{name:"timeCrystal",val:25},{name:"relic",val:1}],unlocks:{tech:["voidSpace"],upgrades:["tachyonAccelerators","chronoforge","chronoEngineers"]}},{name:"cryptotheology",label:$I("science.cryptotheology.label"),description:$I("science.cryptotheology.desc"),
effectDesc:$I("science.cryptotheology.effectDesc"),prices:[{name:"science",val:65E4},{name:"relic",val:5}],unlocks:{upgrades:["relicStation"]},calculateEffects:function(a,b){a.researched&&b.time.queue.unlockQueueSource("transcendenceUpgrades")}},{name:"voidSpace",label:$I("science.voidSpace.label"),description:$I("science.voidSpace.desc"),effectDesc:$I("science.voidSpace.effectDesc"),prices:[{name:"science",val:8E5},{name:"timeCrystal",val:30},{name:"void",val:100}],unlocks:{tech:["paradoxalKnowledge"],
upgrades:["voidAspiration"],voidSpace:["cryochambers"],challenges:["atheism"]},calculateEffects:function(a,b){a.researched&&b.time.queue.unlockQueueSource("voidSpace")}},{name:"paradoxalKnowledge",label:$I("science.paradoxalKnowledge.label"),description:$I("science.paradoxalKnowledge.desc"),effectDesc:$I("science.paradoxalKnowledge.effectDesc"),prices:[{name:"science",val:1E6},{name:"timeCrystal",val:40},{name:"void",val:250}],unlocks:{upgrades:["distorsion"],chronoforge:["ressourceRetrieval"],voidSpace:["chronocontrol",
"voidResonator"]}}],policies:[{name:"liberty",label:$I("policy.liberty.label"),description:$I("policy.liberty.desc"),prices:[{name:"culture",val:150}],effects:{maxKittens:0,happinessKittenProductionRatio:.1},unlocked:!1,blocked:!1,blocks:["tradition"],unlocks:{policies:["authocracy","republic"]},calculateEffects:function(a,b){a.effects.maxKittens=b.ironWill?0:1}},{name:"tradition",label:$I("policy.tradition.label"),description:$I("policy.tradition.desc"),prices:[{name:"culture",val:150}],effects:{cultureFromManuscripts:1,
manuscriptParchmentCost:-5,manuscriptCultureCost:-100},unlocked:!1,blocked:!1,blocks:["liberty"],unlocks:{policies:["authocracy","monarchy"]}},{name:"monarchy",label:$I("policy.monarchy.label"),description:$I("policy.monarchy.desc"),prices:[{name:"culture",val:1500}],effects:{goldPolicyRatio:-.1},unlocked:!1,upgrades:{buildings:["factory"]},blocked:!1,blocks:["authocracy","republic","communism"],unlocks:{policies:["liberalism","fascism"]}},{name:"authocracy",label:$I("policy.autocracy.label"),description:$I("policy.autocracy.desc"),
prices:[{name:"culture",val:1500}],effects:{rankLeaderBonusConversion:0},unlocked:!1,blocked:!1,blocks:["monarchy","republic","liberalism"],calculateEffects:function(a,b){for(var c=0,d=0;d<b.bld.buildingGroups.length;d++)if("population"==b.bld.buildingGroups[d].name){for(var e=0;e<b.bld.buildingGroups[d].buildings.length;e++){var f=b.bld.getBuildingExt(b.bld.buildingGroups[d].buildings[e]);b.resPool.isStorageLimited(b.bld.getPrices(f.meta.name))?f.meta.almostLimited=!1:(c+=1,f.meta.almostLimited=
a.researched&&b.resPool.isStorageLimited(b.bld.getPrices(f.meta.name,1)))}break}a.effects.rankLeaderBonusConversion=.004*c},unlocks:{policies:["communism","fascism","socialism"]}},{name:"republic",label:$I("policy.republic.label"),description:$I("policy.republic.desc"),prices:[{name:"culture",val:1500}],effects:{boostFromLeader:.01},unlocked:!1,blocked:!1,blocks:["monarchy","authocracy","fascism"],unlocks:{policies:["liberalism","communism","socialism"]}},{name:"socialism",label:$I("policy.socialism.label"),
description:$I("policy.socialism.desc"),prices:[{name:"culture",val:7500}],unlocked:!1,blocked:!1,blocks:[]},{name:"liberalism",label:$I("policy.liberalism.label"),description:$I("policy.liberalism.desc"),prices:[{name:"culture",val:15E3}],effects:{goldCostReduction:.2,globalRelationsBonus:10},unlocked:!1,blocked:!1,blocks:["communism","fascism"],evaluateLocks:function(a){return(a.science.getPolicy("monarchy").researched||a.science.getPolicy("republic").researched)&&0<a.bld.getBuildingExt("factory").meta.val}},
{name:"communism",label:$I("policy.communism.label"),description:$I("policy.communism.desc"),prices:[{name:"culture",val:15E3}],effects:{factoryCostReduction:.3,coalPolicyRatio:.25,ironPolicyRatio:.25,titaniumPolicyRatio:.25},unlocked:!1,blocked:!1,blocks:["liberalism","fascism"],evaluateLocks:function(a){return(a.science.getPolicy("republic").researched||a.science.getPolicy("authocracy").researched)&&0<a.bld.getBuildingExt("factory").meta.val}},{name:"fascism",label:$I("policy.fascism.label"),description:$I("policy.fascism.desc"),
prices:[{name:"culture",val:15E3}],effects:{logHouseCostReduction:.5},unlocked:!1,blocked:!1,blocks:["liberalism","communism"],evaluateLocks:function(a){return(a.science.getPolicy("monarchy").researched||a.science.getPolicy("authocracy").researched)&&0<a.bld.getBuildingExt("factory").meta.val}},{name:"technocracy",label:$I("policy.technocracy.label"),description:$I("policy.technocracy.desc"),prices:[{name:"culture",val:15E4}],effects:{technocracyScienceCap:.2},unlocked:!1,blocked:!1,blocks:["theocracy",
"expansionism"]},{name:"theocracy",label:$I("policy.theocracy.label"),description:$I("policy.theocracy.desc"),prices:[{name:"culture",val:15E4}],effects:{faithPolicyRatio:.2},unlocked:!1,blocked:!1,requiredLeaderJob:"priest",blocks:["technocracy","expansionism"]},{name:"expansionism",label:$I("policy.expansionism.label"),description:$I("policy.expansionism.desc"),prices:[{name:"culture",val:15E4}],effects:{unobtainiumPolicyRatio:.15},unlocked:!1,blocked:!1,blocks:["technocracy","theocracy"]},{name:"transkittenism",
label:$I("policy.transkittenism.label"),description:$I("policy.transkittenism.desc"),prices:[{name:"culture",val:15E5}],effects:{aiCoreProductivness:1,aiCoreUpgradeBonus:.1},unlocked:!1,blocked:!1,blocks:["necrocracy","radicalXenophobia"],upgrades:{buildings:["library"],spaceBuilding:["moonOutpost"]}},{name:"necrocracy",label:$I("policy.necrocracy.label"),description:$I("policy.necrocracy.desc"),prices:[{name:"culture",val:15E5}],effects:{blsProductionBonus:.001,leviathansEnergyModifier:.05},unlocked:!1,
blocked:!1,blocks:["transkittenism","radicalXenophobia"]},{name:"radicalXenophobia",label:$I("policy.radicalXenophobia.label"),description:$I("policy.radicalXenophobia.desc"),prices:[{name:"culture",val:15E5}],effects:{mausoleumBonus:1,pactsAvailable:5},upgrades:{transcendenceUpgrades:["mausoleum"]},calculateEffects:function(a,b){a.effects.pactsAvailable=5;if(1<=b.religion.getPact("fractured").on||!b.getFeatureFlag("MAUSOLEUM_PACTS"))a.effects.pactsAvailable=0;b.updateCaches()},unlocks:{pacts:["pactOfCleansing",
"pactOfDestruction","pactOfExtermination","pactOfPurity"]},unlocked:!1,blocked:!1,blocks:["transkittenism","necrocracy"]},{name:"diplomacy",label:$I("policy.diplomacy.label"),description:$I("policy.diplomacy.desc"),prices:[{name:"culture",val:1600}],effects:{tradeCatpowerDiscount:5},unlocked:!1,unlocks:{policies:["knowledgeSharing","culturalExchange"]},blocked:!1,blocks:["isolationism"]},{name:"isolationism",label:$I("policy.isolationism.label"),description:$I("policy.isolationism.desc"),prices:[{name:"culture",
val:1600}],effects:{tradeGoldDiscount:1},unlocked:!1,unlocks:{policies:["bigStickPolicy","cityOnAHill"]},blocked:!1,blocks:["diplomacy"]},{name:"zebraRelationsAppeasement",label:$I("policy.zebraRelationsAppeasement.label"),description:$I("policy.zebraRelationsAppeasement.desc"),prices:[{name:"culture",val:5E3}],effects:{goldPolicyRatio:-.05,zebraRelationModifier:15},unlocked:!1,blocked:!1,blocks:["zebraRelationsBellicosity"]},{name:"zebraRelationsBellicosity",label:$I("policy.zebraRelationsBellicosity.label"),
description:$I("policy.zebraRelationsBellicosity.desc"),prices:[{name:"culture",val:5E3}],effects:{nonZebraRelationModifier:5,zebraRelationModifier:-10},unlocked:!1,blocked:!1,blocks:["zebraRelationsAppeasement"]},{name:"knowledgeSharing",label:$I("policy.knowledgeSharing.label"),description:$I("policy.knowledgeSharing.desc"),prices:[{name:"culture",val:4E3}],effects:{sciencePolicyRatio:.05},unlocked:!1,blocked:!1,blocks:["culturalExchange"],evaluateLocks:function(a){return a.science.getPolicy("diplomacy").researched&&
a.science.get("astronomy").researched}},{name:"culturalExchange",label:$I("policy.culturalExchange.label"),description:$I("policy.culturalExchange.desc"),prices:[{name:"culture",val:4E3}],effects:{culturePolicyRatio:.05},unlocked:!1,blocked:!1,blocks:["knowledgeSharing"],evaluateLocks:function(a){return a.science.getPolicy("diplomacy").researched&&a.science.get("astronomy").researched}},{name:"bigStickPolicy",label:$I("policy.bigStickPolicy.label"),description:$I("policy.bigStickPolicy.desc"),prices:[{name:"culture",
val:4E3}],effects:{embassyCostReduction:.15},unlocked:!1,blocked:!1,blocks:["cityOnAHill"],evaluateLocks:function(a){return a.science.getPolicy("isolationism").researched&&a.science.get("astronomy").researched&&!a.challenges.isActive("pacifism")}},{name:"cityOnAHill",label:$I("policy.cityOnAHill.label"),description:$I("policy.cityOnAHill.desc"),prices:[{name:"culture",val:4E3}],effects:{onAHillCultureCap:.05},unlocked:!1,blocked:!1,blocks:["bigStickPolicy"],evaluateLocks:function(a){return a.science.getPolicy("isolationism").researched&&
a.science.get("astronomy").researched}},{name:"outerSpaceTreaty",label:$I("policy.outerSpaceTreaty.label"),description:$I("policy.outerSpaceTreaty.desc"),prices:[{name:"culture",val:1E4}],effects:{globalRelationsBonus:10},unlocked:!1,blocked:!1,blocks:["militarizeSpace"],evaluateLocks:function(a){return 0<a.space.getBuilding("sattelite").val}},{name:"militarizeSpace",label:$I("policy.militarizeSpace.label"),description:$I("policy.militarizeSpace.desc"),prices:[{name:"culture",val:1E4}],effects:{satelliteSynergyBonus:.1},
unlocked:!1,upgrades:{spaceBuilding:["sattelite"],buildings:["observatory"]},blocked:!1,blocks:["outerSpaceTreaty"],evaluateLocks:function(a){return 0<a.space.getBuilding("sattelite").val&&!a.challenges.isActive("pacifism")}},{name:"stoicism",label:$I("policy.stoicism.label"),description:$I("policy.stoicism.desc"),prices:[{name:"culture",val:2500}],effects:{luxuryDemandRatio:-.5,breweryConsumptionRatio:-.25},unlocked:!1,blocked:!1,blocks:["epicurianism"],unlocks:{policies:["rationality","mysticism",
"rationing","frugality"]},upgrades:{buildings:["brewery"]}},{name:"epicurianism",label:$I("policy.epicurianism.label"),description:$I("policy.epicurianism.desc"),prices:[{name:"culture",val:2500}],effects:{luxuryHappinessBonus:1},unlocked:!1,blocked:!1,blocks:["stoicism"],unlocks:{policies:["rationality","mysticism","carnivale","extravagance"]}},{name:"carnivale",label:$I("policy.carnivale.label"),description:$I("policy.carnivale.desc"),prices:[{name:"culture",val:3500}],effects:{festivalArrivalRatio:.3,
festivalLuxuryConsumptionRatio:.3},unlocked:!1,blocked:!1,blocks:["extravagance"]},{name:"extravagance",label:$I("policy.extravagance.label"),description:$I("policy.extravagance.desc"),prices:[{name:"culture",val:3500}],effects:{luxuryDemandRatio:2,consumableLuxuryHappiness:5},unlocked:!1,blocked:!1,blocks:["carnivale"]},{name:"rationing",label:$I("policy.rationing.label"),description:$I("policy.rationing.desc"),prices:[{name:"culture",val:3500}],effects:{hapinnessConsumptionRatio:-.1,hunterRatio:.1},
unlocked:!1,blocked:!1,blocks:["frugality"]},{name:"frugality",label:$I("policy.frugality.label"),description:$I("policy.frugality.desc"),prices:[{name:"culture",val:3500}],effects:{mintRatio:.1},unlocked:!1,blocked:!1,blocks:["rationing"],upgrades:{buildings:["mint"]}},{name:"rationality",label:$I("policy.rationality.label"),description:$I("policy.rationality.desc"),prices:[{name:"culture",val:3E3}],effects:{sciencePolicyRatio:.05,ironPolicyRatio:.05},unlocked:!1,blocked:!1,blocks:["mysticism"]},
{name:"mysticism",label:$I("policy.mysticism.label"),description:$I("policy.mysticism.desc"),prices:[{name:"culture",val:3E3}],effects:{culturePolicyRatio:.05,faithPolicyRatio:.05},unlocked:!1,blocked:!1,blocks:["rationality"]},{name:"stripMining",label:$I("policy.stripMining.label"),description:$I("policy.stripMining.desc"),prices:[{name:"science",val:2E3}],effects:{environmentUnhappiness:-2,mineralsPolicyRatio:.3,cathPollutionRatio:.05},unlocked:!1,unlocks:{policies:["sustainability","fullIndustrialization"]},
blocked:!1,blocks:["clearCutting","environmentalism"]},{name:"clearCutting",label:$I("policy.clearCutting.label"),description:$I("policy.clearCutting.desc"),prices:[{name:"science",val:2E3}],effects:{environmentUnhappiness:-2,woodPolicyRatio:.3,cathPollutionRatio:.05},unlocked:!1,unlocks:{policies:["sustainability","fullIndustrialization"]},blocked:!1,blocks:["stripMining","environmentalism"]},{name:"environmentalism",label:$I("policy.environmentalism.label"),description:$I("policy.environmentalism.desc"),
prices:[{name:"culture",val:2E3}],effects:{environmentHappinessBonus:3,cathPollutionRatio:-.05},unlocked:!1,unlocks:{policies:["conservation","openWoodlands"]},blocked:!1,blocks:["stripMining","clearCutting"]},{name:"sustainability",label:$I("policy.sustainability.label"),description:$I("policy.sustainability.desc"),prices:[{name:"culture",val:1E4}],effects:{environmentHappinessBonus:5,cathPollutionRatio:-.05},unlocked:!1,blocked:!1,blocks:["fullIndustrialization"],evaluateLocks:function(a){return(a.science.getPolicy("stripMining").researched||
a.science.getPolicy("clearCutting").researched)&&a.science.get("industrialization").researched}},{name:"fullIndustrialization",label:$I("policy.fullIndustrialization.label"),description:$I("policy.fullIndustrialization.desc"),prices:[{name:"culture",val:1E4}],upgrades:{buildings:["factory"]},effects:{environmentFactoryCraftBonus:.05,cathPollutionRatio:.05},unlocked:!1,blocked:!1,blocks:["sustainability"],evaluateLocks:function(a){return(a.science.getPolicy("stripMining").researched||a.science.getPolicy("clearCutting").researched)&&
a.science.get("industrialization").researched}},{name:"conservation",label:$I("policy.conservation.label"),description:$I("policy.conservation.desc"),prices:[{name:"culture",val:1E4}],effects:{environmentHappinessBonus:5,cathPollutionRatio:-.05},unlocked:!1,blocked:!1,blocks:["openWoodlands"],evaluateLocks:function(a){return a.science.getPolicy("environmentalism").researched&&a.science.get("ecology").researched}},{name:"openWoodlands",label:$I("policy.openWoodlands.label"),description:$I("policy.openWoodlands.desc"),
prices:[{name:"culture",val:1E4}],effects:{mineralsPolicyRatio:.125,woodPolicyRatio:.125,cathPollutionRatio:.05},unlocked:!1,blocked:!1,blocks:["conservation"],evaluateLocks:function(a){return a.science.getPolicy("environmentalism").researched&&a.science.get("ecology").researched}},{name:"cryochamberExtraction",label:$I("policy.cryochamberExtraction.label"),description:$I("policy.cryochamberExtraction.desc"),prices:[{name:"manpower",val:1E4}],unlocked:!1,blocked:!1,blocks:["terraformingInsight"],
onResearch:function(a){a.time.getVSU("usedCryochambers").val+=1;a.time.getVSU("usedCryochambers").on+=1}},{name:"terraformingInsight",label:$I("policy.terraformingInsight.label"),description:$I("policy.terraformingInsight.desc"),prices:[{name:"manpower",val:1E4}],effects:{terraformingMaxKittensRatio:.1},unlocked:!1,blocked:!1,blocks:["cryochamberExtraction"]},{name:"siphoning",label:$I("policy.siphoning.label"),description:$I("policy.siphoning.desc"),prices:[{name:"necrocorn",val:1}],calculateEffect:function(a,
b){a.getFeatureFlag("MAUSOLEUM_PACTS")||(b.unlocked=!1)},evaluateLocks:function(a){return a.getFeatureFlag("MAUSOLEUM_PACTS")},unlocked:!1,blocked:!1,blocks:[]}],metaCache:null,effectsBase:{environmentHappinessBonusModifier:1,environmentUnhappinessModifier:1},constructor:function(a){if(a.getFeatureFlag("SPACE_EXPL"))for(var b=this.techs.length-1;0<=b;b--)if("dimensionalPhysics"==this.techs[b].name){this.techs[b].unlocks.tech||(this.techs[b].unlocks.tech=["artificialGravity"]);break}this.game=a;this.metaCache=
{};this.registerMeta("research",this.techs,{getEffect:function(c,d){var e=0;c.effect&&(e=c.effects[d]||0);return e}});this.registerMeta("research",this.policies,{getEffect:function(c,d){var e=0;c.effect&&(e=c.effects[d]||0);return e}});this.setEffectsCachedExisting()},get:function(a){var b=this.metaCache[a];if(b)return b;for(b=this.techs.length-1;0<=b;b--)if(this.techs[b].name==a)return this.metaCache[a]=this.techs[b],this.techs[b];console.error("Failed to get tech for tech name '"+a+"'");return null},
getPolicy:function(a){return this.getMeta(a,this.policies)},getPrices:function(a){var b=$.extend(!0,[],a.prices);b=this.game.village.getEffectLeader("scientist",b);this.game.ironWill&&this.game.challenges.isActive("blackSky")&&"construction"==a.name&&(b=b.concat([{name:"gold",val:5}]));return b},resetState:function(){for(var a=0;a<this.techs.length;a++){var b=this.techs[a];b.unlocked="calendar"==b.name;b.researched=!1}for(a=0;a<this.policies.length;a++)b=this.policies[a],b.unlocked=!1,b.blocked=!1,
b.researched=!1;this.policyToggleResearched=this.policyToggleBlocked=this.hideResearched=!1},save:function(a){a.science={hideResearched:this.hideResearched,policyToggleResearched:this.policyToggleResearched,policyToggleBlocked:this.policyToggleBlocked,techs:this.filterMetadata(this.techs,["name","unlocked","researched"]),policies:this.filterMetadata(this.policies,["name","unlocked","blocked","researched"])}},load:function(a){a.science&&(this.hideResearched=a.science.hideResearched,this.policyToggleResearched=
a.science.policyToggleResearched,this.policyToggleBlocked=a.science.policyToggleBlocked,this.loadMetadata(this.techs,a.science.techs,"technologies"),this.loadMetadata(this.policies,a.science.policies,"policies"));for(a=this.techs.length-1;0<=a;a--){var b=this.techs[a];b.researched&&this.game.unlock(b.unlocks)}for(a=this.policies.length-1;0<=a;a--)b=this.policies[a],b.researched&&this.game.unlock(b.unlocks)},unlockAll:function(){for(var a=this.techs.length-1;0<=a;a--){var b=this.techs[a];b.researched=
!0;b.unlocked=!0;this.game.unlock(b.unlocks)}this.game.msg("All techs are unlocked!")}});
dojo.declare("classes.ui.PolicyBtnController",com.nuclearunicorn.game.ui.BuildingNotStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.tooltipName=!0;a.simplePrices=!1;return a},getMetadata:function(a){a.metaCached||(a.metaCached=this.game.science.getPolicy(a.options.id));return a.metaCached},getName:function(a){var b=a.metadata;return b.blocked?b.label+" "+$I("btn.blocked.capital"):this.inherited(arguments)},getPrices:function(a){a=a.metadata;for(var b=this.game.getEffect("policyFakeBought"),
c=[],d=0;d<a.prices.length;d++)c.push({val:a.prices[d].val*Math.pow(1.25,b),name:a.prices[d].name});return c},updateVisible:function(a){var b=a.metadata;a.visible=b.unlocked;b.researched&&this.game.science.policyToggleResearched&&(a.visible=!1);b.blocked&&this.game.science.policyToggleBlocked&&(a.visible=!1)},updateEnabled:function(a){this.inherited(arguments);a.metadata.blocked&&(a.enabled=!1)},shouldBeBough:function(a,b){if(this.game.village.leader&&a.metadata.requiredLeaderJob&&this.game.village.leader.job!=
a.metadata.requiredLeaderJob)return b=this.game.village.getJob(a.metadata.requiredLeaderJob).title,this.game.msg($I("msg.policy.wrongLeaderJobForResearch",[a.metadata.label,b]),"important"),!1;if("transkittenism"==a.metadata.name&&15<=this.game.bld.getBuildingExt("aiCore").meta.effects.aiLevel)return this.game.msg($I("msg.policy.aiNotMerges"),"alert","ai"),!1;if(1!=a.metadata.blocked){for(var c=0;c<a.metadata.blocks.length;c++)if(this.game.science.getPolicy(a.metadata.blocks[c]).researched)return a.metadata.blocked=
!0,!1;var d=!1;if(b.opts.noConfirm)return!0;b.ui.confirm($I("policy.confirmation.title"),$I("policy.confirmation.title"),function(){d=!0})}return d},buyItem:function(a,b,c){!a.metadata.researched&&this.hasResources(a)||this.game.devMode?this.shouldBeBough(a,this.game)?(this.payPrice(a),this.onPurchase(a),c(!0),this.game.render()):c(!1):c(!1)},onPurchase:function(a){this.inherited(arguments);var b=a.metadata;if(b.blocks)for(var c in b.blocks)this.game.science.getPolicy(b.blocks[c]).blocked=!0;if(b.onResearch)b.onResearch(this.game)}});
dojo.declare("classes.ui.PolicyPanel",com.nuclearunicorn.game.ui.Panel,{render:function(a){var b=this.inherited(arguments),c=this;dojo.create("span",{style:{display:"inline-block",marginBottom:"10px",width:"50%"}},b).innerHTML=$I("msg.policy.exclusivity");var d=dojo.create("div",{style:{float:"right"}},b),e=dojo.create("input",{id:"policyToggleResearched",type:"checkbox",checked:this.game.science.policyToggleResearched,style:{}},d);dojo.connect(e,"onclick",this,function(){this.game.science.policyToggleResearched=
!this.game.science.policyToggleResearched;dojo.empty(b);this.game.render(b)});dojo.create("label",{innerHTML:$I("science.policyToggleResearched.label")+"<br>",for:"policyToggleResearched"},d);e=dojo.create("input",{id:"policyToggleBlocked",type:"checkbox",checked:this.game.science.policyToggleBlocked,style:{}},d);dojo.connect(e,"onclick",this,function(){this.game.science.policyToggleBlocked=!this.game.science.policyToggleBlocked;dojo.empty(b);this.game.render(b)});dojo.create("label",{innerHTML:$I("science.policyToggleBlocked.label"),
for:"policyToggleBlocked"},d);var f=new classes.ui.PolicyBtnController(this.game);dojo.forEach(this.game.science.policies,function(g,h){g=new com.nuclearunicorn.game.ui.BuildingResearchBtn({id:g.name,controller:f},c.game);g.render(b);c.addChild(g)});dojo.create("div",{style:{clear:"both"}},b)}});
dojo.declare("com.nuclearunicorn.game.ui.TechButtonController",com.nuclearunicorn.game.ui.BuildingNotStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.tooltipName=!0;a.simplePrices=!1;return a},getMetadata:function(a){a.metaCached||(a.metaCached=this.game.science.get(a.options.id));return a.metaCached},getPrices:function(a){var b=this.game.village.getEffectLeader("scientist",this.inherited(arguments));this.game.ironWill&&this.game.challenges.isActive("blackSky")&&"construction"==
a.metadata.name&&(b=b.concat([{name:"gold",val:5}]));return b},updateVisible:function(a){var b=a.metadata;a.visible=b.unlocked;if(b.researched&&this.game.science.hideResearched)return a.visible=!1;if("metaphysics"==b.name||"chronophysics"==b.name||"cryptotheology"==b.name)if("metaphysics"==b.name&&!game.space.programs[0].on&&3>game.stats.getStat("totalResets").val||"chronophysics"==b.name&&!game.resPool.resources[31].unlocked&&!game.resPool.resources[25].unlocked||"cryptotheology"==b.name&&!game.resPool.resources[33].unlocked)return a.visible=
!1}});
dojo.declare("com.nuclearunicorn.game.ui.tab.Library",com.nuclearunicorn.game.ui.tab,{metaphysicsPanel:null,render:function(a){this.buttons=[];var b=this.game.science.get("civil"),c=dojo.create("div",{style:{float:"right"}},a);b=dojo.create("input",{id:"toggleResearched",type:"checkbox",checked:this.game.science.hideResearched,style:{display:b?"":"none"}},c);dojo.connect(b,"onclick",this,function(){this.game.science.hideResearched=!this.game.science.hideResearched;dojo.empty(a);this.render(a)});dojo.create("label",
{innerHTML:$I("science.toggleResearched.label"),for:"toggleResearched"},c);c=dojo.create("table",{className:"table",style:{width:"100%"}},a);dojo.create("tr",null,c);this.tdTop=dojo.create("td",{colspan:2},dojo.create("tr",null,c));b=dojo.create("tr",null,c);for(c=0;c<this.game.science.techs.length;c++){var d=this.createTechBtn(this.game.science.techs[c]);d.updateVisible();d.updateEnabled();this.addButton(d);d.render(b)}this.policyPanel=new classes.ui.PolicyPanel($I("policy.panel.label"),this.game.science);
this.policyPanel.game=this.game;this.policyPanel.render(a);this.metaphysicsPanel=null;b=this.game.science.get("metaphysics").researched&&1<this.game.resPool.get("paragon").value;if(!b)for(c=this.game.prestige.perks.length-1;0<=c;c--)if(this.game.prestige.perks[c].researched){b=!0;break}b&&(this.metaphysicsPanel=new classes.ui.PrestigePanel($I("prestige.panel.label"),this.game.prestige),this.metaphysicsPanel.game=this.game,this.metaphysicsPanel.render(a));this.game.detailedPollutionInfo&&(this.detailedPollutionInfo=
dojo.create("span",{style:{display:"inline-block",marginBottom:"20px"}},a));this.update()},update:function(){this.inherited(arguments);this.metaphysicsPanel&&this.metaphysicsPanel.update();this.policyPanel&&this.policyPanel.update();if(this.game.detailedPollutionInfo&&this.detailedPollutionInfo){var a=this.game.bld.cathPollution,b=this.game.bld.cathPollutionPerTick;this.detailedPollutionInfo.innerHTML="Pollution is "+Math.floor(a)+" ("+this.game.getDisplayValueExt(a)+") <br>Polution per tick is "+
Math.floor(b);var c=this.game.bld.getPollutionLevel();this.detailedPollutionInfo.innerHTML+="<br>Pollution level is "+c;0<=c&&(this.detailedPollutionInfo.innerHTML+="<br>Pollution future effects might be at this pollution level:",this.detailedPollutionInfo.innerHTML+="<br>\u2014 Less catnip production",1<=c&&(this.detailedPollutionInfo.innerHTML+="<br>\u2014 Less kitten happines: "+this.game.bld.pollutionEffects.pollutionHappines+"%"),2<=c&&(this.detailedPollutionInfo.innerHTML+="<br>\u2014 Kittens arrive "+
this.game.bld.pollutionEffects.pollutionArrivalSlowdown+" times slower."),4<c?this.detailedPollutionInfo.innerHTML+="<br>\u2014 SR effect doesn't apply to wood and catnip":3<=c&&(this.detailedPollutionInfo.innerHTML+="<br>\u2014 Less SR effect on wood and catnip"));0>b&&a?this.detailedPollutionInfo.innerHTML+="<br> To zero "+this.game.toDisplaySeconds((-a/b/this.game.calendar.ticksPerDay).toFixed()):0<b&&(a=(Math.pow(10,1+c)*this.game.bld.getPollutionLevelBase()-a)/b/this.game.calendar.ticksPerDay,
this.detailedPollutionInfo.innerHTML+="<br> To next level "+this.game.toDisplaySeconds(a.toFixed()))}},constructor:function(a,b){this.game=b},createTechBtn:function(a){var b=new com.nuclearunicorn.game.ui.TechButtonController(this.game);return new com.nuclearunicorn.game.ui.BuildingResearchBtn({id:a.name,controller:b},this.game)}});
