dojo.declare("classes.managers.TimeManager",com.nuclearunicorn.core.TabManager,{game:null,testShatter:0,flux:0,heat:0,isAccelerated:!1,timestamp:null,queue:null,constructor:function(a){this.game=a;this.registerMeta("stackable",this.chronoforgeUpgrades,null);this.registerMeta("stackable",this.voidspaceUpgrades,null);this.setEffectsCachedExisting();this.queue=new classes.queue.manager(a)},save:function(a){a.time={timestamp:this.game.pauseTimestamp||Date.now(),flux:this.flux,heat:this.heat,testShatter:this.testShatter,
isAccelerated:this.isAccelerated,cfu:this.filterMetadata(this.chronoforgeUpgrades,"name val on heat unlocked isAutomationEnabled".split(" ")),vsu:this.filterMetadata(this.voidspaceUpgrades,["name","val","on"]),queueItems:this.queue.queueItems,queueSources:this.queue.queueSources};this._forceChronoFurnaceStop(a.time.cfu)},_forceChronoFurnaceStop:function(a){for(var b=0;b<a.length;b++){var c=a[b];if("blastFurnace"==c.name){c.isAutomationEnabled=!1;break}}},load:function(a){if(a.time){this.flux=a.time.flux||
0;this.heat=a.time.heat||0;this.testShatter=a.time.testShatter||0;this.isAccelerated=a.time.isAccelerated||!1;this.loadMetadata(this.chronoforgeUpgrades,a.time.cfu);this.loadMetadata(this.voidspaceUpgrades,a.time.vsu);this.getCFU("timeBoiler").unlocked=0<this.getCFU("blastFurnace").val;a.time.usedCryochambers&&this.loadMetadata(this.voidspaceUpgrades,a.time.usedCryochambers);0<this.getVSU("usedCryochambers").val&&(this.getVSU("usedCryochambers").unlocked=!0);var b=a.time.timestamp||Date.now();this.gainTemporalFlux(b);
this.timestamp=b;this.queue.queueItems=a.time.queueItems||[];this.queue.queueSources=a.time.queueSources||this.queue.queueSourcesDefault;if(this.queue.queueSources==={}||"boolean"!=typeof this.queue.queueSources.buildings)this.queue.queueSources=this.queue.queueSourcesDefault;this.queue.alphabeticalSort=a.time.queueAlphabeticalSort;for(var c in this.queue.queueSourcesDefault)void 0===this.queue.queueSources[c]&&(this.queue.queueSources[c]=this.queue.queueSourcesDefault[c]);this.queue.updateQueueSourcesArr();
this.game.getFeatureFlag("QUEUE")||$("#queueLink").hide()}},gainTemporalFlux:function(a){if(this.game.science.get("calendar").researched&&(a=Date.now()-(a||0),!(0>=a))){this.game.updateCaches();this.game.resPool.update();var b=this.getCFU("temporalAccelerator");a=this.game.resPool.addResEvent("temporalFlux",Math.round(a/6E4*this.game.ticksPerSecond*(1+b.val*b.effects.timeRatio)));a=Math.floor(a/this.game.ticksPerSecond);0<a&&this.game.msg($I("time.redshift.temporalFlux",[a]))}},resetState:function(){this.isAccelerated=
!1;this.timestamp=Date.now();for(var a=this.heat=this.flux=0;a<this.chronoforgeUpgrades.length;a++){var b=this.chronoforgeUpgrades[a];this.resetStateStackable(b)}for(a=0;a<this.voidspaceUpgrades.length;a++)b=this.voidspaceUpgrades[a],this.resetStateStackable(b)},update:function(){this.isAccelerated&&0<this.game.resPool.get("temporalFlux").value&&this.game.resPool.addResEvent("temporalFlux",-1);this.game.resPool.get("temporalFlux").value||(this.isAccelerated=!1);if(0<this.heat){var a=Math.min(this.game.getEffect("heatPerTick"),
this.heat),b=1+this.game.getEffect("heatEfficiency");this.getCFU("blastFurnace").heat+=a*b;this.heat-=a;0>this.heat&&(this.heat=0)}for(var c in this.chronoforgeUpgrades)a=this.chronoforgeUpgrades[c],a.action&&a.action(a,this.game);this.calculateRedshift()},updateQueue:function(){this.game.getFeatureFlag("QUEUE")&&this.queue.update()},applyRedshift:function(a,b){this.game.calculateAllEffects();this.game.village.updateResourceProduction();this.game.resPool.update();this.game.updateResources();var c=
this.game.resPool.fastforward(a),d=0;b||(d=this.game.calendar.fastForward(a));this.game.bld.fastforward(a);this.game.workshop.fastforward(a);this.game.village.fastforward(a);this.game.space.fastforward(a);this.game.religion.fastforward(a);this.game.resPool.enforceLimits(c);0<this.heat&&(b=this.game.getEffect("heatPerTick"),b=Math.min(this.heat,a*this.game.calendar.ticksPerDay*b),a=this.getCFU("blastFurnace"),c=1+this.game.getEffect("heatEfficiency"),a.heat+=b*c,this.heat-=b,a.on&&a.isAutomationEnabled&&
100<=a.heat&&(b=Math.floor(a.heat/100),a.heat-=100*b,1==this.testShatter?this.shatterInGroupCycles(b):this.shatter(b)));return d},calculateRedshift:function(){var a=Date.now(),b=this.game.opts.enableRedshift?a-this.timestamp:0;this.timestamp=a;if(!(0>=b||(a=Math.round(b/2E3),3>a))){b=1E3<=this.game.calendar.year||0<this.game.resPool.get("paragon").value?40:10;b*=this.game.calendar.daysPerSeason*this.game.calendar.seasonsPerYear;a>b&&(a=b);if(this.game.getFeatureFlag("QUEUE_REDSHIFT")){var c=this.queue.getFirstItemEtaDay();
b=a;c[1]||(this.applyRedshift(a),b=0);for(;0<b;){c=this.queue.getFirstItemEtaDay();if(!c[1]){this.applyRedshift(b,!0);break}if(c[1]&1){c=c[0];c/=this.game.calendar.daysPerSeason*this.game.calendar.seasonsPerYear;c=Math.ceil(c);c*=this.game.calendar.daysPerSeason*this.game.calendar.seasonsPerYear;if(c>b){this.applyRedshift(b,!0);this.queue.update();break}this.applyRedshift(c,!0);b-=c;this.queue.update()}else this.applyRedshift(b,!0),b=0}b=this.game.calendar.fastForward(a)}else b=this.applyRedshift(a);
this.game.msg($I("time.redshift",[a])+(b?$I("time.redshift.ext",[b]):""))}},chronoforgeUpgrades:[{name:"temporalBattery",label:$I("time.cfu.temporalBattery.label"),description:$I("time.cfu.temporalBattery.desc"),prices:[{name:"timeCrystal",val:5}],effects:{temporalFluxMax:750},priceRatio:1.25,unlocked:!0},{name:"blastFurnace",label:$I("time.cfu.blastFurnace.label"),description:$I("time.cfu.blastFurnace.desc"),prices:[{name:"timeCrystal",val:25},{name:"relic",val:5}],priceRatio:1.25,effects:{heatPerTick:.02,
heatMax:100},calculateEffects:function(a,b){a.effects.heatMax=100+b.getEffect("heatMaxExpansion")},heat:0,on:0,isAutomationEnabled:!1,action:function(a,b){a.calculateEffects(a,b);null==a.isAutomationEnabled&&(a.isAutomationEnabled=!1);a.on<a.val&&(a.on=a.val);if(a.on&&a.isAutomationEnabled&&100<=a.heat){var c=5,d=b.time.testShatter;b.time.getCFU("temporalPress").isAutomationEnabled&&1==d&&(c=Math.max(c,b.getEffect("shatterYearBoost")));var g=Math.floor(a.heat/100);g>c&&(g=c);a.heat-=100*g;1==d?b.time.shatterInGroupCycles(g):
b.time.shatter(g)}},unlocks:{chronoforge:["timeBoiler"]},unlocked:!0},{name:"timeBoiler",label:$I("time.cfu.timeBoiler.label"),description:$I("time.cfu.timeBoiler.desc"),prices:[{name:"timeCrystal",val:25E3}],priceRatio:1.25,effects:{heatMaxExpansion:10,energyConsumption:1},upgrades:{chronoforge:["blastFurnace"]},updateEffects:function(a,b){a.effects.heatMaxExpansion=10*a.on;a.effects.energyConsumption=a.on},action:function(a,b){a.updateEffects(a,b)},unlocked:!1},{name:"temporalAccelerator",label:$I("time.cfu.temporalAccelerator.label"),
description:$I("time.cfu.temporalAccelerator.desc")+"\n"+$I("time.cfu.temporalAccelerator.desc2"),prices:[{name:"timeCrystal",val:10},{name:"relic",val:1E3}],priceRatio:1.25,effects:{timeRatio:.05},calculateEffects:function(a,b){null===a.isAutomationEnabled&&(a.isAutomationEnabled=1==b.time.testShatter);b.time.testShatter=a.isAutomationEnabled?1:0},isAutomationEnabled:null,upgrades:{chronoforge:["temporalImpedance"]},unlocked:!0},{name:"temporalImpedance",label:$I("time.cfu.temporalImpedance.label"),
description:$I("time.cfu.temporalImpedance.desc"),prices:[{name:"timeCrystal",val:100},{name:"relic",val:250}],priceRatio:1.05,effects:{timeImpedance:1E3},calculateEffects:function(a,b){a.effects.timeImpedance=Math.round(1E3*(1+b.getEffect("timeRatio")))},unlocked:!1},{name:"ressourceRetrieval",label:$I("time.cfu.ressourceRetrieval.label"),description:$I("time.cfu.ressourceRetrieval.desc"),prices:[{name:"timeCrystal",val:1E3}],priceRatio:1.3,limitBuild:100,effects:{shatterTCGain:.01},unlocked:!1},
{name:"temporalPress",label:$I("time.cfu.temporalPress.label"),description:$I("time.cfu.temporalPress.desc"),prices:[{name:"timeCrystal",val:100},{name:"void",val:10}],priceRatio:1.1,limitBuild:0,effects:{shatterYearBoost:0,energyConsumption:5},calculateEffects:function(a,b){null==a.isAutomationEnabled&&1<b.challenges.getChallenge("1000Years").on&&(a.isAutomationEnabled=!1);a.effects.shatterYearBoost=a.isAutomationEnabled?5*b.calendar.yearsPerCycle:b.calendar.yearsPerCycle;a.limitBuild=b.getEffect("temporalPressCap");
a.priceRatio=Math.max(1.01,1.1-.001*b.challenges.getChallenge("1000Years").on)},isAutomationEnabled:null,unlocked:!1}],voidspaceUpgrades:[{name:"cryochambers",label:$I("time.vsu.cryochambers.label"),description:$I("time.vsu.cryochambers.desc"),prices:[{name:"karma",val:1},{name:"timeCrystal",val:2},{name:"void",val:100}],priceRatio:1.25,limitBuild:0,breakIronWill:!0,effects:{maxKittens:1},upgrades:{voidSpace:["cryochambers"]},calculateEffects:function(a,b){a.limitBuild=b.bld.get("chronosphere").on+
b.getEffect("cryochamberSupport");a.on=Math.min(a.val,a.limitBuild)},unlocked:!1,flavor:$I("time.vsu.cryochambers.flavor")},{name:"usedCryochambers",label:$I("time.vsu.usedCryochambers.label"),description:$I("time.vsu.usedCryochambers.desc"),prices:[],fixPrices:[{name:"temporalFlux",val:3E3},{name:"timeCrystal",val:100},{name:"void",val:500}],priceRatio:1.25,limitBuild:0,effects:{},calculateEffects:function(a,b){0<a.val&&b.time.queue.unlockQueueSource("voidSpace")},unlocked:!1},{name:"voidHoover",
label:$I("time.vsu.voidHoover.label"),description:$I("time.vsu.voidHoover.desc"),prices:[{name:"antimatter",val:1E3},{name:"timeCrystal",val:10},{name:"void",val:250}],priceRatio:1.25,effects:{temporalParadoxVoid:1},unlocked:!1},{name:"voidRift",label:$I("time.vsu.voidRift.label"),description:$I("time.vsu.voidRift.desc"),prices:[{name:"void",val:75}],priceRatio:1.3,effects:{umbraBoostRatio:.1,globalResourceRatio:.02},upgrades:{spaceBuilding:["hrHarvester"]},unlocked:!1},{name:"chronocontrol",label:$I("time.vsu.chronocontrol.label"),
description:$I("time.vsu.chronocontrol.desc"),prices:[{name:"temporalFlux",val:3E3},{name:"timeCrystal",val:30},{name:"void",val:500}],priceRatio:1.25,effects:{temporalParadoxDay:0,energyConsumption:15},calculateEffects:function(a,b){a.effects.temporalParadoxDay=1+b.getEffect("temporalParadoxDayBonus")},unlockScheme:{name:"vintage",threshold:1},unlocks:{upgrades:["turnSmoothly"]},unlocked:!1},{name:"voidResonator",label:$I("time.vsu.voidResonator.label"),description:$I("time.vsu.voidResonator.desc"),
prices:[{name:"timeCrystal",val:1E3},{name:"relic",val:1E4},{name:"void",val:50}],priceRatio:1.25,effects:{voidResonance:.1},unlocked:!1}],effectsBase:{heatPerTick:.01,heatMax:100,temporalFluxMax:3E3},getCFU:function(a){return this.getMeta(a,this.chronoforgeUpgrades)},getVSU:function(a){return this.getMeta(a,this.voidspaceUpgrades)},shatter:function(a){a=a||1;var b=this.game,c=b.calendar,d=b.getEffect("routeSpeed")||1,g=b.getEffect("shatterTCGain")*(1+b.getEffect("rrRatio")),f=0<b.getEffect("voidResonance"),
e=c.daysPerSeason*c.seasonsPerYear,p=c.daysPerSeason*(c.seasonsPerYear-c.season)-c.day;c.day=0;for(var k=c.season=0;k<a;k++){var m=0==k?p:e,r=m*c.ticksPerDay,q;for(q in b.space.planets){var h=b.space.planets[q];h.unlocked&&!h.reached&&(h.routeDays=Math.max(0,h.routeDays-m*d))}if(0<g){m={};for(q=0;q<b.resPool.resources.length;q++)h=b.resPool.resources[q],m[h.name]=Math.max(h.value,h.maxValue||Number.POSITIVE_INFINITY),b.resPool.addRes(h,b.getResourcePerTick(h.name,!0)*r*g,!1,!0);this.game.workshop.get("chronoEngineers").researched&&
this.game.workshop.craftByEngineers(r*g);for(q=0;q<b.resPool.resources.length;q++)h=b.resPool.resources[q],h.value=Math.min(h.value,m[h.name]);b.bld.cacheCathPollutionPerTick();b.bld.cathPollutionFastForward(r*g)}f&&b.religion.triggerOrderOfTheVoid(r);c.year++;c.onNewYear(k+1==a)}1==a?b.msg($I("time.tc.shatterOne"),"","tcShatter"):b.msg($I("time.tc.shatter",[a]),"","tcShatter");this.flux+=a-1+p/e;b.challenges.getChallenge("1000Years").unlocked=!0;b.challenges.isActive("1000Years")&&1E3<=c.year&&b.challenges.researchChallenge("1000Years")},
shatterInCycles:function(a){var b=a=a||1,c=this.game,d=c.calendar,g=d.year+a,f=c.getEffect("routeSpeed")||1,e=c.getEffect("shatterTCGain")*(1+c.getEffect("rrRatio")),p=0<c.getEffect("voidResonance"),k=d.daysPerSeason*d.seasonsPerYear,m=d.daysPerSeason*(d.seasonsPerYear-d.season)-d.day,r=m;d.day=0;d.season=0;var q=m+(a-1)*k,h;for(h in c.space.planets){var n=c.space.planets[h];n.unlocked&&!n.reached&&(n.routeDays=Math.max(0,n.routeDays-q*f))}for(;0<b;){f=Math.min(d.yearsPerCycle-d.cycleYear,b);m=((f-
1)*k+m)*d.ticksPerDay;if(0<e){q={};for(h=0;h<c.resPool.resources.length;h++)n=c.resPool.resources[h],q[n.name]=Math.max(n.value,n.maxValue||Number.POSITIVE_INFINITY),c.resPool.addRes(n,c.getResourcePerTick(n.name,!0)*m*e,!1,!0);this.game.workshop.get("chronoEngineers").researched&&this.game.workshop.craftByEngineers(m*e);for(h=0;h<c.resPool.resources.length;h++)n=c.resPool.resources[h],n.value=Math.min(n.value,q[n.name]);c.bld.cacheCathPollutionPerTick();c.bld.cathPollutionFastForward(m*e)}p&&c.religion.triggerOrderOfTheVoid(m);
d.year+=f;d.onNewYears(g==d.year,f,!1);d.calculateMilleniumProduction(d.getMilleniaChanged(d.year-f,d.year));b-=f;m=d.daysPerSeason*d.seasonsPerYear}1==a?c.msg($I("time.tc.shatterOne"),"","tcShatter"):c.msg($I("time.tc.shatter",[a]),"","tcShatter");this.flux+=a-1+r/k;c.challenges.getChallenge("1000Years").unlocked=!0;c.challenges.isActive("1000Years")&&1E3<=d.year&&c.challenges.researchChallenge("1000Years")},shatterInGroupCycles:function(a){a=a||1;if(1==a)this.shatter(1);else{var b=a,c=this.game,
d=c.calendar,g=d.year,f=d.year+a,e=c.getEffect("routeSpeed")||1,p=c.getEffect("shatterTCGain")*(1+c.getEffect("rrRatio")),k=0<c.getEffect("voidResonance"),m=d.daysPerSeason*d.seasonsPerYear,r=d.daysPerSeason*(d.seasonsPerYear-d.season)-d.day,q=r;d.day=0;d.season=0;var h=this.game.bld.get("aiCore").effects.aiLevel,n=0;14<h&&1!=this.game.science.getPolicy("transkittenism").researched&&1!=a&&(n=h-14);h=-Math.min(1,.01*n);var y=r+(a-1)*m,t;for(t in c.space.planets){var v=c.space.planets[t];v.unlocked&&
!v.reached&&(v.routeDays=Math.max(0,v.routeDays-y*e))}e=[0,0,0,0,0,0,0,0,0,0];if(0==b%50)for(t in e)e[t]=b/10;else{y=b-b%50;for(t in e)e[t]=y/10;b-=y;e[d.cycle]+=Math.min(d.yearsPerCycle-d.cycleYear,b);b-=Math.min(d.yearsPerCycle-d.cycleYear,b);for(t=1;t<d.cyclesPerEra;t++)e[(d.cycle+t)%10]+=Math.min(d.yearsPerCycle,b),b+=-Math.min(d.yearsPerCycle,b)}b=a;y=d.cycle;for(v=0;v<d.cyclesPerEra;v++){var w=e[(v+y)%10];if(w){r=((w-1)*m+r)*d.ticksPerDay;if(0<p){1==w&&(n=0);var A={},u={};for(t=0;t<c.resPool.resources.length;t++){var l=
c.resPool.resources[t],x=Math.max(l.value,l.maxValue||Number.POSITIVE_INFINITY),z=c.resPool.addRes(l,c.getResourcePerTick(l.name,!0)*r*p,!1,!0);n&&l.aiCanDestroy&&(u[l.name]=z);A[l.name]=x}this.game.workshop.get("chronoEngineers").researched&&this.game.workshop.craftByEngineers(r*p);for(t=0;t<c.resPool.resources.length;t++)l=c.resPool.resources[t],n&&l.aiCanDestroy&&(z=l.value-u[l.name],u[l.name]/=w||1,x==l.MaxValue&&z+u[l.name]-(z+u[l.name])*h>=x?x=Math.min(x,l.value)*(1+h):l.maxValue?x=Math.min(x,
l.value)*Math.pow(1+h,w):(u[l.name]=Math.max(u[l.name],0),c.resPool.addResEvent(l.name,-u[l.name]*(1-Math.abs(Math.pow(h,w)))/(Math.abs(1-h)||1)-z*(1-Math.pow(1+h,w))))),l.value=Math.min(l.value,A[l.name]);c.bld.cacheCathPollutionPerTick();c.bld.cathPollutionFastForward(r*p)}k&&c.religion.triggerOrderOfTheVoid(r);d.year+=Math.min(5,b);d.onNewYears(f==d.year,Math.min(5,b),!1);b-=Math.min(5,b);r=d.daysPerSeason*d.seasonsPerYear}}0>b&&console.error("max years shattered negative "+toString(b));d.year+=
b;d.onNewYears(f==d.year,b,!1);d.calculateMilleniumProduction(d.getMilleniaChanged(g,d.year));1==a?c.msg($I("time.tc.shatterOne"),"","tcShatter"):c.msg($I("time.tc.shatter",[a]),"","tcShatter");n&&this.game.msg($I("ai.apocalypse.msg",[n]),"alert","ai");this.flux+=a-1+q/m;c.challenges.getChallenge("1000Years").unlocked=!0;c.challenges.isActive("1000Years")&&1E3<=d.year&&c.challenges.researchChallenge("1000Years")}},compareShatterTime:function(a,b,c,d,g){if(!c){for(var f=new Date,e=0;e<b;e++)this.shatter(a);
var p=new Date;console.log("oldShatterAverafe = "+(p.getTime()-f.getTime())/b)}if(!g){var k=new Date;for(e=0;e<b;e++)this.shatterInGroupCycles(a);var m=new Date;console.log("Group shatter average = "+(m.getTime()-k.getTime())/b)}if(!d){var r=new Date;for(e=0;e<b;e++)this.shatterInCycles(a);var q=new Date;d||console.log("Cycle shatter average= "+(q.getTime()-r.getTime())/b)}c||g||console.log("newEfficensy = "+(p.getTime()-f.getTime())/(m.getTime()-k.getTime()));c||d||console.log("new1Efficensy = "+
(p.getTime()-f.getTime())/(q.getTime()-r.getTime()))},unlockAll:function(){for(var a in this.cfu)this.cfu[a].unlocked=!0;this.game.msg("All time upgrades are unlocked")}});
dojo.declare("classes.ui.time.AccelerateTimeBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{fetchModel:function(a){var b=this.inherited(arguments),c=this;b.toggle={title:this.game.time.isAccelerated?$I("btn.on.minor"):$I("btn.off.minor"),tooltip:this.game.time.isAccelerated?$I("time.AccelerateTimeBtn.tooltip.accelerated"):$I("time.AccelerateTimeBtn.tooltip.normal"),cssClass:this.game.time.isAccelerated?"fugit-on":"fugit-off",handler:function(d,g){0>=c.game.resPool.get("temporalFlux").value?
(c.game.time.isAccelerated=!1,c.game.resPool.get("temporalFlux").value=0):c.game.time.isAccelerated=!c.game.time.isAccelerated;g(!0)}};return b},buyItem:function(){}});dojo.declare("classes.ui.time.AccelerateTimeBtn",com.nuclearunicorn.game.ui.ButtonModern,{renderLinks:function(){this.toggle=this.addLink(this.model.toggle)},update:function(){this.inherited(arguments);this.updateLink(this.toggle,this.model.toggle)}});
dojo.declare("classes.ui.TimeControlWgt",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){this.addChild(new classes.ui.time.AccelerateTimeBtn({name:$I("time.AccelerateTimeBtn.label"),description:$I("time.AccelerateTimeBtn.desc"),prices:[],controller:new classes.ui.time.AccelerateTimeBtnController(a)},a))},render:function(a){var b=dojo.create("div",null,a);this.timeSpan=dojo.create("span",null,b);UIUtils.attachTooltip(this.game,this.timeSpan,0,200,dojo.hitch(this,function(){var c=$I("time.flux.desc");
this.game.workshop.get("chronoforge").researched&&(c+="<br>"+$I("time.chronoheat"));return c}));b=dojo.create("div",{style:{paddingTop:"20px"}},b);this.inherited(arguments,[b])},update:function(){var a=this.game.resPool.get("temporalFlux");this.timeSpan.innerHTML=$I("time.flux")+": "+this.game.getDisplayValueExt(a.value)+" / "+a.maxValue;var b=a.value/this.game.ticksPerSecond;this.timeSpan.innerHTML+=" ("+(1>b?"0"+$I("unit.s"):this.game.toDisplaySeconds(b))+" / "+this.game.toDisplaySeconds(a.maxValue/
this.game.ticksPerSecond)+")";if(this.game.workshop.get("chronoforge").researched){this.timeSpan.innerHTML+="<br>"+$I("time.heat")+": ";a=this.game.getEffect("heatMax");this.timeSpan.innerHTML=this.game.time.heat>a?this.timeSpan.innerHTML+("<span style='color:red;'>"+this.game.getDisplayValueExt(this.game.time.heat)+"</span>"):this.timeSpan.innerHTML+this.game.getDisplayValueExt(this.game.time.heat);this.timeSpan.innerHTML+=" / "+this.game.getDisplayValueExt(a);b=this.game.getEffect("heatPerTick")*
this.game.ticksPerSecond;var c=this.game.time.heat/b;this.timeSpan.innerHTML+=" ("+(1>c?"0"+$I("unit.s"):this.game.toDisplaySeconds(c))+" / "+this.game.toDisplaySeconds(a/b)+")"}this.inherited(arguments)}});
dojo.declare("classes.ui.time.ShatterTCBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{defaults:function(){var a=this.inherited(arguments);a.hasResourceHover=!0;return a},fetchModel:function(a){var b=this.inherited(arguments);b.nextCycleLink=this._newLink(b,this.game.calendar.yearsPerCycle);b.previousCycleLink=this._newLink(b,this.game.calendar.yearsPerCycle*(this.game.calendar.cyclesPerEra-1));b.tenErasLink=this._newLink(b,10*this.game.calendar.yearsPerCycle*this.game.calendar.cyclesPerEra);
var c=this.game.getEffect("shatterYearBoost");c&&(b.customLink=this._newLink(b,c));return b},_newLink:function(a,b){var c=this;return{visible:this.game.opts.showNonApplicableButtons||this.getPricesMultiple(a,b).timeCrystal<=this.game.resPool.get("timeCrystal").value&&this.getPricesMultiple(a,b).void<=this.game.resPool.get("void").value,title:"x"+b,handler:function(d){c.doShatterAmt(a,b)}}},getName:function(a){var b=this.inherited(arguments);this.game.time.heat>this.game.getEffect("heatMax")&&(b+=
$I("common.warning"));return b},getPrices:function(a){a=$.extend(!0,[],a.options.prices);if(this.game.getEffect("shatterVoidCost")){var b=this.game.getEffect("shatterVoidCost");a.push({name:"void",val:b})}for(var c in a)if(b=a[c],"timeCrystal"==b.name){var d=this.game.calendar.darkFutureYears(!0);0<d&&(b.val=1+d/1E3*.01);d=this.game.getEffect("heatMax");this.game.time.heat>d&&(b.val*=1+.01*(this.game.time.heat-d));b.val*=1+this.game.getLimitedDR(this.game.getEffect("shatterCostReduction"),1)+this.game.getEffect("shatterCostIncreaseChallenge")}else"void"==
b.name&&(d=this.game.getEffect("heatMax"),this.game.time.heat>d&&(b.val*=1+.01*(this.game.time.heat-d)));return a},getPricesMultiple:function(a,b){var c={void:0,timeCrystal:0};a=$.extend(!0,[],a.options.prices);var d=this.game.getEffect("heatMax"),g=this.game.challenges.getChallenge("1000Years").researched?5:10;if(this.game.getEffect("shatterVoidCost")){var f=this.game.getEffect("shatterVoidCost");a.push({name:"void",val:f})}if(500<b){if(this.game.time.heat<=d||1!=a.length)return"skip";k=a[0].val;
var e=this.game.calendar.darkFutureYears(!0);0<e&&(k=1+e/1E3*.01);k*=1+this.game.getLimitedDR(this.game.getEffect("shatterCostReduction"),1)+this.game.getEffect("shatterCostIncreaseChallenge");c.timeCrystal=k*(1+.01*(this.game.time.heat-d))*b+k*g*.01*b*(b-1)/2;return c}for(f=0;f<b;f++)for(var p in a)if(e=a[p],"timeCrystal"==e.name){var k=e.val;e=this.game.calendar.darkFutureYears(!0);0<e&&(k=1+e/1E3*.01);this.game.time.heat+f*g>d&&(k*=1+.01*(this.game.time.heat+f*g-d));k*=1+this.game.getLimitedDR(this.game.getEffect("shatterCostReduction"),
1)+this.game.getEffect("shatterCostIncreaseChallenge");c.timeCrystal+=k}else"void"==e.name&&(k=e.val,this.game.time.heat+f*g>d&&(k*=1+.01*(this.game.time.heat+f*g-d)),c.void+=k);c.void=Math.round(1E3*c.void)/1E3;return c},buyItem:function(a,b,c){if(a.enabled&&this.hasResources(a)){b=this.getPrices(a);for(var d in b)this.game.resPool.addResEvent(b[d].name,-b[d].val);this.doShatter(a,1);c(!0)}c(!1);return!0},doShatterAmt:function(a,b){if(a.enabled){var c=this.getPricesMultiple(a,b);"skip"!==c&&(c.void?
c.timeCrystal<=this.game.resPool.get("timeCrystal").value&&c.void<=this.game.resPool.get("void").value&&(this.game.resPool.addResEvent("timeCrystal",-c.timeCrystal),this.game.resPool.addResEvent("void",-c.void),this.doShatter(a,b)):c.timeCrystal<=this.game.resPool.get("timeCrystal").value&&(this.game.resPool.addResEvent("timeCrystal",-c.timeCrystal),this.doShatter(a,b)))}},doShatter:function(a,b){a=this.game.challenges.getChallenge("1000Years").researched?5:10;this.game.time.heat+=b*a;1==this.game.time.testShatter?
this.game.time.shatterInGroupCycles(b):2==this.game.time.testShatter?this.game.time.shatterInCycles(b):this.game.time.shatter(b)},updateVisible:function(a){a.visible=1<=this.game.resPool.get("timeCrystal").value}});
dojo.declare("classes.ui.time.ShatterTCBtn",com.nuclearunicorn.game.ui.ButtonModern,{renderLinks:function(){this.tenEras=this.addLink(this.model.tenErasLink);this.previousCycle=this.addLink(this.model.previousCycleLink);this.nextCycle=this.addLink(this.model.nextCycleLink);this.model.customLink&&(this.custom=this.addLink(this.model.customLink))},update:function(){this.inherited(arguments);dojo.style(this.nextCycle.link,"display",this.model.nextCycleLink.visible?"":"none");dojo.style(this.previousCycle.link,
"display",this.model.previousCycleLink.visible?"":"none");dojo.style(this.tenEras.link,"display",this.model.tenErasLink.visible?"":"none");this.custom&&dojo.style(this.custom.link,"display",this.model.customLink&&this.model.customLink.visible?"":"none");this.model.tenErasLink.visible?(dojo.addClass(this.tenEras.link,"rightestLink"),dojo.removeClass(this.previousCycle.link,"rightestLink")):this.model.previousCycleLink.visible?(dojo.addClass(this.previousCycle.link,"rightestLink"),dojo.removeClass(this.nextCycle.link,
"rightestLink")):this.model.nextCycleLink.visible&&dojo.addClass(this.nextCycle.link,"rightestLink");this.model.customLink&&this.updateLink(this.custom,this.model.customLink)}});
dojo.declare("classes.ui.time.ChronoforgeBtnController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{getMetadata:function(a){a.metaCached||(a.metaCached=this.game.time.getCFU(a.options.id));return a.metaCached},getName:function(a){var b=a.metadata;return b.heat?this.inherited(arguments)+" ["+this.game.getDisplayValueExt(b.heat)+"%]":this.inherited(arguments)},handleToggleAutomationLinkClick:function(a){a=a.metadata;a.isAutomationEnabled=!a.isAutomationEnabled;this.game.upgrade({chronoforge:[a.name]})}});
dojo.declare("classes.ui.ChronoforgeWgt",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){this.addChild(new classes.ui.time.ShatterTCBtn({name:$I("time.shatter.tc"),description:$I("time.shatter.tc.desc"),prices:[{name:"timeCrystal",val:1}],controller:new classes.ui.time.ShatterTCBtnController(a)},a));var b=new classes.ui.time.ChronoforgeBtnController(a),c;for(c in a.time.chronoforgeUpgrades)this.addChild(new com.nuclearunicorn.game.ui.BuildingStackableBtn({id:a.time.chronoforgeUpgrades[c].name,
controller:b},a))},render:function(a){var b=dojo.create("div",null,a);b=dojo.create("div",{style:{paddingTop:"20px"}},b);this.inherited(arguments,[b])},update:function(){this.inherited(arguments)}});
dojo.declare("classes.ui.time.VoidSpaceBtnController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{getMetadata:function(a){a.metaCached||(a.metaCached=this.game.time.getVSU(a.options.id));return a.metaCached},getName:function(a){var b=a.metadata;return"cryochambers"==b.name&&b.on!=b.val?b.label+" ("+b.on+"/"+b.val+")":this.inherited(arguments)},getPrices:function(a){var b=this.inherited(arguments);if("cryochambers"==a.metadata.name)for(var c=0;c<b.length;c++)"karma"==b[c].name&&(b[c].val-=
b[c].val*this.game.getLimitedDR(.01*this.game.prestige.getBurnedParagonRatio(),1));return b}});
dojo.declare("classes.ui.time.FixCryochamberBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{defaults:function(){var a=this.inherited(arguments);a.hasResourceHover=!0;return a},buyItem:function(a,b,c){if(a.enabled){var d=b.shiftKey?1E3:b.ctrlKey||b.metaKey?this.game.opts.batchSize||10:1;d=Math.min(d,this.game.time.getVSU("usedCryochambers").val);b=!1;for(var g=0;g<d&&this.hasResources(a);++g)this.payPrice(a),b|=this.doFixCryochamber(a);b&&(a=this.game.time.getVSU("cryochambers"),
a.calculateEffects(a,this.game));c(b)}else c(!1)},doFixCryochamber:function(a){a=this.game.time.getVSU("cryochambers");var b=this.game.time.getVSU("usedCryochambers");return this.game.workshop.get("chronoforge").researched&&b.val?(--b.val,--b.on,a.val+=1,a.on+=1,b.on||(b.unlocked=!1),!0):!1},updateVisible:function(a){a.visible=this.game.workshop.get("chronoforge").researched&&0!=this.game.time.getVSU("usedCryochambers").val}});
dojo.declare("classes.ui.VoidSpaceWgt",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){this.addChild(new com.nuclearunicorn.game.ui.ButtonModern({name:$I("time.fixCryochambers.label"),description:$I("time.fixCryochambers.desc"),prices:a.time.getVSU("usedCryochambers").fixPrices,controller:new classes.ui.time.FixCryochamberBtnController(a)},a));var b=new classes.ui.time.VoidSpaceBtnController(a),c;for(c in a.time.voidspaceUpgrades)this.addChild(new com.nuclearunicorn.game.ui.BuildingStackableBtn({id:a.time.voidspaceUpgrades[c].name,
controller:b},a))},render:function(a){var b=dojo.create("div",null,a);b=dojo.create("div",{style:{paddingTop:"20px"}},b);this.inherited(arguments,[b])},update:function(){this.inherited(arguments)}});
dojo.declare("classes.ui.ResetWgt",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){this.addChild(new com.nuclearunicorn.game.ui.ButtonModern({name:$I("menu.reset"),description:$I("time.reset.desc"),prices:[],handler:function(b){a.reset()},controller:new com.nuclearunicorn.game.ui.ButtonModernController(a)},a))},render:function(a){var b=dojo.create("div",null,a),c=dojo.create("div",{style:{paddingTop:"20px"}},b);this.inherited(arguments,[c]);this.resetDiv=dojo.create("div",{style:{paddingTop:"20px"}},
b)},update:function(){this.inherited(arguments);var a=$I("time.reset.instructional"),b=this.game.getResetPrestige(),c=b.paragonPoints,d=b.karmaKittens;b=this.game.getUnlimitedDR(this.game.karmaKittens,5);d=this.game.getUnlimitedDR(d,5);b=Math.floor(100*(d-b))/100;a+="<br>"+$I("time.reset.karma")+": "+b;a+="<br>"+$I("time.reset.paragon")+": "+c;this.game.ironWill&&(a+="<br>"+$I("time.reset.zebra")+": "+this.game._getBonusZebras());this.resetDiv.innerHTML=a}});
dojo.declare("classes.tab.TimeTab",com.nuclearunicorn.game.ui.tab,{container:null,constructor:function(a){a=new com.nuclearunicorn.game.ui.Panel($I("tab.name.time"));this.addChild(a);var b=new classes.ui.TimeControlWgt(this.game);b.setGame(this.game);a.addChild(b);this.resetPanel=new com.nuclearunicorn.game.ui.Panel($I("menu.reset"));this.resetPanel.setVisible(!0);this.addChild(this.resetPanel);a=new classes.ui.ResetWgt(this.game);a.setGame(this.game);this.resetPanel.addChild(a);this.cfPanel=new com.nuclearunicorn.game.ui.Panel($I("workshop.chronoforge.label"));
this.cfPanel.setVisible(!1);this.addChild(this.cfPanel);a=new classes.ui.ChronoforgeWgt(this.game);a.setGame(this.game);this.cfPanel.addChild(a);this.vsPanel=new com.nuclearunicorn.game.ui.Panel($I("science.voidSpace.label"));this.vsPanel.setVisible(!1);this.addChild(this.vsPanel);a=new classes.ui.VoidSpaceWgt(this.game);a.setGame(this.game);this.vsPanel.addChild(a)},render:function(a){this.container=a;this.inherited(arguments);this.update()},update:function(){this.inherited(arguments);this.game.workshop.get("chronoforge").researched&&
this.cfPanel.setVisible(!0);(this.game.science.get("voidSpace").researched||0<this.game.time.getVSU("usedCryochambers").val)&&this.vsPanel.setVisible(!0)}});
dojo.declare("classes.queue.manager",null,{game:null,alphabeticalSort:!0,queueItems:[],toggleAlphabeticalSort:function(){this.alphabeticalSort=!this.alphabeticalSort},getFirstItemEtaDay:function(){if(0==this.queueItems.length)return[0,!1];var a=0,b=this.getQueueElementModel(this.queueItems[0]).prices,c=this.game.workshop.getConsumptionEngineers(),d;for(d in b){var g=b[d],f=this.game.resPool.get(g.name);if(!(f.value>=g.val)){if(f.maxValue<g.val)return[a,!1];var e=this.game.getResourcePerTick(f.name,
!0);if(!e)return[a,!1];var p=this.game.workshop.getEffectEngineer(f.name,!0);a=Math.max(a,(g.val-f.value)/(e+(c[f.name]||0)+p)/this.game.calendar.ticksPerDay);p&&(g=1/this.game.workshop.getEffectEngineer(f.name,!1)/this.game.calendar.ticksPerDay,a=Math.ceil(a/g)*g)}}a=Math.ceil(a);return[a,!0]},updateQueueSourcesArr:function(){for(var a in this.queueSources)if(this.queueSources[a]){var b=!0,c;for(c in this.queueSourcesArr)if(this.queueSourcesArr[c].name==a){b=!1;break}b&&this.queueSourcesArr.push({name:a,
label:this.queueLabels[a]})}},queueLabels:{buildings:$I("buildings.tabName"),tech:$I("techs.panel.label"),upgrades:$I("workshop.upgradePanel.label"),policies:$I("policy.panel.label"),religion:$I("religion.panel.orderOfTheSun.label"),zebraUpgrades:$I("workshop.zebraUpgradesPanel.label"),spaceMission:$I("space.ground.control.label"),spaceBuilding:$I("tab.name.space"),zigguratUpgrades:$I("religion.panel.ziggurat.label"),transcendenceUpgrades:$I("religion.panel.cryptotheology.label"),chronoforge:$I("workshop.chronoforge.label"),
voidSpace:$I("science.voidSpace.label")},queueSourcesArr:[{name:"buildings",label:$I("buildings.tabName")}],queueSourcesDefault:{buildings:!0,tech:!1,upgrades:!1,policies:!1,religion:!1,zebraUpgrades:!1,spaceMission:!1,spaceBuilding:!1,zigguratUpgrades:!1,transcendenceUpgrades:!1,chronoforge:!1,voidSpace:!1},queueSources:{},queueNonStackable:["tech","upgrades","policies","zebraUpgrades","spaceMission"],unlockQueueSource:function(a){!1===this.queueSources[a]&&(this.queueSources[a]=!0,this.queueSourcesArr.push({name:a,
label:this.queueLabels[a]}))},cap:0,baseCap:2,constructor:function(a){this.game=a},calculateCap:function(){return this.game.bld.getBuildingExt("aiCore").meta.on+this.game.space.getBuilding("entangler").effects.hashRateLevel+this.baseCap+this.game.getEffect("queueCap")},queueLength:function(){var a=0,b;for(b in this.queueItems)a+=this.queueItems[b].value||1;return a},addToQueue:function(a,b,c,d){if(!a||!b)console.error("queueMgr#addToQueue: unable to add item:",a,b,c);else if(!(this.queueLength()>=
this.cap))if(0<this.queueItems.length&&this.queueItems[this.queueItems.length-1].name==a){if(!this.queueNonStackable.includes(b)&&(this.queueItems[this.queueItems.length-1].value=(this.queueItems[this.queueItems.length-1].value||1)+1,d))for(;this.queueLength()<this.cap;)this.addToQueue(a,b,c,!1)}else if(c||="$"+a+"$",this.queueItems.push({name:a,type:b,label:c,value:1}),d&&!this.queueNonStabkable.includes(b))for(;this.queueLength()<this.cap;)this.addToQueue(a,b,c,!1)},remove:function(a,b){if(0>a||
a>=this.queueItems.length)return console.warn("queue#remove - invalid index",a),!1;var c=this.queueItems[a];c.value-=b;c.value||this.queueItems.splice(a,1);return!0},getQueueOptions:function(a){return this.alphabeticalSort?this.getQueueOptionsAlphabetical(a):this.getQueueOptionsUnsorted(a)},getQueueOptionsAlphabetical:function(a){return this.getQueueOptionsUnsorted(a).sort(function(b,c){return b.label.localeCompare(c.label)})},getQueueOptionsUnsorted:function(a){var b=[];switch(a){case "buildings":var c=
this.game.bld,d;for(d in c.buildingsData)if(a=c.buildingsData[d],a.unlocked){var g=a.name,f=a.label;a.stages&&a.stages&&(f=a.stages[a.stage].label);b.push({name:g,label:f})}return b;case "spaceBuilding":c=this.game.space.spaceBuildingsMap;for(d in c)a=this.game.space.getBuilding(c[d]),a.unlocked&&b.push({name:a.name,label:a.label});return b;case "zigguratUpgrades":a=this.game.religion.zigguratUpgrades;for(d in a)a=this.game.religion.zigguratUpgrades[d],a.unlocked&&b.push({name:a.name,label:a.label});
return b;case "transcendenceUpgrades":a=this.game.religion.transcendenceUpgrades;for(d in a)a=this.game.religion.transcendenceUpgrades[d],a.unlocked&&b.push({name:a.name,label:a.label});return b;case "chronoforge":c=this.game.time.chronoforgeUpgrades;for(d in c)a=c[d],a.unlocked&&b.push({name:a.name,label:a.label});return b;case "voidSpace":c=this.game.time.voidspaceUpgrades;for(d in c)a=c[d],"usedCryochambers"==a.name?b.push({name:a.name,label:$I("time.fixCryochambers.label")}):a.unlocked&&b.push({name:a.name,
label:a.label});return b;case "tech":a=this.game.science.techs;for(d in a)c=a[d],c.unlocked&&!c.researched&&b.push({name:c.name,label:c.label});return b;case "upgrades":c=this.game.workshop.upgrades;for(d in c)a=c[d],a.unlocked&&!a.researched&&b.push({name:a.name,label:a.label});return b;case "zebraUpgrades":c=this.game.workshop.zebraUpgrades;for(d in c)a=c[d],a.unlocked&&!a.researched&&b.push({name:a.name,label:a.label});return b;case "spaceMission":a=this.game.space.programs;for(d in a)c=a[d],c.unlocked&&
!c.val&&b.push({name:c.name,label:c.label});return b;case "policies":a=this.game.science.policies;for(d in a)c=a[d],!c.unlocked||c.researched||c.blocked||b.push({name:c.name,label:c.label});return b;case "religion":c=this.game.religion.religionUpgrades;if(this.game.challenges.getChallenge("atheism").active)return b;for(d in c)a=c[d],!(a.faith<=this.game.religion.faith)||a.noStackable&&a.val||b.push({name:a.name,label:a.label});return b;default:return b}},dropLastItem:function(){var a=this.queueItems[0];
a.value&&1<a.value?--a.value:(this.queueItems.shift(),this.game._publish("ui/update",this.game))},listDrop:function(a){this.dropLastItem();this.showList()},getQueueElementModel:function(a){var b=this.game.getUnlockByName(a.name,a.type);if(b){var c={id:b.name};switch(a.type){case "policies":c.controller=new classes.ui.PolicyBtnController(this.game);var d=c.controller.fetchModel(c);break;case "tech":c.controller=new com.nuclearunicorn.game.ui.TechButtonController(this.game);d=c.controller.fetchModel(c);
break;case "buildings":a=(new classes.BuildingMeta(b)).getMeta();c={key:a.name,name:a.label,description:a.description,building:a.name};c.controller="object"==typeof a.stages?new classes.ui.btn.StagingBldBtnController(this.game):new classes.ui.btn.BuildingBtnModernController(this.game);d=c.controller.fetchModel(c);break;case "spaceMission":c.controller=new com.nuclearunicorn.game.ui.SpaceProgramBtnController(this.game);d=c.controller.fetchModel(c);break;case "spaceBuilding":c.controller=new classes.ui.space.PlanetBuildingBtnController(this.game);
d=c.controller.fetchModel(c);break;case "chronoforge":c.controller=new classes.ui.time.ChronoforgeBtnController(this.game);d=c.controller.fetchModel(c);break;case "voidSpace":c.controller=new classes.ui.time.VoidSpaceBtnController(this.game);d=c.controller.fetchModel(c);"usedCryochambers"==a.name&&(c.controller=new classes.ui.time.FixCryochamberBtnController(this.game),this.game.getUnlockByName("cryochambers",a.type),d.prices=this.game.time.getVSU("usedCryochambers").fixPrices,d.enabled=this.game.resPool.hasRes(d.prices),
console.log(d));break;case "zigguratUpgrades":c.controller=new com.nuclearunicorn.game.ui.ZigguratBtnController(this.game);d=c.controller.fetchModel(c);break;case "religion":c.controller=new com.nuclearunicorn.game.ui.ReligionBtnController(this.game);d=c.controller.fetchModel(c);break;case "transcendenceUpgrades":c.controller=new classes.ui.TranscendenceBtnController(this.game);d=c.controller.fetchModel(c);break;case "pacts":c.controller=new com.nuclearunicorn.game.ui.PactsBtnController(this.game);
d=c.controller.fetchModel(c);break;case "upgrades":c.controller=new com.nuclearunicorn.game.ui.UpgradeButtonController(this.game);d=c.controller.fetchModel(c);break;case "zebraUpgrades":c.controller=new com.nuclearunicorn.game.ui.ZebraUpgradeButtonController(this.game),d=c.controller.fetchModel(c)}return d}console.error("invalid queue item:",a)},update:function(){this.cap=this.calculateCap();if(this.queueItems.length){var a=this.queueItems[0],b=this.game.getUnlockByName(a.name,a.type),c="val";if(b){var d=
{id:b.name},g=!0;switch(a.type){case "policies":c=["researched","blocked"];d.controller=new classes.ui.PolicyBtnController(this.game);var f={researched:b.researched,blocked:b.blocked},e=d.controller.fetchModel(d);break;case "tech":c="researched";d.controller=new com.nuclearunicorn.game.ui.TechButtonController(this.game);f=b.researched;e=d.controller.fetchModel(d);break;case "buildings":e=(new classes.BuildingMeta(b)).getMeta();f=b.val;d={key:e.name,name:e.label,description:e.description,building:e.name};
d.controller="object"==typeof e.stages?new classes.ui.btn.StagingBldBtnController(this.game):new classes.ui.btn.BuildingBtnModernController(this.game);e=d.controller.fetchModel(d);d.controller.build(e,1);g=!1;break;case "spaceMission":c="reached";d.controller=new com.nuclearunicorn.game.ui.SpaceProgramBtnController(this.game);f=b.researched;e=d.controller.fetchModel(d);break;case "spaceBuilding":d.controller=new classes.ui.space.PlanetBuildingBtnController(this.game);f=b.val;e=d.controller.fetchModel(d);
break;case "chronoforge":d.controller=new classes.ui.time.ChronoforgeBtnController(this.game);f=b.val;e=d.controller.fetchModel(d);break;case "voidSpace":d.controller=new classes.ui.time.VoidSpaceBtnController(this.game);f=b.val;e=d.controller.fetchModel(d);"usedCryochambers"==a.name&&(d.controller=new classes.ui.time.FixCryochamberBtnController(this.game),b=this.game.getUnlockByName("cryochambers",a.type),e.prices=this.game.time.getVSU("usedCryochambers").fixPrices,e.enabled=this.game.resPool.hasRes(e.prices),
console.log(e));break;case "zigguratUpgrades":d.controller=new com.nuclearunicorn.game.ui.ZigguratBtnController(this.game);f=b.val;e=d.controller.fetchModel(d);break;case "religion":d.controller=new com.nuclearunicorn.game.ui.ReligionBtnController(this.game);f=b.val;e=d.controller.fetchModel(d);break;case "transcendenceUpgrades":d.controller=new classes.ui.TranscendenceBtnController(this.game);f=b.val;e=d.controller.fetchModel(d);break;case "pacts":d.controller=new com.nuclearunicorn.game.ui.PactsBtnController(this.game);
f=b.val;e=d.controller.fetchModel(d);break;case "upgrades":c="researched";d.controller=new com.nuclearunicorn.game.ui.UpgradeButtonController(this.game);f=b.researched;e=d.controller.fetchModel(d);break;case "zebraUpgrades":c="researched",d.controller=new com.nuclearunicorn.game.ui.ZebraUpgradeButtonController(this.game),f=b.researched,e=d.controller.fetchModel(d)}d.controller||(console.error(a.name+" of "+a.type+" queing is not supported!"),this.queueItems.shift(),this.game._publish("ui/update",
this.game));g&&d.controller.buyItem(e,1,function(k){});a=!1;if(Array.isArray(c))for(var p in c)f[c[p]]!=e.metadata[c[p]]&&(a=!0);else a=f!=e.metadata[c];a&&(this.dropLastItem(),this.game._publish("ui/update",this.game));if("research"==c||"reached"==c&&1==e.metadata[c]||c.includes("blocked")&&1==e.metadata.blocked||c.includes("research")&&1==e.metadata.research)this.dropLastItem(),this.game._publish("ui/update",this.game)}else console.error("invalid queue item:",a)}}});
