dojo.declare("classes.managers.TimeManager",com.nuclearunicorn.core.TabManager,{game:null,testShatter:0,flux:0,heat:0,isAccelerated:!1,timestamp:null,constructor:function(a){this.game=a;this.registerMeta("stackable",this.chronoforgeUpgrades,null);this.registerMeta("stackable",this.voidspaceUpgrades,null);this.setEffectsCachedExisting()},save:function(a){a.time={timestamp:this.game.pauseTimestamp||Date.now(),flux:this.flux,heat:this.heat,testShatter:this.testShatter,isAccelerated:this.isAccelerated,
cfu:this.filterMetadata(this.chronoforgeUpgrades,["name","val","on","heat","unlocked"]),vsu:this.filterMetadata(this.voidspaceUpgrades,["name","val","on"])};this._forceChronoFurnaceStop(a.time.cfu)},_forceChronoFurnaceStop:function(a){for(var b=0;b<a.length;b++){var c=a[b];if("blastFurnace"==c.name){c.isAutomationEnabled=!1;break}}},load:function(a){a.time&&(this.flux=a.time.flux||0,this.heat=a.time.heat||0,this.testShatter=a.time.testShatter||0,this.isAccelerated=a.time.isAccelerated||!1,this.loadMetadata(this.chronoforgeUpgrades,
a.time.cfu),this.loadMetadata(this.voidspaceUpgrades,a.time.vsu),this.getCFU("timeBoiler").unlocked=0<this.getCFU("blastFurnace").val,a.time.usedCryochambers&&this.loadMetadata(this.voidspaceUpgrades,a.time.usedCryochambers),0<this.getVSU("usedCryochambers").val&&(this.getVSU("usedCryochambers").unlocked=!0),a=a.time.timestamp||Date.now(),this.gainTemporalFlux(a),this.timestamp=a)},gainTemporalFlux:function(a){if(this.game.science.get("calendar").researched&&(a=Date.now()-(a||0),!(0>=a))){this.game.updateCaches();
this.game.resPool.update();var b=this.getCFU("temporalAccelerator");a=this.game.resPool.addResEvent("temporalFlux",Math.round(a/6E4*this.game.ticksPerSecond*(1+b.val*b.effects.timeRatio)));a=Math.floor(a/this.game.ticksPerSecond);0<a&&this.game.msg($I("time.redshift.temporalFlux",[a]))}},resetState:function(){this.isAccelerated=!1;this.timestamp=Date.now();for(var a=this.heat=this.flux=0;a<this.chronoforgeUpgrades.length;a++){var b=this.chronoforgeUpgrades[a];this.resetStateStackable(b)}for(a=0;a<
this.voidspaceUpgrades.length;a++)b=this.voidspaceUpgrades[a],this.resetStateStackable(b)},update:function(){this.isAccelerated&&0<this.game.resPool.get("temporalFlux").value&&this.game.resPool.addResEvent("temporalFlux",-1);this.game.resPool.get("temporalFlux").value||(this.isAccelerated=!1);if(0<this.heat){var a=Math.min(this.game.getEffect("heatPerTick"),this.heat);this.getCFU("blastFurnace").heat+=a;this.heat-=a;0>this.heat&&(this.heat=0)}for(var b in this.chronoforgeUpgrades)a=this.chronoforgeUpgrades[b],
a.action&&a.action(a,this.game);this.calculateRedshift()},calculateRedshift:function(){var a=Date.now(),b=this.game.opts.enableRedshift?a-this.timestamp:0;this.timestamp=a;if(!(0>=b||(a=Math.round(b/2E3),3>a))){b=1E3<=this.game.calendar.year||0<this.game.resPool.get("paragon").value?40:10;b*=this.game.calendar.daysPerSeason*this.game.calendar.seasonsPerYear;a>b&&(a=b);this.game.resPool.update();this.game.updateResources();var c=this.game.resPool.fastforward(a);b=this.game.calendar.fastForward(a);
this.game.bld.fastforward(a);this.game.workshop.fastforward(a);this.game.village.fastforward(a);this.game.space.fastforward(a);this.game.religion.fastforward(a);this.game.resPool.enforceLimits(c);if(0<this.heat){c=this.game.getEffect("heatPerTick");var d=Math.min(this.heat,a*this.game.calendar.ticksPerDay*c);c=this.getCFU("blastFurnace");c.heat+=d;this.heat-=d;c.on&&c.isAutomationEnabled&&100<=c.heat&&(d=Math.floor(c.heat/100),c.heat-=100*d,1==this.testShatter?this.shatterInGroupCycles(d):this.shatter(d))}this.game.msg($I("time.redshift",
[a])+(b?$I("time.redshift.ext",[b]):""))}},chronoforgeUpgrades:[{name:"temporalBattery",label:$I("time.cfu.temporalBattery.label"),description:$I("time.cfu.temporalBattery.desc"),prices:[{name:"timeCrystal",val:5}],effects:{temporalFluxMax:750},priceRatio:1.25,unlocked:!0},{name:"blastFurnace",label:$I("time.cfu.blastFurnace.label"),description:$I("time.cfu.blastFurnace.desc"),prices:[{name:"timeCrystal",val:25},{name:"relic",val:5}],priceRatio:1.25,effects:{heatPerTick:.02,heatMax:100},calculateEffects:function(a,
b){a.effects.heatMax=100+b.getEffect("heatMaxExpansion")},heat:0,on:0,isAutomationEnabled:!1,action:function(a,b){a.calculateEffects(a,b);null==a.isAutomationEnabled&&(a.isAutomationEnabled=!1);a.on<a.val&&(a.on=a.val);if(a.on&&a.isAutomationEnabled&&100<=a.heat){var c=Math.floor(a.heat/100);5<c&&(c=5);a.heat-=100*c;1==b.time.testShatter?b.time.shatterInGroupCycles(c):b.time.shatter(c)}},unlocks:{chronoforge:["timeBoiler"]},unlocked:!0},{name:"timeBoiler",label:$I("time.cfu.timeBoiler.label"),description:$I("time.cfu.timeBoiler.desc"),
prices:[{name:"timeCrystal",val:25E3}],priceRatio:1.25,effects:{heatMaxExpansion:10,energyConsumption:1},upgrades:{chronoforge:["blastFurnace"]},updateEffects:function(a,b){a.effects.heatMaxExpansion=10*a.on;a.effects.energyConsumption=a.on},action:function(a,b){a.updateEffects(a,b)},unlocked:!1},{name:"temporalAccelerator",label:$I("time.cfu.temporalAccelerator.label"),description:$I("time.cfu.temporalAccelerator.desc")+"\n"+$I("time.cfu.temporalAccelerator.desc2"),prices:[{name:"timeCrystal",val:10},
{name:"relic",val:1E3}],priceRatio:1.25,effects:{timeRatio:.05},calculateEffects:function(a,b){null===a.isAutomationEnabled&&(a.isAutomationEnabled=1==b.time.testShatter);b.time.testShatter=a.isAutomationEnabled?1:0},isAutomationEnabled:null,upgrades:{chronoforge:["temporalImpedance"]},unlocked:!0},{name:"temporalImpedance",label:$I("time.cfu.temporalImpedance.label"),description:$I("time.cfu.temporalImpedance.desc"),prices:[{name:"timeCrystal",val:100},{name:"relic",val:250}],priceRatio:1.05,effects:{timeImpedance:1E3},
calculateEffects:function(a,b){a.effects.timeImpedance=Math.round(1E3*(1+b.getEffect("timeRatio")))},unlocked:!1},{name:"ressourceRetrieval",label:$I("time.cfu.ressourceRetrieval.label"),description:$I("time.cfu.ressourceRetrieval.desc"),prices:[{name:"timeCrystal",val:1E3}],priceRatio:1.3,limitBuild:100,effects:{shatterTCGain:.01},unlocked:!1},{name:"temporalPress",label:$I("time.cfu.temporalPress.label"),description:$I("time.cfu.temporalPress.desc"),prices:[{name:"timeCrystal",val:100},{name:"void",
val:10}],priceRatio:1.1,limitBuild:0,effects:{shatterYearBoost:0,energyConsumption:5},calculateEffects:function(a,b){null==a.isAutomationEnabled&&1<b.challenges.getChallenge("1000Years").on&&(a.isAutomationEnabled=!1);a.effects.shatterYearBoost=a.isAutomationEnabled?5*b.calendar.yearsPerCycle:b.calendar.yearsPerCycle;a.limitBuild=b.getEffect("temporalPressCap");a.priceRatio=Math.max(1.05,1.1-.001*b.challenges.getChallenge("1000Years").on)},isAutomationEnabled:null,unlocked:!1}],voidspaceUpgrades:[{name:"cryochambers",
label:$I("time.vsu.cryochambers.label"),description:$I("time.vsu.cryochambers.desc"),prices:[{name:"karma",val:1},{name:"timeCrystal",val:2},{name:"void",val:100}],priceRatio:1.25,limitBuild:0,breakIronWill:!0,effects:{maxKittens:1},upgrades:{voidSpace:["cryochambers"]},calculateEffects:function(a,b){a.limitBuild=b.bld.get("chronosphere").on+b.getEffect("cryochamberSupport");a.on=Math.min(a.val,a.limitBuild)},unlocked:!1,flavor:$I("time.vsu.cryochambers.flavor")},{name:"usedCryochambers",label:$I("time.vsu.usedCryochambers.label"),
description:$I("time.vsu.usedCryochambers.desc"),prices:[],priceRatio:1.25,limitBuild:0,effects:{},unlocked:!1},{name:"voidHoover",label:$I("time.vsu.voidHoover.label"),description:$I("time.vsu.voidHoover.desc"),prices:[{name:"antimatter",val:1E3},{name:"timeCrystal",val:10},{name:"void",val:250}],priceRatio:1.25,effects:{temporalParadoxVoid:1},unlocked:!1},{name:"voidRift",label:$I("time.vsu.voidRift.label"),description:$I("time.vsu.voidRift.desc"),prices:[{name:"void",val:75}],priceRatio:1.3,effects:{umbraBoostRatio:.1,
globalResourceRatio:.02},upgrades:{spaceBuilding:["hrHarvester"]},unlocked:!1},{name:"chronocontrol",label:$I("time.vsu.chronocontrol.label"),description:$I("time.vsu.chronocontrol.desc"),prices:[{name:"temporalFlux",val:3E3},{name:"timeCrystal",val:30},{name:"void",val:500}],priceRatio:1.25,effects:{temporalParadoxDay:0,energyConsumption:15},calculateEffects:function(a,b){a.effects.temporalParadoxDay=1+b.getEffect("temporalParadoxDayBonus")},unlockScheme:{name:"vintage",threshold:1},unlocks:{upgrades:["turnSmoothly"]},
unlocked:!1},{name:"voidResonator",label:$I("time.vsu.voidResonator.label"),description:$I("time.vsu.voidResonator.desc"),prices:[{name:"timeCrystal",val:1E3},{name:"relic",val:1E4},{name:"void",val:50}],priceRatio:1.25,effects:{voidResonance:.1},unlocked:!1}],effectsBase:{heatPerTick:.01,heatMax:100,temporalFluxMax:3E3},getCFU:function(a){return this.getMeta(a,this.chronoforgeUpgrades)},getVSU:function(a){return this.getMeta(a,this.voidspaceUpgrades)},shatter:function(a){a=a||1;var b=this.game,c=
b.calendar,d=b.getEffect("routeSpeed")||1,l=b.getEffect("shatterTCGain")*(1+b.getEffect("rrRatio")),k=0<b.getEffect("voidResonance"),e=c.daysPerSeason*c.seasonsPerYear,t=c.daysPerSeason*(c.seasonsPerYear-c.season)-c.day;c.day=0;for(var g=c.season=0;g<a;g++){var m=0==g?t:e,q=m*c.ticksPerDay,p;for(p in b.space.planets){var f=b.space.planets[p];f.unlocked&&!f.reached&&(f.routeDays=Math.max(0,f.routeDays-m*d))}if(0<l){m={};for(p=0;p<b.resPool.resources.length;p++)f=b.resPool.resources[p],m[f.name]=Math.max(f.value,
f.maxValue||Number.POSITIVE_INFINITY),b.resPool.addRes(f,b.getResourcePerTick(f.name,!0)*q*l,!1,!0);this.game.workshop.get("chronoEngineers").researched&&this.game.workshop.craftByEngineers(q*l);for(p=0;p<b.resPool.resources.length;p++)f=b.resPool.resources[p],f.value=Math.min(f.value,m[f.name]);b.bld.cacheCathPollutionPerTick();b.bld.cathPollutionFastForward(q*l)}k&&b.religion.triggerOrderOfTheVoid(q);c.year++;c.onNewYear(g+1==a)}1==a?b.msg($I("time.tc.shatterOne"),"","tcShatter"):b.msg($I("time.tc.shatter",
[a]),"","tcShatter");this.flux+=a-1+t/e;b.challenges.getChallenge("1000Years").unlocked=!0;b.challenges.isActive("1000Years")&&1E3<=c.year&&b.challenges.researchChallenge("1000Years");b.upgrade({buildings:["pasture"]})},shatterInCycles:function(a){var b=a=a||1,c=this.game,d=c.calendar,l=d.year+a,k=c.getEffect("routeSpeed")||1,e=c.getEffect("shatterTCGain")*(1+c.getEffect("rrRatio")),t=0<c.getEffect("voidResonance"),g=d.daysPerSeason*d.seasonsPerYear,m=d.daysPerSeason*(d.seasonsPerYear-d.season)-d.day,
q=m;d.day=0;d.season=0;var p=m+(a-1)*g,f;for(f in c.space.planets){var n=c.space.planets[f];n.unlocked&&!n.reached&&(n.routeDays=Math.max(0,n.routeDays-p*k))}for(;0<b;){k=Math.min(d.yearsPerCycle-d.cycleYear,b);m=((k-1)*g+m)*d.ticksPerDay;if(0<e){p={};for(f=0;f<c.resPool.resources.length;f++)n=c.resPool.resources[f],p[n.name]=Math.max(n.value,n.maxValue||Number.POSITIVE_INFINITY),c.resPool.addRes(n,c.getResourcePerTick(n.name,!0)*m*e,!1,!0);this.game.workshop.get("chronoEngineers").researched&&this.game.workshop.craftByEngineers(m*
e);for(f=0;f<c.resPool.resources.length;f++)n=c.resPool.resources[f],n.value=Math.min(n.value,p[n.name]);c.bld.cacheCathPollutionPerTick();c.bld.cathPollutionFastForward(m*e)}t&&c.religion.triggerOrderOfTheVoid(m);d.year+=k;d.onNewYears(l==d.year,k,!1);d.calculateMilleniumProduction(d.getMilleniaChanged(d.year-k,d.year));b-=k;m=d.daysPerSeason*d.seasonsPerYear}1==a?c.msg($I("time.tc.shatterOne"),"","tcShatter"):c.msg($I("time.tc.shatter",[a]),"","tcShatter");this.flux+=a-1+q/g;c.challenges.getChallenge("1000Years").unlocked=
!0;c.challenges.isActive("1000Years")&&1E3<=d.year&&c.challenges.researchChallenge("1000Years");this.game.upgrade({buildings:["pasture"]})},shatterInGroupCycles:function(a){a=a||1;if(1==a)this.shatter(1);else{var b=a,c=this.game,d=c.calendar,l=d.year,k=d.year+a,e=c.getEffect("routeSpeed")||1,t=c.getEffect("shatterTCGain")*(1+c.getEffect("rrRatio")),g=0<c.getEffect("voidResonance"),m=d.daysPerSeason*d.seasonsPerYear,q=d.daysPerSeason*(d.seasonsPerYear-d.season)-d.day,p=q;d.day=0;d.season=0;var f=this.game.bld.get("aiCore").effects.aiLevel,
n=0;14<f&&1!=this.game.science.getPolicy("transkittenism").researched&&1!=a&&(n=f-14);f=-Math.min(1,.01*n);var y=q+(a-1)*m,r;for(r in c.space.planets){var v=c.space.planets[r];v.unlocked&&!v.reached&&(v.routeDays=Math.max(0,v.routeDays-y*e))}e=[0,0,0,0,0,0,0,0,0,0];if(0==b%50)for(r in e)e[r]=b/10;else{y=b-b%50;for(r in e)e[r]=y/10;b-=y;e[d.cycle]+=Math.min(d.yearsPerCycle-d.cycleYear,b);b-=Math.min(d.yearsPerCycle-d.cycleYear,b);for(r=1;r<d.cyclesPerEra;r++)e[(d.cycle+r)%10]+=Math.min(d.yearsPerCycle,
b),b+=-Math.min(d.yearsPerCycle,b)}b=a;y=d.cycle;for(v=0;v<d.cyclesPerEra;v++){var w=e[(v+y)%10];if(w){q=((w-1)*m+q)*d.ticksPerDay;if(0<t){1==w&&(n=0);var A={},u={};for(r=0;r<c.resPool.resources.length;r++){var h=c.resPool.resources[r],x=Math.max(h.value,h.maxValue||Number.POSITIVE_INFINITY),z=c.resPool.addRes(h,c.getResourcePerTick(h.name,!0)*q*t,!1,!0);n&&h.aiCanDestroy&&(u[h.name]=z);A[h.name]=x}this.game.workshop.get("chronoEngineers").researched&&this.game.workshop.craftByEngineers(q*t);for(r=
0;r<c.resPool.resources.length;r++)h=c.resPool.resources[r],n&&h.aiCanDestroy&&(z=h.value-u[h.name],u[h.name]/=w||1,x==h.MaxValue&&z+u[h.name]-(z+u[h.name])*f>=x?x=Math.min(x,h.value)*(1+f):h.maxValue?x=Math.min(x,h.value)*Math.pow(1+f,w):(u[h.name]=Math.max(u[h.name],0),c.resPool.addResEvent(h.name,-u[h.name]*(1-Math.abs(Math.pow(f,w)))/(Math.abs(1-f)||1)-z*(1-Math.pow(1+f,w))))),h.value=Math.min(h.value,A[h.name]);c.bld.cacheCathPollutionPerTick();c.bld.cathPollutionFastForward(q*t)}g&&c.religion.triggerOrderOfTheVoid(q);
d.year+=Math.min(5,b);d.onNewYears(k==d.year,Math.min(5,b),!1);b-=Math.min(5,b);q=d.daysPerSeason*d.seasonsPerYear}}0>b&&console.error("max years shattered negative "+toString(b));d.year+=b;d.onNewYears(k==d.year,b,!1);d.calculateMilleniumProduction(d.getMilleniaChanged(l,d.year));1==a?c.msg($I("time.tc.shatterOne"),"","tcShatter"):c.msg($I("time.tc.shatter",[a]),"","tcShatter");n&&this.game.msg($I("ai.apocalypse.msg",[n]),"alert","ai");this.flux+=a-1+p/m;c.challenges.getChallenge("1000Years").unlocked=
!0;c.challenges.isActive("1000Years")&&1E3<=d.year&&c.challenges.researchChallenge("1000Years");this.game.upgrade({buildings:["pasture"]})}},compareShatterTime:function(a,b,c,d,l){if(!c){for(var k=new Date,e=0;e<b;e++)this.shatter(a);var t=new Date;console.log("oldShatterAverafe = "+(t.getTime()-k.getTime())/b)}if(!l){var g=new Date;for(e=0;e<b;e++)this.shatterInGroupCycles(a);var m=new Date;console.log("Group shatter average = "+(m.getTime()-g.getTime())/b)}if(!d){var q=new Date;for(e=0;e<b;e++)this.shatterInCycles(a);
var p=new Date;d||console.log("Cycle shatter average= "+(p.getTime()-q.getTime())/b)}c||l||console.log("newEfficensy = "+(t.getTime()-k.getTime())/(m.getTime()-g.getTime()));c||d||console.log("new1Efficensy = "+(t.getTime()-k.getTime())/(p.getTime()-q.getTime()))},unlockAll:function(){for(var a in this.cfu)this.cfu[a].unlocked=!0;this.game.msg("All time upgrades are unlocked")}});
dojo.declare("classes.ui.time.AccelerateTimeBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{fetchModel:function(a){var b=this.inherited(arguments),c=this;b.toggle={title:this.game.time.isAccelerated?$I("btn.on.minor"):$I("btn.off.minor"),tooltip:this.game.time.isAccelerated?$I("time.AccelerateTimeBtn.tooltip.accelerated"):$I("time.AccelerateTimeBtn.tooltip.normal"),cssClass:this.game.time.isAccelerated?"fugit-on":"fugit-off",handler:function(d,l){0>=c.game.resPool.get("temporalFlux").value?
(c.game.time.isAccelerated=!1,c.game.resPool.get("temporalFlux").value=0):c.game.time.isAccelerated=!c.game.time.isAccelerated;l(!0)}};return b},buyItem:function(){}});dojo.declare("classes.ui.time.AccelerateTimeBtn",com.nuclearunicorn.game.ui.ButtonModern,{renderLinks:function(){this.toggle=this.addLink(this.model.toggle)},update:function(){this.inherited(arguments);this.updateLink(this.toggle,this.model.toggle)}});
dojo.declare("classes.ui.TimeControlWgt",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){this.addChild(new classes.ui.time.AccelerateTimeBtn({name:$I("time.AccelerateTimeBtn.label"),description:$I("time.AccelerateTimeBtn.desc"),prices:[],controller:new classes.ui.time.AccelerateTimeBtnController(a)},a))},render:function(a){var b=dojo.create("div",null,a);this.timeSpan=dojo.create("span",null,b);UIUtils.attachTooltip(this.game,this.timeSpan,0,200,dojo.hitch(this,function(){var c=$I("time.flux.desc");
this.game.workshop.get("chronoforge").researched&&(c+="<br>"+$I("time.chronoheat"));return c}));b=dojo.create("div",{style:{paddingTop:"20px"}},b);this.inherited(arguments,[b])},update:function(){var a=this.game.resPool.get("temporalFlux");this.timeSpan.innerHTML=$I("time.flux")+": "+this.game.getDisplayValueExt(a.value)+" / "+a.maxValue;var b=a.value/this.game.ticksPerSecond;this.timeSpan.innerHTML+=" ("+(1>b?"0"+$I("unit.s"):this.game.toDisplaySeconds(b))+" / "+this.game.toDisplaySeconds(a.maxValue/
this.game.ticksPerSecond)+")";if(this.game.workshop.get("chronoforge").researched){this.timeSpan.innerHTML+="<br>"+$I("time.heat")+": ";a=this.game.getEffect("heatMax");this.timeSpan.innerHTML=this.game.time.heat>a?this.timeSpan.innerHTML+("<span style='color:red;'>"+this.game.getDisplayValueExt(this.game.time.heat)+"</span>"):this.timeSpan.innerHTML+this.game.getDisplayValueExt(this.game.time.heat);this.timeSpan.innerHTML+=" / "+this.game.getDisplayValueExt(a);b=this.game.getEffect("heatPerTick")*
this.game.ticksPerSecond;var c=this.game.time.heat/b;this.timeSpan.innerHTML+=" ("+(1>c?"0"+$I("unit.s"):this.game.toDisplaySeconds(c))+" / "+this.game.toDisplaySeconds(a/b)+")"}this.inherited(arguments)}});
dojo.declare("classes.ui.time.ShatterTCBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{defaults:function(){var a=this.inherited(arguments);a.hasResourceHover=!0;return a},fetchModel:function(a){var b=this.inherited(arguments);b.nextCycleLink=this._newLink(b,this.game.calendar.yearsPerCycle);b.previousCycleLink=this._newLink(b,this.game.calendar.yearsPerCycle*(this.game.calendar.cyclesPerEra-1));b.tenErasLink=this._newLink(b,10*this.game.calendar.yearsPerCycle*this.game.calendar.cyclesPerEra);
var c=this.game.getEffect("shatterYearBoost");c&&(b.customLink=this._newLink(b,c));return b},_newLink:function(a,b){var c=this;return{visible:this.game.opts.showNonApplicableButtons||this.getPricesMultiple(a,b).timeCrystal<=this.game.resPool.get("timeCrystal").value&&this.getPricesMultiple(a,b).void<=this.game.resPool.get("void").value,title:"x"+b,handler:function(d){c.doShatterAmt(a,b)}}},getName:function(a){var b=this.inherited(arguments);this.game.time.heat>this.game.getEffect("heatMax")&&(b+=
$I("common.warning"));return b},getPrices:function(a){a=$.extend(!0,[],a.options.prices);if(this.game.getEffect("shatterVoidCost")){var b=this.game.getEffect("shatterVoidCost");a.push({name:"void",val:b})}for(var c in a)if(b=a[c],"timeCrystal"==b.name){var d=this.game.calendar.darkFutureYears(!0);0<d&&(b.val=1+d/1E3*.01);d=this.game.getEffect("heatMax");this.game.time.heat>d&&(b.val*=1+.01*(this.game.time.heat-d));b.val*=1+this.game.getLimitedDR(this.game.getEffect("shatterCostReduction"),1)+this.game.getEffect("shatterCostIncreaseChallenge")}else"void"==
b.name&&(d=this.game.getEffect("heatMax"),this.game.time.heat>d&&(b.val*=1+.01*(this.game.time.heat-d)));return a},getPricesMultiple:function(a,b){var c={void:0,timeCrystal:0};a=$.extend(!0,[],a.options.prices);var d=this.game.getEffect("heatMax"),l=this.game.challenges.getChallenge("1000Years").researched?5:10;if(this.game.getEffect("shatterVoidCost")){var k=this.game.getEffect("shatterVoidCost");a.push({name:"void",val:k})}if(500<b){if(this.game.time.heat<=d||1!=a.length)return"skip";g=a[0].val;
var e=this.game.calendar.darkFutureYears(!0);0<e&&(g=1+e/1E3*.01);g*=1+this.game.getLimitedDR(this.game.getEffect("shatterCostReduction"),1)+this.game.getEffect("shatterCostIncreaseChallenge");c.timeCrystal=g*(1+.01*(this.game.time.heat-d))*b+g*l*.01*b*(b-1)/2;return c}for(k=0;k<b;k++)for(var t in a)if(e=a[t],"timeCrystal"==e.name){var g=e.val;e=this.game.calendar.darkFutureYears(!0);0<e&&(g=1+e/1E3*.01);this.game.time.heat+k*l>d&&(g*=1+.01*(this.game.time.heat+k*l-d));g*=1+this.game.getLimitedDR(this.game.getEffect("shatterCostReduction"),
1)+this.game.getEffect("shatterCostIncreaseChallenge");c.timeCrystal+=g}else"void"==e.name&&(g=e.val,this.game.time.heat+k*l>d&&(g*=1+.01*(this.game.time.heat+k*l-d)),c.void+=g);c.void=Math.round(1E3*c.void)/1E3;return c},buyItem:function(a,b,c){if(a.enabled&&this.hasResources(a)){b=this.getPrices(a);for(var d in b)this.game.resPool.addResEvent(b[d].name,-b[d].val);this.doShatter(a,1);c(!0)}c(!1);return!0},doShatterAmt:function(a,b){if(a.enabled){var c=this.getPricesMultiple(a,b);"skip"!==c&&(c.void?
c.timeCrystal<=this.game.resPool.get("timeCrystal").value&&c.void<=this.game.resPool.get("void").value&&(this.game.resPool.addResEvent("timeCrystal",-c.timeCrystal),this.game.resPool.addResEvent("void",-c.void),this.doShatter(a,b)):c.timeCrystal<=this.game.resPool.get("timeCrystal").value&&(this.game.resPool.addResEvent("timeCrystal",-c.timeCrystal),this.doShatter(a,b)))}},doShatter:function(a,b){a=this.game.challenges.getChallenge("1000Years").researched?5:10;this.game.time.heat+=b*a;1==this.game.time.testShatter?
this.game.time.shatterInGroupCycles(b):this.game.time.shatter(b)},updateVisible:function(a){a.visible=1<=this.game.resPool.get("timeCrystal").value}});
dojo.declare("classes.ui.time.ShatterTCBtn",com.nuclearunicorn.game.ui.ButtonModern,{renderLinks:function(){this.tenEras=this.addLink(this.model.tenErasLink);this.previousCycle=this.addLink(this.model.previousCycleLink);this.nextCycle=this.addLink(this.model.nextCycleLink);this.model.customLink&&(this.custom=this.addLink(this.model.customLink))},update:function(){this.inherited(arguments);dojo.style(this.nextCycle.link,"display",this.model.nextCycleLink.visible?"":"none");dojo.style(this.previousCycle.link,
"display",this.model.previousCycleLink.visible?"":"none");dojo.style(this.tenEras.link,"display",this.model.tenErasLink.visible?"":"none");this.custom&&dojo.style(this.custom.link,"display",this.model.customLink&&this.model.customLink.visible?"":"none");this.model.tenErasLink.visible?(dojo.addClass(this.tenEras.link,"rightestLink"),dojo.removeClass(this.previousCycle.link,"rightestLink")):this.model.previousCycleLink.visible?(dojo.addClass(this.previousCycle.link,"rightestLink"),dojo.removeClass(this.nextCycle.link,
"rightestLink")):this.model.nextCycleLink.visible&&dojo.addClass(this.nextCycle.link,"rightestLink");this.model.customLink&&this.updateLink(this.custom,this.model.customLink)}});
dojo.declare("classes.ui.time.ChronoforgeBtnController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{getMetadata:function(a){a.metaCached||(a.metaCached=this.game.time.getCFU(a.options.id));return a.metaCached},getName:function(a){var b=a.metadata;return b.heat?this.inherited(arguments)+" ["+this.game.getDisplayValueExt(b.heat)+"%]":this.inherited(arguments)},handleToggleAutomationLinkClick:function(a){a=a.metadata;a.isAutomationEnabled=!a.isAutomationEnabled;this.game.upgrade({chronoforge:[a.name]})}});
dojo.declare("classes.ui.ChronoforgeWgt",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){this.addChild(new classes.ui.time.ShatterTCBtn({name:$I("time.shatter.tc"),description:$I("time.shatter.tc.desc"),prices:[{name:"timeCrystal",val:1}],controller:new classes.ui.time.ShatterTCBtnController(a)},a));var b=new classes.ui.time.ChronoforgeBtnController(a),c;for(c in a.time.chronoforgeUpgrades)this.addChild(new com.nuclearunicorn.game.ui.BuildingStackableBtn({id:a.time.chronoforgeUpgrades[c].name,
controller:b},a))},render:function(a){var b=dojo.create("div",null,a);b=dojo.create("div",{style:{paddingTop:"20px"}},b);this.inherited(arguments,[b])},update:function(){this.inherited(arguments)}});
dojo.declare("classes.ui.time.VoidSpaceBtnController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{getMetadata:function(a){a.metaCached||(a.metaCached=this.game.time.getVSU(a.options.id));return a.metaCached},getName:function(a){var b=a.metadata;return"cryochambers"==b.name&&b.on!=b.val?b.label+" ("+b.on+"/"+b.val+")":this.inherited(arguments)},getPrices:function(a){var b=this.inherited(arguments);if("cryochambers"==a.metadata.name)for(var c=0;c<b.length;c++)"karma"==b[c].name&&(b[c].val-=
b[c].val*this.game.getLimitedDR(.01*this.game.prestige.getBurnedParagonRatio(),1));return b}});
dojo.declare("classes.ui.time.FixCryochamberBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{defaults:function(){var a=this.inherited(arguments);a.hasResourceHover=!0;return a},buyItem:function(a,b,c){if(a.enabled){var d=b.shiftKey?1E3:b.ctrlKey||b.metaKey?this.game.opts.batchSize||10:1;d=Math.min(d,this.game.time.getVSU("usedCryochambers").val);b=!1;for(var l=0;l<d&&this.hasResources(a);++l)this.payPrice(a),b|=this.doFixCryochamber(a);b&&(a=this.game.time.getVSU("cryochambers"),
a.calculateEffects(a,this.game));c(b)}else c(!1)},doFixCryochamber:function(a){a=this.game.time.getVSU("cryochambers");var b=this.game.time.getVSU("usedCryochambers");return this.game.workshop.get("chronoforge").researched&&b.val?(--b.val,--b.on,a.val+=1,a.on+=1,b.on||(b.unlocked=!1),!0):!1},updateVisible:function(a){a.visible=this.game.workshop.get("chronoforge").researched&&0!=this.game.time.getVSU("usedCryochambers").val}});
dojo.declare("classes.ui.VoidSpaceWgt",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){this.addChild(new com.nuclearunicorn.game.ui.ButtonModern({name:$I("time.fixCryochambers.label"),description:$I("time.fixCryochambers.desc"),prices:[{name:"temporalFlux",val:3E3},{name:"timeCrystal",val:100},{name:"void",val:500}],controller:new classes.ui.time.FixCryochamberBtnController(a)},a));var b=new classes.ui.time.VoidSpaceBtnController(a),c;for(c in a.time.voidspaceUpgrades)this.addChild(new com.nuclearunicorn.game.ui.BuildingStackableBtn({id:a.time.voidspaceUpgrades[c].name,
controller:b},a))},render:function(a){var b=dojo.create("div",null,a);b=dojo.create("div",{style:{paddingTop:"20px"}},b);this.inherited(arguments,[b])},update:function(){this.inherited(arguments)}});
dojo.declare("classes.ui.ResetWgt",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){this.addChild(new com.nuclearunicorn.game.ui.ButtonModern({name:$I("menu.reset"),description:$I("time.reset.desc"),prices:[],handler:function(b){a.reset()},controller:new com.nuclearunicorn.game.ui.ButtonModernController(a)},a))},render:function(a){var b=dojo.create("div",null,a),c=dojo.create("div",{style:{paddingTop:"20px"}},b);this.inherited(arguments,[c]);this.resetDiv=dojo.create("div",{style:{paddingTop:"20px"}},
b)},update:function(){this.inherited(arguments);var a=$I("time.reset.instructional"),b=this.game.resPool.get("kittens").value,c=this.game.getUnlimitedDR(this.game.karmaKittens,5);b=this.game.getUnlimitedDR(this.game.karmaKittens+this.game._getKarmaKittens(b),5);c=Math.floor(100*(b-c))/100;b=this.game.getResetPrestige().paragonPoints;a+="<br>"+$I("time.reset.karma")+": "+c;a+="<br>"+$I("time.reset.paragon")+": "+b;this.game.ironWill&&(a+="<br>"+$I("time.reset.zebra")+": "+this.game._getBonusZebras());
this.resetDiv.innerHTML=a}});
dojo.declare("classes.tab.TimeTab",com.nuclearunicorn.game.ui.tab,{container:null,constructor:function(a){a=new com.nuclearunicorn.game.ui.Panel($I("tab.name.time"));this.addChild(a);var b=new classes.ui.TimeControlWgt(this.game);b.setGame(this.game);a.addChild(b);this.resetPanel=new com.nuclearunicorn.game.ui.Panel($I("menu.reset"));this.resetPanel.setVisible(!0);this.addChild(this.resetPanel);a=new classes.ui.ResetWgt(this.game);a.setGame(this.game);this.resetPanel.addChild(a);this.cfPanel=new com.nuclearunicorn.game.ui.Panel($I("workshop.chronoforge.label"));
this.cfPanel.setVisible(!1);this.addChild(this.cfPanel);a=new classes.ui.ChronoforgeWgt(this.game);a.setGame(this.game);this.cfPanel.addChild(a);this.vsPanel=new com.nuclearunicorn.game.ui.Panel($I("science.voidSpace.label"));this.vsPanel.setVisible(!1);this.addChild(this.vsPanel);a=new classes.ui.VoidSpaceWgt(this.game);a.setGame(this.game);this.vsPanel.addChild(a)},render:function(a){this.container=a;this.inherited(arguments);this.update()},update:function(){this.inherited(arguments);this.game.workshop.get("chronoforge").researched&&
this.cfPanel.setVisible(!0);(this.game.science.get("voidSpace").researched||0<this.game.time.getVSU("usedCryochambers").val)&&this.vsPanel.setVisible(!0)}});
