dojo.declare("classes.ui.Toolbar",null,{icons:null,game:null,constructor:function(a){this.game=a;this.icons=[];this.addIcon(new classes.ui.toolbar.ToolbarMOTD(a));this.addIcon(new classes.ui.toolbar.ToolbarHappiness(a));this.addIcon(new classes.ui.toolbar.ToolbarEnergy(a))},addIcon:function(a){this.icons.push(a)},render:function(a){dojo.empty(a);for(var b in this.icons){var c=this.icons[b].render(a);this.icons[b].getOpts().hasTooltip&&(this.attachToolbarTooltip(c,this.icons[b]),dojo.connect(c,"onclick",
this.icons[b],"onClick"));switch(b){case "0":dojo.addClass(c,"motd");break;case "1":dojo.addClass(c,"happiness");break;case "2":dojo.addClass(c,"energy")}}this.update(!0)},update:function(a){for(var b in this.icons)(this.icons[b].getOpts().needUpdate||a)&&this.icons[b].update();a=this.game.resPool.get("sorrow");b=a.value;$("#sorrowTooltip").html(b?$I("resources.sorrow.short")+": "+b.toFixed()+"%":"");a=a.value==a.maxValue;$("#sorrowTooltip").addClass(a?"max":"")},attachToolbarTooltip:function(a,b){var c=
dojo.byId("tooltip");dojo.empty(c);dojo.connect(a,"onmouseover",this,dojo.partial(function(e,d){this.game.tooltipUpdateFunc=function(){e.innerHTML=b.getTooltip()};this.game.tooltipUpdateFunc();if(d=$(d.originalTarget||d.toElement).offset())dojo.style(e,"left",d.left+"px"),dojo.style(e,"top",d.top+"px"),dojo.style(e,"display",""),dojo.style(a,"fontWeight","bold")},c));dojo.connect(a,"onmouseout",this,dojo.partial(function(e,d){this.game.tooltipUpdateFunc=null;dojo.style(e,"display","none");dojo.style(d,
"fontWeight","normal")},c,a))},updateTooltip:function(a,b,c){b.innerHTML=dojo.hitch(this,c)()}});dojo.declare("classes.ui.ToolbarIcon",null,{game:null,container:null,constructor:function(a){this.game=a},render:function(a){return this.container=dojo.create("span",{className:"toolbarIcon"},a)},update:function(){},getTooltip:function(){return"Unimplemented"},onClick:function(){},getOpts:function(){return{needUpdate:!0,hasTooltip:!0}}});
dojo.declare("classes.ui.toolbar.ToolbarHappiness",classes.ui.ToolbarIcon,{update:function(){5>=this.game.village.getKittens()?dojo.style(this.container,"display","none"):dojo.style(this.container,"display","");this.container.innerHTML="(:3)&nbsp;"+Math.floor(100*this.game.village.happiness)+"%"},getTooltip:function(){var a=this.game.getEffect("happiness");a=$I("village.happiness.base")+": 100%<br>"+$I("village.happiness.buildings")+": +"+Math.floor(a)+"%<br>";var b=0,c=this.game.resPool.resources;
var e=10+this.game.getEffect("luxuryHappinessBonus");for(var d=c.length-1;0<=d;d--)"common"!=c[d].type&&0<c[d].value&&(b+=e,"elderBox"==c[d].name&&this.game.resPool.get("wrappingPaper").value&&(b-=e));a+=$I("village.happiness.rare.resources")+": +"+this.game.getDisplayValueExt(b,!1,!1,0)+"%<br>";b=this.game.resPool.get("karma");0<b.value&&(a+=$I("village.happiness.karma")+": +"+this.game.getDisplayValueExt(b.value,!1,!1,0)+"%<br>");0<this.game.calendar.festivalDays&&(b=(30*(1+this.game.getEffect("festivalRatio"))).toFixed(),
a+=$I("village.happiness.festival")+": +"+b+"%<br>");b=this.game.village.getUnhappiness()/(1+this.game.getEffect("unhappinessRatio"));c=b*this.game.getEffect("unhappinessRatio",!0);e=this.game.village.getEnvironmentEffect();d=this.game.getEffect("challengeHappiness");a+=$I("village.happiness.penalty")+": -"+this.game.getDisplayValueExt(b+c,!1,!1,0)+"%<br>";a+="* "+$I("village.happiness.penalty.base")+": -"+this.game.getDisplayValueExt(b,!1,!1,0)+"%<br>";a+="* "+$I("village.happiness.penalty.mitigated")+
": "+this.game.getDisplayValueExt(-c,!1,!1,0)+"%<br>";a+=$I("village.happiness.environment")+": "+this.game.getDisplayValueExt(e,!1,!1,0)+"%<br>";d&&(a+=$I("village.happiness.challenges")+": "+this.game.getDisplayValueExt(d,!1,!1,0)+"%<br>");b=this.game.village.getKittens()-this.game.village.maxKittens;0<b&&(a+=$I("village.happiness.overpopulation")+": -"+2*b+"%<br>");return a}});
dojo.declare("classes.ui.toolbar.ToolbarEnergy",classes.ui.ToolbarIcon,{update:function(){this.game.science.get("electricity").researched?dojo.style(this.container,"display",""):dojo.style(this.container,"display","none");var a=this.game.resPool;this.container.innerHTML="&#9889;&nbsp;"+this.game.getDisplayValueExt(a.energyProd-a.energyCons)+$I("unit.watt");a.energyProd<a.energyCons?($(this.container).removeClass("warningWinter"),$(this.container).addClass("warning")):a.energyWinterProd<a.energyCons?
($(this.container).removeClass("warning"),$(this.container).addClass("warningWinter")):($(this.container).removeClass("warning"),$(this.container).removeClass("warningWinter"))},getTooltip:function(){var a=this.game.resPool,b=a.energyProd-a.energyCons,c=this.game.resPool.getEnergyDelta();b=0<=b?"":"<br><br>"+$I("navbar.energy.penalty")+"<span class='energyPenalty'>-"+Math.floor(100*(1-c))+"%</span>";return $I("navbar.energy.prod")+"<span class='energyProduction'>"+this.game.getDisplayValueExt(a.energyProd,
!0,!1)+$I("unit.watt")+"</span><br>"+$I("navbar.energy.cons")+"<span class='energyConsumption'>-"+this.game.getDisplayValueExt(a.energyCons)+$I("unit.watt")+"</span>"+b}});
dojo.declare("classes.ui.toolbar.ToolbarMOTD",classes.ui.ToolbarIcon,{update:function(){var a=this.game.server;a.showMotd&&a.motdTitle&&(this.container.innerHTML="&nbsp;"+a.motdTitle+"&nbsp;");a.motdFreshMessage?dojo.addClass(this.container,"freshMessage"):dojo.removeClass(this.container,"freshMessage")},getTooltip:function(){var a=this.game.server;if(a.showMotd&&a.motdContent)return a.motdFreshMessage=!1,"Message of the day:<br />"+a.motdContent}});
