window.$r=React.createElement;dojo.declare("mixin.IReactAware",null,{component:null,container:null,constructor:function(a,b){this.component=a;this.game=b},render:function(a){this.game.ui.dirtyComponents.push(this);React.render($r(this.component,{game:this.game}),a);return this.container=a},update:function(){},destroy:function(){if(!this.container)throw"Integrity failure, trying to unmount component on an empty container";React.unmountComponentAtNode(this.container)}});
dojo.declare("classes.ui.UISystem",null,{game:null,setGame:function(a){this.game=a},render:function(){},update:function(){},updateOptions:function(){},unlockScheme:function(a){},relockSchemes:function(){},notifyLogEvent:function(a){},confirm:function(a,b,d,c){},openPopupPage:function(a){},pulse:function(a){},displayAutosave:function(){},resetConsole:function(){},renderFilters:function(){},renderConsoleLog:function(){},saveExport:function(a){},observeCallback:function(){},observeClear:function(){},
updateCalendar:function(){},updateLanguage:function(){},updateNotation:function(){},load:function(){},save:function(){},isEffectMultiplierEnabled:function(){return!1},checkForUpdates:function(){}});
dojo.declare("classes.ui.DesktopUI",classes.ui.UISystem,{containerId:null,toolbar:null,calenderDivTooltip:null,calendarSignSpanTooltip:null,fontSize:null,activeTabId:"Bonfire",keyStates:{shiftKey:!1,ctrlKey:!1,altKey:!1},isDisplayOver:!1,isChatActive:!1,isChatVisited:!1,isCenter:!1,defaultSchemes:"default dark grassy sleek black wood bluish grayish greenish tombstone spooky".split(" "),allSchemes:["default"].concat((new classes.KGConfig).statics.schemes),dirtyComponents:[],constructor:function(a){this.containerId=
a;dojo.connect($("html")[0],"onclick",this,function(){this.game.stats.getStat("totalClicks").val+=1});dojo.connect($("html")[0],"onkeyup",this,function(b){var d=[{name:"Bonfire",key:"B",shift:!0,alt:!1,control:!1},{name:"Village",key:"V",shift:!0,alt:!1,control:!1},{name:"Science",key:"S",shift:!0,alt:!1,control:!1},{name:"Workshop",key:"W",shift:!0,alt:!1,control:!1},{name:"Trade",key:"T",shift:!0,alt:!1,control:!1},{name:"Religion",key:"R",shift:!0,alt:!1,control:!1},{name:"Space",key:"P",shift:!0,
alt:!1,control:!1},{name:"Time",key:"I",shift:!0,alt:!1,control:!1},{name:"Achievements",key:"M",shift:!0,alt:!1,control:!1},{name:"Stats",key:"A",shift:!0,alt:!1,control:!1},{name:"Challenges",key:"C",shift:!0,alt:!1,control:!1},{name:"Close Options",key:"Escape",shift:!1,alt:!1,control:!1,action:function(){$("div.dialog:visible").last().hide()}}],c=null;for(e in d){var f=d[e];if(f.key===b.key&&f.shift==b.shiftKey&&f.alt==b.altKey&&f.control==b.ctrlKey){c=f;break}}var e=b.target.type;e="TEXTAREA"===
b.target.tagName||"INPUT"===b.target.tagName&&("text"===e||"number"===e||"password"===e||"email"===e);d=48<=b.keyCode&&57>=b.keyCode||96<=b.keyCode&&105>=b.keyCode;if(c&&c.action)c.action();else if(!e&&d)c=9,97<=b.keyCode?c=b.keyCode-97:49<=b.keyCode&&57>=b.keyCode&&(c=b.keyCode-49),this.game.tabs[c].visible&&(this.game.ui.activeTabId=this.game.tabs[c].tabId,this.game.ui.render());else if(!e&&(37==b.keyCode||39==b.keyCode)){c=[];for(e=d=0;e<this.game.tabs.length;e++)f=this.game.tabs[e],f.visible&&
(f.tabId==this.game.ui.activeTabId&&(d=c.length),c.push(f));if(b=c[d+(37==b.keyCode?-1:1)])this.game.ui.activeTabId=b.tabId,this.game.ui.render()}else if(!e&&c&&c.name!=this.game.ui.activeTabId)for(e=0;e<this.game.tabs.length;e++)if(this.game.tabs[e].tabId===c.name&&this.game.tabs[e].visible){this.game.ui.activeTabId=c.name;this.game.ui.render();break}})},setGame:function(a){this.game=a},render:function(){var a=this.game,b=dojo.byId("midColumn"),d=b.scrollTop,c=dojo.byId(this.containerId),f;for(f in this.dirtyComponents)this.dirtyComponents[f].destroy();
this.dirtyComponents=[];dojo.empty(c);var e=dojo.create("div",{className:"tabsContainer"},c);a.calendar.render();var q=[];for(f=0;f<a.tabs.length;f++){var g=a.tabs[f];g.domNode=null;g.visible&&q.push(g)}for(f=0;f<q.length;f++){g=q[f];g.updateTab();var r=dojo.create("a",{href:"#",innerHTML:g.tabName,className:"tab "+g.tabId,style:{whiteSpace:"nowrap"}},e);g.domNode=r;this.activeTabId==g.tabId&&dojo.addClass(r,"activeTab");dojo.connect(r,"onclick",this,dojo.partial(function(k){this.activeTabId=k.tabId;
this.render();this.game.telemetry.logRouteChange(k.tabId)},g));f<q.length-1&&dojo.create("span",{innerHTML:" | "},e)}for(f=0;f<a.tabs.length;f++)if(g=a.tabs[f],this.activeTabId==g.tabId){c=dojo.create("div",{className:"tabInner "+g.tabId},c);g.render(c);break}this.calenderDivTooltip||(g=dojo.byId("calendarDiv"),this.calenderDivTooltip=UIUtils.attachTooltip(a,g,0,200,dojo.hitch(a.calendar,function(){var k="";1E5<this.year&&(k=$I("calendar.year.tooltip")+" "+this.year.toLocaleString());if(a.science.get("paradoxalKnowledge").researched){1E5<
this.year&&(k+="<br>");var l=Math.trunc(this.trueYear());1E5<l&&(l=l.toLocaleString());k+=$I("calendar.trueYear")+" "+l}return k})));this.calendarSignSpanTooltip||(g=dojo.byId("calendarSign"),this.calendarSignSpanTooltip=UIUtils.attachTooltip(a,g,0,60,dojo.hitch(a.calendar,function(){var k=this.cycles[this.cycle];if(!k)return"";var l=dojo.create("div",{className:"button_tooltip"},null),m=dojo.create("div",{innerHTML:k.title+" ("+$I("calendar.year")+" "+this.cycleYear+")",style:{textAlign:"center",
clear:"both"}},l);if(a.prestige.getPerk("numerology").researched){dojo.style(m,"borderBottom","1px solid gray");dojo.style(m,"paddingBottom","4px");dojo.create("div",{innerHTML:$I("cycle.effects.title")+":",style:{textAlign:"center",paddingTop:"4px"}},l);m=k.effects;for(var n in m){var p=dojo.create("div",null,l),h=a.getEffectMeta(n);h=h.title+":";dojo.create("span",{innerHTML:h,style:{float:"left",fontSize:"16px"}},p);h=1<m[n]?"+":"";h+=(100*(m[n]-1)).toFixed(0)+"%";dojo.create("span",{innerHTML:h,
style:{float:"right",fontSize:"16px",paddingLeft:"6px"}},p);dojo.create("span",{innerHTML:"&nbsp;",style:{clear:"both"}},p)}}if(a.prestige.getPerk("numeromancy").researched&&this.festivalDays)for(n in dojo.create("div",{innerHTML:$I("cycle.effects.festival.title"),style:{textAlign:"center"}},l),m=k.festivalEffects,m)p=dojo.create("div",null,l),h=a.getEffectMeta(n),h=h.title+":",dojo.create("span",{innerHTML:h,style:{float:"left",fontSize:"16px"}},p),h=1<m[n]?"+":"",h+=(100*(m[n]-1)).toFixed(0)+"%",
dojo.create("span",{innerHTML:h,style:{float:"right",fontSize:"16px",paddingLeft:"6px"}},p),dojo.create("span",{innerHTML:"&nbsp;",style:{clear:"both"}},p);return l.outerHTML})));b.scrollTop=d;this.update();b=new Date;1==b.getDate()&&3==b.getMonth()?$(".console-intro").css("font-size","300%").addClass("blaze").text($I("console.intro.zebra")):$(".console-intro").text($I("console.intro"));React.render($r(WLeftPanel,{game:this.game}),document.getElementById("leftColumnViewport"));React.render($r(WMidPanel,
{game:this.game}),document.getElementById("midColumnViewport"));this.game.getFeatureFlag("QUEUE")&&React.render($r(WQueue,{game:this.game}),document.getElementById("queueViewport"));React.render($r(WToolbar,{game:this.game}),document.getElementById("headerToolbar"));b=d=c=null},update:function(){this.updateTabs();this.updateFastHunt();this.updateFastPraise();this.updateCalendar();this.updateUndoButton();this.updateAdvisors();0==this.game.ticks%5&&this.game.tooltipUpdateFunc&&this.game.tooltipUpdateFunc();
this.game._publish("ui/update",this.game)},updateTabs:function(){for(var a=this.game.tabs,b=0;b<a.length;b++){var d=a[b];d.tabId==this.activeTabId&&d.update()}if(this.game.village.leader)switch(dojo.query("a.tab.traitLeaderBonus").removeClass("traitLeaderBonus engineer metallurgist chemist merchant manager scientist wise"),this.game.village.leader.trait.name){case "engineer":dojo.query("a.tab.Workshop").addClass("traitLeaderBonus engineer");break;case "metallurgist":dojo.query("a.tab.Workshop").addClass("traitLeaderBonus metallurgist");
break;case "chemist":dojo.query("a.tab.Workshop").addClass("traitLeaderBonus chemist");break;case "merchant":dojo.query("a.tab.Trade").addClass("traitLeaderBonus merchant");break;case "manager":dojo.query("a.tab.Village").addClass("traitLeaderBonus manager");break;case "scientist":dojo.query("a.tab.Science").addClass("traitLeaderBonus scientist");break;case "wise":dojo.query("a.tab.Religion").addClass("traitLeaderBonus wise")}},updateFastHunt:function(){this.fastHuntContainer||(this.fastHuntContainer=
dojo.byId("fastHuntContainer"))},updateFastPraise:function(){this.fastPraiseContainer||(this.fastPraiseContainer=dojo.byId("fastPraiseContainer"));this.fastPraiseContainer&&(0<this.game.religion.faith?"hidden"==this.fastPraiseContainer.style.visibility&&(this.fastPraiseContainer.style.visibility="visible"):"visible"==this.fastPraiseContainer.style.visibility&&(this.fastPraiseContainer.style.visibility="hidden"))},updateCalendar:function(){var a=this.game.calendar,b=a.getCurSeasonTitle(),d=this.game.science.get("calendar").researched,
c=dojo.byId("calendarDiv");if(d){d="";a.weather&&(d=" ("+$I("calendar.weather."+a.weather)+")");var f=a.year;1E5<f&&(f=this.game.getDisplayValueExt(f,!1,!1,0));c.innerHTML=$I("calendar.year.full",[f.toLocaleString(),b+d,Math.floor(a.day)]);document.title=$I("navbar.title")+" - "+$I("calendar.year.full",[a.year,b,Math.floor(a.day)]);this.game.ironWill&&a.observeBtn&&(document.title="[EVENT!]"+document.title);b=dojo.byId("calendarSign");(c=a.cycles[a.cycle])&&this.game.science.get("astronomy").researched&&
(b.style.color=a.cycleYearColor(),b.innerHTML=c.glyph+" ")}else c.textContent=b},updateUndoButton:function(){var a=null!==this.game.undoChange;$("#undoBtn").toggle(a);a&&$("#undoBtn").text($I("ui.undo",[Math.floor(this.game.undoChange.ttl/this.game.ticksPerSecond)]))},updateAdvisors:function(){},updateLanguage:function(){var a=$("#languageSelector");$("#languageApplyLink").toggle(a.val()!=i18nLang.getLanguage())},applyLanguage:function(){var a=$("#languageSelector");i18nLang.updateLanguage(a.val());
this.game.updateOptionsUI();window.location.reload()},updateNotation:function(){var a=$("#notationSelector");this.game.opts.notation=a.val()},updateOptions:function(){var a=this.game;0>a.unlockedSchemes.indexOf(a.colorScheme)&&(a.colorScheme="default");$("body").removeClass();"default"!=a.colorScheme&&($("body").addClass("scheme_"+a.colorScheme),a.opts.hideBGImage||$("body").addClass("with_background_image"));a.opts.tooltipsInRightColumn?$("#tooltip").detach().appendTo("#rightColumn").addClass("tooltip-in-right-column"):
$("#tooltip").detach().appendTo("#game").removeClass("tooltip-in-right-column");$("#workersToggle")[0].checked=a.useWorkers;$("#forceHighPrecision")[0].checked=a.opts.forceHighPrecision;$("#usePerSecondValues")[0].checked=a.opts.usePerSecondValues;$("#usePercentageResourceValues")[0].checked=a.opts.usePercentageResourceValues;$("#showNonApplicableButtons")[0].checked=a.opts.showNonApplicableButtons;$("#usePercentageConsumptionValues")[0].checked=a.opts.usePercentageConsumptionValues;$("#highlightUnavailable")[0].checked=
a.opts.highlightUnavailable;$("#hideSell")[0].checked=a.opts.hideSell;$("#hideDowngrade")[0].checked=a.opts.hideDowngrade;$("#hideBGImage")[0].checked=a.opts.hideBGImage;$("#tooltipsInRightColumn")[0].checked=a.opts.tooltipsInRightColumn;$("#enableRedshift")[0].checked=a.opts.enableRedshift;$("#batchSize")[0].value=a.opts.batchSize;$("#forceLZ")[0].checked=a.opts.forceLZ;$("#compressSaveFile")[0].checked=a.opts.compressSaveFile;$("#disableTelemetry")[0].checked=a.opts.disableTelemetry;$("#noConfirm")[0].checked=
a.opts.noConfirm;$("#IWSmelter")[0].checked=a.opts.IWSmelter;$("#autoSaveReset")[0].checked=a.opts.autoSaveReset;var b=i18nLang.getLanguage(),d=i18nLang.getAvailableLocales(),c=i18nLang.getAvailableLocaleLabels(),f=$("#languageSelector");f.empty();for(var e=0;e<d.length;e++)$("<option />").attr("value",d[e]).text(c[d[e]]).appendTo(f);f.val(b);b=a.opts.notation;d=$("#notationSelector");d.empty();c=(new classes.KGConfig).statics.notations;for(e in c)$("<option />").attr("value",c[e]).text($I("opts.notation."+
c[e])).appendTo(d);d.val(b);b=$("#schemeToggle");b.empty();for(e=0;e<this.allSchemes.length;++e)d=this.allSchemes[e],c=$("<option />").attr("value",d).text($I("opts.theme."+d)),0>a.unlockedSchemes.indexOf(d)&&(0<=this.defaultSchemes.indexOf(d)?a.unlockedSchemes.push(d):c.html("&nbsp;&nbsp;"+$I("opts.theme."+d)).attr("disabled","disabled")),c.appendTo(b);b.val(a.colorScheme)},unlockScheme:function(a){0>this.game.unlockedSchemes.indexOf(a)&&($("#schemeToggle > option[value="+a+"]").removeAttr("disabled"),
this.game.msg($I("opts.theme.unlocked")+$I("opts.theme."+a),"important"),this.game.unlockedSchemes.push(a))},relockSchemes:function(){this.game.unlockedSchemes=this.defaultSchemes;this.updateOptions()},displayAutosave:function(){dojo.style(dojo.byId("autosaveTooltip"),"opacity","1");dojo.animateProperty({node:"autosaveTooltip",properties:{opacity:0},duration:1200}).play()},getFontSize:function(){if(null==this.fontSize){var a=getComputedStyle(dojo.byId("leftColumn")).fontSize;this.fontSize=parseInt(a,
10)||16}return this.fontSize},zoomUp:function(){this.fontSize=this.getFontSize()+1;this.updateFontSize()},zoomDown:function(){this.fontSize=this.getFontSize()-1;1>this.fontSize&&(this.fontSize=1);this.updateFontSize()},updateFontSize:function(){$("#leftColumn").css("font-size",this.fontSize+"px")},hideChat:function(){$("#rightTabLog").show();$("#IRCChatInner").css("visibility","hidden");$("#logLink").toggleClass("active",!0);$("#chatLink").toggleClass("active",!1);$("#queueLink").toggleClass("active",
!1);$("#rightTabChat").hide();$("#rightTabQueue").hide()},loadChat:function(){$("#rightTabChat").show();$("#rightTabLog").hide();$("#rightTabQueue").hide();$("#logLink").toggleClass("active",!1);$("#chatLink").toggleClass("active",!0);$("#queueLink").toggleClass("active",!1);$("#IRCChatInner").css("visibility","visible");if(!this.isChatActive){var a=$(window.top).height()||850;$("#IRCChatInner iframe").css("height",a-180);this.isChatActive=!0}},loadQueue:function(){$("#rightTabChat").hide();$("#rightTabLog").hide();
$("#rightTabQueue").show();$("#IRCChatInner").css("visibility","hidden");$("#logLink").toggleClass("active",!1);$("#chatLink").toggleClass("active",!1);$("#queueLink").toggleClass("active",!0);$("#rightTabChat").hide()},resetConsole:function(){this.game.console.resetState()},renderFilters:function(){var a=this.game.console,b=dojo.byId("logFilters");dojo.empty(b);var d=!1,c;for(c in a.filters)a.filters[c].unlocked&&(this._createFilter(a.filters[c],c,b),d=!0);$("#logFiltersBlock").toggle(d)},onLoad:function(){var a=
this;$(document).on("keyup keydown keypress",function(b){a.keyStates={shiftKey:b.shiftKey,ctrlKey:b.ctrlKey,altKey:b.altKey}});this.updateIndexHTMLLanguage()},updateIndexHTMLLanguage:function(){$("#save-link").text($I("menu.save"));$("#options-link").text($I("menu.options"));$("#reset-link").text($I("menu.reset"));$("#wipe-link").text($I("menu.wipe"));$("#getTheApp-link").text($I("menu.getTheApp"));$("#autosaveTooltip").text($I("ui.autosave.tooltip"));$("#saveTooltip").text($I("ui.save.tooltip"));
$("#logLink").text($I("ui.log.link"));$("#chatLink").text($I("ui.chat.link"));this.game.getFeatureFlag("QUEUE")&&$("#queueLink").text($I("ui.queue.link"));$("#clearLogHref").text($I("ui.clear.log"));$("#logFiltersBlockText").html($I("ui.log.filters.block"));$("#pauseBtn").text($I("ui.pause"));$("#pauseBtn").attr("title",$I("ui.pause.title"));$("#undoBtn").attr("title",$I("ui.undo.title"));$(".close").text($I("ui.close"));$("#optionLanguage").text($I("ui.option.language"));$("#addTranslationLink").text($I("ui.option.language.add"));
$("#languageApplyLink").text($I("ui.option.language.apply"));$("#optionScheme").text($I("ui.option.scheme"));$("#schemeRelock").text($I("ui.option.scheme.relock"));$("#schemeTip").text($I("ui.option.scheme.tip"));$("#optionWorkers").html($I("ui.option.workers"));$("#optionForceHighPrecision").text($I("ui.option.force.high.precision"));$("#optionUsePerSecondValues").html($I("ui.option.use.per.second.values"));$("#optionUsePercentageResourceValues").text($I("ui.option.use.percentage.resource.values"));
$("#optionShowNonApplicableButtons").text($I("ui.option.show.non.applicable.buttons"));$("#optionUsePercentageConsumptionValues").text($I("ui.option.use.percentage.consumption.values"));$("#optionHighlightUnavailable").text($I("ui.option.highlight.unavailable"));$("#optionHideSell").text($I("ui.option.hide.sell"));$("#optionHideDowngrade").text($I("ui.option.hide.downgrade"));$("#optionHideBGImage").html($I("ui.option.hide.bgimage"));$("#optionTooltipsInRightColumn").text($I("ui.option.tooltips.right"));
$("#optionMore").text($I("ui.option.more"));$("#optionNoConfirm").text($I("ui.option.no.confirm"));$("#optionIWSmelter").text($I("ui.option.iw.smelter"));$("#optionDisableTelemetry").text($I("ui.option.disable.telemetry"));$("#optionEnableRedshift").text($I("ui.option.enable.redshift"));$("#optionEnableRedshiftGflops").text($I("ui.option.enable.redshiftGflops"));$("#optionBatchSize").text($I("ui.option.batch.size"));$("#optionForceLZ").html($I("ui.option.force.lz"));$("#optionCompressSaveFile").html($I("ui.option.compress.savefile"));
$("#exportButton").attr("value",$I("ui.option.export.button"));$("#importButton").attr("value",$I("ui.option.import.button"));$("#exportTo").text($I("ui.option.export"));$("#exportToDropbox").attr("value",$I("ui.option.export.dropbox"));$("#exportToSimpleFile").attr("value",$I("ui.option.export.simple.file"));$("#exportToFullFile").attr("value",$I("ui.option.export.full.file"));$("#exportToText").text($I("ui.option.export.text"));$("#closeButton").attr("value",$I("ui.option.close.button"));$("#importWarning").text($I("ui.option.import.warning"));
$("#importFrom").text($I("ui.option.import.from"));$("#importFromDropbox").attr("value",$I("ui.option.import.from.dropbox"));$("#importFromText").text($I("ui.option.import.from.text"));$("#doImportButton").attr("value",$I("ui.option.do.import.button"));$("#cancelButton").attr("value",$I("ui.option.cancel.button"));$("#appText").html($I("ui.option.app.text"));$("#appAndroid").text($I("ui.option.app.android"));$("#appIOS").text($I("ui.option.app.ios"));$("#optionNotation").text($I("ui.option.notation"));
$("#optionDisablePollution").text($I("ui.option.pollution"))},_createFilter:function(a,b,d){b="filter-"+b;var c=dojo.create("input",{id:b,type:"checkbox",checked:a.enabled},d);dojo.connect(c,"onclick",this,function(){a.enabled=c.checked});dojo.create("label",{"for":b,innerHTML:a.title},d);dojo.create("br",null,d)},logMessagesToFade:15,renderConsoleLog:function(){var a=this.game.console,b=a.messages,d=dojo.byId("gameLog");if(b.length){b=b[b.length-1];if(!b.span){var c=dojo.create("span",{className:"msg"},
d);b.type&&dojo.addClass(c,"type_"+b.type);b.noBullet&&dojo.addClass(c,"noBullet");b.span=c}"date"===b.type?dojo.place(b.span,d,"first"):dojo.place(b.span,d,1);dojo.attr(b.span,{innerHTML:b.text});b=dojo.byId("gameLog").childNodes.length;b>a.maxMessages&&dojo.destroy(dojo.byId("gameLog").childNodes[b-1]);d=dojo.query("span",d);b=this.logMessagesToFade+1;a=a.maxMessages-b;b=1/b;for(c=a+1;c<d.length;c++)dojo.style(d[c],"opacity",1-(c-a)*b)}},notifyLogEvent:function(a){},saveExport:function(a,b){$("#exportDiv").show();
$("#exportData").val(a);$("#exportData").select()},confirm:function(a,b,d,c){window.confirm(b)?d.apply(window):void 0!=c&&c.apply(window)},showDialog:function(a){var b=$("#"+a);b.show();$(".close",b).click(function(){$(".close",b).unbind();b.hide()})},displayAppDialog:function(){this.showDialog("appDiv")},load:function(){for(var a=this.game.tabs,b=0;b<a.length;b++){var d=a[b];if(this.activeTabId==d.tabId){d.visible||(this.activeTabId=a[0].tabId);break}}this.game.telemetry.logRouteChange(this.activeTabId);
a=LCstorage["com.nuclearunicorn.kittengame.ui"];try{a=a?JSON.parse(a):{},this.fontSize=a.fontSize||16,this.isChatVisited=a.isChatVisited||!1,this.isCenter=a.isCenter||!1}catch(c){console.error("unable to load ui data")}this.updateFontSize();this.updateCenter()},save:function(){LCstorage["com.nuclearunicorn.kittengame.ui"]=JSON.stringify({fontSize:this.fontSize,isChatVisited:this.isChatVisited,isCenter:this.isCenter,theme:this.game.colorScheme})},updateCenter:function(){this.isCenter?($("#game").addClass("centered"),
$("#toggleCenter").html("&lt;")):($("#game").removeClass("centered"),$("#toggleCenter").html("&gt;"))},toggleCenter:function(){this.isCenter=!this.isCenter;this.updateCenter()},isEffectMultiplierEnabled:function(){return this.keyStates.shiftKey},checkForUpdates:function(){var a=this;if(!(100>a.game.ticks)){var b=Date.now();$.getJSON("build.version.json?="+b).then(function(d){d.buildRevision>a.game.telemetry.buildRevision&&($("#newVersion").toggle(!0),a.game.msg("\u6709\u65b0\u7248\u672c\uff0c\u53ef\u4ee5\u70b9\u51fb\u53f3\u4e0a\u89d2\u66f4\u65b0\u6309\u94ae\u3002"))})}}});
