dojo.declare("classes.managers.VillageManager",com.nuclearunicorn.core.TabManager,{kittens:0,maxKittens:0,kittensPerTickBase:.01,catnipPerKitten:-.85,happiness:1,jobs:[{name:"woodcutter",title:$I("village.job.woodcutter"),description:$I("village.job.woodcutter.desc"),modifiers:{wood:.018},value:0,unlocked:!0,defaultUnlocked:!0,flavor:$I("village.woodcutter.flavor")},{name:"farmer",title:$I("village.job.farmer"),description:$I("village.job.farmer.desc"),modifiers:{catnip:1},value:0,unlocked:!1},{name:"scholar",
title:$I("village.job.scholar"),description:$I("village.job.scholar.desc"),modifiers:{},calculateEffects:function(a,b){var c={science:.035};b.workshop.get("astrophysicists").researched&&(c.starchart=1E-4);a.modifiers=c},value:0,unlocked:!1},{name:"hunter",title:$I("village.job.hunter"),description:$I("village.job.hunter.desc"),modifiers:{manpower:.06},value:0,unlocked:!1,flavor:$I("village.job.hunter.flavor")},{name:"miner",title:$I("village.job.miner"),description:$I("village.job.miner.desc"),modifiers:{minerals:.05},
value:0,unlocked:!1,flavor:$I("village.job.miner.flavor")},{name:"priest",title:$I("village.job.priest"),description:$I("village.job.priest.desc"),modifiers:{faith:.0015},value:0,unlocked:!1,calculateEffects:function(a,b){if(b.challenges.isActive("atheism")){a.unlocked=!1;for(var c in b.village.sim.kittens)a=b.village.sim.kittens[c],"priest"==a.job&&(b.village.unassignJob(a),console.warn("Kitten was unasigned from being a priest in atheism! "+a.name+" "+a.surname))}},evaluateLocks:function(a){return!a.challenges.isActive("atheism")}},
{name:"geologist",title:$I("village.job.geologist"),description:$I("village.job.geologist.desc"),modifiers:{},calculateEffects:function(a,b){var c=.015,d=0;b.workshop.get("miningDrill").researched&&(c+=.01,d+=5E-4);b.workshop.get("unobtainiumDrill").researched&&(c+=.015,d+=5E-4);b.workshop.get("geodesy").researched?(c+=.0075,d+=8E-4):d=0;b={coal:c};0<d&&(b.gold=d);a.modifiers=b},value:0,unlocked:!1},{name:"engineer",title:$I("village.job.engineer"),description:$I("village.job.engineer.desc"),modifiers:{},
value:0,unlocked:!1}],jobNames:null,resourceModifiers:{catnip:0},game:null,sim:null,map:null,deathTimeout:0,leader:null,senators:null,traits:null,getRankExp:function(a){return 500*Math.pow(1.75,a)},canHaveLeaderOrPromote:function(){return this.game.workshop.get("register").researched&&!this.game.challenges.isActive("anarchy")},getEffectLeader:function(a,b){var c=1;this.game.science.getPolicy("monarchy").researched&&(c=1.95);if(this.leader&&this.leader.trait.name==a){var d=1+this.game.prestige.getBurnedParagonRatio();
switch(a){case "engineer":b=.05*d*c;break;case "metallurgist":b=.1*d*c;break;case "chemist":b=.075*d*c;break;case "merchant":b=.03*d*c;break;case "manager":b=.5*d*c;break;case "scientist":for(a=0;a<b.length;a++)"science"==b[a].name&&(b[a].val-=b[a].val*this.game.getLimitedDR(.05*d*c,1));break;case "wise":for(a=0;a<b.length;a++)if("faith"==b[a].name||"gold"==b[a].name)b[a].val-=b[a].val*this.game.getLimitedDR(.09+.01*d*c,1)}}return b},updateEffectCached:function(){this.map.updateEffectCached()},constructor:function(a){this.game=
a;this.sim=new classes.village.KittenSim(a);this.map=new classes.village.Map(a);this.jobNames=[];for(a=0;a<this.jobs.length;++a)this.jobNames.push(this.jobs[a].name);this.senators=[];this.traits=[]},getJob:function(a){return this.getMeta(a,this.jobs)},getBiome:function(a){return this.getMeta(a,this.map.biomes)},getJobLimit:function(a){return"engineer"==a?this.game.bld.get("factory").val:"priest"==a&&this.game.challenges.isActive("atheism")?0:1E5},assignJob:function(a,b){var c=this.getJob(a.name);
b=Math.min(b,this.getFreeKittens(),this.getJobLimit(a.name)-c.value);0<b&&(this.sim.assignJob(a.name,b),c.value+=b,"engineer"==a.name&&this.game.workshopTab.updateTab(),"hunter"==a.name&&(this.sim.hadKittenHunters=!0))},unassignJob:function(a){var b=this.game,c=a.job;c&&(b.village.getJob(c).value--,b.village.sim.unassignCraftJobIfEngineer(c,a),a.job=null)},calculateSimMaxKittens:function(){var a=this.game.getEffect("maxKittensRatio");return a?Math.round(this.maxKittens*(1+this.game.getLimitedDR(a,
1))):this.maxKittens},update:function(){var a=this.kittensPerTickBase*(1+this.game.getEffect("kittenGrowthRatio"));0<this.game.calendar.festivalDays&&(a*=2+this.game.getEffect("festivalArrivalRatio"));var b=this.game.bld.pollutionEffects.pollutionArrivalSlowdown+this.game.getEffect("arrivalSlowdown");1<b&&(a/=b);this.sim.maxKittens=this.calculateSimMaxKittens();b=this.game.getResourcePerTick("catnip",!0);b=this.game.resPool.get("catnip").value+b;0<this.sim.getKittens()?0>b||this.game.challenges.isActive("winterIsComing")&&
this.sim.getKittens()>this.sim.maxKittens&&"cold"==this.game.calendar.weather?(a=Math.abs(Math.round(b)),1<a&&(a=1),0<a&&0>=this.deathTimeout?(a=this.sim.killKittens(a),0>b?this.game.msg(a+(1===a?" "+$I("village.msg.kitten")+" ":" "+$I("village.msg.kittens")+" ")+$I("village.msg.starved")):this.game.msg(a+(1===a?" "+$I("village.msg.kitten")+" ":" "+$I("village.msg.kittens")+" ")+$I("village.msg.froze")),this.game.deadKittens+=a,this.deathTimeout=5*this.game.ticksPerSecond):this.deathTimeout--,this.sim.update(0)):
this.sim.update(a):this.sim.update(a);for(a=0;a<this.jobs.length;a++){b=this.jobs[a];var c=b.name,d=this.getJobLimit(c);b.value>d&&this.sim.removeJob(c,b.value-d)}0>this.getFreeKittens()&&this.clearJobs(!0);this.updateHappines();this.map.update()},fastforward:function(a){a*=this.game.calendar.ticksPerDay;var b=this.kittensPerTickBase*(1+this.game.getEffect("kittenGrowthRatio"));0<this.game.calendar.festivalDays&&(b*=2+this.game.getEffect("festivalArrivalRatio"));this.sim.maxKittens=this.calculateSimMaxKittens();
this.sim.update(b,a)},getFreeKittens:function(){for(var a=0,b=this.jobs.length-1;0<=b;b--)a+=this.jobs[b].value;return(this.game.challenges.isActive("anarchy")?Math.round(this.getKittens()*(.5-this.game.getLimitedDR(this.game.getEffect("kittenLaziness"),.25))):this.getKittens())-a},hasFreeKittens:function(a){a=a||1;return 0<=this.getFreeKittens()-a},getWorkerKittens:function(a){for(var b=this.jobs.length-1;0<=b;b--)if(this.jobs[b].name==a)return this.jobs[b].value;return 0},getFreeEngineers:function(){for(var a=
0,b=this.game.workshop.crafts.length-1;0<=b;b--)a+=this.game.workshop.crafts[b].value;return this.getWorkerKittens("engineer")-a},clearJobs:function(a){for(var b=this.jobs.length-1;0<=b;b--){var c=this.jobs[b];if(a||"engineer"!=c.name)c.value=0}this.sim.clearJobs(a);a&&this.game.workshop.clearEngineers()},getKittens:function(){return this.sim.getKittens()},getResProduction:function(){this.resourceProduction||this.updateResourceProduction();var a=dojo.clone(this.resourceProduction),b=this.game.resPool.get("zebras");
0<b.value&&(a.manpower=a.manpower?a.manpower:0,a.manpower+=.15);if(1<b.value){var c=Math.floor(this.game.getEffect("zebraPreparations"));a.manpower+=this.game.getLimitedDR(.05*(b.value-1),2+.05*c)}return a},updateResourceProduction:function(){var a={},b=this.game.science.getPolicy("theocracy"),c=this.happiness+(this.happiness-1)*this.game.getEffect("happinessKittenProductionRatio"),d;for(d in this.sim.kittens){var e=this.sim.kittens[d];if(e.isLeader&&b.researched&&e.job!=b.requiredLeaderJob){e.isLeader=
!1;this.game.village.leader=null;var f=this.game.village.getJob(b.requiredLeaderJob).title;this.game.msg($I("msg.policy.wrongLeaderJobDemoted",[b.label,f]),"important")}if(e.job){var g=this.getJob(e.job);if(g){f=this.game.village.getValueModifierPerSkill(e.skills[e.job]||0);for(var k in g.modifiers){var h=g.modifiers[k]+g.modifiers[k]*f;0<h&&(e.isLeader&&(h*=this.getLeaderBonus(e.rank)),!e.isLeader&&this.game.village.leader&&(h*=1+(this.getLeaderBonus(this.game.village.leader.rank)-1)*this.game.getEffect("boostFromLeader")),
h*=c);a[k]=a[k]?a[k]+h:h}"engineer"==g.name&&"undefined"!=typeof e.engineerSpeciality&&null!=e.engineerSpeciality&&(k="ES"+e.engineerSpeciality,h=1+(this.game.getEffect(e.engineerSpeciality+"AutomationBonus")||0),g=this.game.workshop.getCraft(e.engineerSpeciality).tier-e.rank,0<g&&(h-=h*g*.15),h+=h*f,0<h&&(e.isLeader&&(h*=this.getLeaderBonus(e.rank)),!e.isLeader&&this.game.village.leader&&(h*=1+(this.getLeaderBonus(this.game.village.leader.rank)-1)*this.game.getEffect("boostFromLeader")),h*=c),a[k]=
a[k]?a[k]+h:h)}}}this.resourceProduction=a},updateTraits:function(){for(var a=[],b=0;b<this.sim.kittens.length;b++){var c=this.game.village.sim.kittens[b].trait;0>a.indexOf(c)&&a.unshift(c)}this.traits=a},getLeaderBonus:function(a){a=0==a?1:(a+1)/1.4;this.game.science.getPolicy("authocracy").researched&&(a*=2);return a},getResConsumption:function(){var a=this.getKittens(),b=(1+this.game.getEffect("luxuryDemandRatio"))*(1+(this.game.calendar.festivalDays?this.game.getEffect("festivalLuxuryConsumptionRatio"):
0));return{catnip:this.catnipPerKitten*a,furs:-.01*a*b,ivory:-.007*a*b,spice:-.001*a*b}},resetState:function(){this.maxKittens=0;this.sim.maxKittens=0;this.leader=null;this.senators=[];this.sim.kittens=[];for(var a=0;a<this.jobs.length;a++){var b=this.jobs[a];b.value=0;b.unlocked=b.defaultUnlocked||!1}},save:function(a){var b=[],c;for(c in this.sim.kittens){var d=this.sim.kittens[c].save(this.game.opts.compressSaveFile,this.jobNames);b.push(d)}a.village={kittens:b,maxKittens:this.maxKittens,jobs:this.filterMetadata(this.jobs,
["name","unlocked","value"]),biomes:this.filterMetadata(this.map.biomes,["name","unlocked","level","cp"]),currentBiome:this.map.currentBiome,hadKittenHunters:this.sim.hadKittenHunters,map:this.map.save()}},load:function(a){if(a.village){var b=a.village.kittens;b.length||(b=[]);this.sim.kittens=[];this.game.village.traits=[];for(var c=b.length-1;0<=c;c--){var d=b[c],e=new com.nuclearunicorn.game.village.Kitten;e.load(d,this.jobNames);0>this.game.village.traits.indexOf(e.trait)&&this.game.village.traits.unshift(e.trait);
e.isLeader&&(this.game.village.leader=e);this.sim.kittens.unshift(e)}this.maxKittens=a.village.maxKittens;this.loadMetadata(this.jobs,a.village.jobs);a.village.biomes&&(this.loadMetadata(this.map.biomes,a.village.biomes),this.map.currentBiome=a.village.currentBiome);this.sim.hadKittenHunters=void 0===a.village.hadKittenHunters?!0:a.village.hadKittenHunters;a.village.map&&this.map.load(a.village.map)}this.updateResourceProduction()},getUnhappiness:function(){return this.game.science.getPolicy("fascism").researched?
0:2*(this.getKittens()-5)*(1+this.game.getEffect("unhappinessRatio"))},getEnvironmentEffect:function(){var a=this.game;return a.getEffect("environmentHappinessBonus")+a.getEffect("environmentUnhappiness")+a.bld.pollutionEffects.pollutionHappines},updateHappines:function(){var a=100,b=this.getUnhappiness();5<this.getKittens()&&(a-=b);b=this.getEnvironmentEffect();var c=this.game.getEffect("happiness"),d=this.game.getEffect("challengeHappiness");a+=c+b+d;b=this.game.resPool.resources;c=10+this.game.getEffect("luxuryHappinessBonus");
for(d=b.length-1;0<=d;d--)"common"!=b[d].type&&0<b[d].value&&(a+=c,"elderBox"==b[d].name&&this.game.resPool.get("wrappingPaper").value&&(a-=c),"uncommon"==b[d].type&&(a+=this.game.getEffect("consumableLuxuryHappiness")));this.game.calendar.festivalDays&&(a+=30*(1+this.game.getEffect("festivalRatio")));b=this.game.resPool.get("karma");a+=b.value;b=this.getKittens()-this.maxKittens;0<b&&(a-=2*b);25>a&&(a=25);this.happiness=a/100},sendHunters:function(){this.gainHuntRes(1)},huntAll:function(){var a=
Math.floor(this.game.resPool.get("manpower").value/100);a=Infinity==a?Number.MAX_VALUE/100:a;1<=a&&(this.game.resPool.addResEvent("manpower",100*-a),this.gainHuntRes(a));1E3<=a&&!this.game.challenges.getChallenge("pacifism").unlocked&&(this.game.challenges.getChallenge("pacifism").unlocked=!0)},gainHuntRes:function(a){var b=this.game.resPool.addResEvent("unicorns",this.game.math.binominalRandomInteger(a,.05));0<b&&(b=1==b?$I("village.new.one.unicorn"):$I("village.new.many.unicorns",[this.game.getDisplayValueExt(b)]),
this.game.msg(b,"important","hunt"));10<=this.game.resPool.get("zebras").value&&0<this.game.resPool.addResEvent("bloodstone",this.game.math.binominalRandomInteger(a,0==this.game.resPool.get("bloodstone").value?.05:5E-4))&&1==this.game.resPool.get("bloodstone").value&&this.game.msg($I("village.new.bloodstone"),"important","ironWill");b=this.game.getEffect("hunterRatio")+this.game.village.getEffectLeader("manager",0);if(this.game.ironWill&&this.game.workshop.get("goldOre").researched){var c=this.game.math.binominalRandomInteger(a,
.25);c=this.game.resPool.addResEvent("gold",5*this.game.math.irwinHallRandom(c)+5*b*this.game.math.irwinHallRandom(c));0<c&&this.game.msg($I("village.msg.hunt.gold",[this.game.getDisplayValueExt(c)]),null,"hunt",!0)}c=this.game.math.binominalRandomInteger(a,.45+.02*b);c=this.game.resPool.addResEvent("ivory",50*this.game.math.irwinHallRandom(c)+40*b*this.game.math.irwinHallRandom(c));0<c&&this.game.msg($I("village.msg.hunt.ivory",[this.game.getDisplayValueExt(c)]),null,"hunt",!0);b=this.game.resPool.addResEvent("furs",
80*this.game.math.irwinHallRandom(a)+65*b*this.game.math.irwinHallRandom(a));0<b&&this.game.msg($I("village.msg.hunt.furs",[this.game.getDisplayValueExt(b)]),null,"hunt",!0);b=$I("village.msg.hunt.success");1<a&&(b+=$I("village.msg.hunt.from",[a]));this.game.msg(b,null,"hunt")},holdFestival:function(a){var b=0<this.game.calendar.festivalDays;this.game.prestige.getPerk("carnivals").researched?this.game.calendar.festivalDays+=this.game.calendar.daysPerSeason*this.game.calendar.seasonsPerYear*a:this.game.calendar.festivalDays=
this.game.calendar.daysPerSeason*this.game.calendar.seasonsPerYear;b?this.game.msg($I("village.festival.msg.ext")):this.game.msg($I("village.festival.msg.start"))},rand:function(a){return this.game.rand(a)},optimizeJobs:function(){for(var a={},b=this.game.village.sim.kittens.length-1;0<=b;b--){var c=this.game.village.sim.kittens[b].job;c&&"engineer"!=c&&(a[c]=void 0===a[c]?1:a[c]+1)}if(0!==Object.getOwnPropertyNames(a).length){this.game.village.clearJobs(!1);this.game.village.leader&&this.game.science.getPolicy("theocracy").researched&&
(this.game.village.leader.job="priest",--a.priest,this.game.village.getJob("priest").value+=1,0==a.priest&&delete a.priest);for(;0!==Object.getOwnPropertyNames(a).length;)for(c in a)this.assignJob(this.getJob(c),1),1==a[c]?delete a[c]:--a[c];this.game.msg($I("village.reassign.msg"));this.game.villageTab.updateTab();this.game.village.updateResourceProduction();this.game.updateResources()}},promoteKittens:function(){for(var a=[],b=0;b<this.sim.kittens.length;b++){var c=-1;null!=this.sim.kittens[b].engineerSpeciality&&
(c=this.game.workshop.getCraft(this.sim.kittens[b].engineerSpeciality).tier,this.sim.kittens[b].rank>=c&&(c=-1));a.push({kitten:this.sim.kittens[b],rank:c})}if(a.length){a.sort(function(f,g){return g.rank-f.rank});c=0;var d=!1;for(b=0;b<a.length;b++){var e=this.sim.promote(a[b].kitten,0<a[b].rank?a[b].rank:void 0);0<e?c++:0>e&&(d=!0)}0==c?this.game.msg($I(d?"village.kittens.promotion.nogold":"village.kittens.have.best.rank")):1==c?this.game.msg($I("village.leader.promoted.one.kitten")):this.game.msg($I("village.leader.promoted.many.kittens",
[c]))}},getValueModifierPerSkill:function(a){if(this.game.challenges.isActive("anarchy"))return 0;var b=0;switch(!0){case 100>a:break;case 500>a:b=.0125;break;case 1200>a:b=.025;break;case 2500>a:b=.045;break;case 5E3>a:b=.075;break;case 9E3>a:b=.125;break;default:b=.1875*(1+this.game.getLimitedDR(this.game.getEffect("masterSkillMultiplier"),4))}return b*(1+this.game.getEffect("skillMultiplier"))},getSkillExpRange:function(a){switch(!0){case 100>a:return[0,100];case 500>a:return[100,500];case 2500>
a:return[500,2500];case 5E3>a:return[2500,5E3];case 9E3>a:return[5E3,9E3];case 2E4>a:return[9E3,2E4];default:return[2E4,a]}}});
dojo.declare("com.nuclearunicorn.game.village.Kitten",null,{statics:{SAVE_PACKET_OFFSET:100},names:"Angel Charlie Mittens Oreo Lily Ellie Amber Molly Jasper Oscar Theo Maddie Cassie Timber Meeko Micha Tami Plato Bea Cedar Cleo Dali Fiona Hazel Iggi Jasmine Kali Luna Reilly Reo Rikka Ruby Tammy".split(" "),surnames:"Smoke Dust Chalk Fur Clay Paws Tails Sand Scratch Berry Shadow Ash Bark Bowl Brass Dusk Gaze Gleam Grass Moss Plaid Puff Rain Silk Silver Speck Stripes Tingle Wool Yarn".split(" "),traits:[{name:"scientist",
title:$I("village.trait.scientist")},{name:"manager",title:$I("village.trait.manager")},{name:"engineer",title:$I("village.trait.engineer")},{name:"merchant",title:$I("village.trait.merchant")},{name:"wise",title:$I("village.trait.wise")},{name:"metallurgist",title:$I("village.trait.metallurgist")},{name:"chemist",title:$I("village.trait.chemist")},{name:"none",title:$I("village.trait.none")}],colors:[{color:"brown"},{color:"cinamon"},{color:"cream"},{color:"black"},{color:"fawn"},{color:"white"},
{color:"lilac"}],varieties:[{style:"dual"},{style:"tabby"},{style:"torbie"},{style:"calico"},{style:"spots"}],name:"Undefined",surname:"Undefined",job:null,trait:null,age:0,skills:null,exp:0,rank:0,rarity:0,color:0,variety:0,isLeader:!1,isSenator:!1,constructor:function(){this.name=this.names[this.rand(this.names.length)];this.surname=this.surnames[this.rand(this.surnames.length)];this.trait=this.traits[this.rand(this.traits.length)];this.age=5+this.rand(10);30>this.rand(100)&&(this.age+=this.rand(30));
10>=this.rand(100)&&(this.color=this.rand(6)+1,10>=this.rand(100)&&(this.variety=this.rand(4)+1));5>=this.rand(100)&&(this.rarity=this.rand(2)+1,10>=this.rand(100)&&(this.rarity+=1));this.exp=0;this.skills={}},rand:function(a){return Math.floor(Math.random()*a)},load:function(a,b){void 0!=a.ssn?this.loadCompressed(a,b):this.loadUncompressed(a)},loadUncompressed:function(a){this.name=a.name;this.surname=a.surname;this.age=a.age;this.skills=a.skills;this.exp=a.exp||0;this.trait=this.traits[this._getTraitIndex(a.trait.name)];
this.job=a.job;this.engineerSpeciality=a.engineerSpeciality||null;this.rank=a.rank||0;this.isLeader=a.isLeader||!1;this.isSenator=!1;this.isAdopted=a.isAdopted||!1;this.color=a.color||0;this.variety=a.variety||0;this.rarity=a.rarity||0;for(var b in this.skills)20001<this.skills[b]&&(this.skills[b]=20001)},loadCompressed:function(a,b){var c=this._splitSSN(a.ssn,7);this.name=a.name||this.names[c[0]];this.surname=a.surname||this.surnames[c[1]];this.age=c[2];this.trait=this.traits[c[3]];this.color=c[4];
this.variety=c[5];this.rarity=c[6];this.skills={};c=a.skills||0;for(var d="number"==typeof c,e=b.length-1;0<=e;--e){var f=d?c:c[e]||0;20001<f&&(f=20001);this.skills[b[e]]=f}this.exp=a.exp||0;this.job=void 0!=a.job?b[a.job]:null;this.engineerSpeciality=a.engineerSpeciality||null;this.rank=a.rank||0;this.isLeader=a.isLeader||!1;this.isSenator=!1;this.isAdopted=a.isAdopted||!1},_splitSSN:function(a,b){for(var c=[],d=0;d<b;++d){var e=a%this.statics.SAVE_PACKET_OFFSET;a-=e;a/=this.statics.SAVE_PACKET_OFFSET;
c.push(e)}return c},save:function(a,b){return a?this.saveCompressed(b):this.saveUncompressed()},saveUncompressed:function(){var a={},b;for(b in this.skills)0<this.skills[b]&&(a[b]=this.skills[b]);return{name:this.name,surname:this.surname,age:this.age,color:this.color||void 0,variety:this.variety||void 0,rarity:this.rarity||void 0,skills:a,exp:this.exp||void 0,trait:{name:this.trait.name},job:this.job||void 0,engineerSpeciality:this.engineerSpeciality||void 0,rank:this.rank||void 0,isLeader:this.isLeader||
void 0,isAdopted:this.isAdopted||void 0}},saveCompressed:function(a){for(var b=[],c=Number.MAX_VALUE,d=-c,e=0;e<a.length;++e){var f=this.skills[a[e]]||0;b[e]=f;c=Math.min(f,c);d=Math.max(f,d)}c==d&&(b=d);c=this.names.indexOf(this.name);d=this.surnames.indexOf(this.surname);a={ssn:this._mergeSSN([-1<c?c:0,-1<d?d:0,this.age,this._getTraitIndex(this.trait.name),this.color,this.variety,this.rarity]),skills:b||void 0,exp:this.exp||void 0,job:this.job?a.indexOf(this.job):void 0,engineerSpeciality:this.engineerSpeciality||
void 0,rank:this.rank||void 0,isLeader:this.isLeader||void 0,isAdopted:this.isAdopted||void 0};if(0>=c||0>=d)a.name=this.name,a.surname=this.surname;return a},_mergeSSN:function(a){for(var b=0,c=a.length-1;0<=c;--c)b*=this.statics.SAVE_PACKET_OFFSET,b+=a[c];return b},_getTraitIndex:function(a){for(var b=this.traits.length-1;0<=b;b--)if(this.traits[b].name===a)return b}});
dojo.declare("classes.village.Map",null,{game:null,villageLevel:0,exploredLevel:0,currentBiome:null,explorersLevel:0,hqLevel:0,hp:10,energy:70,defaultFaunaNames:["\u5de8\u86fe","mantis","slime mold"],biomes:[{name:"village",title:"\u6751\u5e84",desc:"\u63d0\u9ad8\u6240\u6709\u7684\u751f\u7269\u7fa4\u843d",terrainPenalty:1,faunaPenalty:0,unlocked:!0},{name:"plains",title:"\u5e73\u539f",desc:"\u6bcf\u7b49\u7ea7\u63d0\u9ad8\u732b\u8584\u8377\u4ea7\u91cf 1%",terrainPenalty:1,unlocked:!0,unlocks:{biomes:["hills"]}},
{name:"hills",title:"Hills",desc:"TBD",terrainPenalty:1.2,unlocked:!1,unlocks:{biomes:["mountain"]},evaluateLocks:function(a){return 5<=a.village.getBiome("plains").level||5<=a.village.getBiome("forest").level},lore:{5:"You can see small lizards enjoying the sun"}},{name:"forest",title:"\u68ee\u6797",desc:"\u6bcf\u7b49\u7ea7\u63d0\u9ad8\u6728\u6750\u4ea7\u91cf 1%",lore:{5:"It smells really nice",10:"The forest is rumored to be endless and covering half of the planet",15:"There is something in the forest and no one knows what it is. Not many are sure if it really exists. If it does, it is somewhere deep below, days of travel, years, centuries maybe."},
terrainPenalty:1.2,faunaPenalty:1.5,unlocked:!0,unlocks:{biomes:["boneForest"]}},{name:"boneForest",title:"Bone Forest",terrainPenalty:1.9,unlocked:!1,evaluateLocks:function(a){return 25<=a.village.getBiome("forest").level&&5<=a.village.getBiome("rainForest").level},lore:{5:"A place where trees are made of bones"}},{name:"rainForest",title:"\u96e8\u6797",description:"TBD",terrainPenalty:1.4,unlocked:!1,5:"The trees are so tall you don't see where it ends. When the rains start they can go for hundreds of years.",
10:"In the fog you can see the mountains. The mountains have eyes and sometime change places."},{name:"mountain",title:"\u9ad8\u5c71",description:"\u6bcf\u7b49\u7ea7\u63d0\u9ad8\u77ff\u7269\u4ea7\u91cf 1%",terrainPenalty:1.2,lore:{5:"Remember to grab your mandatory 50 meters of rope. The ascend will take quite some time.",10:"A small and larger structures cut from a limestone are towering there. Griffins call this place The White Citadel.",15:"Everything is so pale and white we don\u2019t know what exactly is it made of. There are some red marking and drawings everywhere",
20:"Why is this place called a citadel? You can see some system there. This place is a structure on its own, a ziggurat made of ziggurats."},evaluateLocks:function(a){return 10<=a.village.getBiome("hills").level},unlocks:{biomes:["volcano"]},unlocked:!1},{name:"volcano",title:"Volcano",description:"TBD",terrainPenalty:3.5,unlocked:!1,lore:{5:"TBD"},evaluateLocks:function(a){return 25<=a.village.getBiome("mountain").level}},{name:"desert",title:"Desert",description:"TBD",terrainPenalty:1.5,unlocked:!1,
lore:{5:"An endless white desert with occasional red rock formations"},evaluateLocks:function(a){return 15<=a.village.getBiome("plains").level}},{name:"bloodDesert",title:"Crimson Desert",description:"",terrainPenalty:1.5,lore:{5:"There are tales of horrible monsters and lost cities and endless deserts of red sand",10:"You can travel further. But you don\u2019t really want to see what\u2019s there in the desert.",15:"Once there was an ocean of blood. No one knows why, maybe a frozen shard of Redmoon felt there millenia ago."},
unlocked:!1},{name:"swamp",title:"Swamp",description:"Everything that is edible is poisonous and so are the trees and the grass and the air is also poisonous slightly",terrainPenalty:1.95,lore:{5:"Everything here tries to kill you",10:"All plants here are poisonous and so are the trees and the water and the air is also poisonous slightly",15:"All you can see are the endless swamplands with lost ziggurats and rotten watchtowers"},unlocked:!1}],constructor:function(a){this.game=a;this.resetMap()},init:function(){},
resetMap:function(){this.init()},toLevel:function(a){return 100*(1+1.1*Math.pow(a.level+1,1.18+.1*a.terrainPenalty))},update:function(){for(var a in this.biomes){var b=this.biomes[a];"village"==b.name&&(this.game.globalEffectsCached.exploreRatio=.1*(b.level-1));var c=b.faunaNames||this.defaultFaunaNames;c=c[this.game.rand(c.length)];if(!b.fauna||!b.fauna.length){var d=10*(b.faunaPenalty||1);this.game.rand(1E4)<=d&&(b.fauna=[{title:c,hp:this.game.rand(10)+5,atk:1,def:1}])}}this.currentBiome?this.explore(this.currentBiome):
(this.energy<this.getMaxEnergy()&&(this.energy+=.5),this.hp<this.getMaxHP()&&(this.hp+=.01),this.energy>this.getMaxEnergy()&&(this.energy=this.getMaxEnergy()),this.hp>this.getMaxHP()&&(this.hp=this.getMaxHP()))},getMaxEnergy:function(){return(70+5*this.hqLevel)*(1+.01*this.hqLevel)},getMaxHP:function(){return(10+.1*this.explorersLevel)*(1+.01*this.explorersLevel)},explore:function(a){a=this.game.village.getBiome(a);a.level||(a.level=0);a.cp||(a.cp=0);var b=this.game.resPool.get("manpower");this.energy-=
.1;a.fauna&&a.fauna.length&&(this.combat(),0>=this.hp&&(this.currentBiome=null,this.game.msg("All contact with the expedition have been lost","important","explore")));0>=this.energy&&(this.currentBiome=null,this.game.msg("Your explorers have returned from expedition","important","explore"));var c=this.toLevel(a);if(.1<=b.value&&(b.value-=.1,a.cp+=.1,a.cp>=c))this.onLevelUp(a)},combat:function(){var a=this.game.village.getBiome(this.currentBiome),b;for(b in a.fauna){var c=a.fauna[b];0<c.hp&&(this.hp-=
.1*c.atk,c.hp-=.2)}a.fauna=a.fauna.filter(function(d){return 0<d.hp})},onLevelUp:function(a){a.cp=0;a.level++;a.unlocks&&this.game.unlock(a.unlocks)},getExplorationPrice:function(a,b){a=this.getTile(a,b);return 1*(1+this.getExploreRatio())*Math.pow(1.01,a.level)},getExploreRatio:function(){return.1*(this.villageLevel-1)},getPriceReduction:function(){return 2E-5*Math.sqrt(this.exploredLevel-1)},updateEffectCached:function(){this.game.globalEffectsCached.mapPriceReduction=-this.getPriceReduction()},
save:function(){return{hqLevel:this.hqLevel,energy:this.energy,explorersLevel:this.explorersLevel}},load:function(a){this.hqLevel=a.hqLevel||0;this.energy=a.energy||100;this.explorersLevel=a.explorersLevel||0}});
dojo.declare("classes.ui.village.BiomeBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{fetchModel:function(a){this.biome||(this.biome=this.game.village.getBiome(a.id));var b=this.inherited(arguments);b.biome=this.biome;return b},clickHandler:function(a,b){a=a.biome;console.log("CURRENT BIOME:",a);this.game.village.map.currentBiome=a.name},getName:function(a){var b=this.game.village.map,c=a.options.name;void 0!==this.biome.level&&(c+=", lv."+this.biome.level);if(this.biome.cp){var d=
b.toLevel(this.biome);c+=" ["+(this.biome.cp/d*100).toFixed(2)+"%]";b.currentBiome==a.options.id&&(c+=" (\u5f53\u524d)")}return c},updateVisible:function(a){a.visible=this.biome.unlocked}});
dojo.declare("classes.ui.village.BiomeBtn",com.nuclearunicorn.game.ui.ButtonModern,{renderLinks:function(){},update:function(){this.inherited(arguments)},getTooltipHTML:function(){return function(a,b){a.fetchExtendedModel(b);a=dojo.create("div",{className:"tooltip-inner"},null);b.tooltipName&&dojo.create("div",{innerHTML:b.name,className:"tooltip-divider"},a);var c=b.biome,d=null;if(c.lore)for(var e in c.lore)c.level>e&&(d=c.lore[e]);b=dojo.create("div",{innerHTML:b.description,className:"desc"},
a);d&&(dojo.create("div",{innerHTML:d,className:"desc"},a),dojo.style(b,"borderBottom","1px solid gray"));if(c.fauna)for(e in c.fauna)b=c.fauna[e],d=dojo.create("div",{style:{overflow:"hidden"}},a),dojo.create("span",{innerHTML:b.title,style:{float:"left"}},d),dojo.create("span",{innerHTML:this.game.getDisplayValueExt(b.hp)+"hp",style:{float:"right"}},d);return a.outerHTML}}});
dojo.declare("classes.village.ui.map.UpgradeHQController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.simplePrices=!1;return a},getMetadata:function(a){var b=this.game.village.map;a.metaCached||(a.metaCached={label:$I("village.btn.upgradeHQ"),description:$I("village.btn.upgradeHQ.desc"),val:b.hqLevel,on:b.hqLevel});return a.metaCached},getPrices:function(a){a=dojo.clone(a.options.prices);for(var b=0;b<a.length;b++)a[b].val*=Math.pow(1.25,
this.game.village.map.hqLevel);return a},buyItem:function(a,b,c){this.inherited(arguments);this.game.ui.render()},incrementValue:function(a){this.inherited(arguments);this.game.village.map.hqLevel++},hasSellLink:function(a){return!1},updateVisible:function(a){a.visible=!0}});
dojo.declare("classes.village.ui.map.UpgradeExplorersController",com.nuclearunicorn.game.ui.BuildingStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.simplePrices=!1;return a},getMetadata:function(a){var b=this.game.village.map;a.metaCached||(a.metaCached={label:$I("village.btn.upgradeExplorers"),description:$I("village.btn.upgradeExplorers.desc"),val:b.explorersLevel,on:b.explorersLevel});return a.metaCached},getPrices:function(a){a=dojo.clone(a.options.prices);for(var b=
0;b<a.length;b++)a[b].val*=Math.pow(1.25,this.game.village.map.explorersLevel);return a},buyItem:function(a,b,c){this.inherited(arguments);this.game.ui.render()},incrementValue:function(a){this.inherited(arguments);this.game.village.map.explorersLevel++},hasSellLink:function(a){return!1},updateVisible:function(a){a.visible=!0}});
dojo.declare("classes.village.ui.MapOverviewWgt",[mixin.IChildrenAware,mixin.IGameAware],{constructor:function(a){this.setGame(a);for(var b in a.village.map.biomes){var c=a.village.map.biomes[b];this.addChild(new classes.ui.village.BiomeBtn({id:c.name,name:c.title,description:c.desc,prices:[],controller:new classes.ui.village.BiomeBtnController(a)},a))}this.upgradeExplorersBtn=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("village.btn.upgradeExplorers"),description:$I("village.btn.upgradeExplorers.desc"),
handler:dojo.hitch(this,function(){}),prices:[{name:"manpower",val:100}],controller:new classes.village.ui.map.UpgradeExplorersController(this.game)},this.game);this.upgradeHQBtn=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("village.btn.upgradeHQ"),description:$I("village.btn.upgradeHQ.desc"),handler:dojo.hitch(this,function(){}),prices:[{name:"catnip",val:1E3}],controller:new classes.village.ui.map.UpgradeHQController(this.game)},this.game)},render:function(a){var b=this.game.village.map,
c=dojo.create("div",null,a),d=dojo.create("div",{style:{paddingTop:"20px"}},c);this.upgradeExplorersBtn.render(d);this.upgradeHQBtn.render(d);dojo.create("div",{innerHTML:"\u751f\u7269\u7fa4\u843d",style:{paddingBottom:"10px"}},c);this.explorationDiv=dojo.create("div",null,c);this.teamDiv=dojo.create("div",{innerHTML:"\u63a2\u7d22\u8005: \u8865\u7ed9 []"},c);this.explorerDiv=dojo.create("div",{innerHTML:"\u63a2\u7d22\u8005: lvl 0, HP: "+b.hp.toFixed(1)+"/"+b.getMaxHP()},c);d=dojo.create("div",{style:{paddingTop:"20px"}},
c);this.inherited(arguments,[d])},update:function(){var a=this.game.village.map,b=a.currentBiome?this.game.village.getBiome(a.currentBiome):null;if(b){var c=a.toLevel(b);this.explorationDiv.innerHTML="\u5f53\u524d\u63a2\u7d22: ["+b.title+"], "+(b.cp/c*100).toFixed(0)+"% [Cancel]"}this.upgradeExplorersBtn.update();this.upgradeHQBtn.update();this.teamDiv.innerHTML="\u8865\u7ed9 ["+a.energy.toFixed(0)+" days]";this.explorerDiv.innerHTML="\u63a2\u7d22\u8005: HP: "+a.hp.toFixed(1)+"/"+a.getMaxHP().toFixed(1);
this.inherited(arguments)}});
dojo.declare("classes.village.KittenSim",null,{kittens:null,game:null,nextKittenProgress:0,maxKittens:0,hadKittenHunters:!1,constructor:function(a){this.kittens=[];this.game=a},update:function(a,b){var c=this.game;b||=1;if(this.kittens.length<this.maxKittens&&(this.nextKittenProgress+=b*a,1<=this.nextKittenProgress)){a=Math.floor(this.nextKittenProgress);this.nextKittenProgress-=a;for(var d=0;d<a;d++)this.kittens.length<this.maxKittens&&(this.addKitten(),10>=this.maxKittens&&1==b&&c.msg($I("village.msg.kitten.has.joined")));
this.kittens.length>=this.maxKittens&&(this.nextKittenProgress=0)}a=1;100<this.kittens.length?a=5:500<this.kittens.length?a=10:1E3<this.kittens.length&&(a=20);if(0==c.ticks%a||1!=b){1==b&&(b=a);a=this.kittens.length<=this.maxKittens?1/(1+this.game.getLimitedDR(this.game.getEffect("maxKittensRatio"),1)):1;a=((c.workshop.get("internet").researched?Math.max(this.getKittens()*a/1E4,.01):.01)+c.getEffect("skillXP"))*b;d=c.workshop.get("neuralNetworks").researched;for(var e=this.kittens.length-1;0<=e;e--){var f=
this.kittens[e];if(!f.exp){f.exp=0;for(var g in f.skills)f.exp+=f.skills[g]}void 0===f.rank&&(f.rank=0);f.trait||(f.trait=f.traits[f.rand(f.traits.length)]);if(f.job&&0<=c.calendar.day&&!c.challenges.isActive("anarchy")){f.skills[f.job]||(f.skills[f.job]=0);if("engineer"!=f.job||null!=f.engineerSpeciality)20001>f.skills[f.job]&&(f.skills[f.job]=Math.min(f.skills[f.job]+a,20001)),f.exp+=a;if(d)for(var k=c.village.jobs.length-1;0<=k;k--){if(c.village.jobs[k].unlocked){var h=c.village.jobs[k].name,l=
c.village.jobs[k].value;0<l&&20001!==f.skills[h]&&(f.skills[h]||(f.skills[h]=0),l*=.001*b,f.skills[h]=Math.min(f.skills[h]+l,20001))}}else for(g in f.skills)g!=f.job&&0<f.skills[g]&&(l=Math.min(.001*b,f.skills[g]),f.skills[g]-=l,f.exp-=l)}}}},addKitten:function(){var a=new com.nuclearunicorn.game.village.Kitten;this.kittens.push(a);0>this.game.village.traits.indexOf(a.trait)&&this.game.village.traits.unshift(a.trait);this.game.villageTab.updateTab();this.game.kongregate&&this.game.kongregate.stats.submit("kittens",
this.kittens.length);this.game.stats.getStat("totalKittens").val++},killKittens:function(a){a>this.kittens.length&&(a=this.kittens.length);this.game.stats.getStat("kittensDead").val+=a;a=this.kittens.splice(this.kittens.length-a,a);for(var b=this.game.village,c=a.length-1;0<=c;c--){var d=a[c];b.unassignJob(d);d===b.leader&&(b.leader=null)}this.game.villageTab.updateTab();this.game.workshopTab.updateTab();this.game.village.updateResourceProduction();this.game.village.updateTraits();this.game.updateResources();
return a.length},sortKittensByExp:function(){this.kittens.sort(function(a,b){var c=a.rank-b.rank;return 0!=c?c:a.exp-b.exp})},getKittens:function(){return this.kittens.length},rand:function(a){return Math.floor(Math.random()*a)},getSkillsSorted:function(a){var b=[],c;for(c in a)b.push({name:c,val:a[c]});b.sort(function(d,e){return e.val-d.val});return b},getSkillsSortedWithJob:function(a,b){var c=[],d;for(d in a)d!=b&&c.push({name:d,val:a[d]});c.sort(function(e,f){return f.val-e.val});c.unshift({name:b,
val:a[b]});return c},assignJob:function(a,b){for(var c=[],d=this.game.workshop.get("register").researched&&this.game.village.leader,e=this.kittens.length-1;0<=e;e--){var f=this.kittens[e];f.job||(d?c.push({id:e,val:f.skills[a]||0,leader:f.isLeader}):c.push({id:e}))}d&&c.sort(function(g,k){return k.val-g.val||k.leader-g.leader});for(e=(b||1)-1;0<=e;e--)c.length?(b=c.shift(),this.kittens[b.id].job=a):console.error("failed to assign job",a);this.game.village.updateResourceProduction()},removeJob:function(a,
b){for(var c=[],d=this.game.workshop.get("register").researched&&this.game.village.leader,e=this.kittens.length-1;0<=e;e--){var f=this.kittens[e];f.job==a&&(d?c.push({id:e,val:f.skills[a]?f.skills[a]:0,leader:f.isLeader}):c.push({id:e}))}d&&c.sort(function(g,k){return g.val-k.val||g.leader-k.leader});for(e=(b||1)-1;0<=e;e--)c.length?(b=c.shift(),f=this.kittens[b.id],this.game.village.unassignJob(f)):console.error("failed to remove job",a);this.game.village.updateResourceProduction();"engineer"==a&&
this.game.workshopTab.updateTab()},assignCraftJob:function(a){for(var b=this.game.workshop.get("register").researched&&this.game.village.leader?!0:!1,c=[],d=this.kittens.length-1;0<=d;d--){var e=this.kittens[d];"engineer"!=e.job||e.engineerSpeciality||(b?c.push({id:d,val:e.skills.engineer?e.skills.engineer:0,rank:e.rank}):c.push({id:d}))}b&&(c.sort(function(f,g){return g.val-f.val}),c.sort(function(f,g){return g.rank-f.rank}));return c.length?(this.kittens[c[0].id].engineerSpeciality=a.name,"wood"==
a.name&&this.game.achievements.unlockBadge("evergreen"),!0):!1},unassignCraftJob:function(a){for(var b=this.game.workshop.get("register").researched&&void 0!=this.game.village.leader?!0:!1,c=[],d=this.kittens.length-1;0<=d;d--){var e=this.kittens[d];"engineer"==e.job&&e.engineerSpeciality==a.name&&(b?c.push({id:d,val:e.skills.engineer?e.skills.engineer:0,rank:e.rank}):c.push({id:d}))}b&&(c.sort(function(f,g){return g.val-f.val}),c.sort(function(f,g){return g.rank-f.rank}));return c.length?(this.kittens[c[c.length-
1].id].engineerSpeciality=null,!0):!1},unassignCraftJobIfEngineer:function(a,b){"engineer"==a&&b.engineerSpeciality&&(a=this.game.workshop.getCraft(b.engineerSpeciality))&&0<a.value&&a.value--;b.engineerSpeciality=null},clearCraftJobs:function(){for(var a=this.kittens.length-1;0<=a;a--)this.kittens[a].engineerSpeciality=null},promote:function(a,b){var c=a.rank;if("undefined"==typeof b){b=a.rank+1;var d=1}else d=b-c;if(0>=d)return 0;var e=this.expToPromote(c,b,a.exp);c=this.goldToPromote(c,b,this.game.resPool.get("gold").value);
if(e[0]&&c[0])return a.rank=b,a.exp-=e[1],this.game.resPool.addResEvent("gold",-c[1]),1;if(1<d)return this.promote(a);if(e[0]&&!c[0])return-1},expToPromote:function(a,b,c){for(var d=0,e=0;e<b-a;e++)d+=this.game.village.getRankExp(a+e);return d>c?[!1,0]:[!0,d]},goldToPromote:function(a,b,c){for(var d=0,e=0;e<b-a;e++)d+=25*(a+e+1);return d>c?[!1,0]:[!0,d]},clearJobs:function(a){for(var b=this.kittens.length-1;0<=b;b--){var c=this.kittens[b];if(a||"engineer"!=c.job)c.job=null,c.engineerSpeciality=null}}});
dojo.declare("com.nuclearunicorn.game.ui.JobButtonController",com.nuclearunicorn.game.ui.ButtonModernController,{defaults:function(){var a=this.inherited(arguments);a.tooltipName=!0;return a},initModel:function(a){var b=this.inherited(arguments);b.job=this.getJob(b);return b},getJob:function(a){return this.game.village.getJob(a.options.job)},updateEnabled:function(a){this.inherited(arguments);if(!this.game.village.hasFreeKittens()||this.game.village.getJobLimit(a.options.job)<=this.game.village.getWorkerKittens(a.options.job))a.enabled=
!1},getName:function(a){return this.inherited(arguments)+" ("+a.job.value+")"},getDescription:function(a){return a.job.description},updateVisible:function(a){a.visible=a.job.unlocked},clickHandler:function(a,b){if(b.ctrlKey||b.metaKey)this.assignJobs(a,this.game.opts.batchSize||10);else if(b.shiftKey)if(this.game.opts.noConfirm)this.assignAllJobs(a);else{var c=this;this.game.ui.confirm("",$I("village.btn.assignall.confirmation.msg"),function(){c.assignAllJobs(a)},function(){})}else this.assignJobs(a,
1)},unassignJobs:function(a,b){a=a.job;a.value<b&&(b=a.value);0<b&&this.game.village.sim.removeJob(a.name,b)},unassignAllJobs:function(a){this.unassignJobs(a,a.job.value)},assignJobs:function(a,b){this.game.village.assignJob(a.job,b)},assignAllJobs:function(a){var b=this.game.village.getFreeKittens();this.assignJobs(a,b)},fetchModel:function(a){var b=this.inherited(arguments),c=this;b.unassignLinks=[{id:"unassign",title:"[&ndash;]",alt:"\u51cf",handler:function(){c.unassignJobs(b,1)}},{id:"unassign5",
title:"[-5]",handler:function(){c.unassignJobs(b,5)}},{id:"unassign25",title:"[-25]",handler:function(){c.unassignJobs(b,25)}},{id:"unassignAll",title:$I("btn.all.unassign"),handler:function(){c.unassignAllJobs(b)}}];b.assignLinks=[{id:"assign",title:"[+]",alt:"\u52a0",handler:function(){c.assignJobs(b,1)}},{id:"assign5",title:"[+5]",handler:function(){c.assignJobs(b,5)}},{id:"assign25",title:"[+25]",handler:function(){c.assignJobs(b,25)}},{id:"assignall",title:$I("btn.all.assign"),handler:function(){c.assignAllJobs(b)}}];
return b},getEffects:function(a){return a.job.modifiers},getFlavor:function(a){return a.job.flavour}});dojo.declare("com.nuclearunicorn.game.ui.JobButton",com.nuclearunicorn.game.ui.ButtonModern,{renderLinks:function(){this.unassignLinks=this.addLinkList(this.model.unassignLinks);this.assignLinks=this.addLinkList(this.model.assignLinks)}});
dojo.declare("classes.ui.village.Census",null,{game:null,records:null,container:null,filterJob:null,filterTrait:null,constructor:function(a){this.game=a;this.records=[]},render:function(a){this.records=[];this.container=a;dojo.empty(a);this.governmentDiv=null;this.game.challenges.isActive("anarchy")||this.renderGovernment(a);var b=dojo.create("div",{className:"censusFilters",style:{height:"24px"}},a),c=dojo.create("select",{style:{float:"right"}},b);dojo.create("option",{value:"",innerHTML:$I("village.trait.filter.all")},
c);for(var d=0;d<this.game.village.traits.length;d++){var e=this.game.village.traits[d];dojo.create("option",{value:e.name,innerHTML:e.title,selected:e.name===this.filterTrait},c)}dojo.connect(c,"onchange",this,function(h){this.filterTrait=h.target.value;this.render(this.container)});b=dojo.create("select",{style:{float:"right"}},b);dojo.create("option",{value:"",innerHTML:$I("village.census.filter.all")},b);for(d=0;d<this.game.village.jobs.length;d++)c=this.game.village.jobs[d],c.unlocked&&dojo.create("option",
{value:c.name,innerHTML:c.title,selected:c.name===this.filterJob},b);dojo.connect(b,"onchange",this,function(h){this.filterJob=h.target.value;this.render(this.container)});b=0;c=this.game.village.sim;c.sortKittensByExp();for(d=c.kittens.length-1;0<=d&&10>b;d--)if(e=c.kittens[d],!(this.filterJob&&e.job!==this.filterJob||this.filterTrait&&e.trait.name!==this.filterTrait)){b++;var f=dojo.create("div",{className:"census-block",innerHTML:""},a);dojo.addClass(f,e.isLeader?" simLeader":"");var g=dojo.create("div",
{style:{display:"inline-block"}},f);f=dojo.create("div",{style:{display:"inline-block",float:"right"}},f);if(!this.game.challenges.isActive("anarchy"))var k=dojo.create("a",{href:"#",innerHTML:"",className:"leaderHref",style:{float:"right"},title:"\u5206\u914d\u9886\u8896"},f);f=dojo.create("a",{href:"#",innerHTML:$I("village.btn.unassign.job"),className:"unassignHref",style:{display:e.job?"block":"none",clear:"both"}},f);dojo.connect(f,"onclick",this,dojo.partial(function(h,l,m){m.preventDefault();
h.village.unassignJob(h.village.sim.kittens[l]);h.village.updateResourceProduction();h.render()},this.game,d));this.game.challenges.isActive("anarchy")||dojo.connect(k,"onclick",this,dojo.partial(function(h,l,m){m.preventDefault();m=h.game;if(l=m.village.sim.kittens[l])h.makeLeader(l),h.renderGovernment(h.container),this.render(this.container),m.ui.updateTabs(),h.update()},this,d));this.records.push({content:g,kitten:e,unassignHref:f,leaderHref:k})}},makeLeader:function(a){var b=this.game.science.getPolicy("theocracy");
b.researched&&a.job!=b.requiredLeaderJob?(a=this.game.village.getJob(b.requiredLeaderJob).title,this.game.msg($I("msg.policy.kittenNotMadeLeader",[b.label,a]),"important")):(b=this.game,b.village.leader&&(b.village.leader.isLeader=!1),a.isLeader=!0,b.village.leader=a)},getGovernmentInfo:function(){var a="\u65e0",b=this.game.village.leader;if(b){a="none"==b.trait.name?$I("village.census.trait.none"):b.trait.title+" ("+$I("village.bonus.desc."+b.trait.name)+") ["+$I("village.census.rank")+" "+b.rank+
"]";var c=Math.floor(this.game.village.getRankExp(b.rank));a=this.getStyledName(b,!0)+", "+a+"<br /> \u7ecf\u9a8c: "+this.game.getDisplayValueExt(b.exp);c>b.exp&&(a+=" ("+Math.floor(100*b.exp/c)+"%)");0<b.rank&&(a+="<br /><br />"+$I("village.job.bonus")+": x"+this.game.village.getLeaderBonus(b.rank).toFixed(1)+" ("+(b.job?this.game.village.getJob(b.job).title:"")+")")}return{leaderInfo:a}},getSkillInfo:function(a){for(var b=a.job?this.game.village.sim.getSkillsSortedWithJob(a.skills,a.job):this.game.village.sim.getSkillsSorted(a.skills),
c="",d=0;d<Math.min(b.length,3);d++){var e=b[d].val,f="",g="";if(0>=e||"undefined"==typeof e)break;var k=this.game.village.getSkillExpRange(e),h=k[0];k=(e-h)/(k[1]-h)*100;b[d].name==a.job&&(f="style='font-weight: bold'",g=this.game.village.getValueModifierPerSkill(a.skills[a.job]),g=0<g&&a.isLeader?this.game.village.getLeaderBonus(a.rank)*(g+1)-1:g,g=0<g&&!a.isLeader&&this.game.village.leader?(this.game.village.getLeaderBonus((this.game.village.leader||0).rank)*this.game.getEffect("boostFromLeader")+
1)*(g+1)-1:g,g*=100,g=0<g?" +"+g.toFixed(0)+"%":"");c+="<span class='skill' title='"+e.toFixed(2)+"'"+f+">"+this.game.village.getJob(b[d].name).title+g+" ("+this.game.villageTab.skillToText(e)+" "+k.toFixed()+"%)</span><br>"}return c},renderGovernment:function(a){var b=this.governmentDiv;this.governmentDiv?dojo.empty(b):this.governmentDiv=b=dojo.create("div",{className:"currentGovernment",style:{paddingBottom:"10px"}},a);this.leaderDiv=dojo.create("div",{className:"currentLeader"},b);a=this.game.village.leader;
b=this.game.resPool.get("gold");if(a){var c=this.game.village.getRankExp(a.rank),d=25*(a.rank+1);this.promoteLeaderHref=dojo.create("a",{href:"#",innerHTML:$I("village.census.leader.propmote",[this.game.getDisplayValueExt(c.toFixed()),d]),style:{display:a.exp<c||b.value<d?"none":"block"}},this.governmentDiv);dojo.connect(this.promoteLeaderHref,"onclick",this,dojo.partial(function(e,f,g){g.preventDefault();this.game.village.sim.promote(f);e.renderGovernment(e.container);e.update()},this,a));b=dojo.create("div",
null,this.governmentDiv);this.unassignLeaderJobHref=dojo.create("a",{href:"#",innerHTML:$I("village.btn.unassign"),style:{display:a.job?"inline-block":"none"}},b);dojo.connect(this.unassignLeaderJobHref,"onclick",this,dojo.partial(function(e,f,g){g.preventDefault();g=e.game;f.job&&(g.village.unassignJob(f),g.village.updateResourceProduction(),e.renderGovernment(e.container),e.update(),g.render())},this,a))}},getStyledName:function(a,b){return this.game.religion.getPact("fractured").val&&this.game.getFeatureFlag("MAUSOLEUM_PACTS")?
(a.randTimer?a.randTimer+=-1:(b=this.game.createRandomVarietyAndColor(this.game.rand(76),this.game.rand(76)),a.fakeColor=b[0],a.fakeName=this.game.createRandomName()+this.game.createRandomName(1,"    -/_")+this.game.createRandomName(),a.fakeVariety=b[1],a.randTimer=10+this.game.rand(41)),"<span class='name color-"+(a.fakeColor&&a.colors[a.fakeColor+1]?a.colors[a.fakeColor+1].color:"none")+" variety-"+(a.fakeVariety&&a.varieties[a.fakeVariety+1]?a.varieties[a.fakeVariety+1].style:"none")+"'>"+a.fakeName+
"</span>"):"<span class='name color-"+(a.color&&a.colors[a.color+1]?a.colors[a.color+1].color:"none")+" variety-"+(a.variety&&a.varieties[a.variety+1]?a.varieties[a.variety+1].style:"none")+"'>"+a.name+" "+a.surname+"</span>"},update:function(){var a=this.game.village.leader;a&&this.unassignLeaderJobHref&&(this.unassignLeaderJobHref.style.display=a.job?"block":"none");a=this.getGovernmentInfo();this.game.challenges.isActive("anarchy")||(this.leaderDiv.innerHTML="<span>"+$I("village.census.lbl.leader")+
":</span> "+a.leaderInfo);for(a=0;a<this.records.length;a++){var b=this.records[a],c=b.kitten;c.job?dojo.style(b.unassignHref,"display","block"):dojo.style(b.unassignHref,"display","none");b.content.innerHTML="<div class='info'>"+this.getStyledName(c)+", "+(this.game.religion.getPact("fractured").val&&this.game.getFeatureFlag("MAUSOLEUM_PACTS")?"???":c.age)+" "+$I("village.census.age")+", "+(this.game.religion.getPact("fractured").val&&this.game.getFeatureFlag("MAUSOLEUM_PACTS")?"???":c.trait.title)+
(0==c.rank?"":" ("+$I("village.census.rank")+" "+c.rank+")")+"</div>";var d=this.getSkillInfo(c);b.content.innerHTML+=d;this.game.challenges.isActive("anarchy")||(b.leaderHref.innerHTML=c.isLeader?"&#9733;":"&#9734;")}}});dojo.declare("com.nuclearunicorn.game.ui.CensusPanel",com.nuclearunicorn.game.ui.Panel,{census:null,constructor:function(a,b,c){this.census=new classes.ui.village.Census(c)},render:function(a){var b=this.inherited(arguments);this.census.render(b)},update:function(){this.census.update()}});
dojo.declare("classes.village.ui.VillageButtonController",com.nuclearunicorn.game.ui.ButtonModernController,{defaults:function(){var a=this.inherited(arguments);a.simplePrices=!1;a.hasResourceHover=!0;return a}});
dojo.declare("classes.village.ui.FestivalButtonController",classes.village.ui.VillageButtonController,{fetchModel:function(a){var b=this.inherited(arguments);b.x10Link=this._newLink(10);b.x100Link=this._newLink(100);return b},_newLink:function(a){var b=this;return{title:"x"+a,visible:this.game.prestige.getPerk("carnivals").researched&&(this.game.opts.showNonApplicableButtons||this.hasMultipleResources(a)),handler:function(c,d){b.hasMultipleResources(a)?(b.game.villageTab.holdFestival(a),b.game.resPool.addResEvent("manpower",
-1500*a),b.game.resPool.addResEvent("culture",-5E3*a),b.game.resPool.addResEvent("parchment",-2500*a),d(!0)):d(!1)}}},updateVisible:function(a){a.visible=this.game.science.get("drama").researched},hasMultipleResources:function(a){return this.game.resPool.get("manpower").value>=1500*a&&this.game.resPool.get("culture").value>=5E3*a&&this.game.resPool.get("parchment").value>=2500*a}});
dojo.declare("classes.village.ui.FestivalButton",com.nuclearunicorn.game.ui.ButtonModern,{renderLinks:function(){this.x100=this.addLink(this.model.x100Link);this.x10=this.addLink(this.model.x10Link)},update:function(){this.inherited(arguments);dojo.style(this.x10.link,"display",this.model.x10Link.visible?"":"none");dojo.style(this.x100.link,"display",this.model.x100Link.visible?"":"none");this.model.x100Link.visible?(dojo.addClass(this.x100.link,"rightestLink"),dojo.removeClass(this.x10.link,"rightestLink")):
this.model.x10Link.visible&&dojo.addClass(this.x10.link,"rightestLink")}});
dojo.declare("com.nuclearunicorn.game.ui.tab.Village",com.nuclearunicorn.game.ui.tab,{tdTop:null,advModeButtons:null,huntBtn:null,festivalBtn:null,constructor:function(a,b){this.game=b;this.advModeButtons=[]},createJobBtn:function(a,b){return new com.nuclearunicorn.game.ui.JobButton({name:a.title,job:a.name,controller:new com.nuclearunicorn.game.ui.JobButtonController(b)},b)},render:function(a){this.advModeButtons=[];this.buttons=[];this.jobsPanel=new com.nuclearunicorn.game.ui.Panel($I("village.panel.job"),
this.game.village);this.game.ironWill&&!this.game.village.getKittens()&&this.jobsPanel.setVisible(!1);for(var b=this.jobsPanel.render(a),c=dojo.create("table",{className:"table",style:{width:"100%"}},b),d=0;d<this.game.village.jobs.length;d++){var e=this.createJobBtn(this.game.village.jobs[d],this.game);e.updateEnabled();e.updateVisible();e.render(b);this.addButton(e)}e=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("village.btn.job.clear"),description:$I("village.btn.job.clear.desc"),handler:dojo.hitch(this,
function(){var f=this.game;f.opts.noConfirm?f.village.clearJobs(!0):f.ui.confirm("",$I("village.tab.clear.job.confirmation.msg"),function(){f.village.clearJobs(!0)})}),controller:new com.nuclearunicorn.game.ui.ButtonModernController(this.game)},this.game);e.render(b);this.addButton(e);dojo.create("tr",null,c);this.tdTop=dojo.create("td",{colspan:2},dojo.create("tr",null,c));b=this.game.getFeatureFlag("VILLAGE_MAP")&&this.game.science.get("archery").researched;this.mapPanel=new com.nuclearunicorn.game.ui.Panel("Map",
this.game.village);this.mapPanel.setVisible(b);b=this.mapPanel.render(a);this.mapWgt=new classes.village.ui.MapOverviewWgt(this.game);this.mapWgt.render(b);this.statisticsPanel=new com.nuclearunicorn.game.ui.Panel($I("village.panel.management"),this.game.village);5>this.game.village.getKittens()&&0==this.game.resPool.get("zebras").value&&this.statisticsPanel.setVisible(!1);b=this.statisticsPanel.render(a);this.advVillageTable=b=dojo.create("table",{style:{width:"100%"}},b);b=dojo.create("tr",{},b);
c=dojo.create("td",{style:"cursor: pointer; width: 50%; text-align: center;"},b);UIUtils.attachTooltip(this.game,c,0,200,dojo.hitch(this,function(){return $I("village.panel.management.desc")}));this.happinessStats=c;b=dojo.create("td",{},b);c=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("village.btn.hunters"),description:$I("village.btn.hunters.desc"),handler:dojo.hitch(this,function(){this.sendHunterSquad()}),prices:[{name:"manpower",val:100}],controller:new classes.village.ui.VillageButtonController(this.game,
{updateVisible:function(f){f.visible=this.game.science.get("archery").researched&&!this.game.challenges.isActive("pacifism")}})},this.game);c.render(b);this.huntBtn=c;c=new classes.village.ui.FestivalButton({name:$I("village.btn.festival"),description:$I("village.btn.festival.desc"),handler:dojo.hitch(this,function(){this.holdFestival(1)}),prices:[{name:"manpower",val:1500},{name:"culture",val:5E3},{name:"parchment",val:2500}],controller:new classes.village.ui.FestivalButtonController(this.game)},
this.game);c.render(b);this.festivalBtn=c;c=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("village.btn.manage"),description:$I("village.btn.manage.desc"),handler:dojo.hitch(this,function(){this.game.village.optimizeJobs()}),controller:new classes.village.ui.VillageButtonController(this.game,{updateVisible:function(f){f.visible=void 0!=this.game.village.leader&&this.game.village.canHaveLeaderOrPromote()}})},this.game);c.render(b);this.optimizeJobsBtn=c;c=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("village.btn.promote"),
description:$I("village.btn.promote.desc"),handler:dojo.hitch(this,function(){this.game.village.promoteKittens()}),controller:new classes.village.ui.VillageButtonController(this.game,{updateVisible:function(f){f.visible=void 0!==this.game.village.leader&&this.game.village.canHaveLeaderOrPromote()}})},this.game);c.render(b);this.promoteKittensBtn=c;c=new com.nuclearunicorn.game.ui.ButtonModern({name:$I("village.btn.unwrap"),description:"",handler:dojo.hitch(this,function(){var f=this.game;f.ui.confirm("",
$I("village.btn.unwrap.confirmation.msg"),function(){f.redeemGift();f.render()})}),controller:new classes.village.ui.VillageButtonController(this.game,{updateVisible:function(f){f.visible=!this.game.isEldermass()&&0<this.game.resPool.get("elderBox").value}})},this.game);c.render(b);this.redeemGiftBtn=c;this.censusPanel=new com.nuclearunicorn.game.ui.CensusPanel($I("village.panel.census"),this.game.village,this.game);this.game.science.get("civil").researched||this.censusPanel.setVisible(!1);this.censusPanelContainer=
this.censusPanel.render(a);this.update()},update:function(){this.inherited(arguments);this.tdTop&&(this.tdTop.innerHTML=$I("village.general.free.kittens.label")+": "+this.game.village.getFreeKittens()+" / "+this.game.resPool.get("kittens").value);if(this.happinessStats){var a=100*this.game.village.happiness;a=1E4>a?Math.floor(a):this.game.getDisplayValueExt(a);this.happinessStats.innerHTML=$I("village.census.lbl.happiness")+":  "+a+"%"}if(a=this.game.calendar.festivalDays)this.happinessStats.innerHTML+=
"<br><br> "+$I("village.census.lbl.festival.duration")+" "+this.game.toDisplayDays(a);this.statisticsPanel&&this.statisticsPanel.setVisible(5<=this.game.village.getKittens()||0<this.game.resPool.get("zebras").value);this.huntBtn&&this.huntBtn.update();this.festivalBtn&&this.festivalBtn.update();this.mapPanel&&this.mapPanel.update();this.mapWgt&&this.mapWgt.update();this.censusPanel&&(a=this.game.science.get("civil").researched,this.censusPanel.setVisible(a),this.censusPanel.update());a=this.game.ironWill&&
!this.game.village.getKittens();this.jobsPanel.setVisible(!a);this.updateTab()},updateTab:function(){this.tabName=this.getVillageTitle();var a=this.game.village.getFreeKittens();0<a&&(this.tabName+=" <span class='genericWarning'>("+this.game.getDisplayValueExt(a,!1,!1,0)+")</span>");this.domNode&&(this.domNode.innerHTML=this.tabName)},getVillageTitle:function(){var a=this.game.village.getKittens();switch(!0){case 1E4<a:return $I("village.tab.title.deities");case 5E3<a:return $I("village.tab.title.elders");
case 2E3<a:return $I("village.tab.title.union");case 1500<a:return $I("village.tab.title.council");case 1200<a:return $I("village.tab.title.consortium");case 1E3<a:return $I("village.tab.title.civilisation");case 900<a:return $I("village.tab.title.society");case 800<a:return $I("village.tab.title.reich");case 700<a:return $I("village.tab.title.federation");case 600<a:return $I("village.tab.title.hegemony");case 500<a:return $I("village.tab.title.dominion");case 400<a:return $I("village.tab.title.imperium");
case 300<a:return $I("village.tab.title.empire");case 250<a:return $I("village.tab.title.megapolis");case 200<a:return $I("village.tab.title.metropolis");case 150<a:return $I("village.tab.title.city");case 100<a:return $I("village.tab.title.town");case 50<a:return $I("village.tab.title.smalltown");case 30<a:return $I("village.tab.title.settlement");case 15<a:return $I("village.tab.title.village");case 0<a:return $I("village.tab.title.smallvillage");default:return $I("village.tab.title.outpost")}},
skillToText:function(a){switch(!0){case 100>a:return $I("village.skill.dabbling");case 500>a:return $I("village.skill.novice");case 1200>a:return $I("village.skill.adequate");case 2500>a:return $I("village.skill.competent");case 5E3>a:return $I("village.skill.skilled");case 9E3>a:return $I("village.skill.proficient");default:return $I("village.skill.master")}},sendHunterSquad:function(){this.game.village.sendHunters()},holdFestival:function(a){this.game.village.holdFestival(a)},rand:function(a){return Math.floor(Math.random()*
a)}});
