dojo.declare("classes.managers.WorkshopManager",com.nuclearunicorn.core.TabManager,{game:null,hideResearched:!1,upgrades:[{name:"mineralHoes",label:$I("workshop.mineralHoes.label"),description:$I("workshop.mineralHoes.desc"),effects:{catnipJobRatio:.5},prices:[{name:"minerals",val:275},{name:"science",val:100}],unlocks:{upgrades:["ironHoes"]}},{name:"ironHoes",label:$I("workshop.ironHoes.label"),description:$I("workshop.ironHoes.desc"),effects:{catnipJobRatio:.3},prices:[{name:"iron",val:25},{name:"science",
val:200}]},{name:"mineralAxes",label:$I("workshop.mineralAxes.label"),description:$I("workshop.mineralAxes.desc"),effects:{woodJobRatio:.7},prices:[{name:"minerals",val:500},{name:"science",val:100}],unlocks:{upgrades:["ironAxes"]}},{name:"ironAxes",label:$I("workshop.ironAxes.label"),description:$I("workshop.ironAxes.desc"),effects:{woodJobRatio:.5},prices:[{name:"iron",val:50},{name:"science",val:200}]},{name:"steelAxe",label:$I("workshop.steelAxe.label"),description:$I("workshop.steelAxe.desc"),
effects:{woodJobRatio:.5},prices:[{name:"science",val:2E4},{name:"steel",val:75}]},{name:"reinforcedSaw",label:$I("workshop.reinforcedSaw.label"),description:$I("workshop.reinforcedSaw.desc"),effects:{lumberMillRatio:.2},prices:[{name:"iron",val:1E3},{name:"science",val:2500}],upgrades:{buildings:["lumberMill"]}},{name:"steelSaw",label:$I("workshop.steelSaw.label"),description:$I("workshop.steelSaw.desc"),effects:{lumberMillRatio:.2},prices:[{name:"science",val:52E3},{name:"steel",val:750}],upgrades:{buildings:["lumberMill"]},
unlocks:{upgrades:["titaniumSaw"]}},{name:"titaniumSaw",label:$I("workshop.titaniumSaw.label"),description:$I("workshop.titaniumSaw.desc"),effects:{lumberMillRatio:.15},prices:[{name:"titanium",val:500},{name:"science",val:7E4}],upgrades:{buildings:["lumberMill"]},unlocks:{upgrades:["alloySaw"]}},{name:"alloySaw",label:$I("workshop.alloySaw.label"),description:$I("workshop.alloySaw.desc"),effects:{lumberMillRatio:.15},prices:[{name:"science",val:85E3},{name:"alloy",val:75}],upgrades:{buildings:["lumberMill"]}},
{name:"titaniumAxe",label:$I("workshop.titaniumAxe.label"),description:$I("workshop.titaniumAxe.desc"),effects:{woodJobRatio:.5},prices:[{name:"titanium",val:10},{name:"science",val:38E3}]},{name:"alloyAxe",label:$I("workshop.alloyAxe.label"),description:$I("workshop.alloyAxe.desc"),effects:{woodJobRatio:.5},prices:[{name:"science",val:7E4},{name:"alloy",val:25}]},{name:"unobtainiumAxe",label:$I("workshop.unobtainiumAxe.label"),description:$I("workshop.unobtainiumAxe.desc"),effects:{woodJobRatio:.5},
prices:[{name:"unobtainium",val:75},{name:"science",val:125E3}]},{name:"unobtainiumSaw",label:$I("workshop.unobtainiumSaw.label"),description:$I("workshop.unobtainiumSaw.desc"),effects:{lumberMillRatio:.25},prices:[{name:"unobtainium",val:125},{name:"science",val:145E3}],upgrades:{buildings:["lumberMill"]}},{name:"stoneBarns",label:$I("workshop.stoneBarns.label"),description:$I("workshop.stoneBarns.desc"),effects:{barnRatio:.75},prices:[{name:"wood",val:1E3},{name:"minerals",val:750},{name:"iron",
val:50},{name:"science",val:500}],upgrades:{buildings:["barn","warehouse","harbor"]}},{name:"reinforcedBarns",label:$I("workshop.reinforcedBarns.label"),description:$I("workshop.reinforcedBarns.desc"),effects:{barnRatio:.8},prices:[{name:"iron",val:100},{name:"science",val:800},{name:"beam",val:25},{name:"slab",val:10}],upgrades:{buildings:["barn","warehouse","harbor"]},unlocks:{upgrades:["titaniumBarns"]}},{name:"reinforcedWarehouses",label:$I("workshop.reinforcedWarehouses.label"),description:$I("workshop.reinforcedWarehouses.desc"),
effects:{warehouseRatio:.25},prices:[{name:"science",val:15E3},{name:"plate",val:50},{name:"steel",val:50},{name:"scaffold",val:25}],upgrades:{buildings:["barn","warehouse","harbor","mint"]},unlocks:{upgrades:["ironwood"]}},{name:"titaniumBarns",label:$I("workshop.titaniumBarns.label"),description:$I("workshop.titaniumBarns.desc"),effects:{barnRatio:1},prices:[{name:"titanium",val:25},{name:"science",val:6E4},{name:"steel",val:200},{name:"scaffold",val:250}],upgrades:{buildings:["barn","warehouse",
"harbor"]}},{name:"alloyBarns",label:$I("workshop.alloyBarns.label"),description:$I("workshop.alloyBarns.desc"),effects:{barnRatio:1},prices:[{name:"science",val:75E3},{name:"plate",val:750},{name:"alloy",val:20}],upgrades:{buildings:["barn","warehouse","harbor"]}},{name:"concreteBarns",label:$I("workshop.concreteBarns.label"),description:$I("workshop.concreteBarns.desc"),effects:{barnRatio:.75},prices:[{name:"titanium",val:2E3},{name:"science",val:1E5},{name:"concrate",val:45}],upgrades:{buildings:["barn",
"warehouse","harbor"]}},{name:"titaniumWarehouses",label:$I("workshop.titaniumWarehouses.label"),description:$I("workshop.titaniumWarehouses.desc"),effects:{warehouseRatio:.5},prices:[{name:"titanium",val:50},{name:"science",val:7E4},{name:"steel",val:500},{name:"scaffold",val:500}],upgrades:{buildings:["barn","warehouse","harbor","mint"]}},{name:"alloyWarehouses",label:$I("workshop.alloyWarehouses.label"),description:$I("workshop.alloyWarehouses.desc"),effects:{warehouseRatio:.45},prices:[{name:"titanium",
val:750},{name:"science",val:9E4},{name:"alloy",val:50}],upgrades:{buildings:["barn","warehouse","harbor","mint"]}},{name:"concreteWarehouses",label:$I("workshop.concreteWarehouses.label"),description:$I("workshop.concreteWarehouses.desc"),effects:{warehouseRatio:.35},prices:[{name:"titanium",val:1250},{name:"science",val:1E5},{name:"concrate",val:35}],upgrades:{buildings:["barn","warehouse","harbor","mint"]}},{name:"storageBunkers",label:$I("workshop.storageBunkers.label"),description:$I("workshop.storageBunkers.desc"),
effects:{warehouseRatio:.2},prices:[{name:"unobtainium",val:500},{name:"science",val:25E3},{name:"concrate",val:1250}],upgrades:{buildings:["barn","warehouse","harbor","mint"]}},{name:"energyRifts",label:$I("workshop.energyRifts.label"),description:$I("workshop.energyRifts.desc"),effects:{},prices:[{name:"titanium",val:7500},{name:"uranium",val:250},{name:"science",val:2E5}],upgrades:{buildings:["accelerator"]}},{name:"stasisChambers",label:$I("workshop.stasisChambers.label"),description:$I("workshop.stasisChambers.desc"),
effects:{acceleratorRatio:.95},prices:[{name:"uranium",val:2E3},{name:"science",val:235E3},{name:"timeCrystal",val:1},{name:"alloy",val:200}],upgrades:{buildings:["accelerator"]},unlocks:{upgrades:["voidEnergy"]}},{name:"voidEnergy",label:$I("workshop.voidEnergy.label"),description:$I("workshop.voidEnergy.desc"),effects:{acceleratorRatio:.75},prices:[{name:"uranium",val:2500},{name:"science",val:275E3},{name:"timeCrystal",val:2},{name:"alloy",val:250}],upgrades:{buildings:["accelerator"]},unlocks:{upgrades:["darkEnergy"]}},
{name:"darkEnergy",label:$I("workshop.darkEnergy.label"),description:$I("workshop.darkEnergy.desc"),effects:{acceleratorRatio:2.5},prices:[{name:"science",val:35E4},{name:"timeCrystal",val:3},{name:"eludium",val:75}],upgrades:{buildings:["accelerator"]}},{name:"chronoforge",label:$I("workshop.chronoforge.label"),description:$I("workshop.chronoforge.desc"),prices:[{name:"science",val:5E5},{name:"timeCrystal",val:10},{name:"relic",val:5}]},{name:"tachyonAccelerators",label:$I("workshop.tachyonAccelerators.label"),
description:$I("workshop.tachyonAccelerators.desc"),effects:{acceleratorRatio:5},prices:[{name:"science",val:5E5},{name:"timeCrystal",val:10},{name:"eludium",val:125}],upgrades:{buildings:["accelerator"]}},{name:"fluxCondensator",label:$I("workshop.fluxCondensator.label"),description:$I("workshop.fluxCondensator.desc"),effects:{},prices:[{name:"unobtainium",val:5E3},{name:"timeCrystal",val:5},{name:"alloy",val:250}]},{name:"lhc",label:$I("workshop.lhc.label"),description:$I("workshop.lhc.desc"),effects:{},
prices:[{name:"unobtainium",val:100},{name:"science",val:25E4},{name:"alloy",val:150}],upgrades:{buildings:["accelerator"]}},{name:"photovoltaic",label:$I("workshop.photovoltaic.label"),description:$I("workshop.photovoltaic.desc"),prices:[{name:"titanium",val:5E3},{name:"science",val:75E3}],effects:{solarFarmRatio:.5},upgrades:{buildings:["pasture"]}},{name:"thinFilm",label:$I("workshop.thinFilm.label"),description:$I("workshop.thinFilm.desc"),prices:[{name:"uranium",val:1E3},{name:"unobtainium",
val:200},{name:"science",val:125E3}],effects:{solarFarmSeasonRatio:1},upgrades:{buildings:["pasture"]}},{name:"qdot",label:$I("workshop.qdot.label"),description:$I("workshop.qdot.desc"),prices:[{name:"science",val:175E3},{name:"eludium",val:200},{name:"thorium",val:1E3}],effects:{solarFarmSeasonRatio:1},upgrades:{buildings:["pasture"]}},{name:"solarSatellites",label:$I("workshop.solarSatellites.label"),description:$I("workshop.solarSatellites.desc"),prices:[{name:"science",val:225E3},{name:"alloy",
val:750}],upgrades:{spaceBuilding:["sattelite"]}},{name:"cargoShips",label:$I("workshop.cargoShips.label"),description:$I("workshop.cargoShips.desc"),effects:{harborRatio:.01},prices:[{name:"science",val:55E3},{name:"blueprint",val:15}],upgrades:{buildings:["harbor"]},flavor:$I("workshop.cargoShips.flavor")},{name:"barges",label:$I("workshop.barges.label"),description:$I("workshop.barges.desc"),effects:{harborCoalRatio:.5},prices:[{name:"titanium",val:1500},{name:"science",val:1E5},{name:"blueprint",
val:30}],upgrades:{buildings:["harbor"]}},{name:"reactorVessel",label:$I("workshop.reactorVessel.label"),description:$I("workshop.reactorVessel.desc"),effects:{shipLimit:.05},prices:[{name:"titanium",val:5E3},{name:"uranium",val:125},{name:"science",val:135E3}],upgrades:{buildings:["harbor"]}},{name:"ironwood",label:$I("workshop.ironwood.label"),description:$I("workshop.ironwood.desc"),effects:{hutPriceRatio:-.5},prices:[{name:"wood",val:15E3},{name:"iron",val:3E3},{name:"science",val:3E4}],unlocks:{upgrades:["silos"]}},
{name:"concreteHuts",label:$I("workshop.concreteHuts.label"),description:$I("workshop.concreteHuts.desc"),effects:{hutPriceRatio:-.3},prices:[{name:"titanium",val:3E3},{name:"science",val:125E3},{name:"concrate",val:45}]},{name:"unobtainiumHuts",label:$I("workshop.unobtainiumHuts.label"),description:$I("workshop.unobtainiumHuts.desc"),effects:{hutPriceRatio:-.25},prices:[{name:"titanium",val:15E3},{name:"unobtainium",val:350},{name:"science",val:2E5}]},{name:"eludiumHuts",label:$I("workshop.eludiumHuts.label"),
description:$I("workshop.eludiumHuts.desc"),effects:{hutPriceRatio:-.1},prices:[{name:"science",val:275E3},{name:"eludium",val:125}]},{name:"silos",label:$I("workshop.silos.label"),description:$I("workshop.silos.desc"),effects:{},prices:[{name:"science",val:5E4},{name:"steel",val:125},{name:"blueprint",val:5}],upgrades:{buildings:["barn","warehouse","harbor"]},unlocks:{upgrades:["titaniumWarehouses"]},flavor:$I("workshop.silos.flavor")},{name:"refrigeration",label:$I("workshop.refrigeration.label"),
description:$I("workshop.refrigeration.desc"),effects:{catnipMaxRatio:.75},prices:[{name:"titanium",val:2500},{name:"science",val:125E3},{name:"blueprint",val:15}]},{name:"compositeBow",label:$I("workshop.compositeBow.label"),description:$I("workshop.compositeBow.desc"),effects:{manpowerJobRatio:.5},calculateEffects:function(a,b){a.effects.manpowerJobRatio=.5*Math.max(0,1+b.getEffect("weaponEfficency"))},prices:[{name:"wood",val:200},{name:"iron",val:100},{name:"science",val:500}]},{name:"crossbow",
label:$I("workshop.crossbow.label"),description:$I("workshop.crossbow.desc"),effects:{manpowerJobRatio:.25},calculateEffects:function(a,b){a.effects.manpowerJobRatio=.25*Math.max(0,1+b.getEffect("weaponEfficency"))},prices:[{name:"iron",val:1500},{name:"science",val:12E3}]},{name:"railgun",label:$I("workshop.railgun.label"),description:$I("workshop.railgun.desc"),effects:{manpowerJobRatio:.25},calculateEffects:function(a,b){a.effects.manpowerJobRatio=.25*Math.max(0,1+b.getEffect("weaponEfficency"))},
prices:[{name:"titanium",val:5E3},{name:"science",val:15E4},{name:"blueprint",val:25}],flavor:$I("workshop.railgun.flavor")},{name:"bolas",label:$I("workshop.bolas.label"),description:$I("workshop.bolas.desc"),effects:{hunterRatio:1},prices:[{name:"wood",val:50},{name:"minerals",val:250},{name:"science",val:1E3}],flavor:$I("workshop.bolas.flavor")},{name:"huntingArmor",label:$I("workshop.huntingArmor.label"),description:$I("workshop.huntingArmor.desc"),effects:{hunterRatio:2},prices:[{name:"iron",
val:750},{name:"science",val:2E3}],flavor:$I("workshop.huntingArmor.flavor")},{name:"steelArmor",label:$I("workshop.steelArmor.label"),description:$I("workshop.steelArmor.desc"),effects:{hunterRatio:.5},prices:[{name:"science",val:1E4},{name:"steel",val:50}]},{name:"alloyArmor",label:$I("workshop.alloyArmor.label"),description:$I("workshop.alloyArmor.desc"),effects:{hunterRatio:.5},prices:[{name:"science",val:5E4},{name:"alloy",val:25}]},{name:"nanosuits",label:$I("workshop.nanosuits.label"),description:$I("workshop.nanosuits.desc"),
effects:{hunterRatio:.5},prices:[{name:"science",val:185E3},{name:"alloy",val:250}]},{name:"caravanserai",label:$I("workshop.caravanserai.label"),description:$I("workshop.caravanserai.desc"),effects:{},prices:[{name:"gold",val:250},{name:"science",val:25E3},{name:"ivory",val:1E4}],upgrades:{buildings:["tradepost"]},flavor:$I("workshop.caravanserai.flavor")},{name:"advancedRefinement",label:$I("workshop.advancedRefinement.label"),description:$I("workshop.advancedRefinement.desc"),effects:{},prices:[{name:"catnip",
val:5E3},{name:"science",val:500}],handler:function(a){a.workshop.getCraft("wood").prices=[{name:"catnip",val:50}]},flavor:$I("workshop.advancedRefinement.flavor")},{name:"goldOre",label:$I("workshop.goldOre.label"),description:$I("workshop.goldOre.desc"),effects:{},prices:[{name:"minerals",val:800},{name:"iron",val:100},{name:"science",val:1E3}],upgrades:{buildings:["smelter"]},flavor:$I("workshop.goldOre.flavor")},{name:"geodesy",label:$I("workshop.geodesy.label"),description:$I("workshop.geodesy.desc"),
effects:{},prices:[{name:"titanium",val:250},{name:"science",val:9E4},{name:"starchart",val:500}],upgrades:{jobs:["geologist"]},flavor:$I("workshop.geodesy.flavor")},{name:"register",label:$I("workshop.register.label"),description:$I("workshop.register.desc"),effects:{},prices:[{name:"gold",val:10},{name:"science",val:500}]},{name:"strenghtenBuild",label:$I("workshop.strenghtenBuild.label"),description:$I("workshop.strenghtenBuild.desc"),effects:{barnRatio:.05,warehouseRatio:.05},prices:[{name:"science",
val:1E5},{name:"concrate",val:50}],unlocks:{upgrades:["concreteWarehouses","concreteBarns","concreteHuts"]},upgrades:{buildings:["barn","warehouse","harbor","mint"]}},{name:"miningDrill",label:$I("workshop.miningDrill.label"),description:$I("workshop.miningDrill.desc"),effects:{},prices:[{name:"titanium",val:1750},{name:"science",val:1E5},{name:"steel",val:750}],upgrades:{jobs:["geologist"]}},{name:"unobtainiumDrill",label:$I("workshop.unobtainiumDrill.label"),description:$I("workshop.unobtainiumDrill.desc"),
effects:{},prices:[{name:"unobtainium",val:250},{name:"science",val:25E4},{name:"alloy",val:1250}],upgrades:{jobs:["geologist"]}},{name:"coalFurnace",label:$I("workshop.coalFurnace.label"),description:$I("workshop.coalFurnace.desc"),effects:{},prices:[{name:"minerals",val:5E3},{name:"iron",val:2E3},{name:"science",val:5E3},{name:"beam",val:35}],upgrades:{buildings:["smelter"]},flavor:$I("workshop.coalFurnace.flavor")},{name:"deepMining",label:$I("workshop.deepMining.label"),description:$I("workshop.deepMining.desc"),
effects:{},prices:[{name:"iron",val:1200},{name:"science",val:5E3},{name:"beam",val:50}],upgrades:{buildings:["mine"]},flavor:$I("workshop.deepMining.flavor")},{name:"pyrolysis",label:$I("workshop.pyrolysis.label"),description:$I("workshop.pyrolysis.desc"),effects:{coalSuperRatio:.2},prices:[{name:"science",val:35E3},{name:"compedium",val:5}]},{name:"electrolyticSmelting",label:$I("workshop.electrolyticSmelting.label"),description:$I("workshop.electrolyticSmelting.desc"),effects:{smelterRatio:.95},
prices:[{name:"titanium",val:2E3},{name:"science",val:1E5}],upgrades:{buildings:["smelter"]}},{name:"oxidation",label:$I("workshop.oxidation.label"),description:$I("workshop.oxidation.desc"),effects:{calcinerRatio:.95},prices:[{name:"science",val:1E5},{name:"steel",val:5E3}],upgrades:{buildings:["calciner"]}},{name:"steelPlants",label:$I("workshop.steelPlants.label"),description:$I("workshop.steelPlants.desc"),effects:{calcinerSteelRatio:.1},prices:[{name:"titanium",val:3500},{name:"science",val:14E4},
{name:"gear",val:750}],unlocks:{upgrades:["automatedPlants"]}},{name:"automatedPlants",label:$I("workshop.automatedPlants.label"),description:$I("workshop.automatedPlants.desc"),effects:{calcinerSteelCraftRatio:.25},prices:[{name:"science",val:2E5},{name:"alloy",val:750}],unlocks:{upgrades:["nuclearPlants"]}},{name:"nuclearPlants",label:$I("workshop.nuclearPlants.label"),description:$I("workshop.nuclearPlants.desc"),effects:{calcinerSteelReactorBonus:.02},prices:[{name:"uranium",val:1E4},{name:"science",
val:25E4}]},{name:"rotaryKiln",label:$I("workshop.rotaryKiln.label"),description:$I("workshop.rotaryKiln.desc"),effects:{calcinerRatio:.75},prices:[{name:"titanium",val:5E3},{name:"science",val:145E3},{name:"gear",val:500}],upgrades:{buildings:["calciner"]}},{name:"fluidizedReactors",label:$I("workshop.fluidizedReactors.label"),description:$I("workshop.fluidizedReactors.desc"),effects:{calcinerRatio:1},prices:[{name:"science",val:175E3},{name:"alloy",val:200}],upgrades:{buildings:["calciner"]}},{name:"nuclearSmelters",
label:$I("workshop.nuclearSmelters.label"),description:$I("workshop.nuclearSmelters.desc"),effects:{},prices:[{name:"uranium",val:250},{name:"science",val:165E3}],upgrades:{buildings:["smelter"]}},{name:"orbitalGeodesy",label:$I("workshop.orbitalGeodesy.label"),description:$I("workshop.orbitalGeodesy.desc"),effects:{},upgrades:{buildings:["quarry"]},prices:[{name:"oil",val:35E3},{name:"science",val:15E4},{name:"alloy",val:1E3}]},{name:"printingPress",label:$I("workshop.printingPress.label"),description:$I("workshop.printingPress.desc"),
effects:{},prices:[{name:"science",val:7500},{name:"gear",val:45}],upgrades:{buildings:["steamworks"]}},{name:"offsetPress",label:$I("workshop.offsetPress.label"),description:$I("workshop.offsetPress.desc"),effects:{},prices:[{name:"oil",val:15E3},{name:"science",val:1E5},{name:"gear",val:250}],upgrades:{buildings:["steamworks"]},flavor:$I("workshop.offsetPress.flavor")},{name:"photolithography",label:$I("workshop.photolithography.label"),description:$I("workshop.photolithography.desc"),effects:{},
prices:[{name:"oil",val:5E4},{name:"uranium",val:250},{name:"science",val:25E4},{name:"alloy",val:1250}],upgrades:{buildings:["steamworks"]}},{name:"uplink",label:$I("workshop.uplink.label"),description:$I("workshop.uplink.desc"),effects:{uplinkDCRatio:.01,uplinkLabRatio:.01},prices:[{name:"science",val:75E3},{name:"alloy",val:1750}],upgrades:{buildings:["library","biolab"]}},{name:"starlink",label:$I("workshop.starlink.label"),description:$I("workshop.starlink.desc"),effects:{uplinkLabRatio:.01},
prices:[{name:"oil",val:25E3},{name:"science",val:175E3},{name:"alloy",val:5E3}],upgrades:{buildings:["library","biolab"]}},{name:"cryocomputing",label:$I("workshop.cryocomputing.label"),description:$I("workshop.cryocomputing.desc"),effects:{},prices:[{name:"science",val:125E3},{name:"eludium",val:15}],upgrades:{buildings:["library"]}},{name:"machineLearning",label:$I("workshop.machineLearning.label"),description:$I("workshop.machineLearning.desc"),effects:{dataCenterAIRatio:.1},prices:[{name:"antimatter",
val:125},{name:"science",val:175E3},{name:"eludium",val:25}],upgrades:{buildings:["library"]}},{name:"factoryAutomation",label:$I("workshop.factoryAutomation.label"),description:$I("workshop.factoryAutomation.desc"),effects:{},prices:[{name:"science",val:1E4},{name:"gear",val:25}],flavor:$I("workshop.factoryAutomation.flavor")},{name:"advancedAutomation",label:$I("workshop.advancedAutomation.label"),description:$I("workshop.advancedAutomation.desc"),effects:{},prices:[{name:"science",val:1E5},{name:"gear",
val:75},{name:"blueprint",val:25}]},{name:"pneumaticPress",label:$I("workshop.pneumaticPress.label"),description:$I("workshop.pneumaticPress.desc"),effects:{},prices:[{name:"science",val:2E4},{name:"gear",val:30},{name:"blueprint",val:5}]},{name:"combustionEngine",label:$I("workshop.combustionEngine.label"),description:$I("workshop.combustionEngine.desc"),effects:{coalRatioGlobalReduction:.2},prices:[{name:"science",val:2E4},{name:"gear",val:25},{name:"blueprint",val:5}],upgrades:{buildings:["steamworks"]},
flavor:$I("workshop.combustionEngine.flavor")},{name:"fuelInjectors",label:$I("workshop.fuelInjectors.label"),description:$I("workshop.fuelInjectors.desc"),effects:{coalRatioGlobalReduction:.2},prices:[{name:"oil",val:2E4},{name:"science",val:1E5},{name:"gear",val:250}],upgrades:{buildings:["steamworks"]}},{name:"factoryLogistics",label:$I("workshop.factoryLogistics.label"),description:$I("workshop.factoryLogistics.desc"),effects:{},prices:[{name:"titanium",val:2E3},{name:"science",val:1E5},{name:"gear",
val:250}],upgrades:{buildings:["factory"]}},{name:"carbonSequestration",label:$I("workshop.carbonSequestration.label"),description:$I("workshop.carbonSequestration.desc"),effects:{},prices:[{name:"titanium",val:1250},{name:"science",val:75E3},{name:"gear",val:125},{name:"steel",val:4E3},{name:"alloy",val:1E3}],upgrades:{buildings:["factory"]}},{name:"factoryOptimization",label:$I("workshop.factoryOptimization.label"),description:$I("workshop.factoryOptimization.desc"),effects:{t1CraftRatio:10,t2CraftRatio:2},
prices:[{name:"titanium",val:1250},{name:"science",val:75E3},{name:"gear",val:125}]},{name:"factoryRobotics",label:$I("workshop.factoryRobotics.label"),description:$I("workshop.factoryRobotics.desc"),effects:{t1CraftRatio:10,t2CraftRatio:5,t3CraftRatio:2},prices:[{name:"titanium",val:2500},{name:"science",val:1E5},{name:"gear",val:250}]},{name:"spaceEngineers",label:$I("workshop.spaceEngineers.label"),description:$I("workshop.spaceEngineers.desc"),effects:{t1CraftRatio:2,t2CraftRatio:2,t3CraftRatio:2,
t4CraftRatio:2},prices:[{name:"science",val:225E3},{name:"alloy",val:500}]},{name:"aiEngineers",label:$I("workshop.aiEngineers.label"),description:$I("workshop.aiEngineers.desc"),effects:{t1CraftRatio:10,t2CraftRatio:5,t3CraftRatio:5,t4CraftRatio:2,t5CraftRatio:2},prices:[{name:"antimatter",val:500},{name:"science",val:35E3},{name:"eludium",val:50}]},{name:"chronoEngineers",label:$I("workshop.chronoEngineers.label"),description:$I("workshop.chronoEngineers.desc"),effects:{t1CraftRatio:2,t2CraftRatio:2,
t3CraftRatio:2,t4CraftRatio:2,t5CraftRatio:2},prices:[{name:"science",val:5E5},{name:"timeCrystal",val:5},{name:"eludium",val:100}]},{name:"spaceManufacturing",label:$I("workshop.spaceManufacturing.label"),description:$I("workshop.spaceManufacturing.desc"),effects:{},prices:[{name:"titanium",val:125E3},{name:"science",val:25E4}],upgrades:{buildings:["factory"]}},{name:"celestialMechanics",label:$I("workshop.celestialMechanics.label"),description:$I("workshop.celestialMechanics.desc"),effects:{},prices:[{name:"science",
val:250}]},{name:"astrolabe",label:$I("workshop.astrolabe.label"),description:$I("workshop.astrolabe.desc"),effects:{},prices:[{name:"titanium",val:5},{name:"science",val:25E3},{name:"starchart",val:75}],upgrades:{buildings:["observatory"]}},{name:"titaniumMirrors",label:$I("workshop.titaniumMirrors.label"),description:$I("workshop.titaniumMirrors.desc"),effects:{libraryRatio:.02},prices:[{name:"titanium",val:15},{name:"science",val:2E4},{name:"starchart",val:20}],upgrades:{buildings:["library"]},
flavor:$I("workshop.titaniumMirrors.flavor")},{name:"unobtainiumReflectors",label:$I("workshop.unobtainiumReflectors.label"),description:$I("workshop.unobtainiumReflectors.desc"),effects:{libraryRatio:.02},prices:[{name:"unobtainium",val:75},{name:"science",val:25E4},{name:"starchart",val:750}],upgrades:{buildings:["library"]}},{name:"eludiumReflectors",label:$I("workshop.eludiumReflectors.label"),description:$I("workshop.eludiumReflectors.desc"),effects:{libraryRatio:.02},prices:[{name:"science",
val:25E4},{name:"eludium",val:15}],upgrades:{buildings:["library"]}},{name:"hydroPlantTurbines",label:$I("workshop.hydroPlantTurbines.label"),description:$I("workshop.hydroPlantTurbines.desc"),effects:{hydroPlantRatio:.15},prices:[{name:"unobtainium",val:125},{name:"science",val:25E4}],upgrades:{buildings:["aqueduct"]}},{name:"amBases",label:$I("workshop.amBases.label"),description:$I("workshop.amBases.desc"),prices:[{name:"antimatter",val:250},{name:"eludium",val:15}],upgrades:{spaceBuilding:["moonBase"]},
unlocks:{upgrades:["aiBases"]}},{name:"aiBases",label:$I("workshop.aiBases.label"),description:$I("workshop.aiBases.desc"),prices:[{name:"antimatter",val:7500},{name:"science",val:75E4}],upgrades:{spaceBuilding:["moonBase"]}},{name:"amFission",label:$I("workshop.amFission.label"),description:$I("workshop.amFission.desc"),prices:[{name:"antimatter",val:175},{name:"science",val:525E3},{name:"thorium",val:7500}],effects:{eludiumAutomationBonus:.25}},{name:"amReactors",label:$I("workshop.amReactors.label"),
description:$I("workshop.amReactors.desc"),effects:{spaceScienceRatio:.95},prices:[{name:"antimatter",val:750},{name:"eludium",val:35}],upgrades:{spaceBuilding:["researchVessel","spaceBeacon"]},unlocks:{upgrades:["amReactorsMK2"]}},{name:"amReactorsMK2",label:$I("workshop.amReactorsMK2.label"),description:$I("workshop.amReactorsMK2.desc"),effects:{spaceScienceRatio:1.5},upgrades:{spaceBuilding:["researchVessel","spaceBeacon"]},prices:[{name:"antimatter",val:1750},{name:"eludium",val:70}],unlocks:{upgrades:["voidReactors"]}},
{name:"voidReactors",label:$I("workshop.voidReactors.label"),description:$I("workshop.voidReactors.desc"),effects:{spaceScienceRatio:4},upgrades:{spaceBuilding:["researchVessel","spaceBeacon"]},prices:[{name:"antimatter",val:2500},{name:"void",val:250}]},{name:"relicStation",label:$I("workshop.relicStation.label"),description:$I("workshop.relicStation.desc"),effects:{beaconRelicsPerDay:.01},upgrades:{spaceBuilding:["spaceBeacon"]},prices:[{name:"antimatter",val:5E3},{name:"eludium",val:100}]},{name:"amDrive",
label:$I("workshop.amDrive.label"),description:$I("workshop.amDrive.desc"),prices:[{name:"antimatter",val:125},{name:"science",val:45E4}],effects:{routeSpeed:25}},{name:"pumpjack",label:$I("workshop.pumpjack.label"),description:$I("workshop.pumpjack.desc"),effects:{oilWellRatio:.45},prices:[{name:"titanium",val:250},{name:"science",val:1E5},{name:"gear",val:125}],upgrades:{buildings:["oilWell"]}},{name:"biofuel",label:$I("workshop.biofuel.label"),description:$I("workshop.biofuel.desc"),effects:{},
prices:[{name:"titanium",val:1250},{name:"science",val:15E4}],upgrades:{buildings:["biolab"]}},{name:"unicornSelection",label:$I("workshop.unicornSelection.label"),description:$I("workshop.unicornSelection.desc"),effects:{unicornsGlobalRatio:.25},prices:[{name:"titanium",val:1500},{name:"science",val:175E3}]},{name:"gmo",label:$I("workshop.gmo.label"),description:$I("workshop.gmo.desc"),effects:{biofuelRatio:.6},prices:[{name:"catnip",val:1E6},{name:"titanium",val:1500},{name:"science",val:175E3}],
upgrades:{buildings:["biolab"]}},{name:"cadSystems",label:$I("workshop.cadSystems.label"),description:$I("workshop.cadSystems.desc"),effects:{cadBlueprintCraftRatio:.01},prices:[{name:"titanium",val:750},{name:"science",val:125E3}]},{name:"seti",label:$I("workshop.seti.label"),description:$I("workshop.seti.desc"),effects:{},prices:[{name:"titanium",val:250},{name:"science",val:125E3}]},{name:"logistics",label:$I("workshop.logistics.label"),description:$I("workshop.logistics.desc"),effects:{skillMultiplier:.15},
prices:[{name:"science",val:1E5},{name:"gear",val:100},{name:"scaffold",val:1E3}]},{name:"augumentation",label:$I("workshop.augumentation.label"),description:$I("workshop.augumentation.desc"),effects:{skillMultiplier:1},prices:[{name:"titanium",val:5E3},{name:"uranium",val:50},{name:"science",val:15E4}]},{name:"internet",label:$I("workshop.internet.label"),description:$I("workshop.internet.desc"),effects:{},prices:[{name:"titanium",val:5E3},{name:"uranium",val:50},{name:"science",val:15E4}]},{name:"neuralNetworks",
label:$I("workshop.neuralNetworks.label"),description:$I("workshop.neuralNetworks.desc"),effects:{},prices:[{name:"titanium",val:7500},{name:"science",val:2E5}],unlocks:{},upgrades:{buildings:["factory"]}},{name:"assistance",label:$I("workshop.assistance.label"),description:$I("workshop.assistance.desc"),effects:{catnipDemandWorkerRatioGlobal:-.25},prices:[{name:"science",val:1E5},{name:"steel",val:1E4},{name:"gear",val:250}]},{name:"enrichedUranium",label:$I("workshop.enrichedUranium.label"),description:$I("workshop.enrichedUranium.desc"),
effects:{uraniumRatio:.25},prices:[{name:"titanium",val:7500},{name:"uranium",val:150},{name:"science",val:175E3}],upgrades:{buildings:["reactor"]}},{name:"coldFusion",label:$I("workshop.coldFusion.label"),description:$I("workshop.coldFusion.desc"),effects:{reactorEnergyRatio:.25},prices:[{name:"science",val:2E5},{name:"eludium",val:25}],upgrades:{buildings:["reactor"]}},{name:"thoriumReactors",label:$I("workshop.thoriumReactors.label"),description:$I("workshop.thoriumReactors.desc"),effects:{reactorThoriumPerTick:-.05,
reactorEnergyRatio:.25},prices:[{name:"science",val:4E5},{name:"thorium",val:1E4}],upgrades:{buildings:["reactor"]},unlocks:{upgrades:["enrichedThorium"]}},{name:"enrichedThorium",label:$I("workshop.enrichedThorium.label"),description:$I("workshop.enrichedThorium.desc"),effects:{reactorThoriumPerTick:.0125},prices:[{name:"science",val:5E5},{name:"thorium",val:12500}],upgrades:{buildings:["reactor"]}},{name:"hubbleTelescope",label:$I("workshop.hubbleTelescope.label"),description:$I("workshop.hubbleTelescope.desc"),
effects:{starchartGlobalRatio:.3},prices:[{name:"oil",val:5E4},{name:"science",val:25E4},{name:"alloy",val:1250}],unlocks:{upgrades:["satnav"]}},{name:"satnav",label:$I("workshop.satnav.label"),description:$I("workshop.satnav.desc"),effects:{satnavRatio:.0125},prices:[{name:"science",val:2E5},{name:"alloy",val:750}]},{name:"satelliteRadio",label:$I("workshop.satelliteRadio.label"),description:$I("workshop.satelliteRadio.desc"),effects:{broadcastTowerRatio:.005},prices:[{name:"science",val:225E3},
{name:"alloy",val:5E3}]},{name:"astrophysicists",label:$I("workshop.astrophysicists.label"),description:$I("workshop.astrophysicists.desc"),effects:{},prices:[{name:"unobtainium",val:350},{name:"science",val:25E4}],upgrades:{jobs:["scholar"]}},{name:"mWReactor",label:$I("workshop.mWReactor.label"),description:$I("workshop.mWReactor.desc"),effects:{lunarOutpostRatio:.75},prices:[{name:"science",val:15E4},{name:"eludium",val:50}]},{name:"eludiumCracker",label:$I("workshop.eludiumCracker.label"),description:$I("workshop.eludiumCracker.desc"),
effects:{crackerRatio:1},prices:[{name:"science",val:275E3},{name:"eludium",val:250}],upgrades:{spaceBuilding:["planetCracker"]}},{name:"thoriumEngine",label:$I("workshop.thoriumEngine.label"),description:$I("workshop.thoriumEngine.desc"),prices:[{name:"science",val:4E5},{name:"gear",val:4E4},{name:"alloy",val:2E3},{name:"ship",val:1E4},{name:"thorium",val:1E5}],effects:{routeSpeed:50}},{name:"spiceNavigation",label:$I("workshop.spiceNavigation.label"),description:$I("workshop.spiceNavigation.desc"),
prices:[{name:"science",val:35E4},{name:"starchart",val:5E5}],unlocks:{spaceBuilding:["navigationRelay"]},flavor:$I("workshop.spiceNavigation.flavor")},{name:"longRangeSpaceships",label:$I("workshop.longRangeSpaceships.label"),description:$I("workshop.longRangeSpaceships.desc"),prices:[{name:"science",val:44E4},{name:"gear",val:9E4},{name:"alloy",val:3500},{name:"tanker",val:500}],unlocks:{spaceBuilding:["spaceShuttle"]},flavor:$I("workshop.longRangeSpaceships.flavor")},{name:"oilRefinery",label:$I("workshop.oilRefinery.label"),
description:$I("workshop.oilRefinery.desc"),effects:{oilWellRatio:.35},prices:[{name:"titanium",val:1250},{name:"science",val:125E3},{name:"gear",val:500}],upgrades:{buildings:["oilWell"]}},{name:"oilDistillation",label:$I("workshop.oilDistillation.label"),description:$I("workshop.oilDistillation.desc"),effects:{oilWellRatio:.75},prices:[{name:"titanium",val:5E3},{name:"science",val:175E3}],upgrades:{buildings:["oilWell"]}},{name:"factoryProcessing",label:$I("workshop.factoryProcessing.label"),description:$I("workshop.factoryProcessing.desc"),
effects:{factoryRefineRatio:.05},prices:[{name:"titanium",val:7500},{name:"science",val:195E3},{name:"concrate",val:125}]},{name:"voidAspiration",label:$I("workshop.voidAspiration.label"),description:$I("workshop.voidAspiration.desc"),effects:{},prices:[{name:"antimatter",val:2E3},{name:"timeCrystal",val:15}],unlocks:{voidSpace:["voidHoover","voidRift"]}},{name:"distorsion",label:$I("workshop.distorsion.label"),description:$I("workshop.distorsion.desc"),effects:{temporalParadoxDayBonus:2},prices:[{name:"antimatter",
val:2E3},{name:"science",val:3E5},{name:"timeCrystal",val:25},{name:"void",val:1E3}],upgrades:{voidSpace:["chronocontrol"]}},{name:"turnSmoothly",label:$I("workshop.turnSmoothly.label"),description:$I("workshop.turnSmoothly.desc"),effects:{temporalFluxProductionChronosphere:1},prices:[{name:"unobtainium",val:1E5},{name:"temporalFlux",val:6500},{name:"timeCrystal",val:25},{name:"void",val:750}],upgrades:{buildings:["chronosphere"]}},{name:"invisibleBlackHand",label:$I("workshop.invisibleBlackHand.label"),
description:$I("workshop.invisibleBlackHand.desc"),prices:[{name:"temporalFlux",val:4096},{name:"timeCrystal",val:128},{name:"void",val:32},{name:"blackcoin",val:64}],unlocks:{}}],crafts:[{name:"wood",label:$I("workshop.crafts.wood.label"),description:$I("workshop.crafts.wood.desc"),prices:[{name:"catnip",val:100}],ignoreBonuses:!0,progressHandicap:1,tier:1},{name:"beam",label:$I("workshop.crafts.beam.label"),description:$I("workshop.crafts.beam.desc"),prices:[{name:"wood",val:175}],progressHandicap:1,
tier:1},{name:"slab",label:$I("workshop.crafts.slab.label"),description:$I("workshop.crafts.slab.desc"),prices:[{name:"minerals",val:250}],progressHandicap:1,tier:1},{name:"plate",label:$I("workshop.crafts.plate.label"),description:$I("workshop.crafts.plate.desc"),prices:[{name:"iron",val:125}],progressHandicap:4,tier:1},{name:"steel",label:$I("workshop.crafts.steel.label"),description:$I("workshop.crafts.steel.desc"),prices:[{name:"coal",val:100},{name:"iron",val:100}],progressHandicap:4,tier:2},
{name:"concrate",label:$I("workshop.crafts.concrate.label"),description:$I("workshop.crafts.concrate.desc"),prices:[{name:"slab",val:2500},{name:"steel",val:25}],progressHandicap:9,tier:4},{name:"gear",label:$I("workshop.crafts.gear.label"),description:$I("workshop.crafts.gear.desc"),prices:[{name:"steel",val:15}],progressHandicap:5,tier:3},{name:"alloy",label:$I("workshop.crafts.alloy.label"),description:$I("workshop.crafts.alloy.desc"),prices:[{name:"titanium",val:10},{name:"steel",val:75}],progressHandicap:7,
tier:4},{name:"eludium",label:$I("workshop.crafts.eludium.label"),description:$I("workshop.crafts.eludium.desc"),prices:[{name:"unobtainium",val:1E3},{name:"alloy",val:2500}],progressHandicap:300,tier:5},{name:"scaffold",label:$I("workshop.crafts.scaffold.label"),description:$I("workshop.crafts.scaffold.desc"),prices:[{name:"beam",val:50}],progressHandicap:2,tier:2},{name:"ship",label:$I("workshop.crafts.ship.label"),description:$I("workshop.crafts.ship.desc"),prices:[{name:"starchart",val:25},{name:"plate",
val:150},{name:"scaffold",val:100}],upgrades:{buildings:["harbor"]},progressHandicap:20,tier:3},{name:"tanker",label:$I("workshop.crafts.tanker.label"),description:$I("workshop.crafts.tanker.desc"),prices:[{name:"alloy",val:1250},{name:"ship",val:200},{name:"blueprint",val:5}],upgrades:{buildings:["harbor"]},progressHandicap:20,tier:5},{name:"kerosene",label:$I("workshop.crafts.kerosene.label"),description:$I("workshop.crafts.kerosene.desc"),prices:[{name:"oil",val:7500}],progressHandicap:5,tier:2},
{name:"parchment",label:$I("workshop.crafts.parchment.label"),description:$I("workshop.crafts.parchment.desc"),prices:[{name:"furs",val:175}],progressHandicap:1,tier:1},{name:"manuscript",label:$I("workshop.crafts.manuscript.label"),description:$I("workshop.crafts.manuscript.desc"),prices:[{name:"culture",val:400},{name:"parchment",val:25}],progressHandicap:2,tier:2},{name:"compedium",label:$I("workshop.crafts.compedium.label"),description:$I("workshop.crafts.compedium.desc"),prices:[{name:"science",
val:1E4},{name:"manuscript",val:50}],progressHandicap:5,tier:3},{name:"blueprint",label:$I("workshop.crafts.blueprint.label"),description:$I("workshop.crafts.blueprint.desc"),prices:[{name:"science",val:25E3},{name:"compedium",val:25}],progressHandicap:10,tier:3},{name:"thorium",label:$I("workshop.crafts.thorium.label"),description:$I("workshop.crafts.thorium.desc"),prices:[{name:"uranium",val:250}],progressHandicap:5,tier:3},{name:"megalith",label:$I("workshop.crafts.megalith.label"),description:$I("workshop.crafts.megalith.desc"),
prices:[{name:"beam",val:25},{name:"slab",val:50},{name:"plate",val:5}],progressHandicap:5,tier:3},{name:"bloodstone",label:$I("workshop.crafts.bloodstone.label"),description:$I("workshop.crafts.bloodstone.desc"),prices:[{name:"timeCrystal",val:5E3},{name:"relic",val:1E4}],progressHandicap:7500,tier:5},{name:"tMythril",label:$I("workshop.crafts.tMythril.label"),description:$I("workshop.crafts.tMythril.desc"),prices:[{name:"bloodstone",val:5},{name:"ivory",val:1E3},{name:"titanium",val:500}],progressHandicap:1E4,
tier:7}],zebraUpgrades:[{name:"darkRevolution",label:$I("workshop.zebraUpgrade.darkRevolution.label"),description:$I("workshop.zebraUpgrade.darkRevolution.desc"),effects:{},prices:[{name:"bloodstone",val:15},{name:"science",val:100}],upgrades:{buildings:["zebraOutpost"]}},{name:"darkBrew",label:$I("workshop.zebraUpgrade.darkBrew.label"),description:$I("workshop.zebraUpgrade.darkBrew.desc"),effects:{},prices:[{name:"bloodstone",val:1},{name:"parchment",val:3E3},{name:"science",val:100}]},{name:"whispers",
label:$I("workshop.zebraUpgrade.whispers.label"),description:$I("workshop.zebraUpgrade.whispers.desc"),effects:{},prices:[{name:"tMythril",val:5}],upgrades:{buildings:["ivoryTemple"]}},{name:"minerologyDepartment",label:$I("workshop.zebraUpgrade.minerologyDepartment.label"),description:$I("workshop.zebraUpgrade.minerologyDepartment.desc"),effects:{},prices:[{name:"science",val:75E3},{name:"compedium",val:75}],upgrades:{buildings:["academy"]}}],effectsBase:{oilMax:0,scienceMax:0,cultureMax:0},metaCache:null,
constructor:function(a){this.game=a;this.metaCache={};this.registerMeta("research",this.upgrades,null);this.registerMeta("research",this.zebraUpgrades,null);this.setEffectsCachedExisting()},get:function(a){var b=this.metaCache[a];if(b)return b;for(var c=this.upgrades.length-1;0<=c;c--)if(this.upgrades[c].name===a)return this.metaCache[b]=this.upgrades[c],this.upgrades[c];console.error("Failed to get upgrade for id '"+a+"'");return null},getCraft:function(a){for(var b=this.crafts.length-1;0<=b;b--)if(this.crafts[b].name===
a)return this.crafts[b];return null},getZebraUpgrade:function(a){var b=this.metaCache[a];if(b)return b;for(var c=this.zebraUpgrades.length-1;0<=c;c--)if(this.zebraUpgrades[c].name===a)return this.metaCache[b]=this.zebraUpgrades[c],this.zebraUpgrades[c];console.error("Failed to get upgrade for id '"+a+"'");return null},resetState:function(){for(var a=0;a<this.upgrades.length;a++){var b=this.upgrades[a];b.unlocked="mineralHoes"==b.name||"ironHoes"==b.name||"mineralAxes"==b.name||"ironAxes"==b.name||
"stoneBarns"==b.name||"reinforcedBarns"==b.name?!0:!1;b.researched=!1}for(a=0;a<this.crafts.length;a++)b=this.crafts[a],b.unlocked="wood"==b.name||"beam"==b.name||"slab"==b.name||"plate"==b.name||"gear"==b.name||"scaffold"==b.name||"manuscript"==b.name||"megalith"==b.name?!0:!1,b.value=0,b.progress=0,"undefined"==typeof b.progressHandicap&&(b.progressHandicap=1);for(a=0;a<this.zebraUpgrades.length;a++)b=this.zebraUpgrades[a],b.researched=!1,b.unlocked=!1;this.getCraft("wood").prices=[{name:"catnip",
val:100}];this.hideResearched=!1},save:function(a){a.workshop={hideResearched:this.hideResearched,upgrades:this.filterMetadata(this.upgrades,["name","unlocked","researched"]),crafts:this.filterMetadata(this.crafts,["name","unlocked","value","progress"]),zebraUpgrades:this.filterMetadata(this.zebraUpgrades,["name","unlocked","researched"])}},load:function(a){if(a.workshop){this.hideResearched=a.workshop.hideResearched;this.loadMetadata(this.upgrades,a.workshop.upgrades);this.loadMetadata(this.crafts,
a.workshop.crafts);this.loadMetadata(this.zebraUpgrades,a.workshop.zebraUpgrades);for(a=0;a<this.upgrades.length;a++){var b=this.upgrades[a];b.researched&&(b.handler&&b.handler(this.game),b.unlocks&&this.game.unlock(b.unlocks))}for(a=0;a<this.zebraUpgrades.length;a++)b=this.zebraUpgrades[a],b.researched&&(b.handler&&b.handler(this.game),b.unlocks&&this.game.unlock(b.unlocks))}},getCraftPrice:function(a){if("ship"!=a.name&&"manuscript"!=a.name)return a.prices;if("manuscript"==a.name&&this.game.science.getPolicy("tradition").researched)return[{name:"parchment",
val:20},{name:"culture",val:300}];a=dojo.clone(a.prices);for(var b=a.length-1;0<=b;b--)"starchart"==a[b].name&&(a[b].val*=1-this.game.getLimitedDR(this.game.getEffect("satnavRatio")*this.game.space.getBuilding("sattelite").on,.75));return a},craft:function(a,b,c,d,e){var g=this.getCraft(a),h=this.game.getResCraftRatio(a);b=Math.ceil(b);h=b*(1+h);if(0>b&&this.game.resPool.get(a).value<Math.abs(h))return!1;for(var f=dojo.clone(this.getCraftPrice(g)),k=f.length-1;0<=k;k--)f[k].val*=b;return e||this.game.resPool.hasRes(f)?
(this.game.resPool.payPrices(f),this.game.resPool.addResEvent(a,h),g.upgrades&&this.game.upgrade(g.upgrades),this.game.stats.getStat("totalCrafts").val++,this.game.stats.getStatCurrent("totalCrafts").val++,c||this.game.registerUndoChange().addEvent("workshop",{metaId:a,val:b}),!0):d?(this.craftAll(a),!0):!1},getEffectEngineer:function(a,b){var c=this.getCraft(a);if(null==c)return 0;var d=(this.game.village.getResProduction()["ES"+a]||0)*(this.game.workshop.get("neuralNetworks").researched?2:1);d*=
this.game.religion.getHGScalingBonus();var e=this.game.getEffect("t"+c.tier+"CraftRatio")||0;0==e&&(e=1);return d*e/(600*this.game.ticksPerSecond*c.progressHandicap)*(1+(b?this.game.getResCraftRatio(a):0))},undo:function(a){var b=a.metaId;a=a.val;if(this.craft(b,-a,!0)){var c=this.game.resPool.get(b);b=this.game.getResCraftRatio(b);this.game.msg($I("workshop.undo.msg",[this.game.getDisplayValueExt(a*(1+b)),c.title||c.name]))}},getCraftAllCount:function(a){a=this.getCraft(a);var b=this.getCraftPrice(a);
return Math.floor(this._getCraftAllCountInternal(a,b))},_getCraftAllCountInternal:function(a,b){a=Number.MAX_VALUE;for(var c=b.length-1;0<=c;c--){var d=this.game.resPool.get(b[c].name).value;d=Infinity==d?Number.MAX_VALUE:d;d/=b[c].val;d<a&&(a=d)}return a},craftAll:function(a){var b=this.getCraftAllCount(a);if(0<b&&b<Number.MAX_VALUE){var c=this.game.getResCraftRatio(a),d=this.game.resPool.get(a);this.craft(a,b,!1,!1,!0)&&this.game.msg($I("workshop.crafted.msg",[this.game.getDisplayValueExt(b*(1+
c)),d.title||a]),null,"craft")}},clearEngineers:function(){for(var a=this.crafts.length-1;0<=a;a--)this.crafts[a].value=0;this.game.village.sim.clearCraftJobs()},update:function(){this.fastforward(1/this.game.calendar.ticksPerDay)},fastforward:function(a){a*=this.game.calendar.ticksPerDay;this.effectsBase.oilMax=Math.floor(500*this.game.resPool.get("tanker").value);var b=this.game.bld.getEffect("scienceMax");this.game.ironWill&&(b*=10);if(this.game.prestige.getPerk("codexLeviathanianus").researched){var c=
this.game.religion.getTU("blackLibrary");c=1+c.val*(c.effects.compendiaTTBoostRatio+this.game.getEffect("blackLibraryBonus"));b*=1+.05*c*this.game.religion.transcendenceTier}b+=this.game.bld.getEffect("scienceMaxCompendia");c=Math.floor(10*this.game.resPool.get("compedium").value);this.effectsBase.scienceMax=Math.min(c,b);b=Math.floor(this.game.resPool.get("manuscript").value);this.effectsBase.cultureMax=this.game.getUnlimitedDR(b,.01);this.effectsBase.cultureMax*=1+this.game.getEffect("cultureFromManuscripts");
0>this.game.village.getFreeEngineers()&&this.clearEngineers();this.craftByEngineers(a)},craftByEngineers:function(a){for(var b=0;b<this.crafts.length;b++){var c=this.crafts[b],d=this.getCraftPrice(c);c.isLimited=this.game.resPool.isStorageLimited(d);if(0!=c.value){var e=Math.max(c.progress,0)+a*this.getEffectEngineer(c.name,!1);1<=e?(e=Math.min(e,this._getCraftAllCountInternal(c,d)),d=Math.floor(e),!c.isLimited&&this.craft(c.name,d,!0)&&(c.progress=e-d)):this.game.resPool.hasRes(d,e)?(c.isLimitedAmt=
!1,c.progress=e):c.isLimitedAmt=!0}}},unlock:function(a){a.researched=!0;a.handler&&a.handler(this.game);a.unlocks&&this.game.unlock(a.unlocks);a.upgrades&&this.game.upgrade(a.upgrades)},unlockAll:function(){for(var a in this.upgrades)this.unlock(this.upgrades[a]);for(a in this.crafts)this.crafts[a].unlocked=!0;for(a in this.zebraUpgrades)this.zebraUpgrades[a].unlocked=!0;this.game.msg($I("workshop.all.upgrades.unlocked"))}});
dojo.declare("com.nuclearunicorn.game.ui.UpgradeButtonController",com.nuclearunicorn.game.ui.BuildingNotStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.tooltipName=!0;a.simplePrices=!1;return a},getMetadata:function(a){a.metaCached||(a.metaCached=this.game.workshop.get(a.options.id));return a.metaCached},getPrices:function(a){return this.game.village.getEffectLeader("scientist",this.inherited(arguments))},updateVisible:function(a){var b=a.metadata;a.visible=b.unlocked;
b.researched&&this.game.workshop.hideResearched&&(a.visible=!1)}});
dojo.declare("com.nuclearunicorn.game.ui.CraftButtonController",com.nuclearunicorn.game.ui.ButtonModernController,{defaults:function(){var a=this.inherited(arguments);a.hasResourceHover=!0;a.simplePrices=!1;return a},initModel:function(a){var b=this.inherited(arguments);b.craft=this.getCraft(b);return b},getCraft:function(a){return this.game.workshop.getCraft(a.options.craft)},updateVisible:function(a){a.visible=a.craft.unlocked},getName:function(a){var b=a.craft;if(this.game.science.get("mechanization").researched&&
0!=b.value){var c=this.game.toDisplayPercentage(b.progress,0,!0);99<c&&(c=99);return a.craft.label+" ("+b.value+") ["+c+"%]"}return this.inherited(arguments)},getDescription:function(a){var b=a.craft;a=b.description;var c=this.game.getResCraftRatio(b.name);"wood"!=b.name&&(c-=this.game.getCraftRatio());0<c&&(a+="<br /><br />"+$I("workshop.craftBtn.desc.effectivenessBonus",[this.game.getDisplayValueExt(100*c,!1,!1,0)]));this.game.science.get("mechanization").researched&&(a+="<br /><br />"+$I("workshop.craftBtn.desc.tier")+
": "+b.tier,c=this.game.getEffect("t"+b.tier+"CraftRatio")||1,1!=c&&(a+="<br />"+$I("workshop.craftBtn.desc.craftRatio")+": "+this.game.getDisplayValueExt((100*(c-1)).toFixed(),!0)+"%"),1!=b.progressHandicap&&(c=this.game.getDisplayValueExt((-100*(1-1/b.progressHandicap)).toFixed(2),!0),a+="<br />"+$I("workshop.craftBtn.desc.progressHandicap")+": "+c+"%"),0!=b.value&&(b=(1/(this.game.workshop.getEffectEngineer(b.name,!1)*this.game.getTicksPerSecondUI())).toFixed(0),a+="<br />=> "+$I("workshop.craftBtn.desc.countdown",
[b])));return a},assignCraftJob:function(a,b){a=a.craft;b=this.game.village.getFreeEngineers()>b?b:this.game.village.getFreeEngineers();for(var c=0,d=0;d<b;d++)if(this.game.village.sim.assignCraftJob(a))c+=1;else break;a.value+=c},unassignCraftJob:function(a,b){a=a.craft;b=a.value>b?b:a.value;a.value-=b;for(var c=0;c<b;c++)this.game.village.sim.unassignCraftJob(a)},fetchModel:function(a){var b=this.inherited(arguments),c=this;this.game.science.get("mechanization").researched?this.controllerOpts.compactStyle?
(b.unassignCraftLinks=[{id:"unassign",title:"-",handler:function(){c.unassignCraftJob(b,1)},enabled:!0},{id:"unassign25",title:"-25",handler:function(){c.unassignCraftJob(b,25)},enabled:!0}],b.assignCraftLinks=[{id:"assign",title:"+",handler:function(){c.assignCraftJob(b,1)},enabled:!0},{id:"assign25",title:"+25",handler:function(){c.assignCraftJob(b,25)},enabled:!0}]):(b.unassignCraftLinks=[{id:"unassign",title:"[&ndash;]",handler:function(){c.unassignCraftJob(b,1)},enabled:!0},{id:"unassign5",title:"[-5]",
handler:function(){c.unassignCraftJob(b,5)},enabled:!0},{id:"unassign25",title:"[-25]",handler:function(){c.unassignCraftJob(b,25)},enabled:!0}],b.assignCraftLinks=[{id:"assign",title:"[+]",handler:function(){c.assignCraftJob(b,1)},enabled:!0},{id:"assign5",title:"[+5]",handler:function(){c.assignCraftJob(b,5)},enabled:!0},{id:"assign25",title:"[+25]",handler:function(){c.assignCraftJob(b,25)},enabled:!0}]):(b.assignCraftLinks=[],b.unassignCraftLinks=[]);return b},buyItem:function(a,b,c){this.game.workshop.craft(a.craft.name,
1);c(!0)}});
dojo.declare("com.nuclearunicorn.game.ui.CraftButton",com.nuclearunicorn.game.ui.ButtonModern,{craftName:null,constructor:function(a,b){this.craftName=a.craft},setEnabled:function(a){this.inherited(arguments);dojo.removeClass(this.domNode,"bldEnabled");dojo.removeClass(this.domNode,"bldlackResConvert");var b=this.model.craft;0<b.value&&(b.isLimitedAmt?dojo.addClass(this.domNode,"bldlackResConvert"):dojo.addClass(this.domNode,"bldEnabled"))},renderLinks:function(){this.model.unassignCraftLinks&&(this.unassignCraftLinks=
this.addLinkList(this.model.unassignCraftLinks));this.model.assignCraftLinks&&(this.assignCraftLinks=this.addLinkList(this.model.assignCraftLinks))}});
dojo.declare("com.nuclearunicorn.game.ui.ZebraUpgradeButtonController",com.nuclearunicorn.game.ui.BuildingNotStackableBtnController,{defaults:function(){var a=this.inherited(arguments);a.tooltipName=!0;a.simplePrices=!1;return a},getMetadata:function(a){a.metaCached||(a.metaCached=this.game.workshop.getZebraUpgrade(a.options.id));return a.metaCached},getPrices:function(a){return this.game.village.getEffectLeader("scientist",this.inherited(arguments))},updateVisible:function(a){var b=a.metadata;a.visible=
b.unlocked?!0:!1;b.researched&&this.game.workshop.hideResearched&&(a.visible=!1)}});
dojo.declare("com.nuclearunicorn.game.ui.tab.Workshop",com.nuclearunicorn.game.ui.tab,{tdTop:null,craftBtns:null,resTd:null,constructor:function(a,b){this.game=b;this.craftBtns=[]},render:function(a){this.craftBtns=[];this.buttons=[];var b=dojo.create("div",{style:{float:"left"}},a);dojo.create("span",{innerHTML:$I("workshop.craft.effectiveness",[this.game.getDisplayValueExt(100*this.game.getCraftRatio(),!1,!1,0)])},b);b=dojo.create("div",{style:{height:"20px"}},a);b=dojo.create("div",{style:{float:"right"}},
b);var c=dojo.create("input",{id:"toggleResearched",type:"checkbox",checked:this.game.workshop.hideResearched},b);dojo.connect(c,"onclick",this,function(){this.game.workshop.hideResearched=!this.game.workshop.hideResearched;dojo.empty(a);this.render(a)});dojo.create("label",{innerHTML:$I("workshop.toggleResearched.label"),for:"toggleResearched"},b);var d=(new com.nuclearunicorn.game.ui.Panel($I("workshop.upgradePanel.label"),this.game.workshop)).render(a);for(b=0;b<this.game.workshop.upgrades.length;b++)c=
this.createBtn(this.game.workshop.upgrades[b]),c.updateEnabled(),c.updateVisible(),this.addButton(c),c.render(d);c=new com.nuclearunicorn.game.ui.Panel($I("workshop.craftPanel.label"),this.game.workshop);d=c.render(a);var e=dojo.create("table",{},d);dojo.create("tr",{},e);d=dojo.create("td",{},e);this.tdTop=dojo.create("td",{colspan:2,style:{cursor:"pointer"}},d);UIUtils.attachTooltip(this.game,this.tdTop,5,0,function(){return $I("workshop.craftPanel.header.tooltip")});var g=this.game.workshop.crafts,
h=new com.nuclearunicorn.game.ui.CraftButtonController(this.game);for(b=0;b<g.length;b++){var f=g[b];f=new com.nuclearunicorn.game.ui.CraftButton({name:f.label,description:f.description,craft:f.name,prices:this.game.workshop.getCraftPrice(f),controller:h},this.game);f.render(d);this.craftBtns.push(f)}b=new com.nuclearunicorn.game.ui.Panel($I("workshop.zebraUpgradesPanel.label"),this.game.workshop);if(0<this.game.bld.getBuildingExt("zebraWorkshop").meta.val)for(d=b.render(a),b=0;b<this.game.workshop.zebraUpgrades.length;b++)g=
this.createZebraUpgradeBtn(this.game.workshop.zebraUpgrades[b]),g.updateEnabled(),g.updateVisible(),this.addButton(g),g.render(d);this.resTd=d=dojo.create("td",{className:"craftStuffPanel",style:{paddingLeft:"50px"}},e);this.renderResources(this.resTd);this.game.science.get("construction").researched||c.setVisible(!1);this.update()},renderResources:function(a){dojo.empty(a);dojo.create("span",{innerHTML:$I("workshop.craftPanel.counts.label")+":"},a);a=dojo.create("table",{style:{paddingTop:"20px"}},
a);for(var b=this.game.resPool.resources,c=0;c<b.length;c++){var d=b[c];if(d.craftable&&d.value){var e=dojo.create("tr",{},a);dojo.create("td",{innerHTML:d.title||d.name+":"},e);dojo.create("td",{innerHTML:this.game.getDisplayValueExt(d.value)},e)}}},createBtn:function(a){var b=new com.nuclearunicorn.game.ui.UpgradeButtonController(this.game);return new com.nuclearunicorn.game.ui.BuildingResearchBtn({id:a.name,controller:b},this.game)},createZebraUpgradeBtn:function(a){var b=new com.nuclearunicorn.game.ui.ZebraUpgradeButtonController(this.game);
return new com.nuclearunicorn.game.ui.BuildingResearchBtn({id:a.name,controller:b},this.game)},update:function(){this.inherited(arguments);for(var a=this.craftBtns.length-1;0<=a;a--){var b=this.craftBtns[a];b.update();0<b.model.craft.value?dojo.addClass(b.domNode,"craftOn"):dojo.removeClass(b.domNode,"craftOn")}this.resTd&&this.renderResources(this.resTd);this.tdTop&&this.game.science.get("mechanization").researched?this.tdTop.innerHTML=$I("workshop.craftPanel.header.freeEngineers")+": "+this.game.village.getFreeEngineers()+
" / "+this.game.village.getWorkerKittens("engineer"):this.tdTop.innerHTML="";this.updateTab()},updateTab:function(){this.tabName=$I("tab.name.workshop");var a=this.game.village.getFreeEngineers();0<a&&(this.tabName+=" <span class='genericWarning'>("+this.game.getDisplayValueExt(a,!1,!1,0)+")</span>");this.domNode&&(this.domNode.innerHTML=this.tabName)}});
