window.LCstorage=window.localStorage;document.all&&!window.localStorage&&(window.LCstorage={},window.LCstorage.removeItem=function(){});dojo.declare("com.nuclearunicorn.core.Control",null,{});
dojo.declare("com.nuclearunicorn.core.TabManager",com.nuclearunicorn.core.Control,{effectsCachedExisting:null,meta:null,panelData:null,constructor:function(){this.effectsCachedExisting={};this.meta=[];this.panelData={}},registerPanel:function(a,b){this.panelData[a]||(this.panelData[a]={collapsed:b.collapsed});b.collapsed=this.panelData[a].collapsed;dojo.connect(b,"onToggle",this,function(c){this.panelData[a].collapsed=c})},registerMeta:function(a,b,c){a?"research"==a?this.meta.push({meta:b,provider:{getEffect:function(d,
e){return d.researched&&d.effects?d.effects[e]:0}}}):"stackable"==a&&this.meta.push({meta:b,provider:{getEffect:function(d,e){return d.effects?d.effects[e]*d.on:0}}}):this.meta.push({meta:b,provider:c})},setEffectsCachedExisting:function(){for(var a=0;a<this.meta.length;a++)if(this.meta[a].meta)for(var b=0;b<this.meta[a].meta.length;b++)for(var c in this.meta[a].meta[b].effects)this.effectsCachedExisting[c]=0;if("object"==typeof this.effectsBase)for(c in this.effectsBase)this.effectsCachedExisting[c]=
0},updateEffectCached:function(){var a=this.effectsBase;a&&=this.game.resPool.addBarnWarehouseRatio(a);for(var b=0;b<this.meta.length;b++)this.updateMetaEffectCached(this.meta[b]);for(var c in this.effectsCachedExisting){var d=0;for(b=0;b<this.meta.length;b++)d+=this.getMetaEffect(c,this.meta[b]);this._hasLimitedDiminishingReturn(c)&&0!==d&&(d=this.game.getLimitedDR(d,1));a&&a[c]&&(d+=a[c]);this.game.globalEffectsCached[c]="number"==typeof this.game.globalEffectsCached[c]?this.game.globalEffectsCached[c]+
d:d}},updateMetaEffectCached:function(a){for(var b=0;b<a.meta.length;b++){var c=a.meta[b];c.totalEffectsCached={};for(var d in this.effectsCachedExisting){var e=a.provider?a.provider.getEffect(c,d)||0:c.effects[d]||0;c.totalEffectsCached[d]=e}}},_hasLimitedDiminishingReturn:function(a){return"catnipDemandRatio"==a||"fursDemandRatio"==a||"ivoryDemandRatio"==a||"spiceDemandRatio"==a||"unhappinessRatio"==a},getMetaEffect:function(a,b){var c=0;if(!b.meta)return 0;for(var d=0;d<b.meta.length;d++){var e=
b.meta[d],f=0;e.totalEffectsCached&&(f=e.totalEffectsCached[a]||0);c+=f}return c||0},getMeta:function(a,b){for(var c=0;c<b.length;c++){var d=b[c];if(d.name==a)return d}console.error("Could not find metadata for ",a,"in",b)},loadMetadata:function(a,b,c){if(b)for(c=0;c<b.length;c++){var d=b[c];if(null!=d){var e=this.getMeta(d.name,a);if(e)for(var f in d)"name"!=f&&(e.hasOwnProperty(f)||console.warn("Can't find elem."+f+" in",e),void 0!==d[f]&&(null!=d[f]&&"object"==typeof d[f]?this.loadMetadata(e[f],
d[f]):e[f]="value"==f?null==d[f]?Infinity:d[f]:d[f]))}}else console.trace(),console.warn("Unable to load metadata table '"+c+"', save record is empty")},filterMetadata:function(a,b){for(var c=[],d=0;d<a.length;d++){for(var e={},f=0;f<b.length;f++){var g=b[f];e[g]=a[d][g]}c.push(e)}return c},resetStateStackable:function(a){a.val=0;a.on=0;"undefined"==a.noStackable&&(a.noStackable=!1);void 0!=a.isAutomationEnabled&&(a.isAutomationEnabled=null);void 0!=a.lackResConvert&&(a.togglable=!0);for(var b in a.effects)if("energyConsumption"==
b||"magnetoRatio"==b||"productionRatio"==b)a.togglable="oilWell"==a.name||"biolab"==a.name||"chronosphere"==a.name||"aiCore"==a.name?!1:!0},resetStateResearch:function(){}});
dojo.declare("com.nuclearunicorn.game.log.Console",null,{static:{filters:{astronomicalEvent:{title:$I("console.filter.astronomicalEvent"),enabled:!0,unlocked:!1},hunt:{title:$I("console.filter.hunt"),enabled:!0,unlocked:!1},trade:{title:$I("console.filter.trade"),enabled:!0,unlocked:!1},craft:{title:$I("console.filter.craft"),enabled:!0,unlocked:!1},workshopAutomation:{title:$I("console.filter.workshopAutomation"),enabled:!0,unlocked:!1},meteor:{title:$I("console.filter.meteor"),enabled:!0,unlocked:!1},
ivoryMeteor:{title:$I("console.filter.ivoryMeteor"),enabled:!0,unlocked:!1},unicornRift:{title:$I("console.filter.unicornRift"),enabled:!0,unlocked:!1},unicornSacrifice:{title:$I("console.filter.unicornSacrifice"),enabled:!0,unlocked:!1},alicornRift:{title:$I("console.filter.alicornRift"),enabled:!0,unlocked:!1},alicornSacrifice:{title:$I("console.filter.alicornSacrifice"),enabled:!0,unlocked:!1},alicornCorruption:{title:$I("console.filter.alicornCorruption"),enabled:!0,unlocked:!1},tcShatter:{title:$I("console.filter.tcShatter"),
enabled:!0,unlocked:!1},tcRefine:{title:$I("console.filter.tcRefine"),enabled:!0,unlocked:!1},faith:{title:$I("console.filter.faith"),enabled:!0,unlocked:!1},elders:{title:$I("console.filter.elders"),enabled:!0,unlocked:!1},blackcoin:{title:$I("console.filter.blackcoin"),enabled:!0,unlocked:!1}}},messages:null,maxMessages:40,messageIdCounter:0,ui:null,game:null,constructor:function(a){this.game=a;this.messages=[];this.filters=dojo.clone(this.static.filters)},msg:function(a,b,c,d){if(c&&this.filters[c]){var e=
this.filters[c];if(!e.unlocked)e.unlocked=!0,this.ui.renderFilters();else if(!e.enabled)return}e=this.game.science.get("calendar").researched;a={text:a,type:b,tag:c,noBullet:d,id:"consoleMessage_"+this.messageIdCounter++,hasCalendarTech:e,year:e?this.game.calendar.year.toLocaleString():null,seasonTitle:e?this.game.calendar.getCurSeasonTitle():null,seasonTitleShorten:e?this.game.calendar.getCurSeasonTitleShorten():null};this.messages.push(a);this.messages.length>this.maxMessages&&this.messages.shift();
this.ui.renderConsoleLog();this.ui.notifyLogEvent(a);return a},clear:function(){this.messages=[];this.ui.renderConsoleLog()},resetState:function(){for(var a in this.filters){var b=this.filters[a];b.unlocked=b.defaultUnlocked||!1;b.enabled=!0}this.ui.renderFilters()},save:function(a){var b={},c;for(c in this.filters){var d=this.filters[c];b[c]={unlocked:d.unlocked,enabled:d.enabled}}a.console={filters:b}},load:function(a){if(a.console&&a.console.filters)for(var b in a.console.filters){var c=a.console.filters[b];
this.filters[b]&&(this.filters[b].unlocked=c.unlocked,this.filters[b].enabled=c.enabled)}}});
dojo.declare("com.nuclearunicorn.game.ui.ButtonController",null,{game:null,controllerOpts:null,constructor:function(a,b){this.game=a;if(!this.game)throw Error("The game instance must be defined for the controller");this.controllerOpts=b||{}},fetchModel:function(a){var b=this.initModel(a);b.name=this.getName(b);b.description=this.getDescription(b);b.prices=this.getPrices(b);b.priceRatio=a.priceRatio;b.handler=a.handler;b.twoRow=a.twoRow;this.updateEnabled(b);this.updateVisible(b);return b},fetchExtendedModel:function(a){var b=
a.prices,c=[];if(b)for(var d=0;d<b.length;d++)c.push(this.createPriceLineModel(a,b[d]));a.priceModels=c},initModel:function(a){var b=this.defaults();b.options=a;return b},defaults:function(){return{name:"",description:"",visible:!0,enabled:!0,handler:null,prices:null,priceRatio:null,twoRow:null,refundPercentage:.5,highlightUnavailable:!1,resourceIsLimited:"",multiplyEffects:!1}},createPriceLineModel:function(a,b){a=this.game.resPool.get(b.name);return{title:a.title||a.name,name:b.name,val:b.val,progress:a.value/
b.val,displayValue:this.game.getDisplayValueExt(b.val)}},hasResources:function(a,b){b||=this.getPrices(a);return this.game.resPool.hasRes(b)},updateEnabled:function(a){a.enabled=this.hasResources(a,a.prices);if(a.highlightUnavailable=this.game.opts.highlightUnavailable){var b=this.game.resPool.isStorageLimited(a.prices);a.resourceIsLimited=b}},updateVisible:function(a){this.controllerOpts&&this.controllerOpts.updateVisible&&this.controllerOpts.updateVisible.apply(this,arguments)},getPrices:function(a){return a.options.prices||
[]},getName:function(a){return this.controllerOpts.getName?this.controllerOpts.getName.apply(this,arguments):a.options.name},getDescription:function(a){return a.options.description},adjustPrice:function(a,b){a=this.getPrices(a);if(a.length)for(var c=0;c<a.length;c++){var d=a[c];d.val*=b}this.game.render()},rejustPrice:function(a,b){a=a.prices;if(a.length)for(var c=0;c<a.length;c++){var d=a[c];d.val/=b}this.game.render()},payPrice:function(a){this.game.resPool.payPrices(a.prices);a.prices=this.getPrices(a)},
clickHandler:function(a,b){a.handler.apply(this,[a,b])},buyItem:function(a,b,c){a.enabled&&this.hasResources(a)&&(this.clickHandler(a,b),this.payPrice(a),a.priceRatio&&this.adjustPrice(a.priceRatio),c(!0));c(!1)},refund:function(a){if(a.prices.length)for(var b=0;b<a.prices.length;b++){var c=a.prices[b];this.game.resPool.get(c.name).isRefundable(this.game)&&!c.isTemporary&&this.game.resPool.addResEvent(c.name,c.val*a.refundPercentage)}else console.warn("unable to refund building, no prices specified in metadata :O")}});
dojo.declare("com.nuclearunicorn.game.ui.Button",com.nuclearunicorn.core.Control,{model:null,controller:null,game:null,domNode:null,container:null,tab:null,buttonTitle:null,constructor:function(a,b){this.game=b;this.setOpts(a);this.init()},setOpts:function(a){this.id=a.id;this.controller=a.controller;if(!this.controller)throw Error("Controller must be defined for the button");this.opts=a},init:function(){},updateVisible:function(){this.domNode&&(this.model.visible?"none"===this.domNode.style.display&&
(this.domNode.style.display="block"):"block"===this.domNode.style.display&&(this.domNode.style.display="none"))},updateEnabled:function(){if(this.domNode){var a=dojo.hasClass(this.domNode,"disabled"),b=dojo.hasClass(this.domNode,"limited");this.model.enabled?(a&&dojo.removeClass(this.domNode,"disabled"),b&&dojo.removeClass(this.domNode,"limited")):(a||dojo.addClass(this.domNode,"disabled"),!b&&this.model.resourceIsLimited&&dojo.addClass(this.domNode,"limited"))}},update:function(){this.model=this.controller.fetchModel(this.opts);
this.updateEnabled();this.updateVisible();this.buttonTitle&&this.buttonTitle.innerHTML!=this.model.name&&(this.buttonTitle.innerHTML=this.model.name)},render:function(a){this.model=this.controller.fetchModel(this.opts);this.container=a;this.domNode=dojo.create("div",{style:{position:"relative",display:this.model.visible?"block":"none"}},a);this.model.twoRow&&(dojo.style(this.domNode,"marginLeft","auto"),dojo.style(this.domNode,"marginRight","auto"));this.buttonContent=dojo.create("div",{className:"btnContent",
title:this.model.description},this.domNode);this.buttonTitle=dojo.create("span",{innerHTML:this.model.name,className:"btnTitle",style:{}},this.buttonContent);this.domNode.className="btn nosel";this.model.enabled||(this.domNode.className+=" disabled");this.updateVisible();dojo.connect(this.domNode,"onclick",this,"onClick");this.afterRender()},animate:function(){var a=jQuery(this.domNode);a.animate({opacity:.5},70,function(){a.animate({opacity:1},70)})},onClick:function(a){this.animate();var b=this;
this.controller.buyItem(this.model,a,function(c){c&&b.update()})},afterRender:function(){var a=this.model.prices;if(a.length&&!this.tooltip){for(var b=dojo.create("div",{classname:"button_tooltip",style:{display:"none",border:"1px solid black",marginLeft:"4px",padding:"5px",position:"absolute",left:"170px",top:"-1px",width:"120px"}},this.domNode),c=[],d=0;d<a.length;d++){var e=a[d],f=dojo.create("div",{style:{overflow:"hidden"}},b),g=dojo.create("span",{innerHTML:e.title,style:{float:"left"}},f);
e=dojo.create("span",{innerHTML:e.displayValue,style:{float:"right"}},f);c.push({name:g,price:e})}dojo.connect(this.domNode,"onmouseover",this,dojo.partial(function(h){dojo.style(h,"display","")},b));dojo.connect(this.domNode,"onmouseout",this,dojo.partial(function(h){dojo.style(h,"display","none")},b));this.tooltip=b;this.tooltipPricesNodes=c}},addLink:function(a){var b=dojo.create("a",{href:"#",innerHTML:a.title,className:(4<a.title.length?"small":"")+(a.cssClass?" "+a.cssClass:""),style:{paddingLeft:"2px",
float:"right",cursor:"pointer"}},null);a=dojo.connect(b,"onclick",this,dojo.partial(function(c,d){d.stopPropagation();d.preventDefault();var e=this;this.animate();dojo.hitch(this,c,d,function(f){f&&e.update()})()},a.handler));dojo.place(b,this.buttonContent);return{link:b,linkHandler:a}},addLinkList:function(a){var b={},c=dojo.create("div",{style:{float:"right"}},this.buttonContent),d=dojo.create("div",{className:"linkContent",style:{display:"none",position:"absolute",float:"right",marginTop:"35px",
zIndex:"100"}},c);if(!a.length)return b;var e=dojo.create("a",{href:"#",className:a[0].id?a[0].id+"Link":"",style:{display:"block",float:"right"},innerHTML:a[0].title,title:a[0].alt||a[0].title},c);d.style.left=e.offsetLeft+"px";dojo.connect(e,"onclick",this,dojo.partial(function(f,g){g.stopPropagation();g.preventDefault();dojo.hitch(this,f)();this.update()},a[0].handler));b[a[0].id]={link:e};if(1>=a.length)return b;dojo.connect(c,"onmouseover",this,dojo.partial(function(f){dojo.style(f,"display",
"block")},d));dojo.connect(c,"onmouseout",this,dojo.partial(function(f){dojo.style(f,"display","none")},d));for(c=1;c<a.length;c++)e=dojo.create("a",{href:"#",innerHTML:a[c].title,title:a[c].alt||a[c].title,className:"dropdown-link",style:{display:"block"}},d),dojo.connect(e,"onclick",this,dojo.partial(function(f,g){g.stopPropagation();g.preventDefault();dojo.hitch(this,f)();this.update()},a[c].handler)),b[a[c].id]={link:e};return b}});
dojo.declare("com.nuclearunicorn.game.ui.ButtonModernController",com.nuclearunicorn.game.ui.ButtonController,{defaults:function(){var a=this.inherited(arguments);a.simplePrices=!0;a.hasResourceHover=!1;a.tooltipName=!1;return a},getFlavor:function(a){},getEffects:function(a){},getTotalEffects:function(a){},getNextEffectValue:function(a,b){},createPriceLineModel:function(a,b){return this._createPriceLineModel(b,a.simplePrices)},_createPriceLineModel:function(a,b,c){var d=this.game.resPool.get(a.name),
e=d.value>=a.val,f=d.maxValue&&(a.val>d.maxValue&&!c||a.baseVal>d.maxValue),g=f?"*":"";g=e||b?this.game.getDisplayValueExt(a.val):this.game.getDisplayValueExt(d.value)+" / "+this.game.getDisplayValueExt(a.val)+g;var h=this.game.getResourcePerTick(d.name,!0),k=0;!e&&0<h&&!b&&(k=(a.val-d.value)/(h*this.game.getTicksPerSecondUI()),1<=k&&(g+=" ("+this.game.toDisplaySeconds(k)+")"));c||=0;f={title:d.title||d.name,name:a.name,val:a.val,hasResources:e,displayValue:g,indent:c,eta:k,hasLimitIssue:f};if(!e&&
d.craftable&&!b&&"wood"!=d.name&&(g=this.game.workshop.getCraft(d.name),g.unlocked)){e=this.game.getResCraftRatio(d.name);f.title="+ "+f.title;f.children=[];g=this.game.workshop.getCraftPrice(g);for(var l in g)h=Math.ceil(g[l].val*(a.val-d.value)/(1+e)),k=h%g[l].val,0!=k&&(h+=g[l].val-k),h=this._createPriceLineModel({name:g[l].name,val:h,baseVal:g[l].val},b,c+1),f.children.push(h)}return f},fetchExtendedModel:function(a){this.inherited(arguments);a.flavor=this.getFlavor(a);this.updateEffectModels(a)},
updateEffectModels:function(a){var b=this.getEffects(a);a.effectModels=[];if(b&&0!==Object.keys(b).length){var c=b,d=a.multiplyEffects&&this.game.ui.isEffectMultiplierEnabled();d&&(c=this.getTotalEffects(a)||b);for(var e in b){var f=this.game.getEffectMeta(e);if("hidden"!==f.type&&(!f.resName||this.game.resPool.get(f.resName).unlocked)){b=c[e];if(!d&&"nonProportional"!==f.calculation){var g=this.getNextEffectValue(a,e);g&&(b=g*(a.metadata.on+1)-b*a.metadata.on)}if(b){g=f.title;if("Max"===e.substr(-3)||
"MaxChallenge"==e.substr(-12)){var h=this.game.resPool.get(f.resName||e.slice(0,-3));h&&(b=this.game.resPool.addResMaxRatios(h,b))}"perTick"===f.type&&this.game.opts.usePerSecondValues?(f=Math.abs(b*this.game.ticksPerSecond),.001<=f?(f=.01>f?3:2,b=this.game.getDisplayValueExt(b*this.game.ticksPerSecond,!1,!1,f)+"/"+$I("unit.sec")):b=this.game.getDisplayValueExt(b*this.game.ticksPerSecond*3600,!1,!1,2)+"/"+$I("unit.h")):b="perDay"===f.type?this.game.getDisplayValueExt(b)+"/"+$I("unit.day"):"perYear"===
f.type?this.game.getDisplayValueExt(b)+"/"+$I("unit.year"):"ratio"===f.type?this.game.toDisplayPercentage(b,2,!1)+"%":"integerRatio"===f.type?this.game.getDisplayValueExt(b)+"%":"energy"===f.type?this.game.getDisplayValueExt(b)+$I("unit.watt"):this.game.getDisplayValueExt(b);a.effectModels.push({displayEffectName:g,displayEffectValue:b})}}}}},isPrecraftAvailable:function(a){for(var b in a.prices)if(this.game.resPool.get(a.prices[b].name).craftable)return!0;return!1},precraft:function(a){this.fetchExtendedModel(a);
for(var b in a.priceModels)this._precraftRes(a.priceModels[b])},_precraftRes:function(a){if(a.children)for(var b in a.children)this._precraftRes(a.children[b]);b=this.game.resPool.get(a.name);b.craftable&&"wood"!=b.name&&this.game.workshop.getCraft(b.name).unlocked&&(a=a.val-b.value,0<a&&(a/=1+this.game.getResCraftRatio(b.name),this.game.workshop.craft(b.name,a,!1,!0)))}});
ButtonModernHelper={getTooltipHTML:function(a,b){a.fetchExtendedModel(b);var c=dojo.create("div",{className:"tooltip-inner"},null);b.tooltipName&&dojo.create("div",{innerHTML:b.name,className:"tooltip-divider"},c);var d=dojo.create("div",{innerHTML:b.description,className:"desc"},c);b.metadata&&void 0!==b.metadata.isAutomationEnabled&&dojo.create("div",{innerHTML:b.metadata.isAutomationEnabled?$I("btn.aon.tooltip"):$I("btn.aoff.tooltip"),className:"desc small"+(b.metadata.isAutomationEnabled?" auto-on":
" auto-off")},c);b.metadata&&b.metadata.effects&&0<b.metadata.effects.cathPollutionPerTickProd&&a.game.science.get("chemistry").researched&&!a.game.opts.disablePollution&&dojo.create("div",{innerHTML:$I("btn.pollution.tooltip"),className:"desc small pollution"},c);b.metadata&&b.metadata.almostLimited&&dojo.create("div",{innerHTML:$I("btn.almostlimited.tooltip"),className:"desc small almostlimited"},c);a=b.priceModels;var e=b.effectModels,f=b.flavor;a&&""!=a||e||f&&""!=f?(dojo.style(d,"paddingBottom",
"8px"),a&&a.length&&(dojo.style(d,"borderBottom","1px solid gray"),ButtonModernHelper.renderPrices(c,b)),e&&ButtonModernHelper.renderEffects(c,e),f&&""!=f&&dojo.create("div",{innerHTML:f,className:"flavor",style:{paddingTop:"20px",fontSize:"12px",fontStyle:"italic"}},c)):dojo.style(d,"paddingBottom","4px");return c.outerHTML},renderPrices:function(a,b){b=b.priceModels;if(b.length)for(var c=0;c<b.length;c++)ButtonModernHelper._renderPriceLine(a,b[c])},_renderPriceLine:function(a,b){var c=dojo.create("div",
{className:"price-block",style:{overflow:"hidden"}},a),d=dojo.create("span",{innerHTML:b.title,style:{float:"left",paddingRight:"10px"}},c);c=dojo.create("span",{innerHTML:b.displayValue,className:b.hasResources?"":"noRes",style:{float:"right"}},c);if(b.children&&b.children.length)for(var e=0;e<b.children.length;e++){for(var f=this._renderPriceLine(a,b.children[e]),g=0;g<b.children[e].indent;++g)f.name.innerHTML="&nbsp;&nbsp;&nbsp;"+f.name.innerHTML;f.name.className="rawRes"}return{name:d,price:c}},
renderEffects:function(a,b,c){if(b&&b.length)for(c||dojo.create("div",{innerHTML:$I("res.effects")+":",className:"tooltip-divider resEffectsTxt",style:{textAlign:"center",width:"100%",borderBottom:"1px solid gray",paddingBottom:"4px",marginBottom:"8px"}},a),c=0;c<b.length;c++){var d=b[c];dojo.create("div",{innerHTML:d.displayEffectName+": "+d.displayEffectValue,className:"effectName"},a)}}};
dojo.declare("com.nuclearunicorn.game.ui.ButtonModern",com.nuclearunicorn.game.ui.Button,{afterRender:function(){dojo.addClass(this.domNode,"modern");this.renderLinks();this.attachTooltip(dojo.partial(this.getTooltipHTML(),this.controller,this.model));this.buttonContent.title="";this.model.hasResourceHover&&(dojo.connect(this.domNode,"onmouseover",this,dojo.hitch(this,function(){this.game.setSelectedObject(this.getSelectedObject())})),dojo.connect(this.domNode,"onmouseout",this,dojo.hitch(this,function(){this.game.clearSelectedObject()})))},
getTooltipHTML:function(){return ButtonModernHelper.getTooltipHTML},attachTooltip:function(a){UIUtils.attachTooltip(this.game,this.domNode,0,300,a)},updateTooltip:function(a,b,c){b.innerHTML=dojo.hitch(this,c)()},renderLinks:function(){},updateLink:function(a,b){if(a){if(!b)return this.game.ui.render;a.link.textContent=b.title;b.cssClass&&(a.link.className=b.cssClass);b.tooltip&&(a.link.title=b.tooltip);dojo.style(a.link,"display",void 0===b.visible||b.visible?"":"none")}},getSelectedObject:function(){return this.model}});
dojo.declare("com.nuclearunicorn.game.ui.BuildingBtnController",com.nuclearunicorn.game.ui.ButtonModernController,{initModel:function(a){var b=this.inherited(arguments);b.metadata=this.getMetadata(b);return b},fetchModel:function(a){var b=this.inherited(arguments);b.hasSellLink=this.hasSellLink(b);b.showSellLink=b.metadata&&b.metadata.val&&b.hasSellLink;var c=this;"undefined"!=typeof b.metadata.togglableOnOff&&(b.togglableOnOffLink={title:b.metadata.on?$I("btn.on.minor"):$I("btn.off.minor"),tooltip:b.metadata.on?
$I("btn.on.tooltip"):$I("btn.off.tooltip"),cssClass:b.metadata.on?"bld-on":"bld-off",enabled:0<b.metadata.val,handler:function(d){c.handleTogglableOnOffClick(b)}});"undefined"!=typeof b.metadata.isAutomationEnabled&&null!==b.metadata.isAutomationEnabled&&(b.toggleAutomationLink={title:b.metadata.isAutomationEnabled?"A":"*",tooltip:b.metadata.isAutomationEnabled?$I("btn.aon.tooltip"):$I("btn.aoff.tooltip"),enabled:0<b.metadata.val,cssClass:b.metadata.isAutomationEnabled?"auto-on":"auto-off",handler:function(d){c.handleToggleAutomationLinkClick(b)}});
b.togglable=b.metadata.togglable;"undefined"!=typeof b.metadata.on&&(b.on=b.metadata.on);b.hasResourceHover=!0;return b},getMetadata:function(a){return this.model.options.building?this.game.bld.get(this.model.options.building):null},getEffects:function(a){return a.metadata.effects},getTotalEffects:function(a){return a.metadata.totalEffectsCached},getNextEffectValue:function(a,b){a=a.metadata;if(a.updateEffects)return a.on++,a.updateEffects(a,this.game),b=a.effects[b],a.on--,a.updateEffects(a,this.game),
b},getDescription:function(a){a=a.metadata.description;return"undefined"!=typeof a?a:""},getFlavor:function(a){a=a.metadata.flavor;return"undefined"!=typeof a?a:""},hasSellLink:function(a){return!1},metadataHasChanged:function(a){},off:function(a,b){b=b||1;var c=a.metadata;b>c.on&&(b=c.on);c.on>=b&&(c.on-=b,c.stages&&(a.metaAccessor.meta.on-=b),this.metadataHasChanged(a),this.game.upgrade(c.upgrades))},offAll:function(a){var b=a.metadata;b.on&&(b.on=0,b.stages&&(a.metaAccessor.meta.on=0),this.metadataHasChanged(a),
this.game.upgrade(b.upgrades))},on:function(a,b){b=b||1;var c=a.metadata;b>c.val-c.on&&(b=c.val-c.on);c.on+b<=c.val&&(c.on+=b,c.stages&&(a.metaAccessor.meta.on+=b),this.metadataHasChanged(a),this.game.upgrade(c.upgrades))},onAll:function(a){var b=a.metadata;b.on<b.val&&(b.on=b.val,b.stages&&(a.metaAccessor.meta.on=b.val),this.metadataHasChanged(a),this.game.upgrade(b.upgrades))},sell:function(a,b){var c=b.metadata;if(c.canSell&&!c.canSell(c,this.game))return!1;var d=c.val-1;if(0<d&&a&&a.shiftKey){d=
0;if(this.game.opts.noConfirm)return this.sellInternal(b,d),!0;var e=this;this.game.ui.confirm($("sell.all.confirmation.title"),$I("sell.all.confirmation.msg"),function(){e.sellInternal(b,d);return!0})}else if(0<=d)return this.sellInternal(b,d),!0},sellInternal:function(a,b){for(var c=a.metadata;c.val>b;)this.decrementValue(a),a.prices=this.getPrices(a),this.refund(a);this.game.upgrade(c.upgrades);this.game.render()},decrementValue:function(a){(a=a.metadata)&&a.val--;a.on>a.val&&(a.on=a.val)},updateVisible:function(a){a.visible=
a.metadata.unlocked||this.game.devMode},handleTogglableOnOffClick:function(a){a=a.metadata;a.on=a.on?0:a.val;this.game.upgrade(a.upgrades)},handleToggleAutomationLinkClick:function(a){a=a.metadata;a.isAutomationEnabled=!a.isAutomationEnabled;this.game.upgrade({buildings:[a.name]})}});
dojo.declare("com.nuclearunicorn.game.ui.BuildingBtn",com.nuclearunicorn.game.ui.ButtonModern,{sellHref:null,toggleHref:null,renderLinks:function(){var a=this.model.metadata;this.model.showSellLink&&!this.sellHref&&(this.sellHref=this.addLink({title:$I("btn.sell.minor"),handler:function(b){this.sell(b)}}),dojo.addClass(this.domNode,"hasSellLink"));(9<a.val||10<a.name.length)&&this.model.hasSellLink&&dojo.addClass(this.domNode,"small-text");"undefined"!=typeof this.model.togglable&&this.model.togglable&&
(this.remove=this.addLinkList([{id:"off1",title:"-",handler:function(){this.controller.off(this.model)}},{id:"off25",title:"-25",handler:function(){this.controller.off(this.model,25)}},{id:"offAll",title:"-"+$I("btn.all.minor"),handler:function(){this.controller.offAll(this.model)}}]),this.add=this.addLinkList([{id:"add1",title:"+",handler:function(){this.controller.on(this.model)}},{id:"add25",title:"+25",handler:function(){this.controller.on(this.model,25)}},{id:"add",title:"+"+$I("btn.all.minor"),
handler:function(){this.controller.onAll(this.model)}}]));this.model.togglableOnOffLink&&(this.toggle=this.addLink(this.model.togglableOnOffLink));this.model.toggleAutomationLink&&(this.toggleAutomation=this.addLink(this.model.toggleAutomationLink))},sell:function(a){this.controller.sell(a,this.model)},update:function(){this.inherited(arguments);if(this.buttonContent){var a=this.model.metadata;if(a&&a.val){this.sellHref&&dojo.style(this.sellHref.link,"display",0<a.val?"":"none");9<a.val&&dojo.style(this.domNode,
"font-size","90%");if(this.toggle||this.remove||this.add)dojo.removeClass(this.domNode,"bldEnabled"),dojo.removeClass(this.domNode,"bldlackResConvert"),a.lackResConvert?dojo.toggleClass(this.domNode,"bldlackResConvert",0<a.on):dojo.toggleClass(this.domNode,"bldEnabled",0<a.on);this.add&&dojo.toggleClass(this.add.add1.link,"enabled",a.on<a.val);this.updateLink(this.toggle,this.model.togglableOnOffLink);this.updateLink(this.toggleAutomation,this.model.toggleAutomationLink)}}}});
dojo.declare("com.nuclearunicorn.game.ui.BuildingStackableBtnController",com.nuclearunicorn.game.ui.BuildingBtnController,{defaults:function(){var a=this.inherited(arguments);a.simplePrices=!1;a.multiplyEffects=!0;return a},getName:function(a){a=a.metadata;return a.val?a.noStackable?a.label+" "+$I("btn.complete"):a.togglableOnOff?a.label+" ("+a.val+")":a.togglable?a.label+" ("+a.on+"/"+a.val+")":a.label+" ("+a.on+")":a.label},getPrices:function(a){a=a.metadata;for(var b=a.priceRatio||1,c=[],d=1-this.game.getLimitedDR(this.game.getEffect(a.name+
"CostReduction"),1),e=0;e<a.prices.length;e++){var f=this.game.getEffect(a.prices[e].name+"CostReduction");f=this.game.getLimitedDR(f,1);c.push({val:a.prices[e].val*Math.pow(b,a.val)*(1-f)*d,name:a.prices[e].name})}return c},updateEnabled:function(a){this.inherited(arguments);var b=a.metadata;"number"==typeof b.limitBuild&&b.limitBuild<=b.val?a.enabled=!1:b.on&&(!b.on||b.noStackable)&&b.on&&b.noStackable&&(a.enabled=!1)},buyItem:function(a,b,c){if(a.enabled&&this.hasResources(a)||this.game.devMode){var d=
a.metadata;if(this.game.ironWill&&d.effects&&0<d.effects.maxKittens&&this.game.science.get("archery").researched){var e=this;this.game.ui.confirm("",$I("iron.will.break.confirmation.msg"),function(){e._buyItem_step2(a,b,c)},function(){c(!1)})}else this._buyItem_step2(a,b,c)}else c(!1)},_buyItem_step2:function(a,b,c){var d=a.metadata;if(!d.noStackable&&b.shiftKey)if(this.game.opts.noConfirm)this.build(a,1E4),c(!0);else{var e=this;this.game.ui.confirm($I("construct.all.confirmation.title"),$I("construct.all.confirmation.msg"),
function(){e.build(a,1E4);c(!0)},function(){c(!1)})}else d.noStackable||!b.ctrlKey&&!b.metaKey?this.build(a,1):this.build(a,this.game.opts.batchSize||10),c(!0)},build:function(a,b){var c=a.metadata,d=0;"number"==typeof c.limitBuild&&c.limitBuild-c.val<b&&(b=c.limitBuild-c.val);if(a.enabled&&this.hasResources(a)||this.game.devMode){for(;this.hasResources(a)&&0<b;)this.incrementValue(a),this.payPrice(a),d++,b--;1<d&&this.game.msg($I("construct.all.msg",[c.label,d]),"notice");c.breakIronWill&&(this.game.ironWill=
!1,a=this.game.science.getPolicy("liberty"),a.calculateEffects(a,this.game),a=this.game.bld.getBuildingExt("zebraOutpost").meta,a.calculateEffects(a,this.game),a.jammed=!1,this.game.diplomacy.onLeavingIW());c.unlocks&&this.game.unlock(c.unlocks);c.calculateEffects&&c.calculateEffects(c,this.game);c.unlockScheme&&c.val>=c.unlockScheme.threshold&&this.game.ui.unlockScheme(c.unlockScheme.name);c.upgrades&&(c.updateEffects&&c.updateEffects(c,this.game),this.game.upgrade(c.upgrades))}return d},incrementValue:function(a){a=
a.metadata;var b=0<a.val&&0==a.on;a.val++;a.on++;(a.togglableOnOff&&(b||1==a.val&&0==this.game.resPool.get("paragon").value)||a.togglable&&b)&&a.on--}});dojo.declare("com.nuclearunicorn.game.ui.BuildingStackableBtn",com.nuclearunicorn.game.ui.BuildingBtn,{onClick:function(a){this.inherited(arguments);this.game.render()}});
dojo.declare("com.nuclearunicorn.game.ui.BuildingNotStackableBtnController",com.nuclearunicorn.game.ui.BuildingBtnController,{getDescription:function(a){var b=a.metadata;return b.effectDesc&&b.researched?this.inherited(arguments)+"<br>"+$I("res.effect")+": "+b.effectDesc:this.inherited(arguments)},getName:function(a){a=a.metadata;return a.researched?a.label+" "+$I("btn.complete.capital"):a.label},getPrices:function(a){return $.extend(!0,[],a.metadata.prices)},updateEnabled:function(a){this.inherited(arguments);
a.metadata.researched&&(a.enabled=!1)},buyItem:function(a,b,c){!a.metadata.researched&&this.hasResources(a)||this.game.devMode?(this.payPrice(a),this.onPurchase(a),c(!0),this.game.render()):c(!1)},onPurchase:function(a){a=a.metadata;a.researched=!0;a.handler&&a.handler(this.game,a);a.unlocks&&this.game.unlock(a.unlocks);a.upgrades&&this.game.upgrade(a.upgrades)}});dojo.declare("com.nuclearunicorn.game.ui.BuildingResearchBtn",com.nuclearunicorn.game.ui.BuildingBtn,{});
dojo.declare("com.nuclearunicorn.game.ui.Spacer",null,{title:"",constructor:function(a){this.title=a},render:function(a){dojo.create("div",{innerHTML:this.title,className:"spacer"},a)},update:function(){}});
dojo.declare("com.nuclearunicorn.game.ui.ContentRowRenderer",null,{twoRows:!1,leftRow:null,rightRow:null,initRenderer:function(a){this.content=a;this.twoRows&&(a=dojo.create("table",{cellpadding:"0",cellspacing:"0",style:{width:"100%"}},a),a=dojo.create("tr",{},a),this.leftRow=dojo.create("td",{style:{verticalAlign:"top"}},a),this.rightRow=dojo.create("td",{style:{verticalAlign:"top"}},a))},getElementContainer:function(a){return this.twoRows?0==a%2?this.leftRow:this.rightRow:this.content}});
dojo.declare("mixin.IGameAware",null,{game:null,setGame:function(a){this.game=a}});dojo.declare("mixin.IChildrenAware",null,{children:null,constructor:function(){this.children=[]},addChild:function(a){if(!a)throw"Child can't be null";this.children.push(a)},render:function(a){dojo.forEach(this.children,function(b,c){b.render(a)})},update:function(){dojo.forEach(this.children,function(a,b){a.update()})}});
dojo.declare("com.nuclearunicorn.game.ui.Panel",[com.nuclearunicorn.game.ui.ContentRowRenderer,mixin.IChildrenAware],{game:null,collapsed:!1,visible:!0,name:"",panelDiv:null,toggle:null,contentDiv:null,constructor:function(a,b){this.name=a;b&&b.registerPanel(a,this)},render:function(a){var b=dojo.create("div",{className:"panelContainer",style:{display:this.visible?"":"none"}},a);this.toggle=dojo.create("div",{innerHTML:this.collapsed?"+":"-",className:"toggle"+(this.collapsed?" collapsed":""),style:{float:"right"}},
b);this.title=dojo.create("div",{innerHTML:this.name,className:"title"},b);this.contentDiv=dojo.create("div",{className:"container",style:{display:this.collapsed?"none":""}},b);dojo.connect(this.toggle,"onclick",this,function(){this.collapse(!this.collapsed)});this.panelDiv=b;this.inherited(arguments,[this.contentDiv]);return this.contentDiv},collapse:function(a){this.collapsed=a;$(this.contentDiv).toggle(!a);this.toggle.innerHTML=a?"+":"-";this.onToggle(a);var b=dojo.hasClass(this.toggle,"collapsed");
a&&!b?dojo.addClass(this.toggle,"collapsed"):!a&&b&&dojo.removeClass(this.toggle,"collapsed")},onToggle:function(a){},setVisible:function(a){this.visible=a;this.panelDiv&&$(this.panelDiv).toggle(a)},update:function(){this.inherited(arguments)},setGame:function(a){this.game=a}});
dojo.declare("com.nuclearunicorn.game.ui.tab",[com.nuclearunicorn.game.ui.ContentRowRenderer,mixin.IChildrenAware],{game:null,buttons:null,tabId:null,tabName:null,domNode:null,visible:!0,constructor:function(a,b){this.tabName=a.name;this.tabId=a.id;this.buttons=[];this.game=b},render:function(a){this.inherited(arguments);this.initRenderer(a)},update:function(){this.inherited(arguments);for(var a=0;a<this.buttons.length;a++)this.buttons[a].update()},updateTab:function(){},addButton:function(a){a.game=
this.game;a.tab=this;this.buttons.push(a)}});
UIUtils={attachTooltip:function(a,b,c,d,e){var f=dojo.byId("game"),g=dojo.byId("tooltip");dojo.connect(b,"onmouseover",this,function(){a.tooltipUpdateFunc=function(){g.innerHTML=dojo.hitch(a,e)()};a.tooltipUpdateFunc();var h=$(b).offset(),k=$(f).offset();h.top-=k.top;h.left-=k.left;h.top+=c;h.left+=d;k=$(window).scrollTop()+$(window).height()-$(g).outerHeight()-25;var l=$(window).scrollLeft()+$(window).width()-$(g).outerWidth()-25;h.top=Math.min(h.top,k);h.left=Math.min(h.left,l);dojo.style(g,"top",
h.top+"px");dojo.style(g,"left",h.left+"px");g.innerHTML&&dojo.style(g,"display","")});dojo.connect(b,"onmouseout",this,function(){a.tooltipUpdateFunc=null;dojo.style(g,"display","none")});return e}};
