WCollapsiblePanel=React.createClass({getInitialState:function(){return{isCollapsed:!1}},render:function(){return $r("div",null,[$r("div",null,[$r("div",{className:"left"},$r("a",{className:"link collapse",onClick:this.toggleCollapsed},this.state.isCollapsed?">("+this.props.title+")":"v"))]),!this.state.isCollapsed&&this.props.children])},toggleCollapsed:function(){this.setState({isCollapsed:!this.state.isCollapsed})}});
WResourceRow=React.createClass({getDefaultProperties:function(){return{resource:null,isEditMode:!1,isRequired:!1,showHiddenResources:!1}},getInitialState:function(){return{visible:!this.props.resource.isHidden}},shouldComponentUpdate:function(a,c){var b=this.oldRes||{},d=a.resource;if(b.value==d.value&&b.maxValue==d.maxValue&&b.perTickCached==d.perTickCached&&this.props.isEditMode==a.isEditMode&&this.props.isRequired==a.isRequired&&this.props.showHiddenResources==a.showHiddenResources&&this.props.isTemporalParadox!=
a.isTemporalParadox&&this.state.visible==c.visible)return!1;this.oldRes={value:d.value,maxValue:d.maxValue,perTickCached:d.perTickCached};return!0},render:function(){var a=this.props.resource;if(!a.visible&&!this.props.showHiddenResources||!(a.unlocked||"kittens"==a.name&&a.maxValue)||!this.state.visible&&!this.props.isEditMode||game.resPool.isNormalCraftableResource(a)&&game.workshop.getCraft(a.name).unlocked)return null;var c=this.props.isTemporalParadox,b=c?0:game.getResourcePerTick(a.name,!0);
b=game.opts.usePerSecondValues?b*game.getTicksPerSecondUI():b;var d=game.opts.usePerSecondValues?"/"+$I("unit.s"):"";game.opts.usePercentageResourceValues&&a.maxValue&&(b=(b/a.maxValue*100).toFixed(2),d="%"+d);d=game.getResourcePerTick(a.name,!1)||game.getResourcePerTickConvertion(a.name)?game.getDisplayValueExt(b,!0,!1)+d:a.calculatePerDay?game.getDisplayValueExt(game.getResourcePerDay(a.name)*("necrocorn"==a.name?1+game.timeAccelerationRatio():1),!0,!1)+"/"+$I("unit.d"):a.calculateOnYear?game.getDisplayValueExt(game.getResourceOnYearProduction(a.name),
!0,!1)+"/"+$I("unit.y"):"";var e={};"uncommon"==a.type&&(e={color:"Coral"});"rare"==a.type&&(e={color:"orange",textShadow:"1px 0px 10px Coral"});a.color&&(e={color:a.color});if(a.style)for(var f in a.style)e[f]=a.style[f];f="resAmount";a.value>.95*a.maxValue&&0<a.maxValue?f="resAmount resLimitNotice":a.value>.75*a.maxValue&&0<a.maxValue&&(f="resAmount resLimitWarn");var g=null,h=null;game.calendar.getCurSeason().modifiers[a.name]&&0!==b&&(b=game.calendar.getWeatherMod(a),g=(b=0==b?-100:Math.max(Math.round(100*
(b-1)),-99))?"["+(0<b?"+":"")+b.toFixed()+"%]":"",0<b?h="positive-weather":0>b&&(h="negative-weather"));b="";420==a.value?b=" blaze":666==a.value?b=" hail":777==a.value?b=" pray":1337==a.value&&(b=" leet");var l="",k=game.village.leader;if(k&&k.job&&(k=game.village.getJob(k.job)))for(var m in k.modifiers)a.name==m&&(l=" resLeaderBonus ");return $r("div",{className:"res-row resource_"+a.name+l+(this.props.isRequired?" highlited":"")+(a.visible?"":" hidden")},[this.props.isEditMode?$r("div",{className:"res-cell"},
$r("input",{type:"checkbox",checked:this.state.visible,onClick:this.toggleView,style:{display:"inline-block"}})):null,$r("div",{className:"res-cell resource-name",style:e,onClick:this.onClickName,title:a.title||a.name},a.title||a.name),$r("div",{className:"res-cell "+f+b},game.getDisplayValueExt(a.value)),$r("div",{className:"res-cell maxRes"},a.maxValue?"/"+game.getDisplayValueExt(a.maxValue):""),$r("div",{className:"res-cell resPerTick",ref:"perTickNode"},c?"???":d),$r("div",{className:"res-cell"+
(h?" "+h:"")},g)])},onClickName:function(a){(this.props.isEditMode||a.ctrlKey||a.metaKey)&&this.toggleView()},toggleView:function(){this.setState({visible:!this.state.visible});this.props.resource.isHidden=this.state.visible},componentDidMount:function(){var a=React.findDOMNode(this.refs.perTickNode);a&&(this.tooltipNode=a,game.attachResourceTooltip(a,this.props.resource))},componentDidUpdate:function(a,c){!this.tooltipNode&&(a=React.findDOMNode(this.refs.perTickNode))&&(this.tooltipNode=a,game.attachResourceTooltip(a,
this.props.resource))},componentWillUnmount:function(){if(!this.tooltipNode){var a=React.findDOMNode(this.refs.perTickNode);a&&(this.tooltipNode=a)}dojo.destroy(this.tooltipNode)}});
WCraftShortcut=React.createClass({getDefaultProperties:function(){return{resource:null,craftFixed:null,craftPercent:null}},render:function(){var a=this.props.resource,c=this.props.recipe,b=this.props.craftFixed,d=this.props.craftPercent,e=game.workshop.getCraftAllCount(a.name);a=game.getResCraftRatio(a.name);var f=game.workshop.getCraftPrice(c),g=b;b<e*d&&(g=Math.floor(e*d));b="res-cell craft-link ";1==d?(b+="all",c=this.hasMinAmt(c)?$r("div",{className:b,onClick:this.doCraftAll,title:"+"+game.getDisplayValueExt(e*
(1+a),null,null,0)},$I("resources.craftTable.all")):$r("div",{className:b})):(b+="craft-"+100*d+"pc",c=game.resPool.hasRes(f,g)?game.opts.usePercentageConsumptionValues?$r("div",{className:b,onClick:this.doCraft,title:"+"+game.getDisplayValueExt(g*(1+a),null,null,0)},100*d+"%"):$r("div",{className:b,onClick:this.doCraft,title:100*d+"%"},$r("span",{className:"plusPrefix"},"+"),game.getDisplayValueExt(g*(1+a),null,null,0)):$r("div",{className:b}));return $r("div",{ref:"linkBlock",style:{display:"contents"}},
c)},componentDidMount:function(){var a=this.props.recipe,c=this.props.craftPercent,b=this.props.craftFixed;if(1!=this.props.craftPercent){var d=React.findDOMNode(this.refs.linkBlock);d&&d.firstChild&&(this.tooltipNode=d,UIUtils.attachTooltip(game,d.firstChild,0,60,dojo.partial(function(e){var f=dojo.create("div",{className:"button_tooltip"},null),g=game.workshop.getCraftPrice(e);e=game.workshop.getCraftAllCount(e.name);e=Math.floor(e*c);b<e&&(b=e);for(e=0;e<g.length;e++){var h=g[e],l=dojo.create("div",
{style:{clear:"both"}},f),k=game.resPool.get(h.name);dojo.create("span",{innerHTML:k.title||k.name,style:{float:"left"}},l);dojo.create("span",{innerHTML:game.getDisplayValueExt(h.val*b),style:{float:"right",paddingLeft:"6px"}},l)}return f.outerHTML},a)))}},hasMinAmt:function(a){var c=Number.MAX_VALUE;a=game.workshop.getCraftPrice(a);for(var b=0;b<a.length;b++){var d=game.resPool.get(a[b].name).value;d=Math.floor(d/a[b].val);d<c&&(c=d)}return 0<c&&c<Number.MAX_VALUE},doCraft:function(a){a=this.props.resource;
var c=game.workshop.getCraftAllCount(a.name);c=Math.floor(c*this.props.craftPercent);var b=this.props.craftFixed;b<c&&(b=c);game.craft(a.name,b)},doCraftAll:function(){game.craftAll(this.props.resource.name)},componentWillUnmount:function(){var a=React.findDOMNode(this.refs.linkBlock);a&&dojo.destroy(a.firstChild)}});
WCraftRow=React.createClass({getDefaultProperties:function(){return{resource:null,isEditMode:!1}},getInitialState:function(){return{visible:!this.props.resource.isHidden}},shouldComponentUpdate:function(a,c){this.oldRes={value:a.resource.value};return!0},render:function(){var a=this.props.resource,c=game.workshop.getCraft(a.name);if(!a.unlocked||!c.unlocked||!this.state.visible&&!this.props.isEditMode)return null;var b={};"uncommon"==a.type&&(b={color:"Coral"});"rare"==a.type&&(b={color:"orange",
textShadow:"1px 0px 10px Coral"});a.color&&(b={color:a.color});if(a.style)for(var d in a.style)b[d]=a.style[d];d=game.getDisplayValueExt(a.value);return $r("div",{className:"res-row craft resource_"+a.name+(0!=game.workshop.getEffectEngineer(a.name)?" craftEngineer ":"")+(this.props.isRequired?" highlited":"")},[this.props.isEditMode?$r("div",{className:"res-cell"},$r("input",{type:"checkbox",checked:this.state.visible,onClick:this.toggleView,style:{display:"inline-block"}})):null,$r("div",{className:"res-cell resource-name",
style:b,onClick:this.onClickName,title:a.title||a.name},a.title||a.name),$r("div",{className:"res-cell resource-value",ref:"perTickNode",title:d},d),$r(WCraftShortcut,{resource:a,recipe:c,craftFixed:1,craftPercent:.01}),$r(WCraftShortcut,{resource:a,recipe:c,craftFixed:25,craftPercent:.05}),$r(WCraftShortcut,{resource:a,recipe:c,craftFixed:100,craftPercent:.1}),$r(WCraftShortcut,{resource:a,recipe:c,craftPercent:1})])},onClickName:function(a){(this.props.isEditMode||a.ctrlKey)&&this.toggleView()},
toggleView:function(){this.setState({visible:!this.state.visible});this.props.resource.isHidden=this.state.visible},componentDidMount:function(){var a=React.findDOMNode(this.refs.perTickNode);a&&(this.tooltipNode=a,game.attachResourceTooltip(a,this.props.resource))},componentDidUpdate:function(a,c){!this.tooltipNode&&(a=React.findDOMNode(this.refs.perTickNode))&&(this.tooltipNode=a,game.attachResourceTooltip(a,this.props.resource))}});
WResourceTable=React.createClass({getDefaultProperties:function(){return{resources:null}},getInitialState:function(){return{isEditMode:!1,isCollapsed:!1,showHiddenResources:!1}},render:function(){var a=[],c;for(c in this.props.resources){var b=this.props.resources[c],d=0<=this.props.reqRes.indexOf(b.name);a.push($r(WResourceRow,{resource:b,isEditMode:this.state.isEditMode,isRequired:d,showHiddenResources:this.state.showHiddenResources,isTemporalParadox:0>game.calendar.day}))}return $r("div",null,
[$r("div",null,[$r("div",{className:"res-toolbar left"},$r("a",{className:"link collapse",onClick:this.toggleCollapsed},this.state.isCollapsed?">("+$I("left.resources")+")":"v")),$r("div",{className:"res-toolbar right"},$r("a",{className:"link"+(this.state.isEditMode?" toggled":""),onClick:this.toggleEdit},"\u2699"),$r(WTooltip,{body:"?"},$I("left.resources.tip")))]),!this.state.isCollapsed&&$r("div",null,[this.state.isEditMode&&$r("div",{style:{textAlign:"right"}},[$r("a",{className:"link",onClick:game.ui.zoomUp.bind(game.ui)},
$I("left.font.inc")),$r("a",{className:"link",onClick:game.ui.zoomDown.bind(game.ui)},$I("left.font.dec"))]),$r("div",{className:"res-table"},a)]),!this.state.isCollapsed&&this.state.isEditMode&&$r("div",{className:"res-toggle-hidden"},[$r("input",{type:"checkbox",checked:this.state.showHiddenResources,onClick:this.toggleHiddenResources,style:{display:"inline-block"}}),$I("res.show.hidden")])])},toggleEdit:function(){this.setState({isEditMode:!this.state.isEditMode})},toggleCollapsed:function(){this.setState({isCollapsed:!this.state.isCollapsed})},
toggleHiddenResources:function(a){this.setState({showHiddenResources:a.target.checked})}});
WCraftTable=React.createClass({getDefaultProperties:function(){return{resources:null,game:null}},getInitialState:function(){return{isEditMode:!1,isCollapsed:!1}},render:function(){var a=[],c;for(c in this.props.resources){var b=this.props.resources[c];if(b.craftable){var d=0<=this.props.reqRes.indexOf(b.name);a.push($r(WCraftRow,{resource:b,isEditMode:this.state.isEditMode,isRequired:d}))}}return 0>=game.bld.get("workshop").on?null:$r("div",null,[$r("div",null,[$r("div",{className:"res-toolbar left"},
$r("a",{className:"link collapse",onClick:this.toggleCollapsed},this.state.isCollapsed?">("+$I("left.craft")+")":"v")),$r("div",{className:"res-toolbar right"},$r("a",{className:"link"+(this.state.isEditMode?" toggled":""),onClick:this.toggleEdit},"\u2699"))]),this.state.isCollapsed?null:$r("div",null,[$r("div",{className:"res-table craftTable"},a)])])},toggleEdit:function(){this.setState({isEditMode:!this.state.isEditMode})},toggleCollapsed:function(){this.setState({isCollapsed:!this.state.isCollapsed})}});
WPins=React.createClass({getPins:function(){var a=[],c;for(c in this.props.game.diplomacy.races){var b=this.props.game.diplomacy.races[c];b.pinned&&a.push({title:$I("left.trade.do",[b.title]),handler:function(d){this.props.game.diplomacy.tradeAll(d)}.bind(this,b)})}return a},render:function(){var a=this.getPins(),c=[],b;for(b in a){var d=a[b];c.push($r("div",{className:"pin-link"},$r("a",{href:"#",onClick:d.handler},d.title)))}return $r(WCollapsiblePanel,{title:$I("left.trade")},c)}});
WLeftPanel=React.createClass({getDefaultProperties:function(){return{game:null}},getInitialState:function(){return{game:this.props.game}},getResources:function(){var a=[],c=this.state.game;a=a.concat(c.resPool.resources);return a=a.concat(c.resPool.getPseudoResources())},render:function(){var a=this.state.game,c=a.getRequiredResources(a.selectedBuilding),b=a.resPool.get("manpower"),d=Math.floor(b.value/100),e=(0<a.resPool.get("paragon").value||a.science.get("archery").researched)&&!a.challenges.isActive("pacifism");
b=100<=b.value;var f=!1;if(0<a.bld.get("field").on){f=a.calendar;var g=f.daysPerSeason-("winter"===f.getCurSeason().name?f.day:0),h=a.winterCatnipPerTick;f=0>=a.resPool.get("catnip").value+g*h*f.ticksPerDay}return $r("div",null,[$r(WResourceTable,{resources:this.getResources(),reqRes:c}),$r("div",{id:"advisorsContainer",style:{paddingTop:"10px",display:f?"block":"none"}},$I("general.food.advisor.text")),$r("div",{id:"fastHuntContainer",className:"pin-link",style:{display:e?"block":"none",visibility:b?
"visible":"hidden"}},$r("a",{href:"#",onClick:this.huntAll},$I("left.hunt")+" (",$r("span",{id:"fastHuntContainerCount"},[a.getDisplayValueExt(d,!1,!1,0)," ",1===d?$I("left.hunt.time"):$I("left.hunt.times")]),")")),$r("div",{id:"fastPraiseContainer",className:"pin-link",style:{visibility:"hidden"}},$r("a",{href:"#",onClick:this.praiseAll},$I("left.praise"))),$r(WPins,{game:a}),$r(WCraftTable,{resources:a.resPool.resources,reqRes:c})])},huntAll:function(a){this.state.game.huntAll(a)},praiseAll:function(a){this.state.game.praise(a)},
componentDidMount:function(){var a=this;dojo.subscribe("ui/update",function(c){a.setState({game:c})})}});
WTooltip=React.createClass({getInitialState:function(){return{showTooltip:!1}},getDefaultProps:function(){return{body:null}},render:function(){return $r("div",{className:"tooltip-block",onMouseOver:this.onMouseOver,onMouseOut:this.onMouseOut},[this.props.body||$r("div",{className:"tooltip-icon"},"[?]"),this.state.showTooltip?$r("div",{className:"tooltip-content"},this.props.children):null])},onMouseOver:function(){this.setState({showTooltip:!0})},onMouseOut:function(){this.setState({showTooltip:!1})}});
